/* Generated by Nimrod Compiler v0.9.5 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nimrod -o /home/andreysh/Projects/nimrod/stone_head/nimcache/application.o /home/andreysh/Projects/nimrod/stone_head/nimcache/application.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>
typedef struct tsurface85253 tsurface85253;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tcell41290 tcell41290;
typedef struct TNimType TNimType;
typedef struct tcellseq41306 tcellseq41306;
typedef struct tgcheap43216 tgcheap43216;
typedef struct tcellset41302 tcellset41302;
typedef struct tpagedesc41298 tpagedesc41298;
typedef struct tmemregion23610 tmemregion23610;
typedef struct tsmallchunk22838 tsmallchunk22838;
typedef struct tllchunk23604 tllchunk23604;
typedef struct tbigchunk22840 tbigchunk22840;
typedef struct tintset22815 tintset22815;
typedef struct ttrunk22811 ttrunk22811;
typedef struct tavlnode23608 tavlnode23608;
typedef struct tgcstat43214 tgcstat43214;
typedef struct tdynamicHEX3Aobjecttype728028 tdynamicHEX3Aobjecttype728028;
typedef struct tdynamicobjectHEX3Aobjecttype728040 tdynamicobjectHEX3Aobjecttype728040;
typedef struct TNimNode TNimNode;
typedef struct tbtree728049 tbtree728049;
typedef struct tcattyapplicationHEX3Aobjecttype785014 tcattyapplicationHEX3Aobjecttype785014;
typedef struct TNimObject TNimObject;
typedef struct tparsestring727006 tparsestring727006;
typedef struct tdynamicintHEX3Aobjecttype728031 tdynamicintHEX3Aobjecttype728031;
typedef struct tpixelformat85243 tpixelformat85243;
typedef struct trect85225 trect85225;
typedef struct tbasechunk22836 tbasechunk22836;
typedef struct tfreecell22828 tfreecell22828;
typedef struct titems728052 titems728052;
typedef struct titem728056 titem728056;
typedef struct tpalette85239 tpalette85239;
typedef struct tcolor85231 tcolor85231;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  tcell41290  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq41306  {
NI Len;
NI Cap;
tcell41290** D;
};
struct  tcellset41302  {
NI Counter;
NI Max;
tpagedesc41298* Head;
tpagedesc41298** Data;
};
typedef tsmallchunk22838* TY23622[512];
typedef ttrunk22811* ttrunkbuckets22813[256];
struct  tintset22815  {
ttrunkbuckets22813 Data;
};
struct  tmemregion23610  {
NI Minlargeobj;
NI Maxlargeobj;
TY23622 Freesmallchunks;
tllchunk23604* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk22840* Freechunkslist;
tintset22815 Chunkstarts;
tavlnode23608* Root;
tavlnode23608* Deleted;
tavlnode23608* Last;
tavlnode23608* Freeavlnodes;
};
struct  tgcstat43214  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap43216  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq41306 Zct;
tcellseq41306 Decstack;
tcellset41302 Cycleroots;
tcellseq41306 Tempstack;
NI Recgclock;
tmemregion23610 Region;
tgcstat43214 Stat;
};
typedef N_NIMCALL_PTR(void, TY2289) (void* p, NI op);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY2289 marker;
};
struct  tdynamicHEX3Aobjecttype728028  {
TNimType* m_type;
NU8 T;
};
struct  tdynamicobjectHEX3Aobjecttype728040  {
  tdynamicHEX3Aobjecttype728028 Sup;
tbtree728049* Value;
NIM_BOOL Fcaseinsensitive;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_CDECL_PTR(NI, TY88420) (NI32 flags);
typedef N_CDECL_PTR(tsurface85253*, TY89187) (NI width, NI height, NI bpp, NU32 flags);
struct  TNimObject  {
TNimType* m_type;
};
struct  tcattyapplicationHEX3Aobjecttype785014  {
  TNimObject Sup;
NI Screenwidth;
NI Screenheight;
NimStringDesc* Clearcolor;
};
typedef N_CDECL_PTR(void, TY89318) (tsurface85253* surface);
typedef N_CDECL_PTR(void, TY88436) (void);
struct  tparsestring727006  {
NimStringDesc* S;
NI A;
};
struct  tdynamicintHEX3Aobjecttype728031  {
  tdynamicHEX3Aobjecttype728028 Sup;
NI Value;
};
typedef N_CDECL_PTR(void, TY89481) (NCSTRING title, NCSTRING icon);
struct  trect85225  {
NI16 X;
NI16 Y;
NU16 W;
NU16 H;
};
struct  tsurface85253  {
NI32 Flags;
tpixelformat85243* Format;
int W;
int H;
NU16 Pitch;
void* Pixels;
int Offset;
void* Hwdata;
trect85225 Cliprect;
NI32 Unused1;
NI32 Locked;
void* Blitmap;
int Formatversion;
int Refcount;
};
typedef NI TY22818[8];
struct  tpagedesc41298  {
tpagedesc41298* Next;
NI Key;
TY22818 Bits;
};
struct  tbasechunk22836  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk22838  {
  tbasechunk22836 Sup;
tsmallchunk22838* Next;
tsmallchunk22838* Prev;
tfreecell22828* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk23604  {
NI Size;
NI Acc;
tllchunk23604* Next;
};
struct  tbigchunk22840  {
  tbasechunk22836 Sup;
tbigchunk22840* Next;
tbigchunk22840* Prev;
NI Align;
NF Data;
};
struct  ttrunk22811  {
ttrunk22811* Next;
NI Key;
TY22818 Bits;
};
typedef tavlnode23608* TY23614[2];
struct  tavlnode23608  {
TY23614 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tbtree728049  {
titems728052* Slots;
tbtree728049* Left;
NI32 Count;
};
struct  tpixelformat85243  {
tpalette85239* Palette;
NU8 Bitsperpixel;
NU8 Bytesperpixel;
NU8 Rloss;
NU8 Gloss;
NU8 Bloss;
NU8 Aloss;
NU8 Rshift;
NU8 Gshift;
NU8 Bshift;
NU8 Ashift;
NI32 Rmask;
NI32 Gmask;
NI32 Bmask;
NI32 Amask;
NI32 Colorkey;
NU8 Alpha;
};
struct  tfreecell22828  {
tfreecell22828* Next;
NI Zerofield;
};
struct  titem728056  {
NimStringDesc* Key;
tdynamicHEX3Aobjecttype728028* Value;
tbtree728049* Node;
NIM_BOOL Valset;
};
struct  tpalette85239  {
NI Ncolors;
tcolor85231* Colors;
};
struct  tcolor85231  {
NU8 R;
NU8 G;
NU8 B;
NU8 Unused;
};
struct titems728052 {
  TGenericSeq Sup;
  titem728056* data[SEQ_DECL_SIZE];
};
N_NIMCALL(NimStringDesc*, HEX2F_772477)(NimStringDesc* head, NimStringDesc* tail);
N_NIMCALL(NimStringDesc*, nosgetApplicationDir)(void);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell41290*, usrtocell_44643)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_46202)(tcell41290* c);
N_NOINLINE(void, addzct_44618)(tcellseq41306* s, tcell41290* c);
static N_INLINE(tdynamicobjectHEX3Aobjecttype728040*, dynamicobject_728293)(NIM_BOOL acaseinsensitive);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_47027)(tcell41290* c);
static N_INLINE(NIM_BOOL, canbecycleroot_44662)(tcell41290* c);
static N_INLINE(void, rtladdcycleroot_45435)(tcell41290* c);
N_NOINLINE(void, incl_42055)(tcellset41302* s, tcell41290* cell);
static N_INLINE(void, decref_46602)(tcell41290* c);
N_NIMCALL(void, initialization_785020)(tcattyapplicationHEX3Aobjecttype785014* this_785022);
N_STDCALL(void, glcleardepth_310802)(NF depth);
N_STDCALL(void, glviewport_645202)(NI32 x, NI32 y, NI32 width, NI32 height);
N_STDCALL(void, glmatrixmode_229002)(NU32 mode);
N_STDCALL(void, glloadidentity_516802)(void);
N_STDCALL(void, glortho_433002)(NF left, NF right, NF bottom, NF top, NF znear, NF zfar);
N_STDCALL(void, glenable_527802)(NU32 cap);
N_NIMCALL(void, clearcolor_736007)(NimStringDesc* str);
N_NIMCALL(void, quit_785032)(tcattyapplicationHEX3Aobjecttype785014* this_785034);
N_NIMCALL(void, init_785037)(NI screenwidth, NI screenheight, NimStringDesc* ccolor);
static N_INLINE(NIM_BOOL, fileexists_771406)(NimStringDesc* filename);
N_NIMCALL(NIM_BOOL, nosexistsFile)(NimStringDesc* filename);
static N_INLINE(tdynamicHEX3Aobjecttype728028*, fromliteral_735510)(NimStringDesc* s, NIM_BOOL acaseinsensitive);
static N_INLINE(void, fromliteral_727126)(NimStringDesc* s, tparsestring727006* Result);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(tdynamicHEX3Aobjecttype728028*, parseany_735341)(tparsestring727006* s, NIM_BOOL acaseinsensitive);
N_NIMCALL(NimStringDesc*, readfile_10440)(NimStringDesc* filename);
static N_INLINE(tdynamicHEX3Aobjecttype728028*, HEX5BHEX5D_735549)(tdynamicHEX3Aobjecttype728028* v, NimStringDesc* key);
N_NIMCALL(tdynamicHEX3Aobjecttype728028*, HEX5BHEX5D_732628)(tdynamicobjectHEX3Aobjecttype728040* v, NimStringDesc* i);
static N_INLINE(NI, asint_730271)(tdynamicHEX3Aobjecttype728028* v);
N_NIMCALL(NI, asintslow_729989)(tdynamicHEX3Aobjecttype728028* v);
N_NIMCALL(void, quit_785105)(void);
N_NIMCALL(void, setwindowcaption_785109)(NimStringDesc* caption);
N_NIMCALL(NimStringDesc*, HEX2A_785114)(NimStringDesc* a, NI b);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
STRING_LITERAL(TMP673, "config.json", 11);
STRING_LITERAL(TMP679, "", 0);
STRING_LITERAL(TMP680, "screen", 6);
STRING_LITERAL(TMP681, "width", 5);
STRING_LITERAL(TMP682, "height", 6);
tsurface85253* screen_785002;
NimStringDesc* configfilename_785003;
extern TFrame* frameptr_13038;
extern tgcheap43216 gch_43244;
tdynamicHEX3Aobjecttype728028* config_785004;
tdynamicobjectHEX3Aobjecttype728040* v_785009;
extern TNimType NTI728015; /* TDynamicObject */
extern TNimType NTI728040; /* TDynamicObject:ObjectType */
extern TY88420 Dl_88419;
extern TY89187 Dl_89186;
extern TY89318 Dl_89317;
extern TY88436 Dl_88435;
extern TY89481 Dl_89480;

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_13038;
	frameptr_13038 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_13038 = (*frameptr_13038).prev;
}

static N_INLINE(tcell41290*, usrtocell_44643)(void* usr) {
	tcell41290* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell41290*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell41290))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_46202)(tcell41290* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_44618(&gch_43244.Zct, c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell41290* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_44643(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell41290* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_44643((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_46202(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(tdynamicobjectHEX3Aobjecttype728040*, dynamicobject_728293)(NIM_BOOL acaseinsensitive) {
	tdynamicobjectHEX3Aobjecttype728040* result;
	nimfr("dynamicObject", "dynobj.nim")
	result = 0;
	nimln(93, "dynobj.nim");
	result = (tdynamicobjectHEX3Aobjecttype728040*) newObj((&NTI728015), sizeof(tdynamicobjectHEX3Aobjecttype728040));
	(*result).Sup.m_type = (&NTI728040);
	nimln(94, "dynobj.nim");
	(*result).Sup.T = ((NU8) 7);
	nimln(95, "dynobj.nim");
	(*result).Fcaseinsensitive = acaseinsensitive;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, canbecycleroot_44662)(tcell41290* c) {
	NIM_BOOL result;
	nimfr("canbeCycleRoot", "gc.nim")
	result = 0;
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	result = !((((*(*c).Typ).flags &(1<<((((NU8) 1))&7)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_45435)(tcell41290* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(189, "gc.nim");
	{
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		if (!!((((NI) ((NI)((*c).Refcount & 3))) == 3))) goto LA3;
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		(*c).Refcount = (NI)((NI)((*c).Refcount & -4) | 3);
		nimln(191, "gc.nim");
		incl_42055(&gch_43244.Cycleroots, c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, incref_47027)(tcell41290* c) {
	nimfr("incRef", "gc.nim")
	nimln(216, "gc.nim");
	nimln(216, "gc.nim");
	(*c).Refcount = (NI)((NU64)((*c).Refcount) + (NU64)(8));
	nimln(219, "gc.nim");
	{
		NIM_BOOL LOC3;
		nimln(219, "gc.nim");
		LOC3 = 0;
		LOC3 = canbecycleroot_44662(c);
		if (!LOC3) goto LA4;
		nimln(220, "gc.nim");
		rtladdcycleroot_45435(c);
	}
	LA4: ;
	popFrame();
}

static N_INLINE(void, decref_46602)(tcell41290* c) {
	nimfr("decRef", "gc.nim")
	nimln(206, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		nimln(207, "gc.nim");
		rtladdzct_46202(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(208, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_44662(c);
		if (!LOC6) goto LA7;
		nimln(211, "gc.nim");
		rtladdcycleroot_45435(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr("asgnRef", "gc.nim")
	nimln(244, "gc.nim");
	{
		tcell41290* LOC5;
		nimln(244, "gc.nim");
		nimln(244, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(244, "gc.nim");
		nimln(244, "gc.nim");
		LOC5 = 0;
		LOC5 = usrtocell_44643(src);
		incref_47027(LOC5);
	}
	LA3: ;
	nimln(245, "gc.nim");
	{
		tcell41290* LOC10;
		nimln(245, "gc.nim");
		nimln(245, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		nimln(245, "gc.nim");
		nimln(245, "gc.nim");
		LOC10 = 0;
		LOC10 = usrtocell_44643((*dest));
		decref_46602(LOC10);
	}
	LA8: ;
	nimln(246, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(void, initialization_785020)(tcattyapplicationHEX3Aobjecttype785014* this_785022) {
	NI LOC1;
	nimfr("initialization", "application.nim")
	nimln(18, "application.nim");
	nimln(18, "application.nim");
	LOC1 = 0;
	LOC1 = Dl_88419(((NI32) 32));
	nimln(20, "application.nim");
	screen_785002 = Dl_89186((*this_785022).Screenwidth, (*this_785022).Screenheight, 16, ((NU32) 2));
	nimln(22, "application.nim");
	glcleardepth_310802(1.0000000000000000e+00);
	nimln(23, "application.nim");
	glviewport_645202(((NI32) 0), ((NI32) 0), ((NI32) ((*this_785022).Screenwidth)), ((NI32) ((*this_785022).Screenheight)));
	nimln(24, "application.nim");
	glmatrixmode_229002(((NU32) 5889));
	nimln(26, "application.nim");
	glloadidentity_516802();
	nimln(28, "application.nim");
	nimln(28, "application.nim");
	nimln(28, "application.nim");
	glortho_433002(0.0, ((double) ((*this_785022).Screenwidth)), ((double) ((*this_785022).Screenheight)), 0.0, 1.0000000000000000e+01, -1.0000000000000000e+00);
	nimln(30, "application.nim");
	glmatrixmode_229002(((NU32) 5888));
	nimln(32, "application.nim");
	glenable_527802(((NU32) 3553));
	nimln(34, "application.nim");
	glloadidentity_516802();
	nimln(36, "application.nim");
	clearcolor_736007((*this_785022).Clearcolor);
	popFrame();
}

N_NIMCALL(void, quit_785032)(tcattyapplicationHEX3Aobjecttype785014* this_785034) {
	nimfr("quit", "application.nim")
	nimln(39, "application.nim");
	Dl_89317(screen_785002);
	nimln(40, "application.nim");
	Dl_88435();
	popFrame();
}

static N_INLINE(NIM_BOOL, fileexists_771406)(NimStringDesc* filename) {
	NIM_BOOL result;
	nimfr("fileExists", "os.nim")
	result = 0;
	nimln(416, "os.nim");
	nimln(417, "os.nim");
	result = nosexistsFile(filename);
	popFrame();
	return result;
}

static N_INLINE(void, fromliteral_727126)(NimStringDesc* s, tparsestring727006* Result) {
	nimfr("fromLiteral", "helperParse.nim")
	nimln(53, "helperParse.nim");
	{
		nimln(53, "helperParse.nim");
		nimln(53, "helperParse.nim");
		if (!!(s == 0)) goto LA3;
		nimln(53, "helperParse.nim");
		unsureAsgnRef((void**) &(*Result).S, copyString(s));
	}
	goto LA1;
	LA3: ;
	{
		nimln(54, "helperParse.nim");
		unsureAsgnRef((void**) &(*Result).S, copyString(((NimStringDesc*) &TMP679)));
	}
	LA1: ;
	popFrame();
}

static N_INLINE(tdynamicHEX3Aobjecttype728028*, fromliteral_735510)(NimStringDesc* s, NIM_BOOL acaseinsensitive) {
	tdynamicHEX3Aobjecttype728028* result;
	tparsestring727006 ps;
	nimfr("fromLiteral", "dynobj.nim")
	result = 0;
	nimln(662, "dynobj.nim");
	chckNil((void*)&ps);
	memset((void*)&ps, 0, sizeof(ps));
	fromliteral_727126(s, &ps);
	nimln(663, "dynobj.nim");
	nimln(663, "dynobj.nim");
	result = parseany_735341(&ps, acaseinsensitive);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(tdynamicHEX3Aobjecttype728028*, HEX5BHEX5D_735549)(tdynamicHEX3Aobjecttype728028* v, NimStringDesc* key) {
	tdynamicHEX3Aobjecttype728028* result;
	nimfr("[]", "dynobj.nim")
	result = 0;
	nimln(673, "dynobj.nim");
	{
		NIM_BOOL LOC3;
		nimln(673, "dynobj.nim");
		LOC3 = 0;
		nimln(673, "dynobj.nim");
		nimln(673, "dynobj.nim");
		LOC3 = !((v == NIM_NIL));
		if (!(LOC3)) goto LA4;
		nimln(673, "dynobj.nim");
		LOC3 = ((*v).T == ((NU8) 7));
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(674, "dynobj.nim");
		nimln(674, "dynobj.nim");
		result = HEX5BHEX5D_732628(((tdynamicobjectHEX3Aobjecttype728040*) (v)), key);
		goto BeforeRet;
	}
	LA5: ;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NI, asint_730271)(tdynamicHEX3Aobjecttype728028* v) {
	NI result;
	nimfr("asInt", "dynobj.nim")
	result = 0;
	nimln(249, "dynobj.nim");
	{
		NIM_BOOL LOC3;
		nimln(249, "dynobj.nim");
		LOC3 = 0;
		nimln(249, "dynobj.nim");
		nimln(249, "dynobj.nim");
		LOC3 = !((v == NIM_NIL));
		if (!(LOC3)) goto LA4;
		nimln(249, "dynobj.nim");
		LOC3 = ((*v).T == ((NU8) 3));
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(249, "dynobj.nim");
		nimln(249, "dynobj.nim");
		result = (*((tdynamicintHEX3Aobjecttype728031*) (v))).Value;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		nimln(250, "dynobj.nim");
		nimln(250, "dynobj.nim");
		result = asintslow_729989(v);
		goto BeforeRet;
	}
	LA1: ;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, init_785037)(NI screenwidth, NI screenheight, NimStringDesc* ccolor) {
	NI swidth;
	NI sheight;
	NI LOC23;
	nimfr("init", "application.nim")
	nimln(49, "application.nim");
	swidth = screenwidth;
	nimln(50, "application.nim");
	sheight = screenheight;
	nimln(52, "application.nim");
	{
		NIM_BOOL LOC3;
		NimStringDesc* LOC6;
		nimln(52, "application.nim");
		LOC3 = 0;
		LOC3 = fileexists_771406(configfilename_785003);
		if (!LOC3) goto LA4;
		nimln(53, "application.nim");
		nimln(53, "application.nim");
		LOC6 = 0;
		LOC6 = readfile_10440(configfilename_785003);
		asgnRef((void**) &config_785004, fromliteral_735510(LOC6, NIM_FALSE));
		nimln(55, "application.nim");
		{
			tdynamicHEX3Aobjecttype728028* LOC9;
			tdynamicHEX3Aobjecttype728028* LOC10;
			tdynamicHEX3Aobjecttype728028* LOC13;
			tdynamicHEX3Aobjecttype728028* LOC14;
			nimln(55, "application.nim");
			nimln(55, "application.nim");
			nimln(55, "application.nim");
			nimln(55, "application.nim");
			LOC9 = 0;
			LOC9 = HEX5BHEX5D_735549(config_785004, ((NimStringDesc*) &TMP680));
			LOC10 = 0;
			LOC10 = HEX5BHEX5D_735549(LOC9, ((NimStringDesc*) &TMP681));
			if (!!((LOC10 == NIM_NIL))) goto LA11;
			nimln(56, "application.nim");
			nimln(56, "application.nim");
			nimln(56, "application.nim");
			LOC13 = 0;
			LOC13 = HEX5BHEX5D_735549(config_785004, ((NimStringDesc*) &TMP680));
			LOC14 = 0;
			LOC14 = HEX5BHEX5D_735549(LOC13, ((NimStringDesc*) &TMP681));
			swidth = asint_730271(LOC14);
		}
		LA11: ;
		nimln(57, "application.nim");
		{
			tdynamicHEX3Aobjecttype728028* LOC17;
			tdynamicHEX3Aobjecttype728028* LOC18;
			tdynamicHEX3Aobjecttype728028* LOC21;
			tdynamicHEX3Aobjecttype728028* LOC22;
			nimln(57, "application.nim");
			nimln(57, "application.nim");
			nimln(57, "application.nim");
			nimln(57, "application.nim");
			LOC17 = 0;
			LOC17 = HEX5BHEX5D_735549(config_785004, ((NimStringDesc*) &TMP680));
			LOC18 = 0;
			LOC18 = HEX5BHEX5D_735549(LOC17, ((NimStringDesc*) &TMP682));
			if (!!((LOC18 == NIM_NIL))) goto LA19;
			nimln(58, "application.nim");
			nimln(58, "application.nim");
			nimln(58, "application.nim");
			LOC21 = 0;
			LOC21 = HEX5BHEX5D_735549(config_785004, ((NimStringDesc*) &TMP680));
			LOC22 = 0;
			LOC22 = HEX5BHEX5D_735549(LOC21, ((NimStringDesc*) &TMP682));
			sheight = asint_730271(LOC22);
		}
		LA19: ;
	}
	LA4: ;
	nimln(60, "application.nim");
	nimln(60, "application.nim");
	LOC23 = 0;
	LOC23 = Dl_88419(((NI32) 32));
	nimln(61, "application.nim");
	screen_785002 = Dl_89186(swidth, sheight, 16, ((NU32) 2));
	nimln(63, "application.nim");
	glcleardepth_310802(1.0000000000000000e+00);
	nimln(64, "application.nim");
	glviewport_645202(((NI32) 0), ((NI32) 0), ((NI32) (swidth)), ((NI32) (sheight)));
	nimln(65, "application.nim");
	glmatrixmode_229002(((NU32) 5889));
	nimln(67, "application.nim");
	glloadidentity_516802();
	nimln(69, "application.nim");
	nimln(69, "application.nim");
	nimln(69, "application.nim");
	glortho_433002(0.0, ((double) (swidth)), ((double) (sheight)), 0.0, 1.0000000000000000e+01, -1.0000000000000000e+00);
	nimln(71, "application.nim");
	glmatrixmode_229002(((NU32) 5888));
	nimln(73, "application.nim");
	glenable_527802(((NU32) 3553));
	nimln(75, "application.nim");
	glloadidentity_516802();
	nimln(77, "application.nim");
	clearcolor_736007(ccolor);
	popFrame();
}

N_NIMCALL(void, quit_785105)(void) {
	nimfr("quit", "application.nim")
	nimln(80, "application.nim");
	Dl_89317(screen_785002);
	nimln(81, "application.nim");
	Dl_88435();
	popFrame();
}

N_NIMCALL(void, setwindowcaption_785109)(NimStringDesc* caption) {
	nimfr("setWindowCaption", "application.nim")
	nimln(84, "application.nim");
	Dl_89480(caption->data, "");
	popFrame();
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) (&(*dest).data[((*dest).Sup.len)- 0])), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(NimStringDesc*, HEX2A_785114)(NimStringDesc* a, NI b) {
	NimStringDesc* result;
	NimStringDesc* s;
	NI i_785130;
	NI res_785133;
	nimfr("*", "application.nim")
	result = 0;
	nimln(87, "application.nim");
	s = copyString(((NimStringDesc*) &TMP679));
	i_785130 = 0;
	nimln(1458, "system.nim");
	res_785133 = 0;
	nimln(1459, "system.nim");
	while (1) {
		NimStringDesc* LOC2;
		nimln(1459, "system.nim");
		if (!(res_785133 <= b)) goto LA1;
		nimln(1458, "system.nim");
		i_785130 = res_785133;
		nimln(88, "application.nim");
		nimln(88, "application.nim");
		LOC2 = 0;
		LOC2 = rawNewString(s->Sup.len + a->Sup.len + 0);
appendString(LOC2, s);
appendString(LOC2, a);
		s = LOC2;
		nimln(1461, "system.nim");
		res_785133 = addInt(res_785133, 1);
	} LA1: ;
	nimln(89, "application.nim");
	nimln(89, "application.nim");
	result = copyString(s);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}
N_NOINLINE(void, applicationInit)(void) {
	NimStringDesc* LOC1;
	nimfr("application", "application.nim")
	nimln(5, "application.nim");
	nimln(5, "application.nim");
	LOC1 = 0;
	LOC1 = nosgetApplicationDir();
	asgnRefNoCycle((void**) &configfilename_785003, HEX2F_772477(LOC1, ((NimStringDesc*) &TMP673)));
	nimln(8, "application.nim");
	asgnRef((void**) &v_785009, dynamicobject_728293(NIM_TRUE));
	popFrame();
}

N_NOINLINE(void, applicationDatInit)(void) {
}

