/* Generated by Nimrod Compiler v0.9.5 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nimrod -o /home/andreysh/Projects/nimrod/stone_head/nimcache/forloops.o /home/andreysh/Projects/nimrod/stone_head/nimcache/forloops.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>
typedef struct tcounterup724431 tcounterup724431;
typedef struct tcounterdown724433 tcounterdown724433;
struct  tcounterup724431  {
NI First;
NI Last;
NI Step;
NI X;
};
struct  tcounterdown724433  {
NI First;
NI Last;
NI Step;
NI X;
};
static N_INLINE(tcounterup724431, countup_724443)(NI a, NI b, NI step);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, next_724451)(tcounterup724431* it, NIM_BOOL* proceed);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(tcounterdown724433, countdown_724476)(NI a, NI b, NI step);
static N_INLINE(NI, next_724484)(tcounterdown724433* it, NIM_BOOL* proceed);
static N_INLINE(NI, subInt)(NI a, NI b);
extern TFrame* frameptr_13038;

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_13038;
	frameptr_13038 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_13038 = (*frameptr_13038).prev;
}

static N_INLINE(tcounterup724431, countup_724443)(NI a, NI b, NI step) {
	tcounterup724431 result;
	nimfr("countup", "forloops.nim")
	memset((void*)&result, 0, sizeof(result));
	nimln(44, "forloops.nim");
	result.First = a;
	nimln(45, "forloops.nim");
	result.Last = b;
	nimln(46, "forloops.nim");
	result.Step = step;
	nimln(47, "forloops.nim");
	result.X = a;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, next_724451)(tcounterup724431* it, NIM_BOOL* proceed) {
	NI result;
	nimfr("next", "forloops.nim")
	result = 0;
	nimln(50, "forloops.nim");
	result = (*it).X;
	nimln(51, "forloops.nim");
	nimln(51, "forloops.nim");
	(*proceed) = (result <= (*it).Last);
	nimln(52, "forloops.nim");
	{
		if (!(*proceed)) goto LA3;
		nimln(53, "forloops.nim");
		(*it).X = addInt((*it).X, (*it).Step);
	}
	LA3: ;
	popFrame();
	return result;
}

static N_INLINE(tcounterdown724433, countdown_724476)(NI a, NI b, NI step) {
	tcounterdown724433 result;
	nimfr("countdown", "forloops.nim")
	memset((void*)&result, 0, sizeof(result));
	nimln(56, "forloops.nim");
	result.First = a;
	nimln(57, "forloops.nim");
	result.Last = b;
	nimln(58, "forloops.nim");
	result.Step = step;
	nimln(59, "forloops.nim");
	result.X = a;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, next_724484)(tcounterdown724433* it, NIM_BOOL* proceed) {
	NI result;
	nimfr("next", "forloops.nim")
	result = 0;
	nimln(62, "forloops.nim");
	result = (*it).X;
	nimln(63, "forloops.nim");
	nimln(63, "forloops.nim");
	(*proceed) = ((*it).Last <= result);
	nimln(64, "forloops.nim");
	{
		if (!(*proceed)) goto LA3;
		nimln(65, "forloops.nim");
		(*it).X = subInt((*it).X, (*it).Step);
	}
	LA3: ;
	popFrame();
	return result;
}
N_NOINLINE(void, forloopsInit)(void) {
	nimfr("forloops", "forloops.nim")
	popFrame();
}

N_NOINLINE(void, forloopsDatInit)(void) {
}

