/* Generated by Nimrod Compiler v0.9.5 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nimrod -o /home/andreysh/Projects/nimrod/stone_head/nimcache/helperParse.o /home/andreysh/Projects/nimrod/stone_head/nimcache/helperParse.c */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct tparsestring727006 tparsestring727006;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  tparsestring727006  {
NimStringDesc* S;
NI A;
};
static N_INLINE(NIM_CHAR, current_727016)(tparsestring727006* s, NIM_BOOL* proceed);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_CHAR, next_727026)(tparsestring727006* s, NIM_BOOL* proceed);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NIM_CHAR, next_727052)(tparsestring727006* s);
static N_INLINE(NIM_CHAR, prev_727076)(tparsestring727006* s, NIM_BOOL* proceed);
static N_INLINE(NI, subInt)(NI a, NI b);
static N_INLINE(NIM_CHAR, prev_727102)(tparsestring727006* s);
static N_INLINE(void, fromliteral_727126)(NimStringDesc* s, tparsestring727006* Result);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(void, fromliteral_727132)(NimStringDesc* s, NI start, tparsestring727006* Result);
static N_INLINE(void, fromstring_727142)(NimStringDesc** s, tparsestring727006* Result);
static N_INLINE(void, fromstring_727149)(NimStringDesc** s, NI start, tparsestring727006* Result);
static N_INLINE(NI, len_727171)(tparsestring727006 s);
static N_INLINE(NimStringDesc*, HEX24_727201)(tparsestring727006 s);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI start);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI first);
static N_INLINE(NimStringDesc*, substr_727207)(tparsestring727006 s, NI first);
static N_INLINE(NimStringDesc*, substr_727214)(tparsestring727006 s, NI first, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_70824, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(NimStringDesc*, slice_727222)(tparsestring727006 s, NI length);
STRING_LITERAL(TMP260, "", 0);
extern TFrame* frameptr_13038;

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_13038;
	frameptr_13038 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_13038 = (*frameptr_13038).prev;
}

static N_INLINE(NIM_CHAR, current_727016)(tparsestring727006* s, NIM_BOOL* proceed) {
	NIM_CHAR result;
	nimfr("current", "helperParse.nim")
	result = 0;
	nimln(25, "helperParse.nim");
	nimln(25, "helperParse.nim");
	nimln(25, "helperParse.nim");
	(*proceed) = ((*s).A < (*s).S->Sup.len);
	nimln(26, "helperParse.nim");
	nimln(26, "helperParse.nim");
	if ((NU)((*s).A) > (NU)((*s).S->Sup.len)) raiseIndexError();
	result = (*s).S->data[(*s).A];
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NIM_CHAR, next_727026)(tparsestring727006* s, NIM_BOOL* proceed) {
	NIM_CHAR result;
	nimfr("next", "helperParse.nim")
	result = 0;
	nimln(29, "helperParse.nim");
	nimln(29, "helperParse.nim");
	nimln(29, "helperParse.nim");
	(*proceed) = ((*s).A < (*s).S->Sup.len);
	nimln(30, "helperParse.nim");
	{
		if (!(*proceed)) goto LA3;
		nimln(30, "helperParse.nim");
		(*s).A = addInt((*s).A, 1);
	}
	LA3: ;
	nimln(31, "helperParse.nim");
	if ((NU)((*s).A) > (NU)((*s).S->Sup.len)) raiseIndexError();
	result = (*s).S->data[(*s).A];
	popFrame();
	return result;
}

static N_INLINE(NIM_CHAR, next_727052)(tparsestring727006* s) {
	NIM_CHAR result;
	nimfr("next", "helperParse.nim")
	result = 0;
	nimln(34, "helperParse.nim");
	{
		nimln(34, "helperParse.nim");
		nimln(34, "helperParse.nim");
		if (!((*s).A < (*s).S->Sup.len)) goto LA3;
		nimln(35, "helperParse.nim");
		(*s).A = addInt((*s).A, 1);
	}
	LA3: ;
	nimln(36, "helperParse.nim");
	if ((NU)((*s).A) > (NU)((*s).S->Sup.len)) raiseIndexError();
	result = (*s).S->data[(*s).A];
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NIM_CHAR, prev_727076)(tparsestring727006* s, NIM_BOOL* proceed) {
	NIM_CHAR result;
	nimfr("prev", "helperParse.nim")
	result = 0;
	nimln(39, "helperParse.nim");
	nimln(39, "helperParse.nim");
	(*proceed) = (0 < (*s).A);
	nimln(40, "helperParse.nim");
	{
		if (!(*proceed)) goto LA3;
		nimln(41, "helperParse.nim");
		(*s).A = subInt((*s).A, 1);
		nimln(42, "helperParse.nim");
		if ((NU)((*s).A) > (NU)((*s).S->Sup.len)) raiseIndexError();
		result = (*s).S->data[(*s).A];
	}
	goto LA1;
	LA3: ;
	{
		nimln(43, "helperParse.nim");
		result = 0;
	}
	LA1: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_CHAR, prev_727102)(tparsestring727006* s) {
	NIM_CHAR result;
	nimfr("prev", "helperParse.nim")
	result = 0;
	nimln(46, "helperParse.nim");
	{
		nimln(46, "helperParse.nim");
		if (!(0 < (*s).A)) goto LA3;
		nimln(47, "helperParse.nim");
		(*s).A = subInt((*s).A, 1);
		nimln(48, "helperParse.nim");
		if ((NU)((*s).A) > (NU)((*s).S->Sup.len)) raiseIndexError();
		result = (*s).S->data[(*s).A];
	}
	goto LA1;
	LA3: ;
	{
		nimln(49, "helperParse.nim");
		result = 0;
	}
	LA1: ;
	popFrame();
	return result;
}

static N_INLINE(void, fromliteral_727126)(NimStringDesc* s, tparsestring727006* Result) {
	nimfr("fromLiteral", "helperParse.nim")
	nimln(53, "helperParse.nim");
	{
		nimln(53, "helperParse.nim");
		nimln(53, "helperParse.nim");
		if (!!(s == 0)) goto LA3;
		nimln(53, "helperParse.nim");
		unsureAsgnRef((void**) &(*Result).S, copyString(s));
	}
	goto LA1;
	LA3: ;
	{
		nimln(54, "helperParse.nim");
		unsureAsgnRef((void**) &(*Result).S, copyString(((NimStringDesc*) &TMP260)));
	}
	LA1: ;
	popFrame();
}

static N_INLINE(void, fromliteral_727132)(NimStringDesc* s, NI start, tparsestring727006* Result) {
	nimfr("fromLiteral", "helperParse.nim")
	nimln(57, "helperParse.nim");
	{
		nimln(57, "helperParse.nim");
		nimln(57, "helperParse.nim");
		if (!!(s == 0)) goto LA3;
		nimln(57, "helperParse.nim");
		unsureAsgnRef((void**) &(*Result).S, copyString(s));
	}
	goto LA1;
	LA3: ;
	{
		nimln(58, "helperParse.nim");
		unsureAsgnRef((void**) &(*Result).S, copyString(((NimStringDesc*) &TMP260)));
	}
	LA1: ;
	nimln(59, "helperParse.nim");
	nimln(59, "helperParse.nim");
	nimln(59, "helperParse.nim");
	(*Result).A = ((start <= (*Result).S->Sup.len) ? start : (*Result).S->Sup.len);
	popFrame();
}

static N_INLINE(void, fromstring_727142)(NimStringDesc** s, tparsestring727006* Result) {
	nimfr("fromString", "helperParse.nim")
	nimln(62, "helperParse.nim");
	{
		nimln(62, "helperParse.nim");
		nimln(62, "helperParse.nim");
		if (!!((*s) == 0)) goto LA3;
		nimln(62, "helperParse.nim");
		unsureAsgnRef((void**) &(*Result).S, (*s));
	}
	goto LA1;
	LA3: ;
	{
		nimln(63, "helperParse.nim");
		unsureAsgnRef((void**) &(*Result).S, copyString(((NimStringDesc*) &TMP260)));
	}
	LA1: ;
	popFrame();
}

static N_INLINE(void, fromstring_727149)(NimStringDesc** s, NI start, tparsestring727006* Result) {
	nimfr("fromString", "helperParse.nim")
	nimln(66, "helperParse.nim");
	{
		nimln(66, "helperParse.nim");
		nimln(66, "helperParse.nim");
		if (!!((*s) == 0)) goto LA3;
		nimln(66, "helperParse.nim");
		unsureAsgnRef((void**) &(*Result).S, (*s));
	}
	goto LA1;
	LA3: ;
	{
		nimln(67, "helperParse.nim");
		unsureAsgnRef((void**) &(*Result).S, copyString(((NimStringDesc*) &TMP260)));
	}
	LA1: ;
	nimln(68, "helperParse.nim");
	nimln(68, "helperParse.nim");
	nimln(68, "helperParse.nim");
	(*Result).A = ((start <= (*Result).S->Sup.len) ? start : (*Result).S->Sup.len);
	popFrame();
}

static N_INLINE(NI, len_727171)(tparsestring727006 s) {
	NI result;
	NI LOC1;
	NI TMP261;
	nimfr("len", "helperParse.nim")
	result = 0;
	nimln(75, "helperParse.nim");
	nimln(75, "helperParse.nim");
	nimln(75, "helperParse.nim");
	nimln(75, "helperParse.nim");
	LOC1 = 0;
	LOC1 = len_727171(s);
	TMP261 = subInt(LOC1, s.A);
	result = (NI64)(TMP261);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NimStringDesc*, HEX24_727201)(tparsestring727006 s) {
	NimStringDesc* result;
	nimfr("$", "helperParse.nim")
	result = 0;
	nimln(86, "helperParse.nim");
	nimln(86, "helperParse.nim");
	nimln(86, "helperParse.nim");
	result = copyStr(s.S, s.A);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NimStringDesc*, substr_727207)(tparsestring727006 s, NI first) {
	NimStringDesc* result;
	NI TMP262;
	nimfr("substr", "helperParse.nim")
	result = 0;
	nimln(89, "helperParse.nim");
	nimln(89, "helperParse.nim");
	nimln(89, "helperParse.nim");
	nimln(89, "helperParse.nim");
	TMP262 = addInt(s.A, first);
	result = copyStr(s.S, (NI64)(TMP262));
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NimStringDesc*, substr_727214)(tparsestring727006 s, NI first, NI last) {
	NimStringDesc* result;
	NI TMP263;
	NI TMP264;
	nimfr("substr", "helperParse.nim")
	result = 0;
	nimln(92, "helperParse.nim");
	nimln(92, "helperParse.nim");
	nimln(92, "helperParse.nim");
	nimln(92, "helperParse.nim");
	TMP263 = addInt(s.A, first);
	nimln(92, "helperParse.nim");
	TMP264 = addInt(s.A, last);
	result = copyStrLast(s.S, (NI64)(TMP263), (NI64)(TMP264));
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NimStringDesc*, slice_727222)(tparsestring727006 s, NI length) {
	NimStringDesc* result;
	NI TMP265;
	NI TMP266;
	nimfr("slice", "helperParse.nim")
	result = 0;
	nimln(95, "helperParse.nim");
	nimln(95, "helperParse.nim");
	nimln(95, "helperParse.nim");
	nimln(95, "helperParse.nim");
	nimln(95, "helperParse.nim");
	TMP265 = addInt(s.A, length);
	TMP266 = subInt((NI64)(TMP265), 1);
	result = copyStrLast(s.S, s.A, (NI64)(TMP266));
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}
N_NOINLINE(void, helperParseInit)(void) {
	nimfr("helperParse", "helperParse.nim")
	popFrame();
}

N_NOINLINE(void, helperParseDatInit)(void) {
}

