/* Generated by Nimrod Compiler v0.9.5 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nimrod -o /home/andreysh/Projects/nimrod/stone_head/nimcache/lazybtree.o /home/andreysh/Projects/nimrod/stone_head/nimcache/lazybtree.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>

#include <stdio.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tcell41290 tcell41290;
typedef struct TNimType TNimType;
typedef struct tcellseq41306 tcellseq41306;
typedef struct tgcheap43216 tgcheap43216;
typedef struct tcellset41302 tcellset41302;
typedef struct tpagedesc41298 tpagedesc41298;
typedef struct tmemregion23610 tmemregion23610;
typedef struct tsmallchunk22838 tsmallchunk22838;
typedef struct tllchunk23604 tllchunk23604;
typedef struct tbigchunk22840 tbigchunk22840;
typedef struct tintset22815 tintset22815;
typedef struct ttrunk22811 ttrunk22811;
typedef struct tavlnode23608 tavlnode23608;
typedef struct tgcstat43214 tgcstat43214;
typedef struct tbtree728049 tbtree728049;
typedef struct titems728052 titems728052;
typedef struct titem728056 titem728056;
typedef struct TNimNode TNimNode;
typedef struct tdynamicHEX3Aobjecttype728028 tdynamicHEX3Aobjecttype728028;
typedef struct rpath728495 rpath728495;
typedef struct titem731043 titem731043;
typedef struct tbtree731036 tbtree731036;
typedef struct rpath731113 rpath731113;
typedef struct titems731039 titems731039;
typedef struct riteratorkeys733093 riteratorkeys733093;
typedef struct rtreeiterator733096 rtreeiterator733096;
typedef struct riteratorvalues733183 riteratorvalues733183;
typedef struct riteratorpairs733251 riteratorpairs733251;
typedef struct tbasechunk22836 tbasechunk22836;
typedef struct tfreecell22828 tfreecell22828;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  tcell41290  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq41306  {
NI Len;
NI Cap;
tcell41290** D;
};
struct  tcellset41302  {
NI Counter;
NI Max;
tpagedesc41298* Head;
tpagedesc41298** Data;
};
typedef tsmallchunk22838* TY23622[512];
typedef ttrunk22811* ttrunkbuckets22813[256];
struct  tintset22815  {
ttrunkbuckets22813 Data;
};
struct  tmemregion23610  {
NI Minlargeobj;
NI Maxlargeobj;
TY23622 Freesmallchunks;
tllchunk23604* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk22840* Freechunkslist;
tintset22815 Chunkstarts;
tavlnode23608* Root;
tavlnode23608* Deleted;
tavlnode23608* Last;
tavlnode23608* Freeavlnodes;
};
struct  tgcstat43214  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap43216  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq41306 Zct;
tcellseq41306 Decstack;
tcellset41302 Cycleroots;
tcellseq41306 Tempstack;
NI Recgclock;
tmemregion23610 Region;
tgcstat43214 Stat;
};
struct  tbtree728049  {
titems728052* Slots;
tbtree728049* Left;
NI32 Count;
};
typedef N_NIMCALL_PTR(void, TY2289) (void* p, NI op);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY2289 marker;
};
struct  titem728056  {
NimStringDesc* Key;
tdynamicHEX3Aobjecttype728028* Value;
tbtree728049* Node;
NIM_BOOL Valset;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct rpath728495 {
NI Field0;
tbtree728049* Field1;
};
typedef rpath728495 TY728488[31];
struct rpath731113 {
NI Field0;
tbtree731036* Field1;
};
typedef rpath731113 TY731106[31];
struct  tbtree731036  {
titems731039* Slots;
tbtree731036* Left;
NI32 Count;
};
struct  titem731043  {
tdynamicHEX3Aobjecttype728028* Key;
NimStringDesc* Value;
tbtree731036* Node;
NIM_BOOL Valset;
};
struct  rtreeiterator733096  {
TNimType* m_type;
TY728488 Path;
NI Level;
titem728056* Current;
};
struct  riteratorkeys733093  {
  rtreeiterator733096 Sup;
};
struct  riteratorvalues733183  {
  rtreeiterator733096 Sup;
};
struct  riteratorpairs733251  {
  rtreeiterator733096 Sup;
};
typedef struct {
N_NIMCALL_PTR(void, ClPrc) (NimStringDesc* akey_734415, tdynamicHEX3Aobjecttype728028* avalue_734417, void* ClEnv);
void* ClEnv;
} TY734421;
typedef N_CLOSURE_PTR(void, TMP418) (NimStringDesc* akey_734415, tdynamicHEX3Aobjecttype728028* avalue_734417);
typedef NI TY22818[8];
struct  tpagedesc41298  {
tpagedesc41298* Next;
NI Key;
TY22818 Bits;
};
struct  tbasechunk22836  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk22838  {
  tbasechunk22836 Sup;
tsmallchunk22838* Next;
tsmallchunk22838* Prev;
tfreecell22828* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk23604  {
NI Size;
NI Acc;
tllchunk23604* Next;
};
struct  tbigchunk22840  {
  tbasechunk22836 Sup;
tbigchunk22840* Next;
tbigchunk22840* Prev;
NI Align;
NF Data;
};
struct  ttrunk22811  {
ttrunk22811* Next;
NI Key;
TY22818 Bits;
};
typedef tavlnode23608* TY23614[2];
struct  tavlnode23608  {
TY23614 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tdynamicHEX3Aobjecttype728028  {
TNimType* m_type;
NU8 T;
};
struct  tfreecell22828  {
tfreecell22828* Next;
NI Zerofield;
};
struct titems728052 {
  TGenericSeq Sup;
  titem728056* data[SEQ_DECL_SIZE];
};
struct titems731039 {
  TGenericSeq Sup;
  titem731043* data[SEQ_DECL_SIZE];
};
static N_INLINE(NI, cmpinline_721516)(NimStringDesc* a, NimStringDesc* b);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tcell41290*, usrtocell_44643)(void* usr);
static N_INLINE(void, rtladdzct_46202)(tcell41290* c);
N_NOINLINE(void, addzct_44618)(tcellseq41306* s, tcell41290* c);
N_NIMCALL(void, swrite_722301)(NimStringDesc** data, NI dataLen0);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_NIMCALL(void, swriteln_722322)(NimStringDesc** data, NI dataLen0);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP282)(void* p, NI op);
N_NIMCALL(void, TMP283)(void* p, NI op);
N_NIMCALL(void, TMP284)(void* p, NI op);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
static N_INLINE(NI, bsearch_728578)(tbtree728049* haystack_728585, NimStringDesc* needle_728588);
N_NIMCALL(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemsize, NI newlen);
static N_INLINE(void, arrins_728778)(titems728052** arr_728786, NI x_728790, NI cnt_728792);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(titem728056*, setitem_728817)(NimStringDesc* akey_728822, tbtree728049* anode_728826);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
static N_INLINE(void, arrcopyclear_729046)(titems728052** dest_729054, titems728052** source_729062, NI startdest_729066, NI startsource_729068, NI cnt_729070);
static N_INLINE(NI, bsearch_731196)(tbtree731036* haystack_731203, tdynamicHEX3Aobjecttype728028* needle_731206);
N_NIMCALL(NI, cmp_731410)(tdynamicHEX3Aobjecttype728028* x_731414, tdynamicHEX3Aobjecttype728028* y_731416);
static N_INLINE(void, arrins_731621)(titems731039** arr_731629, NI x_731633, NI cnt_731635);
static N_INLINE(titem731043*, setitem_731660)(tdynamicHEX3Aobjecttype728028* akey_731665, tbtree731036* anode_731669);
N_NIMCALL(void, TMP383)(void* p, NI op);
N_NIMCALL(void, TMP384)(void* p, NI op);
N_NIMCALL(void, TMP385)(void* p, NI op);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_47027)(tcell41290* c);
static N_INLINE(NIM_BOOL, canbecycleroot_44662)(tcell41290* c);
static N_INLINE(void, rtladdcycleroot_45435)(tcell41290* c);
N_NOINLINE(void, incl_42055)(tcellset41302* s, tcell41290* cell);
static N_INLINE(void, decref_46602)(tcell41290* c);
static N_INLINE(void, arrcopyclear_731846)(titems731039** dest_731854, titems731039** source_731862, NI startdest_731866, NI startsource_731868, NI cnt_731870);
N_NIMCALL(void, TMP414)(void* p, NI op);
static N_INLINE(void, inititerator_733151)(rtreeiterator733096* it_733158, tbtree728049* n_733163);
N_NIMCALL(void, TMP415)(void* p, NI op);
N_NIMCALL(void, TMP416)(void* p, NI op);
static N_INLINE(NIM_BOOL, isclean_733523)(titem728056* it_733532);
N_NIMCALL(void, foreach_734404)(tbtree728049* n_734411, TY734421 visit_734420);
STRING_LITERAL(TMP250, "", 0);
extern TFrame* frameptr_13038;
NimStringDesc* line_722298;
extern tgcheap43216 gch_43244;
TNimType NTI728049; /* TBTree */
TNimType NTI728056; /* TItem */
extern TNimType NTI143; /* string */
extern TNimType NTI728005; /* TDynamic */
extern TNimType NTI134; /* bool */
TNimType NTI728053; /* ref TItem[string, TDynamic] */
TNimType NTI728052; /* TItems */
extern TNimType NTI112; /* int32 */
TNimType NTI728046; /* PBtree */
TNimType NTI731043; /* TItem */
TNimType NTI731036; /* TBTree */
TNimType NTI731039; /* TItems */
TNimType NTI731033; /* PBtree */
TNimType NTI731101; /* ref TItem[TDynamic, string] */
TNimType NTI733096; /* RTreeIterator */
TNimType NTI728495; /* RPath */
extern TNimType NTI106; /* int */
TNimType NTI728488; /* array[0..30, RPath[string, TDynamic]] */
TNimType NTI733093; /* RIteratorKeys */
TNimType NTI733090; /* TIteratorKeys */
TNimType NTI733183; /* RIteratorValues */
TNimType NTI733180; /* TIteratorValues */
TNimType NTI733251; /* RIteratorPairs */
TNimType NTI733248; /* TIteratorPairs */

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_13038;
	frameptr_13038 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_13038 = (*frameptr_13038).prev;
}

static N_INLINE(NI, cmpinline_721516)(NimStringDesc* a, NimStringDesc* b) {
	NI result;
	NI x;
	nimfr("cmpInline", "lazybtree.nim")
	result = 0;
	nimln(96, "lazybtree.nim");
	x = 0;
	nimln(97, "lazybtree.nim");
	while (1) {
		NI TMP248;
		NI TMP249;
		nimln(98, "lazybtree.nim");
		nimln(98, "lazybtree.nim");
		nimln(98, "lazybtree.nim");
		if ((NU)(x) > (NU)(a->Sup.len)) raiseIndexError();
		nimln(98, "lazybtree.nim");
		if ((NU)(x) > (NU)(b->Sup.len)) raiseIndexError();
		TMP248 = subInt(((NI) (((NU8)(a->data[x])))), ((NI) (((NU8)(b->data[x])))));
		result = (NI64)(TMP248);
		nimln(99, "lazybtree.nim");
		{
			NIM_BOOL LOC4;
			nimln(99, "lazybtree.nim");
			LOC4 = 0;
			nimln(99, "lazybtree.nim");
			nimln(99, "lazybtree.nim");
			LOC4 = !((result == 0));
			if (LOC4) goto LA5;
			nimln(99, "lazybtree.nim");
			if ((NU)(x) > (NU)(a->Sup.len)) raiseIndexError();
			LOC4 = ((NU8)(a->data[x]) == (NU8)(0));
			LA5: ;
			if (!LOC4) goto LA6;
			nimln(99, "lazybtree.nim");
			goto LA1;
		}
		LA6: ;
		nimln(100, "lazybtree.nim");
		x = addInt(x, 1);
		nimln(101, "lazybtree.nim");
		nimln(101, "lazybtree.nim");
		nimln(101, "lazybtree.nim");
		if ((NU)(x) > (NU)(a->Sup.len)) raiseIndexError();
		nimln(101, "lazybtree.nim");
		if ((NU)(x) > (NU)(b->Sup.len)) raiseIndexError();
		TMP249 = subInt(((NI) (((NU8)(a->data[x])))), ((NI) (((NU8)(b->data[x])))));
		result = (NI64)(TMP249);
		nimln(102, "lazybtree.nim");
		{
			NIM_BOOL LOC10;
			nimln(102, "lazybtree.nim");
			LOC10 = 0;
			nimln(102, "lazybtree.nim");
			nimln(102, "lazybtree.nim");
			LOC10 = !((result == 0));
			if (LOC10) goto LA11;
			nimln(102, "lazybtree.nim");
			if ((NU)(x) > (NU)(a->Sup.len)) raiseIndexError();
			LOC10 = ((NU8)(a->data[x]) == (NU8)(0));
			LA11: ;
			if (!LOC10) goto LA12;
			nimln(102, "lazybtree.nim");
			goto LA1;
		}
		LA12: ;
		nimln(103, "lazybtree.nim");
		x = addInt(x, 1);
	} LA1: ;
	popFrame();
	return result;
}

static N_INLINE(tcell41290*, usrtocell_44643)(void* usr) {
	tcell41290* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell41290*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell41290))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_46202)(tcell41290* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_44618(&gch_43244.Zct, c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell41290* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_44643(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_46202(c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) (&(*dest).data[((*dest).Sup.len)- 0])), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell41290* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_44643(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell41290* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_44643((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_46202(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(void, swrite_722301)(NimStringDesc** data, NI dataLen0) {
	NimStringDesc* s_722316;
	NI i_722318;
	nimfr("swrite", "lazybtree.nim")
	s_722316 = 0;
	nimln(1531, "system.nim");
	i_722318 = 0;
	nimln(1532, "system.nim");
	while (1) {
		NimStringDesc* LOC2;
		nimln(1532, "system.nim");
		nimln(1532, "system.nim");
		if (!(i_722318 < dataLen0)) goto LA1;
		nimln(1533, "system.nim");
		if ((NU)(i_722318) >= (NU)(dataLen0)) raiseIndexError();
		s_722316 = data[i_722318];
		nimln(263, "lazybtree.nim");
		nimln(263, "lazybtree.nim");
		LOC2 = 0;
		LOC2 = rawNewString(line_722298->Sup.len + s_722316->Sup.len + 0);
appendString(LOC2, line_722298);
appendString(LOC2, s_722316);
		asgnRefNoCycle((void**) &line_722298, LOC2);
		nimln(1534, "system.nim");
		i_722318 = addInt(i_722318, 1);
	} LA1: ;
	popFrame();
}

N_NIMCALL(void, swriteln_722322)(NimStringDesc** data, NI dataLen0) {
	NimStringDesc* LOC1;
	nimfr("swriteln", "lazybtree.nim")
	nimln(266, "lazybtree.nim");
	swrite_722301(data, dataLen0);
	nimln(267, "lazybtree.nim");
	printf("%s\012", (line_722298)->data);
	nimln(268, "lazybtree.nim");
	LOC1 = 0;
	LOC1 = line_722298; line_722298 = copyStringRC1(((NimStringDesc*) &TMP250));
	if (LOC1) nimGCunrefNoCycle(LOC1);
	popFrame();
}
N_NIMCALL(void, TMP282)(void* p, NI op) {
	titem728056* a;
	a = (titem728056*)p;
	nimGCvisit((void*)(*a).Key, op);
	nimGCvisit((void*)(*a).Value, op);
	nimGCvisit((void*)(*a).Node, op);
}
N_NIMCALL(void, TMP283)(void* p, NI op) {
	titems728052* a;
	NI LOC1;
	a = (titems728052*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1], op);
	}
}
N_NIMCALL(void, TMP284)(void* p, NI op) {
	tbtree728049* a;
	a = (tbtree728049*)p;
	nimGCvisit((void*)(*a).Slots, op);
	nimGCvisit((void*)(*a).Left, op);
}

static N_INLINE(NI, bsearch_728578)(tbtree728049* haystack_728585, NimStringDesc* needle_728588) {
	NI result;
	NI sw;
	NI h_728591;
	NI TMP286;
	nimfr("bSearch", "lazybtree.nim")
	result = 0;
	sw = 0;
	nimln(2, "binsearch.nim");
	result = 0;
	nimln(3, "binsearch.nim");
	nimln(3, "binsearch.nim");
	TMP286 = subInt(((NI) ((*haystack_728585).Count)), 1);
	h_728591 = (NI64)(TMP286);
	{
		nimln(5, "binsearch.nim");
		while (1) {
			NI i_728595;
			NI TMP287;
			nimln(5, "binsearch.nim");
			if (!(result <= h_728591)) goto LA2;
			nimln(6, "binsearch.nim");
			nimln(6, "binsearch.nim");
			nimln(6, "binsearch.nim");
			TMP287 = addInt(result, h_728591);
			i_728595 = (NI)((NU64)((NI64)(TMP287)) >> (NU64)(1));
			nimln(7, "binsearch.nim");
			{
				NI TMP288;
				nimln(127, "lazybtree.nim");
				if ((NU)(i_728595) >= (NU)((*haystack_728585).Slots->Sup.len)) raiseIndexError();
				sw = cmpinline_721516((*(*haystack_728585).Slots->data[i_728595]).Key, needle_728588);
				nimln(128, "lazybtree.nim");
				if (!(sw < 0)) goto LA5;
				nimln(7, "binsearch.nim");
				nimln(7, "binsearch.nim");
				TMP288 = addInt(i_728595, 1);
				result = (NI64)(TMP288);
			}
			goto LA3;
			LA5: ;
			{
				NI TMP289;
				nimln(8, "binsearch.nim");
				if (!(sw == 0)) goto LA8;
				nimln(9, "binsearch.nim");
				nimln(9, "binsearch.nim");
				TMP289 = addInt(i_728595, 1);
				result = (NI64)(TMP289);
				nimln(10, "binsearch.nim");
				goto LA1;
			}
			goto LA3;
			LA8: ;
			{
				NI TMP290;
				nimln(12, "binsearch.nim");
				nimln(12, "binsearch.nim");
				TMP290 = subInt(i_728595, 1);
				h_728591 = (NI64)(TMP290);
			}
			LA3: ;
		} LA2: ;
		nimln(13, "binsearch.nim");
		nimln(13, "binsearch.nim");
		if (result == (IL64(-9223372036854775807) - IL64(1))) raiseOverflow();
		result = ((NI64)-(result));
	} LA1: ;
	popFrame();
	return result;
}

static N_INLINE(void, arrins_728778)(titems728052** arr_728786, NI x_728790, NI cnt_728792) {
	NI delta;
	NI TMP292;
	nimfr("arrIns", "lazybtree.nim")
	nimln(148, "lazybtree.nim");
	nimln(148, "lazybtree.nim");
	TMP292 = subInt(cnt_728792, x_728790);
	delta = (NI64)(TMP292);
	nimln(149, "lazybtree.nim");
	{
		nimln(149, "lazybtree.nim");
		if (!(0 <= x_728790)) goto LA3;
		nimln(150, "lazybtree.nim");
		{
			NI TMP293;
			NI TMP294;
			nimln(150, "lazybtree.nim");
			if (!(0 < delta)) goto LA7;
			nimln(151, "lazybtree.nim");
			nimln(151, "lazybtree.nim");
			TMP293 = addInt(x_728790, 1);
			if ((NU)((NI64)(TMP293)) >= (NU)((*arr_728786)->Sup.len)) raiseIndexError();
			if ((NU)(x_728790) >= (NU)((*arr_728786)->Sup.len)) raiseIndexError();
			nimln(151, "lazybtree.nim");
			TMP294 = mulInt(8, delta);
			memmove(((void*) (&(*arr_728786)->data[(NI64)(TMP293)])), ((void*) (&(*arr_728786)->data[x_728790])), (NI64)(TMP294));
		}
		LA7: ;
		nimln(152, "lazybtree.nim");
		if ((NU)(x_728790) >= (NU)((*arr_728786)->Sup.len)) raiseIndexError();
		(*((NI*) (&(*arr_728786)->data[x_728790]))) = 0;
	}
	LA3: ;
	popFrame();
}

static N_INLINE(titem728056*, setitem_728817)(NimStringDesc* akey_728822, tbtree728049* anode_728826) {
	titem728056* result;
	NimStringDesc* LOC1;
	nimfr("setItem", "lazybtree.nim")
	result = 0;
	nimln(89, "lazybtree.nim");
	result = (titem728056*) newObj((&NTI728053), sizeof(titem728056));
	nimln(90, "lazybtree.nim");
	LOC1 = 0;
	LOC1 = (*result).Key; (*result).Key = copyStringRC1(akey_728822);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	nimln(91, "lazybtree.nim");
	asgnRefNoCycle((void**) &(*result).Node, anode_728826);
	popFrame();
	return result;
}

static N_INLINE(void, arrcopyclear_729046)(titems728052** dest_729054, titems728052** source_729062, NI startdest_729066, NI startsource_729068, NI cnt_729070) {
	nimfr("arrCopyClear", "lazybtree.nim")
	nimln(155, "lazybtree.nim");
	{
		NI TMP296;
		NI TMP297;
		nimln(155, "lazybtree.nim");
		if (!(0 < cnt_729070)) goto LA3;
		nimln(156, "lazybtree.nim");
		if ((NU)(startdest_729066) >= (NU)((*dest_729054)->Sup.len)) raiseIndexError();
		if ((NU)(startsource_729068) >= (NU)((*source_729062)->Sup.len)) raiseIndexError();
		nimln(156, "lazybtree.nim");
		TMP296 = mulInt(cnt_729070, 8);
		memcpy(((void*) (&(*dest_729054)->data[startdest_729066])), ((void*) (&(*source_729062)->data[startsource_729068])), (NI64)(TMP296));
		nimln(157, "lazybtree.nim");
		if ((NU)(startsource_729068) >= (NU)((*source_729062)->Sup.len)) raiseIndexError();
		nimln(157, "lazybtree.nim");
		TMP297 = mulInt(cnt_729070, 8);
		zeroMem(((void*) (&(*source_729062)->data[startsource_729068])), (NI64)(TMP297));
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(titem728056*, findorinsert_728469)(tbtree728049** anode_728478, NimStringDesc* akey_728482) {
	titem728056* result;
	TY728488 path;
	NI h_728504;
	tbtree728049* node_728558;
	tbtree728049* left;
	titem728056* litem;
	nimfr("findOrInsert", "lazybtree.nim")
	result = 0;
	memset((void*)path, 0, sizeof(path));
	nimln(320, "lazybtree.nim");
	h_728504 = 0;
	nimln(374, "lazybtree.nim");
	unsureAsgnRef((void**) &node_728558, (*anode_728478));
	nimln(188, "lazybtree.nim");
	while (1) {
		NI x_728487;
		nimln(188, "lazybtree.nim");
		nimln(188, "lazybtree.nim");
		if (!!((node_728558 == NIM_NIL))) goto LA1;
		nimln(189, "lazybtree.nim");
		x_728487 = bsearch_728578(node_728558, akey_728482);
		nimln(190, "lazybtree.nim");
		{
			nimln(190, "lazybtree.nim");
			if (!(x_728487 <= 0)) goto LA4;
			nimln(322, "lazybtree.nim");
			if ((NU)(h_728504) > (NU)(30)) raiseIndexError();
			path[(h_728504)- 0].Field1 = node_728558;
			nimln(323, "lazybtree.nim");
			if ((NU)(h_728504) > (NU)(30)) raiseIndexError();
			nimln(323, "lazybtree.nim");
			if (x_728487 == (IL64(-9223372036854775807) - IL64(1))) raiseOverflow();
			path[(h_728504)- 0].Field0 = ((NI64)-(x_728487));
			nimln(324, "lazybtree.nim");
			h_728504 = addInt(h_728504, 1);
			nimln(192, "lazybtree.nim");
			{
				nimln(192, "lazybtree.nim");
				if (!(x_728487 == 0)) goto LA8;
				nimln(193, "lazybtree.nim");
				unsureAsgnRef((void**) &node_728558, (*node_728558).Left);
			}
			goto LA6;
			LA8: ;
			{
				NI TMP291;
				nimln(195, "lazybtree.nim");
				nimln(195, "lazybtree.nim");
				nimln(195, "lazybtree.nim");
				if (x_728487 == (IL64(-9223372036854775807) - IL64(1))) raiseOverflow();
				TMP291 = subInt(((NI64)-(x_728487)), 1);
				x_728487 = (NI64)(TMP291);
				nimln(196, "lazybtree.nim");
				{
					nimln(196, "lazybtree.nim");
					if (!(x_728487 < ((NI) ((*node_728558).Count)))) goto LA13;
					nimln(197, "lazybtree.nim");
					if ((NU)(x_728487) >= (NU)((*node_728558).Slots->Sup.len)) raiseIndexError();
					unsureAsgnRef((void**) &node_728558, (*(*node_728558).Slots->data[x_728487]).Node);
				}
				goto LA11;
				LA13: ;
				{
					nimln(199, "lazybtree.nim");
					goto LA1;
				}
				LA11: ;
			}
			LA6: ;
		}
		goto LA2;
		LA4: ;
		{
			nimln(201, "lazybtree.nim");
			x_728487 = subInt(x_728487, 1);
			nimln(326, "lazybtree.nim");
			nimln(326, "lazybtree.nim");
			if ((NU)(x_728487) >= (NU)((*node_728558).Slots->Sup.len)) raiseIndexError();
			result = (*node_728558).Slots->data[x_728487];
			goto BeforeRet;
		}
		LA2: ;
	} LA1: ;
	nimln(376, "lazybtree.nim");
	h_728504 = subInt(h_728504, 1);
	left = 0;
	litem = 0;
	nimln(379, "lazybtree.nim");
	while (1) {
		nimln(379, "lazybtree.nim");
		if (!(0 <= h_728504)) goto LA17;
		nimln(380, "lazybtree.nim");
		{
			NI x_728678;
			NI TMP295;
			nimln(380, "lazybtree.nim");
			if ((NU)(h_728504) > (NU)(30)) raiseIndexError();
			if (!((*path[(h_728504)- 0].Field1).Count < ((NI32) 128))) goto LA20;
			nimln(335, "lazybtree.nim");
			if ((NU)(h_728504) > (NU)(30)) raiseIndexError();
			x_728678 = path[(h_728504)- 0].Field0;
			nimln(336, "lazybtree.nim");
			if ((NU)(h_728504) > (NU)(30)) raiseIndexError();
			(*path[(h_728504)- 0].Field1).Count = addInt((*path[(h_728504)- 0].Field1).Count, 1);
			nimln(337, "lazybtree.nim");
			if ((NU)(h_728504) > (NU)(30)) raiseIndexError();
			switch ((*path[(h_728504)- 0].Field1).Count) {
			case 2:
			{
				nimln(338, "lazybtree.nim");
				if ((NU)(h_728504) > (NU)(30)) raiseIndexError();
				(*path[(h_728504)- 0].Field1).Slots = (titems728052*) setLengthSeq(&((*path[(h_728504)- 0].Field1).Slots)->Sup, sizeof(titem728056*), 16);
			}
			break;
			case 16:
			{
				nimln(339, "lazybtree.nim");
				if ((NU)(h_728504) > (NU)(30)) raiseIndexError();
				(*path[(h_728504)- 0].Field1).Slots = (titems728052*) setLengthSeq(&((*path[(h_728504)- 0].Field1).Slots)->Sup, sizeof(titem728056*), 32);
			}
			break;
			case 32:
			{
				nimln(340, "lazybtree.nim");
				if ((NU)(h_728504) > (NU)(30)) raiseIndexError();
				(*path[(h_728504)- 0].Field1).Slots = (titems728052*) setLengthSeq(&((*path[(h_728504)- 0].Field1).Slots)->Sup, sizeof(titem728056*), 80);
			}
			break;
			case 80:
			{
				nimln(341, "lazybtree.nim");
				if ((NU)(h_728504) > (NU)(30)) raiseIndexError();
				(*path[(h_728504)- 0].Field1).Slots = (titems728052*) setLengthSeq(&((*path[(h_728504)- 0].Field1).Slots)->Sup, sizeof(titem728056*), 96);
			}
			break;
			case 96:
			{
				nimln(342, "lazybtree.nim");
				if ((NU)(h_728504) > (NU)(30)) raiseIndexError();
				(*path[(h_728504)- 0].Field1).Slots = (titems728052*) setLengthSeq(&((*path[(h_728504)- 0].Field1).Slots)->Sup, sizeof(titem728056*), 128);
			}
			break;
			default:
			{
			}
			break;
			}
			nimln(344, "lazybtree.nim");
			if ((NU)(h_728504) > (NU)(30)) raiseIndexError();
			nimln(344, "lazybtree.nim");
			if ((NU)(h_728504) > (NU)(30)) raiseIndexError();
			TMP295 = subInt(((NI) ((*path[(h_728504)- 0].Field1).Count)), 1);
			arrins_728778(&(*path[(h_728504)- 0].Field1).Slots, x_728678, (NI64)(TMP295));
			nimln(328, "lazybtree.nim");
			{
				nimln(328, "lazybtree.nim");
				if (!litem == 0) goto LA30;
				nimln(329, "lazybtree.nim");
				result = setitem_728817(akey_728482, node_728558);
				nimln(330, "lazybtree.nim");
				if ((NU)(h_728504) > (NU)(30)) raiseIndexError();
				if ((NU)(x_728678) >= (NU)((*path[(h_728504)- 0].Field1).Slots->Sup.len)) raiseIndexError();
				asgnRefNoCycle((void**) &(*path[(h_728504)- 0].Field1).Slots->data[x_728678], result);
			}
			goto LA28;
			LA30: ;
			{
				nimln(332, "lazybtree.nim");
				asgnRefNoCycle((void**) &(*litem).Node, node_728558);
				nimln(333, "lazybtree.nim");
				if ((NU)(h_728504) > (NU)(30)) raiseIndexError();
				if ((NU)(x_728678) >= (NU)((*path[(h_728504)- 0].Field1).Slots->Sup.len)) raiseIndexError();
				asgnRefNoCycle((void**) &(*path[(h_728504)- 0].Field1).Slots->data[x_728678], litem);
			}
			LA28: ;
			nimln(382, "lazybtree.nim");
			goto BeforeRet;
		}
		goto LA18;
		LA20: ;
		{
			NI x_729005;
			tbtree728049* node_729007;
			nimln(384, "lazybtree.nim");
			if ((NU)(h_728504) > (NU)(30)) raiseIndexError();
			left = path[(h_728504)- 0].Field1;
			nimln(347, "lazybtree.nim");
			if ((NU)(h_728504) > (NU)(30)) raiseIndexError();
			x_729005 = path[(h_728504)- 0].Field0;
			node_729007 = 0;
			nimln(349, "lazybtree.nim");
			node_729007 = (tbtree728049*) newObj((&NTI728046), sizeof(tbtree728049));
			nimln(350, "lazybtree.nim");
			if ((*node_729007).Slots) nimGCunrefNoCycle((*node_729007).Slots);
			(*node_729007).Slots = (titems728052*) newSeqRC1((&NTI728052), 80);
			nimln(351, "lazybtree.nim");
			(*node_729007).Count = ((NI32) 64);
			nimln(352, "lazybtree.nim");
			{
				nimln(352, "lazybtree.nim");
				if (!(x_729005 == 64)) goto LA36;
				nimln(353, "lazybtree.nim");
				arrcopyclear_729046(&(*node_729007).Slots, &(*left).Slots, 0, 64, 64);
				nimln(354, "lazybtree.nim");
				asgnRefNoCycle((void**) &(*node_729007).Left, node_728558);
			}
			goto LA34;
			LA36: ;
			{
				nimln(356, "lazybtree.nim");
				{
					nimln(356, "lazybtree.nim");
					if (!(x_729005 < 64)) goto LA41;
					nimln(357, "lazybtree.nim");
					arrcopyclear_729046(&(*node_729007).Slots, &(*left).Slots, 0, 64, 64);
					nimln(358, "lazybtree.nim");
					arrins_728778(&(*left).Slots, x_729005, 64);
					nimln(328, "lazybtree.nim");
					{
						nimln(328, "lazybtree.nim");
						if (!litem == 0) goto LA45;
						nimln(329, "lazybtree.nim");
						result = setitem_728817(akey_728482, node_728558);
						nimln(330, "lazybtree.nim");
						if ((NU)(x_729005) >= (NU)((*left).Slots->Sup.len)) raiseIndexError();
						asgnRefNoCycle((void**) &(*left).Slots->data[x_729005], result);
					}
					goto LA43;
					LA45: ;
					{
						nimln(332, "lazybtree.nim");
						asgnRefNoCycle((void**) &(*litem).Node, node_728558);
						nimln(333, "lazybtree.nim");
						if ((NU)(x_729005) >= (NU)((*left).Slots->Sup.len)) raiseIndexError();
						asgnRefNoCycle((void**) &(*left).Slots->data[x_729005], litem);
					}
					LA43: ;
					nimln(360, "lazybtree.nim");
					if ((NU)(64) >= (NU)((*left).Slots->Sup.len)) raiseIndexError();
					litem = (*left).Slots->data[64];
					nimln(361, "lazybtree.nim");
					asgnRefNoCycle((void**) &(*node_729007).Left, (*litem).Node);
					nimln(362, "lazybtree.nim");
					if ((NU)(64) >= (NU)((*left).Slots->Sup.len)) raiseIndexError();
					asgnRefNoCycle((void**) &(*left).Slots->data[64], NIM_NIL);
				}
				goto LA39;
				LA41: ;
				{
					NI TMP298;
					NI TMP299;
					NI TMP300;
					NI TMP301;
					NI TMP302;
					nimln(364, "lazybtree.nim");
					nimln(364, "lazybtree.nim");
					TMP298 = subInt(x_729005, 65);
					x_729005 = (NI64)(TMP298);
					nimln(365, "lazybtree.nim");
					arrcopyclear_729046(&(*node_729007).Slots, &(*left).Slots, 0, 65, x_729005);
					nimln(328, "lazybtree.nim");
					{
						nimln(328, "lazybtree.nim");
						if (!litem == 0) goto LA51;
						nimln(329, "lazybtree.nim");
						result = setitem_728817(akey_728482, node_728558);
						nimln(330, "lazybtree.nim");
						if ((NU)(x_729005) >= (NU)((*node_729007).Slots->Sup.len)) raiseIndexError();
						asgnRefNoCycle((void**) &(*node_729007).Slots->data[x_729005], result);
					}
					goto LA49;
					LA51: ;
					{
						nimln(332, "lazybtree.nim");
						asgnRefNoCycle((void**) &(*litem).Node, node_728558);
						nimln(333, "lazybtree.nim");
						if ((NU)(x_729005) >= (NU)((*node_729007).Slots->Sup.len)) raiseIndexError();
						asgnRefNoCycle((void**) &(*node_729007).Slots->data[x_729005], litem);
					}
					LA49: ;
					nimln(367, "lazybtree.nim");
					nimln(367, "lazybtree.nim");
					TMP299 = addInt(x_729005, 1);
					nimln(367, "lazybtree.nim");
					TMP300 = addInt(65, x_729005);
					nimln(367, "lazybtree.nim");
					nimln(367, "lazybtree.nim");
					TMP301 = subInt(64, x_729005);
					TMP302 = subInt((NI64)(TMP301), 1);
					arrcopyclear_729046(&(*node_729007).Slots, &(*left).Slots, (NI64)(TMP299), (NI64)(TMP300), (NI64)(TMP302));
					nimln(368, "lazybtree.nim");
					if ((NU)(64) >= (NU)((*left).Slots->Sup.len)) raiseIndexError();
					litem = (*left).Slots->data[64];
					nimln(369, "lazybtree.nim");
					asgnRefNoCycle((void**) &(*node_729007).Left, (*litem).Node);
					nimln(370, "lazybtree.nim");
					if ((NU)(64) >= (NU)((*left).Slots->Sup.len)) raiseIndexError();
					asgnRefNoCycle((void**) &(*left).Slots->data[64], NIM_NIL);
				}
				LA39: ;
			}
			LA34: ;
			nimln(371, "lazybtree.nim");
			(*left).Count = ((NI32) 64);
			nimln(372, "lazybtree.nim");
			unsureAsgnRef((void**) &node_728558, node_729007);
		}
		LA18: ;
		nimln(386, "lazybtree.nim");
		h_728504 = subInt(h_728504, 1);
	} LA17: ;
	nimln(388, "lazybtree.nim");
	unsureAsgnRef((void**) &(*anode_728478), (tbtree728049*) newObj((&NTI728046), sizeof(tbtree728049)));
	nimln(389, "lazybtree.nim");
	if ((*(*anode_728478)).Slots) nimGCunrefNoCycle((*(*anode_728478)).Slots);
	(*(*anode_728478)).Slots = (titems728052*) newSeqRC1((&NTI728052), 2);
	nimln(390, "lazybtree.nim");
	(*(*anode_728478)).Count = ((NI32) 1);
	nimln(391, "lazybtree.nim");
	asgnRefNoCycle((void**) &(*(*anode_728478)).Left, left);
	nimln(328, "lazybtree.nim");
	{
		nimln(328, "lazybtree.nim");
		if (!litem == 0) goto LA56;
		nimln(329, "lazybtree.nim");
		result = setitem_728817(akey_728482, node_728558);
		nimln(330, "lazybtree.nim");
		if ((NU)(0) >= (NU)((*(*anode_728478)).Slots->Sup.len)) raiseIndexError();
		asgnRefNoCycle((void**) &(*(*anode_728478)).Slots->data[0], result);
	}
	goto LA54;
	LA56: ;
	{
		nimln(332, "lazybtree.nim");
		asgnRefNoCycle((void**) &(*litem).Node, node_728558);
		nimln(333, "lazybtree.nim");
		if ((NU)(0) >= (NU)((*(*anode_728478)).Slots->Sup.len)) raiseIndexError();
		asgnRefNoCycle((void**) &(*(*anode_728478)).Slots->data[0], litem);
	}
	LA54: ;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(titem728056*, find_729523)(tbtree728049* n_729530, NimStringDesc* key_729533) {
	titem728056* result;
	tbtree728049* node;
	nimfr("find", "lazybtree.nim")
	result = 0;
	nimln(257, "lazybtree.nim");
	node = n_729530;
	nimln(188, "lazybtree.nim");
	while (1) {
		NI x_729538;
		nimln(188, "lazybtree.nim");
		nimln(188, "lazybtree.nim");
		if (!!((node == NIM_NIL))) goto LA1;
		nimln(189, "lazybtree.nim");
		x_729538 = bsearch_728578(node, key_729533);
		nimln(190, "lazybtree.nim");
		{
			nimln(190, "lazybtree.nim");
			if (!(x_729538 <= 0)) goto LA4;
			nimln(192, "lazybtree.nim");
			{
				nimln(192, "lazybtree.nim");
				if (!(x_729538 == 0)) goto LA8;
				nimln(193, "lazybtree.nim");
				node = (*node).Left;
			}
			goto LA6;
			LA8: ;
			{
				NI TMP317;
				nimln(195, "lazybtree.nim");
				nimln(195, "lazybtree.nim");
				nimln(195, "lazybtree.nim");
				if (x_729538 == (IL64(-9223372036854775807) - IL64(1))) raiseOverflow();
				TMP317 = subInt(((NI64)-(x_729538)), 1);
				x_729538 = (NI64)(TMP317);
				nimln(196, "lazybtree.nim");
				{
					nimln(196, "lazybtree.nim");
					if (!(x_729538 < ((NI) ((*node).Count)))) goto LA13;
					nimln(197, "lazybtree.nim");
					if ((NU)(x_729538) >= (NU)((*node).Slots->Sup.len)) raiseIndexError();
					node = (*(*node).Slots->data[x_729538]).Node;
				}
				goto LA11;
				LA13: ;
				{
					nimln(199, "lazybtree.nim");
					goto LA1;
				}
				LA11: ;
			}
			LA6: ;
		}
		goto LA2;
		LA4: ;
		{
			nimln(201, "lazybtree.nim");
			x_729538 = subInt(x_729538, 1);
			nimln(256, "lazybtree.nim");
			nimln(256, "lazybtree.nim");
			if ((NU)(x_729538) >= (NU)((*node).Slots->Sup.len)) raiseIndexError();
			result = (*node).Slots->data[x_729538];
			goto BeforeRet;
		}
		LA2: ;
	} LA1: ;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NI, bsearch_731196)(tbtree731036* haystack_731203, tdynamicHEX3Aobjecttype728028* needle_731206) {
	NI result;
	NI sw;
	NI h_731209;
	NI TMP371;
	nimfr("bSearch", "lazybtree.nim")
	result = 0;
	sw = 0;
	nimln(2, "binsearch.nim");
	result = 0;
	nimln(3, "binsearch.nim");
	nimln(3, "binsearch.nim");
	TMP371 = subInt(((NI) ((*haystack_731203).Count)), 1);
	h_731209 = (NI64)(TMP371);
	{
		nimln(5, "binsearch.nim");
		while (1) {
			NI i_731213;
			NI TMP372;
			nimln(5, "binsearch.nim");
			if (!(result <= h_731209)) goto LA2;
			nimln(6, "binsearch.nim");
			nimln(6, "binsearch.nim");
			nimln(6, "binsearch.nim");
			TMP372 = addInt(result, h_731209);
			i_731213 = (NI)((NU64)((NI64)(TMP372)) >> (NU64)(1));
			nimln(7, "binsearch.nim");
			{
				NI TMP373;
				nimln(134, "lazybtree.nim");
				if ((NU)(i_731213) >= (NU)((*haystack_731203).Slots->Sup.len)) raiseIndexError();
				sw = cmp_731410((*(*haystack_731203).Slots->data[i_731213]).Key, needle_731206);
				nimln(135, "lazybtree.nim");
				if (!(sw < 0)) goto LA5;
				nimln(7, "binsearch.nim");
				nimln(7, "binsearch.nim");
				TMP373 = addInt(i_731213, 1);
				result = (NI64)(TMP373);
			}
			goto LA3;
			LA5: ;
			{
				NI TMP374;
				nimln(8, "binsearch.nim");
				if (!(sw == 0)) goto LA8;
				nimln(9, "binsearch.nim");
				nimln(9, "binsearch.nim");
				TMP374 = addInt(i_731213, 1);
				result = (NI64)(TMP374);
				nimln(10, "binsearch.nim");
				goto LA1;
			}
			goto LA3;
			LA8: ;
			{
				NI TMP375;
				nimln(12, "binsearch.nim");
				nimln(12, "binsearch.nim");
				TMP375 = subInt(i_731213, 1);
				h_731209 = (NI64)(TMP375);
			}
			LA3: ;
		} LA2: ;
		nimln(13, "binsearch.nim");
		nimln(13, "binsearch.nim");
		if (result == (IL64(-9223372036854775807) - IL64(1))) raiseOverflow();
		result = ((NI64)-(result));
	} LA1: ;
	popFrame();
	return result;
}

static N_INLINE(void, arrins_731621)(titems731039** arr_731629, NI x_731633, NI cnt_731635) {
	NI delta;
	NI TMP377;
	nimfr("arrIns", "lazybtree.nim")
	nimln(148, "lazybtree.nim");
	nimln(148, "lazybtree.nim");
	TMP377 = subInt(cnt_731635, x_731633);
	delta = (NI64)(TMP377);
	nimln(149, "lazybtree.nim");
	{
		nimln(149, "lazybtree.nim");
		if (!(0 <= x_731633)) goto LA3;
		nimln(150, "lazybtree.nim");
		{
			NI TMP378;
			NI TMP379;
			nimln(150, "lazybtree.nim");
			if (!(0 < delta)) goto LA7;
			nimln(151, "lazybtree.nim");
			nimln(151, "lazybtree.nim");
			TMP378 = addInt(x_731633, 1);
			if ((NU)((NI64)(TMP378)) >= (NU)((*arr_731629)->Sup.len)) raiseIndexError();
			if ((NU)(x_731633) >= (NU)((*arr_731629)->Sup.len)) raiseIndexError();
			nimln(151, "lazybtree.nim");
			TMP379 = mulInt(8, delta);
			memmove(((void*) (&(*arr_731629)->data[(NI64)(TMP378)])), ((void*) (&(*arr_731629)->data[x_731633])), (NI64)(TMP379));
		}
		LA7: ;
		nimln(152, "lazybtree.nim");
		if ((NU)(x_731633) >= (NU)((*arr_731629)->Sup.len)) raiseIndexError();
		(*((NI*) (&(*arr_731629)->data[x_731633]))) = 0;
	}
	LA3: ;
	popFrame();
}
N_NIMCALL(void, TMP383)(void* p, NI op) {
	titems731039* a;
	NI LOC1;
	a = (titems731039*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1], op);
	}
}
N_NIMCALL(void, TMP384)(void* p, NI op) {
	tbtree731036* a;
	a = (tbtree731036*)p;
	nimGCvisit((void*)(*a).Slots, op);
	nimGCvisit((void*)(*a).Left, op);
}
N_NIMCALL(void, TMP385)(void* p, NI op) {
	titem731043* a;
	a = (titem731043*)p;
	nimGCvisit((void*)(*a).Key, op);
	nimGCvisit((void*)(*a).Value, op);
	nimGCvisit((void*)(*a).Node, op);
}

static N_INLINE(NIM_BOOL, canbecycleroot_44662)(tcell41290* c) {
	NIM_BOOL result;
	nimfr("canbeCycleRoot", "gc.nim")
	result = 0;
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	result = !((((*(*c).Typ).flags &(1<<((((NU8) 1))&7)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_45435)(tcell41290* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(189, "gc.nim");
	{
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		if (!!((((NI) ((NI)((*c).Refcount & 3))) == 3))) goto LA3;
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		(*c).Refcount = (NI)((NI)((*c).Refcount & -4) | 3);
		nimln(191, "gc.nim");
		incl_42055(&gch_43244.Cycleroots, c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, incref_47027)(tcell41290* c) {
	nimfr("incRef", "gc.nim")
	nimln(216, "gc.nim");
	nimln(216, "gc.nim");
	(*c).Refcount = (NI)((NU64)((*c).Refcount) + (NU64)(8));
	nimln(219, "gc.nim");
	{
		NIM_BOOL LOC3;
		nimln(219, "gc.nim");
		LOC3 = 0;
		LOC3 = canbecycleroot_44662(c);
		if (!LOC3) goto LA4;
		nimln(220, "gc.nim");
		rtladdcycleroot_45435(c);
	}
	LA4: ;
	popFrame();
}

static N_INLINE(void, decref_46602)(tcell41290* c) {
	nimfr("decRef", "gc.nim")
	nimln(206, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		nimln(207, "gc.nim");
		rtladdzct_46202(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(208, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_44662(c);
		if (!LOC6) goto LA7;
		nimln(211, "gc.nim");
		rtladdcycleroot_45435(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr("asgnRef", "gc.nim")
	nimln(244, "gc.nim");
	{
		tcell41290* LOC5;
		nimln(244, "gc.nim");
		nimln(244, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(244, "gc.nim");
		nimln(244, "gc.nim");
		LOC5 = 0;
		LOC5 = usrtocell_44643(src);
		incref_47027(LOC5);
	}
	LA3: ;
	nimln(245, "gc.nim");
	{
		tcell41290* LOC10;
		nimln(245, "gc.nim");
		nimln(245, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		nimln(245, "gc.nim");
		nimln(245, "gc.nim");
		LOC10 = 0;
		LOC10 = usrtocell_44643((*dest));
		decref_46602(LOC10);
	}
	LA8: ;
	nimln(246, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(titem731043*, setitem_731660)(tdynamicHEX3Aobjecttype728028* akey_731665, tbtree731036* anode_731669) {
	titem731043* result;
	nimfr("setItem", "lazybtree.nim")
	result = 0;
	nimln(89, "lazybtree.nim");
	result = (titem731043*) newObj((&NTI731101), sizeof(titem731043));
	nimln(90, "lazybtree.nim");
	asgnRef((void**) &(*result).Key, akey_731665);
	nimln(91, "lazybtree.nim");
	asgnRefNoCycle((void**) &(*result).Node, anode_731669);
	popFrame();
	return result;
}

static N_INLINE(void, arrcopyclear_731846)(titems731039** dest_731854, titems731039** source_731862, NI startdest_731866, NI startsource_731868, NI cnt_731870) {
	nimfr("arrCopyClear", "lazybtree.nim")
	nimln(155, "lazybtree.nim");
	{
		NI TMP386;
		NI TMP387;
		nimln(155, "lazybtree.nim");
		if (!(0 < cnt_731870)) goto LA3;
		nimln(156, "lazybtree.nim");
		if ((NU)(startdest_731866) >= (NU)((*dest_731854)->Sup.len)) raiseIndexError();
		if ((NU)(startsource_731868) >= (NU)((*source_731862)->Sup.len)) raiseIndexError();
		nimln(156, "lazybtree.nim");
		TMP386 = mulInt(cnt_731870, 8);
		memcpy(((void*) (&(*dest_731854)->data[startdest_731866])), ((void*) (&(*source_731862)->data[startsource_731868])), (NI64)(TMP386));
		nimln(157, "lazybtree.nim");
		if ((NU)(startsource_731868) >= (NU)((*source_731862)->Sup.len)) raiseIndexError();
		nimln(157, "lazybtree.nim");
		TMP387 = mulInt(cnt_731870, 8);
		zeroMem(((void*) (&(*source_731862)->data[startsource_731868])), (NI64)(TMP387));
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(titem731043*, findorinsert_731087)(tbtree731036** anode_731096, tdynamicHEX3Aobjecttype728028* akey_731100) {
	titem731043* result;
	TY731106 path;
	NI h_731122;
	tbtree731036* node_731176;
	tbtree731036* left;
	titem731043* litem;
	nimfr("findOrInsert", "lazybtree.nim")
	result = 0;
	memset((void*)path, 0, sizeof(path));
	nimln(320, "lazybtree.nim");
	h_731122 = 0;
	nimln(374, "lazybtree.nim");
	unsureAsgnRef((void**) &node_731176, (*anode_731096));
	nimln(188, "lazybtree.nim");
	while (1) {
		NI x_731105;
		nimln(188, "lazybtree.nim");
		nimln(188, "lazybtree.nim");
		if (!!((node_731176 == NIM_NIL))) goto LA1;
		nimln(189, "lazybtree.nim");
		x_731105 = bsearch_731196(node_731176, akey_731100);
		nimln(190, "lazybtree.nim");
		{
			nimln(190, "lazybtree.nim");
			if (!(x_731105 <= 0)) goto LA4;
			nimln(322, "lazybtree.nim");
			if ((NU)(h_731122) > (NU)(30)) raiseIndexError();
			path[(h_731122)- 0].Field1 = node_731176;
			nimln(323, "lazybtree.nim");
			if ((NU)(h_731122) > (NU)(30)) raiseIndexError();
			nimln(323, "lazybtree.nim");
			if (x_731105 == (IL64(-9223372036854775807) - IL64(1))) raiseOverflow();
			path[(h_731122)- 0].Field0 = ((NI64)-(x_731105));
			nimln(324, "lazybtree.nim");
			h_731122 = addInt(h_731122, 1);
			nimln(192, "lazybtree.nim");
			{
				nimln(192, "lazybtree.nim");
				if (!(x_731105 == 0)) goto LA8;
				nimln(193, "lazybtree.nim");
				unsureAsgnRef((void**) &node_731176, (*node_731176).Left);
			}
			goto LA6;
			LA8: ;
			{
				NI TMP376;
				nimln(195, "lazybtree.nim");
				nimln(195, "lazybtree.nim");
				nimln(195, "lazybtree.nim");
				if (x_731105 == (IL64(-9223372036854775807) - IL64(1))) raiseOverflow();
				TMP376 = subInt(((NI64)-(x_731105)), 1);
				x_731105 = (NI64)(TMP376);
				nimln(196, "lazybtree.nim");
				{
					nimln(196, "lazybtree.nim");
					if (!(x_731105 < ((NI) ((*node_731176).Count)))) goto LA13;
					nimln(197, "lazybtree.nim");
					if ((NU)(x_731105) >= (NU)((*node_731176).Slots->Sup.len)) raiseIndexError();
					unsureAsgnRef((void**) &node_731176, (*(*node_731176).Slots->data[x_731105]).Node);
				}
				goto LA11;
				LA13: ;
				{
					nimln(199, "lazybtree.nim");
					goto LA1;
				}
				LA11: ;
			}
			LA6: ;
		}
		goto LA2;
		LA4: ;
		{
			nimln(201, "lazybtree.nim");
			x_731105 = subInt(x_731105, 1);
			nimln(326, "lazybtree.nim");
			nimln(326, "lazybtree.nim");
			if ((NU)(x_731105) >= (NU)((*node_731176).Slots->Sup.len)) raiseIndexError();
			result = (*node_731176).Slots->data[x_731105];
			goto BeforeRet;
		}
		LA2: ;
	} LA1: ;
	nimln(376, "lazybtree.nim");
	h_731122 = subInt(h_731122, 1);
	left = 0;
	litem = 0;
	nimln(379, "lazybtree.nim");
	while (1) {
		nimln(379, "lazybtree.nim");
		if (!(0 <= h_731122)) goto LA17;
		nimln(380, "lazybtree.nim");
		{
			NI x_731521;
			NI TMP380;
			nimln(380, "lazybtree.nim");
			if ((NU)(h_731122) > (NU)(30)) raiseIndexError();
			if (!((*path[(h_731122)- 0].Field1).Count < ((NI32) 128))) goto LA20;
			nimln(335, "lazybtree.nim");
			if ((NU)(h_731122) > (NU)(30)) raiseIndexError();
			x_731521 = path[(h_731122)- 0].Field0;
			nimln(336, "lazybtree.nim");
			if ((NU)(h_731122) > (NU)(30)) raiseIndexError();
			(*path[(h_731122)- 0].Field1).Count = addInt((*path[(h_731122)- 0].Field1).Count, 1);
			nimln(337, "lazybtree.nim");
			if ((NU)(h_731122) > (NU)(30)) raiseIndexError();
			switch ((*path[(h_731122)- 0].Field1).Count) {
			case 2:
			{
				nimln(338, "lazybtree.nim");
				if ((NU)(h_731122) > (NU)(30)) raiseIndexError();
				(*path[(h_731122)- 0].Field1).Slots = (titems731039*) setLengthSeq(&((*path[(h_731122)- 0].Field1).Slots)->Sup, sizeof(titem731043*), 16);
			}
			break;
			case 16:
			{
				nimln(339, "lazybtree.nim");
				if ((NU)(h_731122) > (NU)(30)) raiseIndexError();
				(*path[(h_731122)- 0].Field1).Slots = (titems731039*) setLengthSeq(&((*path[(h_731122)- 0].Field1).Slots)->Sup, sizeof(titem731043*), 32);
			}
			break;
			case 32:
			{
				nimln(340, "lazybtree.nim");
				if ((NU)(h_731122) > (NU)(30)) raiseIndexError();
				(*path[(h_731122)- 0].Field1).Slots = (titems731039*) setLengthSeq(&((*path[(h_731122)- 0].Field1).Slots)->Sup, sizeof(titem731043*), 80);
			}
			break;
			case 80:
			{
				nimln(341, "lazybtree.nim");
				if ((NU)(h_731122) > (NU)(30)) raiseIndexError();
				(*path[(h_731122)- 0].Field1).Slots = (titems731039*) setLengthSeq(&((*path[(h_731122)- 0].Field1).Slots)->Sup, sizeof(titem731043*), 96);
			}
			break;
			case 96:
			{
				nimln(342, "lazybtree.nim");
				if ((NU)(h_731122) > (NU)(30)) raiseIndexError();
				(*path[(h_731122)- 0].Field1).Slots = (titems731039*) setLengthSeq(&((*path[(h_731122)- 0].Field1).Slots)->Sup, sizeof(titem731043*), 128);
			}
			break;
			default:
			{
			}
			break;
			}
			nimln(344, "lazybtree.nim");
			if ((NU)(h_731122) > (NU)(30)) raiseIndexError();
			nimln(344, "lazybtree.nim");
			if ((NU)(h_731122) > (NU)(30)) raiseIndexError();
			TMP380 = subInt(((NI) ((*path[(h_731122)- 0].Field1).Count)), 1);
			arrins_731621(&(*path[(h_731122)- 0].Field1).Slots, x_731521, (NI64)(TMP380));
			nimln(328, "lazybtree.nim");
			{
				nimln(328, "lazybtree.nim");
				if (!litem == 0) goto LA30;
				nimln(329, "lazybtree.nim");
				result = setitem_731660(akey_731100, node_731176);
				nimln(330, "lazybtree.nim");
				if ((NU)(h_731122) > (NU)(30)) raiseIndexError();
				if ((NU)(x_731521) >= (NU)((*path[(h_731122)- 0].Field1).Slots->Sup.len)) raiseIndexError();
				asgnRefNoCycle((void**) &(*path[(h_731122)- 0].Field1).Slots->data[x_731521], result);
			}
			goto LA28;
			LA30: ;
			{
				nimln(332, "lazybtree.nim");
				asgnRefNoCycle((void**) &(*litem).Node, node_731176);
				nimln(333, "lazybtree.nim");
				if ((NU)(h_731122) > (NU)(30)) raiseIndexError();
				if ((NU)(x_731521) >= (NU)((*path[(h_731122)- 0].Field1).Slots->Sup.len)) raiseIndexError();
				asgnRefNoCycle((void**) &(*path[(h_731122)- 0].Field1).Slots->data[x_731521], litem);
			}
			LA28: ;
			nimln(382, "lazybtree.nim");
			goto BeforeRet;
		}
		goto LA18;
		LA20: ;
		{
			NI x_731805;
			tbtree731036* node_731807;
			nimln(384, "lazybtree.nim");
			if ((NU)(h_731122) > (NU)(30)) raiseIndexError();
			left = path[(h_731122)- 0].Field1;
			nimln(347, "lazybtree.nim");
			if ((NU)(h_731122) > (NU)(30)) raiseIndexError();
			x_731805 = path[(h_731122)- 0].Field0;
			node_731807 = 0;
			nimln(349, "lazybtree.nim");
			node_731807 = (tbtree731036*) newObj((&NTI731033), sizeof(tbtree731036));
			nimln(350, "lazybtree.nim");
			if ((*node_731807).Slots) nimGCunrefNoCycle((*node_731807).Slots);
			(*node_731807).Slots = (titems731039*) newSeqRC1((&NTI731039), 80);
			nimln(351, "lazybtree.nim");
			(*node_731807).Count = ((NI32) 64);
			nimln(352, "lazybtree.nim");
			{
				nimln(352, "lazybtree.nim");
				if (!(x_731805 == 64)) goto LA36;
				nimln(353, "lazybtree.nim");
				arrcopyclear_731846(&(*node_731807).Slots, &(*left).Slots, 0, 64, 64);
				nimln(354, "lazybtree.nim");
				asgnRefNoCycle((void**) &(*node_731807).Left, node_731176);
			}
			goto LA34;
			LA36: ;
			{
				nimln(356, "lazybtree.nim");
				{
					nimln(356, "lazybtree.nim");
					if (!(x_731805 < 64)) goto LA41;
					nimln(357, "lazybtree.nim");
					arrcopyclear_731846(&(*node_731807).Slots, &(*left).Slots, 0, 64, 64);
					nimln(358, "lazybtree.nim");
					arrins_731621(&(*left).Slots, x_731805, 64);
					nimln(328, "lazybtree.nim");
					{
						nimln(328, "lazybtree.nim");
						if (!litem == 0) goto LA45;
						nimln(329, "lazybtree.nim");
						result = setitem_731660(akey_731100, node_731176);
						nimln(330, "lazybtree.nim");
						if ((NU)(x_731805) >= (NU)((*left).Slots->Sup.len)) raiseIndexError();
						asgnRefNoCycle((void**) &(*left).Slots->data[x_731805], result);
					}
					goto LA43;
					LA45: ;
					{
						nimln(332, "lazybtree.nim");
						asgnRefNoCycle((void**) &(*litem).Node, node_731176);
						nimln(333, "lazybtree.nim");
						if ((NU)(x_731805) >= (NU)((*left).Slots->Sup.len)) raiseIndexError();
						asgnRefNoCycle((void**) &(*left).Slots->data[x_731805], litem);
					}
					LA43: ;
					nimln(360, "lazybtree.nim");
					if ((NU)(64) >= (NU)((*left).Slots->Sup.len)) raiseIndexError();
					litem = (*left).Slots->data[64];
					nimln(361, "lazybtree.nim");
					asgnRefNoCycle((void**) &(*node_731807).Left, (*litem).Node);
					nimln(362, "lazybtree.nim");
					if ((NU)(64) >= (NU)((*left).Slots->Sup.len)) raiseIndexError();
					asgnRefNoCycle((void**) &(*left).Slots->data[64], NIM_NIL);
				}
				goto LA39;
				LA41: ;
				{
					NI TMP388;
					NI TMP389;
					NI TMP390;
					NI TMP391;
					NI TMP392;
					nimln(364, "lazybtree.nim");
					nimln(364, "lazybtree.nim");
					TMP388 = subInt(x_731805, 65);
					x_731805 = (NI64)(TMP388);
					nimln(365, "lazybtree.nim");
					arrcopyclear_731846(&(*node_731807).Slots, &(*left).Slots, 0, 65, x_731805);
					nimln(328, "lazybtree.nim");
					{
						nimln(328, "lazybtree.nim");
						if (!litem == 0) goto LA51;
						nimln(329, "lazybtree.nim");
						result = setitem_731660(akey_731100, node_731176);
						nimln(330, "lazybtree.nim");
						if ((NU)(x_731805) >= (NU)((*node_731807).Slots->Sup.len)) raiseIndexError();
						asgnRefNoCycle((void**) &(*node_731807).Slots->data[x_731805], result);
					}
					goto LA49;
					LA51: ;
					{
						nimln(332, "lazybtree.nim");
						asgnRefNoCycle((void**) &(*litem).Node, node_731176);
						nimln(333, "lazybtree.nim");
						if ((NU)(x_731805) >= (NU)((*node_731807).Slots->Sup.len)) raiseIndexError();
						asgnRefNoCycle((void**) &(*node_731807).Slots->data[x_731805], litem);
					}
					LA49: ;
					nimln(367, "lazybtree.nim");
					nimln(367, "lazybtree.nim");
					TMP389 = addInt(x_731805, 1);
					nimln(367, "lazybtree.nim");
					TMP390 = addInt(65, x_731805);
					nimln(367, "lazybtree.nim");
					nimln(367, "lazybtree.nim");
					TMP391 = subInt(64, x_731805);
					TMP392 = subInt((NI64)(TMP391), 1);
					arrcopyclear_731846(&(*node_731807).Slots, &(*left).Slots, (NI64)(TMP389), (NI64)(TMP390), (NI64)(TMP392));
					nimln(368, "lazybtree.nim");
					if ((NU)(64) >= (NU)((*left).Slots->Sup.len)) raiseIndexError();
					litem = (*left).Slots->data[64];
					nimln(369, "lazybtree.nim");
					asgnRefNoCycle((void**) &(*node_731807).Left, (*litem).Node);
					nimln(370, "lazybtree.nim");
					if ((NU)(64) >= (NU)((*left).Slots->Sup.len)) raiseIndexError();
					asgnRefNoCycle((void**) &(*left).Slots->data[64], NIM_NIL);
				}
				LA39: ;
			}
			LA34: ;
			nimln(371, "lazybtree.nim");
			(*left).Count = ((NI32) 64);
			nimln(372, "lazybtree.nim");
			unsureAsgnRef((void**) &node_731176, node_731807);
		}
		LA18: ;
		nimln(386, "lazybtree.nim");
		h_731122 = subInt(h_731122, 1);
	} LA17: ;
	nimln(388, "lazybtree.nim");
	unsureAsgnRef((void**) &(*anode_731096), (tbtree731036*) newObj((&NTI731033), sizeof(tbtree731036)));
	nimln(389, "lazybtree.nim");
	if ((*(*anode_731096)).Slots) nimGCunrefNoCycle((*(*anode_731096)).Slots);
	(*(*anode_731096)).Slots = (titems731039*) newSeqRC1((&NTI731039), 2);
	nimln(390, "lazybtree.nim");
	(*(*anode_731096)).Count = ((NI32) 1);
	nimln(391, "lazybtree.nim");
	asgnRefNoCycle((void**) &(*(*anode_731096)).Left, left);
	nimln(328, "lazybtree.nim");
	{
		nimln(328, "lazybtree.nim");
		if (!litem == 0) goto LA56;
		nimln(329, "lazybtree.nim");
		result = setitem_731660(akey_731100, node_731176);
		nimln(330, "lazybtree.nim");
		if ((NU)(0) >= (NU)((*(*anode_731096)).Slots->Sup.len)) raiseIndexError();
		asgnRefNoCycle((void**) &(*(*anode_731096)).Slots->data[0], result);
	}
	goto LA54;
	LA56: ;
	{
		nimln(332, "lazybtree.nim");
		asgnRefNoCycle((void**) &(*litem).Node, node_731176);
		nimln(333, "lazybtree.nim");
		if ((NU)(0) >= (NU)((*(*anode_731096)).Slots->Sup.len)) raiseIndexError();
		asgnRefNoCycle((void**) &(*(*anode_731096)).Slots->data[0], litem);
	}
	LA54: ;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(titem731043*, find_732164)(tbtree731036* n_732171, tdynamicHEX3Aobjecttype728028* key_732174) {
	titem731043* result;
	tbtree731036* node;
	nimfr("find", "lazybtree.nim")
	result = 0;
	nimln(257, "lazybtree.nim");
	node = n_732171;
	nimln(188, "lazybtree.nim");
	while (1) {
		NI x_732179;
		nimln(188, "lazybtree.nim");
		nimln(188, "lazybtree.nim");
		if (!!((node == NIM_NIL))) goto LA1;
		nimln(189, "lazybtree.nim");
		x_732179 = bsearch_731196(node, key_732174);
		nimln(190, "lazybtree.nim");
		{
			nimln(190, "lazybtree.nim");
			if (!(x_732179 <= 0)) goto LA4;
			nimln(192, "lazybtree.nim");
			{
				nimln(192, "lazybtree.nim");
				if (!(x_732179 == 0)) goto LA8;
				nimln(193, "lazybtree.nim");
				node = (*node).Left;
			}
			goto LA6;
			LA8: ;
			{
				NI TMP403;
				nimln(195, "lazybtree.nim");
				nimln(195, "lazybtree.nim");
				nimln(195, "lazybtree.nim");
				if (x_732179 == (IL64(-9223372036854775807) - IL64(1))) raiseOverflow();
				TMP403 = subInt(((NI64)-(x_732179)), 1);
				x_732179 = (NI64)(TMP403);
				nimln(196, "lazybtree.nim");
				{
					nimln(196, "lazybtree.nim");
					if (!(x_732179 < ((NI) ((*node).Count)))) goto LA13;
					nimln(197, "lazybtree.nim");
					if ((NU)(x_732179) >= (NU)((*node).Slots->Sup.len)) raiseIndexError();
					node = (*(*node).Slots->data[x_732179]).Node;
				}
				goto LA11;
				LA13: ;
				{
					nimln(199, "lazybtree.nim");
					goto LA1;
				}
				LA11: ;
			}
			LA6: ;
		}
		goto LA2;
		LA4: ;
		{
			nimln(201, "lazybtree.nim");
			x_732179 = subInt(x_732179, 1);
			nimln(256, "lazybtree.nim");
			nimln(256, "lazybtree.nim");
			if ((NU)(x_732179) >= (NU)((*node).Slots->Sup.len)) raiseIndexError();
			result = (*node).Slots->data[x_732179];
			goto BeforeRet;
		}
		LA2: ;
	} LA1: ;
	BeforeRet: ;
	popFrame();
	return result;
}
N_NIMCALL(void, TMP414)(void* p, NI op) {
	riteratorkeys733093* a;
	NI LOC1;
	a = (riteratorkeys733093*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < 31; LOC1++) {
	nimGCvisit((void*)(*a).Sup.Path[LOC1].Field1, op);
	}
	nimGCvisit((void*)(*a).Sup.Current, op);
}

static N_INLINE(void, inititerator_733151)(rtreeiterator733096* it_733158, tbtree728049* n_733163) {
	nimfr("initIterator", "lazybtree.nim")
	nimln(505, "lazybtree.nim");
	asgnRefNoCycle((void**) &(*it_733158).Path[(0)- 0].Field1, n_733163);
	nimln(506, "lazybtree.nim");
	(*it_733158).Path[(0)- 0].Field0 = -1;
	popFrame();
}

N_NIMCALL(riteratorkeys733093*, keys_733114)(tbtree728049* n_733121) {
	riteratorkeys733093* result;
	nimfr("Keys", "lazybtree.nim")
	result = 0;
	nimln(553, "lazybtree.nim");
	result = (riteratorkeys733093*) newObj((&NTI733090), sizeof(riteratorkeys733093));
	(*result).Sup.m_type = (&NTI733093);
	nimln(554, "lazybtree.nim");
	inititerator_733151(((rtreeiterator733096*) (result)), n_733121);
	popFrame();
	return result;
}
N_NIMCALL(void, TMP415)(void* p, NI op) {
	riteratorvalues733183* a;
	NI LOC1;
	a = (riteratorvalues733183*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < 31; LOC1++) {
	nimGCvisit((void*)(*a).Sup.Path[LOC1].Field1, op);
	}
	nimGCvisit((void*)(*a).Sup.Current, op);
}

N_NIMCALL(riteratorvalues733183*, values_733188)(tbtree728049* n_733195) {
	riteratorvalues733183* result;
	nimfr("Values", "lazybtree.nim")
	result = 0;
	nimln(553, "lazybtree.nim");
	result = (riteratorvalues733183*) newObj((&NTI733180), sizeof(riteratorvalues733183));
	(*result).Sup.m_type = (&NTI733183);
	nimln(554, "lazybtree.nim");
	inititerator_733151(((rtreeiterator733096*) (result)), n_733195);
	popFrame();
	return result;
}
N_NIMCALL(void, TMP416)(void* p, NI op) {
	riteratorpairs733251* a;
	NI LOC1;
	a = (riteratorpairs733251*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < 31; LOC1++) {
	nimGCvisit((void*)(*a).Sup.Path[LOC1].Field1, op);
	}
	nimGCvisit((void*)(*a).Sup.Current, op);
}

N_NIMCALL(riteratorpairs733251*, pairs_733256)(tbtree728049* n_733263) {
	riteratorpairs733251* result;
	nimfr("Pairs", "lazybtree.nim")
	result = 0;
	nimln(553, "lazybtree.nim");
	result = (riteratorpairs733251*) newObj((&NTI733248), sizeof(riteratorpairs733251));
	(*result).Sup.m_type = (&NTI733251);
	nimln(554, "lazybtree.nim");
	inititerator_733151(((rtreeiterator733096*) (result)), n_733263);
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, isclean_733523)(titem728056* it_733532) {
	NIM_BOOL result;
	nimfr("isClean", "lazybtree.nim")
	result = 0;
	nimln(70, "lazybtree.nim");
	nimln(70, "lazybtree.nim");
	nimln(70, "lazybtree.nim");
	result = ((*it_733532).Value == NIM_NIL);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(titem728056*, getnext_733434)(rtreeiterator733096* it_733441) {
	titem728056* result;
	NI level;
	tbtree728049* nd;
	nimfr("getNext", "lazybtree.nim")
	result = 0;
	nimln(509, "lazybtree.nim");
	level = (*it_733441).Level;
	nimln(510, "lazybtree.nim");
	if ((NU)(level) > (NU)(30)) raiseIndexError();
	nd = (*it_733441).Path[(level)- 0].Field1;
	nimln(511, "lazybtree.nim");
	{
		NI i;
		nimln(511, "lazybtree.nim");
		nimln(511, "lazybtree.nim");
		if (!!((nd == NIM_NIL))) goto LA3;
		nimln(512, "lazybtree.nim");
		if ((NU)(level) > (NU)(30)) raiseIndexError();
		i = (*it_733441).Path[(level)- 0].Field0;
		nimln(513, "lazybtree.nim");
		while (1) {
			nimln(514, "lazybtree.nim");
			{
				nimln(514, "lazybtree.nim");
				if (!(i < ((NI) ((*nd).Count)))) goto LA8;
				nimln(515, "lazybtree.nim");
				if ((NU)(level) > (NU)(30)) raiseIndexError();
				asgnRefNoCycle((void**) &(*it_733441).Path[(level)- 0].Field1, nd);
				nimln(516, "lazybtree.nim");
				if ((NU)(level) > (NU)(30)) raiseIndexError();
				(*it_733441).Path[(level)- 0].Field0 = i;
				nimln(517, "lazybtree.nim");
				{
					nimln(517, "lazybtree.nim");
					if (!(i < 0)) goto LA12;
					nimln(518, "lazybtree.nim");
					{
						nimln(518, "lazybtree.nim");
						nimln(518, "lazybtree.nim");
						if (!!(((*nd).Left == NIM_NIL))) goto LA16;
						nimln(519, "lazybtree.nim");
						nd = (*nd).Left;
						nimln(520, "lazybtree.nim");
						level = addInt(level, 1);
					}
					goto LA14;
					LA16: ;
					{
						nimln(521, "lazybtree.nim");
						i = addInt(i, 1);
					}
					LA14: ;
				}
				goto LA10;
				LA12: ;
				{
					titem728056* w;
					nimln(523, "lazybtree.nim");
					if ((NU)(i) >= (NU)((*nd).Slots->Sup.len)) raiseIndexError();
					w = (*nd).Slots->data[i];
					nimln(524, "lazybtree.nim");
					{
						NIM_BOOL LOC22;
						nimln(524, "lazybtree.nim");
						nimln(524, "lazybtree.nim");
						LOC22 = 0;
						LOC22 = isclean_733523(w);
						if (!!(LOC22)) goto LA23;
						nimln(525, "lazybtree.nim");
						(*it_733441).Level = level;
						nimln(526, "lazybtree.nim");
						{
							nimln(526, "lazybtree.nim");
							nimln(526, "lazybtree.nim");
							if (!!(((*w).Node == NIM_NIL))) goto LA27;
							nimln(527, "lazybtree.nim");
							level = addInt(level, 1);
							nimln(528, "lazybtree.nim");
							if ((NU)(level) > (NU)(30)) raiseIndexError();
							(*it_733441).Path[(level)- 0].Field0 = -1;
							nimln(529, "lazybtree.nim");
							if ((NU)(level) > (NU)(30)) raiseIndexError();
							asgnRefNoCycle((void**) &(*it_733441).Path[(level)- 0].Field1, (*w).Node);
							nimln(530, "lazybtree.nim");
							(*it_733441).Level = level;
						}
						goto LA25;
						LA27: ;
						{
							NI TMP417;
							nimln(532, "lazybtree.nim");
							if ((NU)(level) > (NU)(30)) raiseIndexError();
							nimln(532, "lazybtree.nim");
							TMP417 = addInt(i, 1);
							(*it_733441).Path[(level)- 0].Field0 = (NI64)(TMP417);
						}
						LA25: ;
						nimln(533, "lazybtree.nim");
						nimln(533, "lazybtree.nim");
						result = w;
						goto BeforeRet;
					}
					LA23: ;
					nimln(534, "lazybtree.nim");
					{
						nimln(534, "lazybtree.nim");
						nimln(534, "lazybtree.nim");
						if (!!(((*w).Node == NIM_NIL))) goto LA32;
						nimln(535, "lazybtree.nim");
						nd = (*w).Node;
						nimln(536, "lazybtree.nim");
						i = -1;
						nimln(537, "lazybtree.nim");
						level = addInt(level, 1);
					}
					goto LA30;
					LA32: ;
					{
						nimln(538, "lazybtree.nim");
						i = addInt(i, 1);
					}
					LA30: ;
				}
				LA10: ;
			}
			goto LA6;
			LA8: ;
			{
				nimln(540, "lazybtree.nim");
				level = subInt(level, 1);
				nimln(541, "lazybtree.nim");
				{
					nimln(541, "lazybtree.nim");
					if (!(level < 0)) goto LA38;
					nimln(541, "lazybtree.nim");
					goto LA5;
				}
				LA38: ;
				nimln(542, "lazybtree.nim");
				if ((NU)(level) > (NU)(30)) raiseIndexError();
				nd = (*it_733441).Path[(level)- 0].Field1;
				nimln(543, "lazybtree.nim");
				if ((NU)(level) > (NU)(30)) raiseIndexError();
				i = (*it_733441).Path[(level)- 0].Field0;
				nimln(544, "lazybtree.nim");
				i = addInt(i, 1);
			}
			LA6: ;
		} LA5: ;
	}
	LA3: ;
	nimln(545, "lazybtree.nim");
	nimln(545, "lazybtree.nim");
	result = NIM_NIL;
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, foreach_734404)(tbtree728049* n_734411, TY734421 visit_734420) {
	nimfr("forEach", "lazybtree.nim")
	nimln(439, "lazybtree.nim");
	{
		tbtree728049* n1_734423;
		NI i_734427;
		nimln(439, "lazybtree.nim");
		nimln(439, "lazybtree.nim");
		if (!!((n_734411 == NIM_NIL))) goto LA3;
		nimln(440, "lazybtree.nim");
		n1_734423 = (*n_734411).Left;
		nimln(441, "lazybtree.nim");
		{
			nimln(441, "lazybtree.nim");
			nimln(441, "lazybtree.nim");
			if (!!((n1_734423 == NIM_NIL))) goto LA7;
			nimln(477, "lazybtree.nim");
			foreach_734404(n1_734423, visit_734420);
		}
		LA7: ;
		nimln(447, "lazybtree.nim");
		i_734427 = 0;
		nimln(448, "lazybtree.nim");
		while (1) {
			titem728056* w_734429;
			nimln(448, "lazybtree.nim");
			if (!(i_734427 < ((NI) ((*n_734411).Count)))) goto LA9;
			nimln(449, "lazybtree.nim");
			if ((NU)(i_734427) >= (NU)((*n_734411).Slots->Sup.len)) raiseIndexError();
			w_734429 = (*n_734411).Slots->data[i_734427];
			nimln(450, "lazybtree.nim");
			{
				NIM_BOOL LOC12;
				nimln(450, "lazybtree.nim");
				nimln(450, "lazybtree.nim");
				LOC12 = 0;
				LOC12 = isclean_733523(w_734429);
				if (!!(LOC12)) goto LA13;
				nimln(479, "lazybtree.nim");
				visit_734420.ClEnv? visit_734420.ClPrc((*w_734429).Key, (*w_734429).Value, visit_734420.ClEnv):((TMP418)(visit_734420.ClPrc))((*w_734429).Key, (*w_734429).Value);
			}
			LA13: ;
			nimln(457, "lazybtree.nim");
			n1_734423 = (*w_734429).Node;
			nimln(458, "lazybtree.nim");
			{
				nimln(458, "lazybtree.nim");
				nimln(458, "lazybtree.nim");
				if (!!((n1_734423 == NIM_NIL))) goto LA17;
				nimln(477, "lazybtree.nim");
				foreach_734404(n1_734423, visit_734420);
			}
			LA17: ;
			nimln(464, "lazybtree.nim");
			i_734427 = addInt(i_734427, 1);
		} LA9: ;
	}
	LA3: ;
	popFrame();
}
N_NOINLINE(void, lazybtreeInit)(void) {
	NimStringDesc* LOC1;
	nimfr("lazybtree", "lazybtree.nim")
	nimln(260, "lazybtree.nim");
	LOC1 = 0;
	LOC1 = line_722298; line_722298 = copyStringRC1(((NimStringDesc*) &TMP250));
	if (LOC1) nimGCunrefNoCycle(LOC1);
	popFrame();
}

N_NOINLINE(void, lazybtreeDatInit)(void) {
static TNimNode* TMP280[3];
static TNimNode* TMP281[4];
static TNimNode* TMP381[4];
static TNimNode* TMP382[3];
static TNimNode* TMP412[3];
static TNimNode* TMP413[2];
static TNimNode TMP242[28];
NTI728049.size = sizeof(tbtree728049);
NTI728049.kind = 18;
NTI728049.base = 0;
NTI728049.flags = 2;
TMP280[0] = &TMP242[1];
NTI728056.size = sizeof(titem728056);
NTI728056.kind = 18;
NTI728056.base = 0;
NTI728056.flags = 2;
TMP281[0] = &TMP242[3];
TMP242[3].kind = 1;
TMP242[3].offset = offsetof(titem728056, Key);
TMP242[3].typ = (&NTI143);
TMP242[3].name = "key";
TMP281[1] = &TMP242[4];
TMP242[4].kind = 1;
TMP242[4].offset = offsetof(titem728056, Value);
TMP242[4].typ = (&NTI728005);
TMP242[4].name = "value";
TMP281[2] = &TMP242[5];
TMP242[5].kind = 1;
TMP242[5].offset = offsetof(titem728056, Node);
TMP242[5].typ = (&NTI728046);
TMP242[5].name = "node";
TMP281[3] = &TMP242[6];
TMP242[6].kind = 1;
TMP242[6].offset = offsetof(titem728056, Valset);
TMP242[6].typ = (&NTI134);
TMP242[6].name = "val_set";
TMP242[2].len = 4; TMP242[2].kind = 2; TMP242[2].sons = &TMP281[0];
NTI728056.node = &TMP242[2];
NTI728053.size = sizeof(titem728056*);
NTI728053.kind = 22;
NTI728053.base = (&NTI728056);
NTI728053.flags = 2;
NTI728053.marker = TMP282;
NTI728052.size = sizeof(titems728052*);
NTI728052.kind = 24;
NTI728052.base = (&NTI728053);
NTI728052.flags = 2;
NTI728052.marker = TMP283;
TMP242[1].kind = 1;
TMP242[1].offset = offsetof(tbtree728049, Slots);
TMP242[1].typ = (&NTI728052);
TMP242[1].name = "slots";
TMP280[1] = &TMP242[7];
TMP242[7].kind = 1;
TMP242[7].offset = offsetof(tbtree728049, Left);
TMP242[7].typ = (&NTI728046);
TMP242[7].name = "left";
TMP280[2] = &TMP242[8];
TMP242[8].kind = 1;
TMP242[8].offset = offsetof(tbtree728049, Count);
TMP242[8].typ = (&NTI112);
TMP242[8].name = "count";
TMP242[0].len = 3; TMP242[0].kind = 2; TMP242[0].sons = &TMP280[0];
NTI728049.node = &TMP242[0];
NTI728046.size = sizeof(tbtree728049*);
NTI728046.kind = 22;
NTI728046.base = (&NTI728049);
NTI728046.flags = 2;
NTI728046.marker = TMP284;
NTI731043.size = sizeof(titem731043);
NTI731043.kind = 18;
NTI731043.base = 0;
NTI731043.flags = 2;
TMP381[0] = &TMP242[10];
TMP242[10].kind = 1;
TMP242[10].offset = offsetof(titem731043, Key);
TMP242[10].typ = (&NTI728005);
TMP242[10].name = "key";
TMP381[1] = &TMP242[11];
TMP242[11].kind = 1;
TMP242[11].offset = offsetof(titem731043, Value);
TMP242[11].typ = (&NTI143);
TMP242[11].name = "value";
TMP381[2] = &TMP242[12];
NTI731036.size = sizeof(tbtree731036);
NTI731036.kind = 18;
NTI731036.base = 0;
NTI731036.flags = 2;
TMP382[0] = &TMP242[14];
NTI731039.size = sizeof(titems731039*);
NTI731039.kind = 24;
NTI731039.base = (&NTI731101);
NTI731039.flags = 2;
NTI731039.marker = TMP383;
TMP242[14].kind = 1;
TMP242[14].offset = offsetof(tbtree731036, Slots);
TMP242[14].typ = (&NTI731039);
TMP242[14].name = "slots";
TMP382[1] = &TMP242[15];
TMP242[15].kind = 1;
TMP242[15].offset = offsetof(tbtree731036, Left);
TMP242[15].typ = (&NTI731033);
TMP242[15].name = "left";
TMP382[2] = &TMP242[16];
TMP242[16].kind = 1;
TMP242[16].offset = offsetof(tbtree731036, Count);
TMP242[16].typ = (&NTI112);
TMP242[16].name = "count";
TMP242[13].len = 3; TMP242[13].kind = 2; TMP242[13].sons = &TMP382[0];
NTI731036.node = &TMP242[13];
NTI731033.size = sizeof(tbtree731036*);
NTI731033.kind = 22;
NTI731033.base = (&NTI731036);
NTI731033.flags = 2;
NTI731033.marker = TMP384;
TMP242[12].kind = 1;
TMP242[12].offset = offsetof(titem731043, Node);
TMP242[12].typ = (&NTI731033);
TMP242[12].name = "node";
TMP381[3] = &TMP242[17];
TMP242[17].kind = 1;
TMP242[17].offset = offsetof(titem731043, Valset);
TMP242[17].typ = (&NTI134);
TMP242[17].name = "val_set";
TMP242[9].len = 4; TMP242[9].kind = 2; TMP242[9].sons = &TMP381[0];
NTI731043.node = &TMP242[9];
NTI731101.size = sizeof(titem731043*);
NTI731101.kind = 22;
NTI731101.base = (&NTI731043);
NTI731101.flags = 2;
NTI731101.marker = TMP385;
NTI733096.size = sizeof(rtreeiterator733096);
NTI733096.kind = 17;
NTI733096.base = 0;
TMP412[0] = &TMP242[19];
NTI728495.size = sizeof(rpath728495);
NTI728495.kind = 18;
NTI728495.base = 0;
NTI728495.flags = 2;
TMP413[0] = &TMP242[21];
TMP242[21].kind = 1;
TMP242[21].offset = offsetof(rpath728495, Field0);
TMP242[21].typ = (&NTI106);
TMP242[21].name = "Field0";
TMP413[1] = &TMP242[22];
TMP242[22].kind = 1;
TMP242[22].offset = offsetof(rpath728495, Field1);
TMP242[22].typ = (&NTI728046);
TMP242[22].name = "Field1";
TMP242[20].len = 2; TMP242[20].kind = 2; TMP242[20].sons = &TMP413[0];
NTI728495.node = &TMP242[20];
NTI728488.size = sizeof(TY728488);
NTI728488.kind = 16;
NTI728488.base = (&NTI728495);
NTI728488.flags = 2;
TMP242[19].kind = 1;
TMP242[19].offset = offsetof(rtreeiterator733096, Path);
TMP242[19].typ = (&NTI728488);
TMP242[19].name = "path";
TMP412[1] = &TMP242[23];
TMP242[23].kind = 1;
TMP242[23].offset = offsetof(rtreeiterator733096, Level);
TMP242[23].typ = (&NTI106);
TMP242[23].name = "level";
TMP412[2] = &TMP242[24];
TMP242[24].kind = 1;
TMP242[24].offset = offsetof(rtreeiterator733096, Current);
TMP242[24].typ = (&NTI728053);
TMP242[24].name = "current";
TMP242[18].len = 3; TMP242[18].kind = 2; TMP242[18].sons = &TMP412[0];
NTI733096.node = &TMP242[18];
NTI733093.size = sizeof(riteratorkeys733093);
NTI733093.kind = 17;
NTI733093.base = (&NTI733096);
TMP242[25].len = 0; TMP242[25].kind = 2;
NTI733093.node = &TMP242[25];
NTI733090.size = sizeof(riteratorkeys733093*);
NTI733090.kind = 22;
NTI733090.base = (&NTI733093);
NTI733090.marker = TMP414;
NTI733183.size = sizeof(riteratorvalues733183);
NTI733183.kind = 17;
NTI733183.base = (&NTI733096);
TMP242[26].len = 0; TMP242[26].kind = 2;
NTI733183.node = &TMP242[26];
NTI733180.size = sizeof(riteratorvalues733183*);
NTI733180.kind = 22;
NTI733180.base = (&NTI733183);
NTI733180.marker = TMP415;
NTI733251.size = sizeof(riteratorpairs733251);
NTI733251.kind = 17;
NTI733251.base = (&NTI733096);
TMP242[27].len = 0; TMP242[27].kind = 2;
NTI733251.node = &TMP242[27];
NTI733248.size = sizeof(riteratorpairs733251*);
NTI733248.kind = 22;
NTI733248.base = (&NTI733251);
NTI733248.marker = TMP416;
}

