/* Generated by Nimrod Compiler v0.9.5 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nimrod -o /home/andreysh/Projects/nimrod/stone_head/nimcache/main.o /home/andreysh/Projects/nimrod/stone_head/nimcache/main.c */
#define NIM_INTBITS 64
#include "nimbase.h"
static N_INLINE(void, initStackBottom)(void);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
N_NOINLINE(void, systemInit)(void);
N_NOINLINE(void, systemDatInit)(void);
N_NOINLINE(void, unsignedInit)(void);
N_NOINLINE(void, unsignedDatInit)(void);
N_NOINLINE(void, sdlInit)(void);
N_NOINLINE(void, sdlDatInit)(void);
N_NOINLINE(void, parseutilsInit)(void);
N_NOINLINE(void, parseutilsDatInit)(void);
N_NOINLINE(void, strutilsInit)(void);
N_NOINLINE(void, strutilsDatInit)(void);
N_NOINLINE(void, macrosInit)(void);
N_NOINLINE(void, macrosDatInit)(void);
N_NOINLINE(void, sequtilsInit)(void);
N_NOINLINE(void, sequtilsDatInit)(void);
N_NOINLINE(void, x11xInit)(void);
N_NOINLINE(void, x11xDatInit)(void);
N_NOINLINE(void, x11xlibInit)(void);
N_NOINLINE(void, x11xlibDatInit)(void);
N_NOINLINE(void, x11keysymInit)(void);
N_NOINLINE(void, x11keysymDatInit)(void);
N_NOINLINE(void, x11xutilInit)(void);
N_NOINLINE(void, x11xutilDatInit)(void);
N_NOINLINE(void, openglopenglInit)(void);
N_NOINLINE(void, openglopenglDatInit)(void);
N_NOINLINE(void, timesInit)(void);
N_NOINLINE(void, timesDatInit)(void);
N_NOINLINE(void, mathInit)(void);
N_NOINLINE(void, mathDatInit)(void);
N_NOINLINE(void, binsearchInit)(void);
N_NOINLINE(void, binsearchDatInit)(void);
N_NOINLINE(void, traitsInit)(void);
N_NOINLINE(void, traitsDatInit)(void);
N_NOINLINE(void, forloopsInit)(void);
N_NOINLINE(void, forloopsDatInit)(void);
N_NOINLINE(void, lazybtreeInit)(void);
N_NOINLINE(void, lazybtreeDatInit)(void);
N_NOINLINE(void, helperInit)(void);
N_NOINLINE(void, helperDatInit)(void);
N_NOINLINE(void, helperParseInit)(void);
N_NOINLINE(void, helperParseDatInit)(void);
N_NOINLINE(void, dynobjInit)(void);
N_NOINLINE(void, dynobjDatInit)(void);
N_NOINLINE(void, colorsInit)(void);
N_NOINLINE(void, colorsDatInit)(void);
N_NOINLINE(void, hashesInit)(void);
N_NOINLINE(void, hashesDatInit)(void);
N_NOINLINE(void, streamsInit)(void);
N_NOINLINE(void, streamsDatInit)(void);
N_NOINLINE(void, lexbaseInit)(void);
N_NOINLINE(void, lexbaseDatInit)(void);
N_NOINLINE(void, unicodeInit)(void);
N_NOINLINE(void, unicodeDatInit)(void);
N_NOINLINE(void, jsonInit)(void);
N_NOINLINE(void, jsonDatInit)(void);
N_NOINLINE(void, posixInit)(void);
N_NOINLINE(void, posixDatInit)(void);
N_NOINLINE(void, osInit)(void);
N_NOINLINE(void, osDatInit)(void);
N_NOINLINE(void, tablesInit)(void);
N_NOINLINE(void, tablesDatInit)(void);
N_NOINLINE(void, applicationInit)(void);
N_NOINLINE(void, applicationDatInit)(void);
N_NOINLINE(void, graphicsInit)(void);
N_NOINLINE(void, graphicsDatInit)(void);
N_NOINLINE(void, utilsInit)(void);
N_NOINLINE(void, utilsDatInit)(void);
N_NOINLINE(void, MGameFieldTypeInit)(void);
N_NOINLINE(void, MGameFieldTypeDatInit)(void);
N_NOINLINE(void, MProtagonistTypeInit)(void);
N_NOINLINE(void, MProtagonistTypeDatInit)(void);
N_NOINLINE(void, MGlobalInit)(void);
N_NOINLINE(void, MGlobalDatInit)(void);
N_NOINLINE(void, MMapsInit)(void);
N_NOINLINE(void, MMapsDatInit)(void);
N_NOINLINE(void, MGameFieldBodyInit)(void);
N_NOINLINE(void, MGameFieldBodyDatInit)(void);
N_NOINLINE(void, MProtagonistBodyInit)(void);
N_NOINLINE(void, MProtagonistBodyDatInit)(void);
N_NOINLINE(void, mainInit)(void);
N_NOINLINE(void, mainDatInit)(void);
extern TFrame* frameptr_13038;

static N_INLINE(void, initStackBottom)(void) {
	void* volatile locals;
	locals = 0;
	locals = ((void*) (&locals));
	setStackBottom(locals);
}
void PreMain() {
	systemDatInit();
	systemInit();
	unsignedDatInit();
	sdlDatInit();
	parseutilsDatInit();
	strutilsDatInit();
	macrosDatInit();
	sequtilsDatInit();
	x11xDatInit();
	x11xlibDatInit();
	x11keysymDatInit();
	x11xutilDatInit();
	openglopenglDatInit();
	timesDatInit();
	mathDatInit();
	binsearchDatInit();
	traitsDatInit();
	forloopsDatInit();
	lazybtreeDatInit();
	helperDatInit();
	helperParseDatInit();
	dynobjDatInit();
	colorsDatInit();
	hashesDatInit();
	streamsDatInit();
	lexbaseDatInit();
	unicodeDatInit();
	jsonDatInit();
	posixDatInit();
	osDatInit();
	tablesDatInit();
	applicationDatInit();
	graphicsDatInit();
	utilsDatInit();
	MGameFieldTypeDatInit();
	MProtagonistTypeDatInit();
	MGlobalDatInit();
	MMapsDatInit();
	MGameFieldBodyDatInit();
	MProtagonistBodyDatInit();
	mainDatInit();
	initStackBottom();
	unsignedInit();
	sdlInit();
	parseutilsInit();
	strutilsInit();
	macrosInit();
	sequtilsInit();
	x11xInit();
	x11xlibInit();
	x11keysymInit();
	x11xutilInit();
	openglopenglInit();
	timesInit();
	mathInit();
	binsearchInit();
	traitsInit();
	forloopsInit();
	lazybtreeInit();
	helperInit();
	helperParseInit();
	dynobjInit();
	colorsInit();
	hashesInit();
	streamsInit();
	lexbaseInit();
	unicodeInit();
	jsonInit();
	posixInit();
	osInit();
	tablesInit();
	applicationInit();
	graphicsInit();
	utilsInit();
	MGameFieldTypeInit();
	MProtagonistTypeInit();
	MGlobalInit();
	MMapsInit();
	MGameFieldBodyInit();
	MProtagonistBodyInit();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMain)(void) {
	PreMain();
	mainInit();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}


static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_13038;
	frameptr_13038 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_13038 = (*frameptr_13038).prev;
}
N_NOINLINE(void, mainInit)(void) {
	nimfr("main", "main.nim")
	popFrame();
}

N_NOINLINE(void, mainDatInit)(void) {
}

