/* Generated by Nimrod Compiler v0.9.5 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nimrod -o /home/andreysh/Projects/nimrod/stone_head/nimcache/math.o /home/andreysh/Projects/nimrod/stone_head/nimcache/math.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <math.h>

#include <stdlib.h>
typedef struct trunningstat718630 trunningstat718630;
struct  trunningstat718630  {
NI N;
NF Sum;
NF Min;
NF Max;
NF Mean;
NF Oldm;
NF Olds;
NF News;
};
N_NIMCALL(NU8, classify_717220)(NF x);
N_NIMCALL(NI, binom_717230)(NI n, NI k);
N_NIMCALL(NI, fac_717255)(NI n);
N_NIMCALL(NIM_BOOL, ispoweroftwo_717278)(NI x);
N_NIMCALL(NI, nextpoweroftwo_717284)(NI x);
N_NIMCALL(NI, countbits32_717824)(NI32 n);
N_NIMCALL(NF, sum_717885)(NF* x_717891, NI x_717891Len0);
N_NIMCALL(NF, mean_717878)(NF* x, NI xLen0);
N_NIMCALL(NF, variance_717946)(NF* x, NI xLen0);
N_NIMCALL(NF, log2_718018)(NF x);
N_NIMCALL(NF, random_717983)(NF max);
N_NIMCALL(void, randomize_718002)(void);
N_NIMCALL(void, randomize_718005)(NI seed);
N_NIMCALL(NF, ntepochTime)(void);
N_NIMCALL(NI, random_717979)(NI max);
N_NIMCALL(NF, mod_718602)(NF x, NF y);
N_NIMCALL(void, push_718640)(trunningstat718630* s, NF x);
N_NIMCALL(void, push_718664)(trunningstat718630* s, NI x);
N_NIMCALL(NF, variance_718671)(trunningstat718630* s);
N_NIMCALL(NF, standarddeviation_718678)(trunningstat718630* s);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
extern TFrame* frameptr_13038;

N_NIMCALL(NU8, classify_717220)(NF x) {
	NU8 result;
	result = 0;
	{
		if (!(x == 0.0)) goto LA3;
		{
			if (!(((NF)(1.0000000000000000e+00) / (NF)(x)) == INF)) goto LA7;
			result = ((NU8) 2);
			goto BeforeRet;
		}
		goto LA5;
		LA7: ;
		{
			result = ((NU8) 3);
			goto BeforeRet;
		}
		LA5: ;
	}
	LA3: ;
	{
		if (!(((NF)(x) * (NF)(5.0000000000000000e-01)) == x)) goto LA12;
		{
			if (!(0.0 < x)) goto LA16;
			result = ((NU8) 5);
			goto BeforeRet;
		}
		goto LA14;
		LA16: ;
		{
			result = ((NU8) 6);
			goto BeforeRet;
		}
		LA14: ;
	}
	LA12: ;
	{
		if (!!((x == x))) goto LA21;
		result = ((NU8) 4);
		goto BeforeRet;
	}
	LA21: ;
	result = ((NU8) 0);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, binom_717230)(NI n, NI k) {
	NI result;
	NI i_717248;
	NI res_717250;
	result = 0;
	{
		if (!(k <= 0)) goto LA3;
		result = 1;
		goto BeforeRet;
	}
	LA3: ;
	{
		if (!(n < (NI64)(2 * k))) goto LA7;
		result = binom_717230(n, (NI64)(n - k));
		goto BeforeRet;
	}
	LA7: ;
	result = n;
	i_717248 = 0;
	res_717250 = 2;
	while (1) {
		if (!(res_717250 <= k)) goto LA9;
		i_717248 = res_717250;
		result = (NI64)((NI64)(result * (NI64)((NI64)(n + 1) - i_717248)) / i_717248);
		res_717250 += 1;
	} LA9: ;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, fac_717255)(NI n) {
	NI result;
	NI i_717271;
	NI res_717273;
	result = 0;
	result = 1;
	i_717271 = 0;
	res_717273 = 2;
	while (1) {
		if (!(res_717273 <= n)) goto LA1;
		i_717271 = res_717273;
		result = (NI64)(result * i_717271);
		res_717273 += 1;
	} LA1: ;
	return result;
}

N_NIMCALL(NIM_BOOL, ispoweroftwo_717278)(NI x) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = !((x == 0));
	if (!(LOC1)) goto LA2;
	LOC1 = ((NI)(x & (NI64)(x - 1)) == 0);
	LA2: ;
	result = LOC1;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, nextpoweroftwo_717284)(NI x) {
	NI result;
	result = 0;
	result = (NI64)(x - 1);
	result = (NI)(result | (NI)((NU64)(result) >> (NU64)(32)));
	result = (NI)(result | (NI)((NU64)(result) >> (NU64)(4)));
	result = (NI)(result | (NI)((NU64)(result) >> (NU64)(2)));
	result = (NI)(result | (NI)((NU64)(result) >> (NU64)(1)));
	result += ((NI) ((NI64)(1 + ((NI) ((x <= 0))))));
	return result;
}

N_NIMCALL(NI, countbits32_717824)(NI32 n) {
	NI result;
	NI32 v;
	result = 0;
	v = n;
	v = (NI32)((NU32)(v) - (NU32)((NI32)((NI32)((NU32)(v) >> (NU32)(((NI32) 1))) & ((NI32) 1431655765))));
	v = (NI32)((NU32)((NI32)(v & ((NI32) 858993459))) + (NU32)((NI32)((NI32)((NU32)(v) >> (NU32)(((NI32) 2))) & ((NI32) 858993459))));
	result = ((NI) ((NI32)((NU32)((NI32)((NU32)((NI32)((NI32)((NU32)(v) + (NU32)((NI32)((NU32)(v) >> (NU32)(((NI32) 4))))) & ((NI32) 252645135))) * (NU32)(((NI32) 16843009)))) >> (NU32)(((NI32) 24)))));
	return result;
}

N_NIMCALL(NF, sum_717885)(NF* x_717891, NI x_717891Len0) {
	NF result;
	NF i_717932;
	NI i_717934;
	result = 0;
	i_717932 = 0;
	i_717934 = 0;
	while (1) {
		if (!(i_717934 < x_717891Len0)) goto LA1;
		i_717932 = x_717891[i_717934];
		result = ((NF)(result) + (NF)(i_717932));
		i_717934 += 1;
	} LA1: ;
	return result;
}

N_NIMCALL(NF, mean_717878)(NF* x, NI xLen0) {
	NF result;
	NF LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = sum_717885(x, xLen0);
	result = ((NF)(LOC1) / (NF)(((double) (xLen0))));
	return result;
}

N_NIMCALL(NF, variance_717946)(NF* x, NI xLen0) {
	NF result;
	NF m;
	NI i_717963;
	NI HEX3Atmp_717972;
	NI res_717974;
	result = 0;
	result = 0.0;
	m = mean_717878(x, xLen0);
	i_717963 = 0;
	HEX3Atmp_717972 = 0;
	HEX3Atmp_717972 = (xLen0-1);
	res_717974 = 0;
	while (1) {
		NF diff;
		if (!(res_717974 <= HEX3Atmp_717972)) goto LA1;
		i_717963 = res_717974;
		diff = ((NF)(x[i_717963]) - (NF)(m));
		result = ((NF)(result) + (NF)(((NF)(diff) * (NF)(diff))));
		res_717974 += 1;
	} LA1: ;
	result = ((NF)(result) / (NF)(((double) (xLen0))));
	return result;
}

N_NIMCALL(NF, log2_718018)(NF x) {
	NF result;
	NF LOC1;
	NF LOC2;
	result = 0;
	LOC1 = 0;
	LOC1 = log(x);
	LOC2 = 0;
	LOC2 = log(2.0000000000000000e+00);
	result = ((NF)(LOC1) / (NF)(LOC2));
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NF, random_717983)(NF max) {
	NF result;
	NF LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = drand48();
	result = ((NF)(LOC1) * (NF)(max));
	return result;
}

N_NIMCALL(void, randomize_718005)(NI seed) {
	srand(((int) (seed)));
	srand48(seed);
}

N_NIMCALL(void, randomize_718002)(void) {
	union { NF source; NI dest; } LOC1;
	LOC1.source = ntepochTime();
	randomize_718005(LOC1.dest);
}

N_NIMCALL(NI, random_717979)(NI max) {
	NI result;
	int LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = rand();
	result = (NI64)(((NI) (LOC1)) % max);
	return result;
}

N_NIMCALL(NF, mod_718602)(NF x, NF y) {
	NF result;
	result = 0;
	{
		if (!(y == 0.0)) goto LA3;
		result = x;
	}
	goto LA1;
	LA3: ;
	{
		NF LOC6;
		LOC6 = 0;
		LOC6 = floor(((NF)(x) / (NF)(y)));
		result = ((NF)(x) - (NF)(((NF)(y) * (NF)(LOC6))));
	}
	LA1: ;
	return result;
}

N_NIMCALL(void, push_718640)(trunningstat718630* s, NF x) {
	(*s).N += 1;
	{
		if (!((*s).N == 1)) goto LA3;
		(*s).Min = x;
		(*s).Max = x;
		(*s).Oldm = x;
		(*s).Mean = x;
		(*s).Olds = 0.0;
	}
	goto LA1;
	LA3: ;
	{
		{
			if (!(x < (*s).Min)) goto LA8;
			(*s).Min = x;
		}
		LA8: ;
		{
			if (!((*s).Max < x)) goto LA12;
			(*s).Max = x;
		}
		LA12: ;
		(*s).Mean = ((NF)((*s).Oldm) + (NF)(((NF)(((NF)(x) - (NF)((*s).Oldm))) / (NF)(((double) ((*s).N))))));
		(*s).News = ((NF)((*s).Olds) + (NF)(((NF)(((NF)(x) - (NF)((*s).Oldm))) * (NF)(((NF)(x) - (NF)((*s).Mean))))));
		(*s).Oldm = (*s).Mean;
		(*s).Olds = (*s).News;
	}
	LA1: ;
	(*s).Sum = ((NF)((*s).Sum) + (NF)(x));
}

N_NIMCALL(void, push_718664)(trunningstat718630* s, NI x) {
	push_718640(s, ((double) (x)));
}

N_NIMCALL(NF, variance_718671)(trunningstat718630* s) {
	NF result;
	result = 0;
	{
		if (!(1 < (*s).N)) goto LA3;
		result = ((NF)((*s).News) / (NF)(((double) ((NI64)((*s).N - 1)))));
	}
	LA3: ;
	return result;
}

N_NIMCALL(NF, standarddeviation_718678)(trunningstat718630* s) {
	NF result;
	NF LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = variance_718671(s);
	result = sqrt(LOC1);
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_13038;
	frameptr_13038 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_13038 = (*frameptr_13038).prev;
}
N_NOINLINE(void, mathInit)(void) {
	nimfr("math", "math.nim")
	popFrame();
}

N_NOINLINE(void, mathDatInit)(void) {
}

