/* Generated by Nimrod Compiler v0.9.5 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nimrod -o /home/andreysh/Projects/nimrod/stone_head/nimcache/MGameFieldBody.o /home/andreysh/Projects/nimrod/stone_head/nimcache/MGameFieldBody.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>
typedef struct tgamefieldHEX3Aobjecttype788006 tgamefieldHEX3Aobjecttype788006;
typedef struct TY791217 TY791217;
typedef struct TY10665 TY10665;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY2289) (void* p, NI op);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY2289 marker;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  tgamefieldHEX3Aobjecttype788006  {
  TNimObject Sup;
NimStringDesc* Fillcolor;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TY10665 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct TY791217 {
  TGenericSeq Sup;
  TY10665* data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, glrect_792048)(NI x1_792052, NI y1_792054, NI x2_792056, NI y2_792058);
N_NIMCALL(void, glvertex_792060)(NI x_792064, NI y_792066, NI z_792068, NI w_792070);
N_NIMCALL(void, glline_792132)(NI x1_792136, NI y1_792138, NI x2_792140, NI y2_792142);
N_NIMCALL(void, draw_792002)(tgamefieldHEX3Aobjecttype788006* this_792004);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(void, glcolor_786005)(NimStringDesc* str);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
extern NIM_CONST TY791217* level2_791243;
STRING_LITERAL(TMP736, "w", 1);
STRING_LITERAL(TMP737, "#F5C2C2", 7);
extern TFrame* frameptr_13038;

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (NI64)((*a).Sup.len * 1));
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_13038;
	frameptr_13038 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_13038 = (*frameptr_13038).prev;
}

N_NIMCALL(void, draw_792002)(tgamefieldHEX3Aobjecttype788006* this_792004) {
	NI i_792036;
	NI res_792197;
	NI i_792130;
	NI res_792200;
	NI i_792180;
	NI res_792203;
	nimfr("draw", "MGameFieldBody.nim")
	i_792036 = 0;
	nimln(4, "utils.nim");
	res_792197 = 0;
	nimln(6, "utils.nim");
	while (1) {
		NI j_792046;
		NI res_792194;
		nimln(6, "utils.nim");
		if (!(res_792197 < 11)) goto LA1;
		nimln(4, "utils.nim");
		i_792036 = res_792197;
		j_792046 = 0;
		nimln(4, "utils.nim");
		res_792194 = 0;
		nimln(6, "utils.nim");
		while (1) {
			nimln(6, "utils.nim");
			if (!(res_792194 < 20)) goto LA2;
			nimln(4, "utils.nim");
			j_792046 = res_792194;
			nimln(17, "MGameFieldBody.nim");
			{
				NI TMP738;
				NI TMP739;
				NI TMP740;
				NI TMP741;
				NI TMP742;
				NI TMP743;
				NI TMP744;
				NI TMP745;
				nimln(17, "MGameFieldBody.nim");
				if ((NU)(i_792036) >= (NU)(level2_791243->Sup.len)) raiseIndexError();
				if ((NU)(j_792046) >= (NU)(level2_791243->data[i_792036]->Sup.len)) raiseIndexError();
				if (!eqStrings(level2_791243->data[i_792036]->data[j_792046], ((NimStringDesc*) &TMP736))) goto LA5;
				nimln(18, "MGameFieldBody.nim");
				glcolor_786005(((NimStringDesc*) &TMP737));
				nimln(19, "MGameFieldBody.nim");
				nimln(19, "MGameFieldBody.nim");
				TMP738 = mulInt(j_792046, 25);
				nimln(19, "MGameFieldBody.nim");
				nimln(19, "MGameFieldBody.nim");
				TMP739 = mulInt(i_792036, 25);
				TMP740 = addInt((NI64)(TMP739), 1);
				nimln(19, "MGameFieldBody.nim");
				nimln(19, "MGameFieldBody.nim");
				nimln(19, "MGameFieldBody.nim");
				TMP741 = addInt(j_792046, 1);
				TMP742 = mulInt((NI64)(TMP741), 25);
				TMP743 = subInt((NI64)(TMP742), 1);
				nimln(19, "MGameFieldBody.nim");
				nimln(19, "MGameFieldBody.nim");
				TMP744 = addInt(i_792036, 1);
				TMP745 = mulInt((NI64)(TMP744), 25);
				glrect_792048((NI64)(TMP738), (NI64)(TMP740), (NI64)(TMP743), (NI64)(TMP745));
			}
			LA5: ;
			nimln(8, "utils.nim");
			res_792194 = addInt(res_792194, 1);
		} LA2: ;
		nimln(8, "utils.nim");
		res_792197 = addInt(res_792197, 1);
	} LA1: ;
	nimln(21, "MGameFieldBody.nim");
	glcolor_786005((*this_792004).Fillcolor);
	i_792130 = 0;
	nimln(1451, "system.nim");
	res_792200 = 0;
	nimln(1452, "system.nim");
	while (1) {
		nimln(1452, "system.nim");
		if (!(res_792200 <= 275)) goto LA7;
		nimln(1451, "system.nim");
		i_792130 = res_792200;
		nimln(24, "MGameFieldBody.nim");
		glline_792132(0, i_792130, 500, i_792130);
		nimln(1454, "system.nim");
		res_792200 = addInt(res_792200, 25);
	} LA7: ;
	i_792180 = 0;
	nimln(1451, "system.nim");
	res_792203 = 0;
	nimln(1452, "system.nim");
	while (1) {
		nimln(1452, "system.nim");
		if (!(res_792203 <= 500)) goto LA8;
		nimln(1451, "system.nim");
		i_792180 = res_792203;
		nimln(27, "MGameFieldBody.nim");
		glline_792132(i_792180, 0, i_792180, 275);
		nimln(1454, "system.nim");
		res_792203 = addInt(res_792203, 25);
	} LA8: ;
	popFrame();
}
N_NOINLINE(void, MGameFieldBodyInit)(void) {
	nimfr("MGameFieldBody", "MGameFieldBody.nim")
	popFrame();
}

N_NOINLINE(void, MGameFieldBodyDatInit)(void) {
}

