/* Generated by Nimrod Compiler v0.9.5 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nimrod -o /home/andreysh/Projects/nimrod/stone_head/nimcache/MGlobal.o /home/andreysh/Projects/nimrod/stone_head/nimcache/MGlobal.c */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct TY790033 TY790033;
typedef struct tcattygameobjectHEX3Aobjecttype790027 tcattygameobjectHEX3Aobjecttype790027;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TNimObject TNimObject;
typedef struct tcell41290 tcell41290;
typedef struct tcellseq41306 tcellseq41306;
typedef struct tgcheap43216 tgcheap43216;
typedef struct tcellset41302 tcellset41302;
typedef struct tpagedesc41298 tpagedesc41298;
typedef struct tmemregion23610 tmemregion23610;
typedef struct tsmallchunk22838 tsmallchunk22838;
typedef struct tllchunk23604 tllchunk23604;
typedef struct tbigchunk22840 tbigchunk22840;
typedef struct tintset22815 tintset22815;
typedef struct ttrunk22811 ttrunk22811;
typedef struct tavlnode23608 tavlnode23608;
typedef struct tgcstat43214 tgcstat43214;
typedef struct TY790055 TY790055;
typedef struct tbasechunk22836 tbasechunk22836;
typedef struct tfreecell22828 tfreecell22828;
struct  TGenericSeq  {
NI len;
NI reserved;
};
typedef N_NIMCALL_PTR(void, TY2289) (void* p, NI op);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY2289 marker;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  tcattygameobjectHEX3Aobjecttype790027  {
  TNimObject Sup;
NU8 Kind;
TNimObject* Node;
};
struct  tcell41290  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq41306  {
NI Len;
NI Cap;
tcell41290** D;
};
struct  tcellset41302  {
NI Counter;
NI Max;
tpagedesc41298* Head;
tpagedesc41298** Data;
};
typedef tsmallchunk22838* TY23622[512];
typedef ttrunk22811* ttrunkbuckets22813[256];
struct  tintset22815  {
ttrunkbuckets22813 Data;
};
struct  tmemregion23610  {
NI Minlargeobj;
NI Maxlargeobj;
TY23622 Freesmallchunks;
tllchunk23604* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk22840* Freechunkslist;
tintset22815 Chunkstarts;
tavlnode23608* Root;
tavlnode23608* Deleted;
tavlnode23608* Last;
tavlnode23608* Freeavlnodes;
};
struct  tgcstat43214  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap43216  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq41306 Zct;
tcellseq41306 Decstack;
tcellset41302 Cycleroots;
tcellseq41306 Tempstack;
NI Recgclock;
tmemregion23610 Region;
tgcstat43214 Stat;
};
typedef NI TY22818[8];
struct  tpagedesc41298  {
tpagedesc41298* Next;
NI Key;
TY22818 Bits;
};
struct  tbasechunk22836  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk22838  {
  tbasechunk22836 Sup;
tsmallchunk22838* Next;
tsmallchunk22838* Prev;
tfreecell22828* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk23604  {
NI Size;
NI Acc;
tllchunk23604* Next;
};
struct  tbigchunk22840  {
  tbasechunk22836 Sup;
tbigchunk22840* Next;
tbigchunk22840* Prev;
NI Align;
NF Data;
};
struct  ttrunk22811  {
ttrunk22811* Next;
NI Key;
TY22818 Bits;
};
typedef tavlnode23608* TY23614[2];
struct  tavlnode23608  {
TY23614 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell22828  {
tfreecell22828* Next;
NI Zerofield;
};
struct TY790033 {
  TGenericSeq Sup;
  tcattygameobjectHEX3Aobjecttype790027* data[SEQ_DECL_SIZE];
};
struct TY790055 {
  TGenericSeq Sup;
  NU8 data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, TMP702)(void* p, NI op);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP703)(void* p, NI op);
static N_INLINE(void, nimGCunref)(void* p);
static N_INLINE(void, decref_46602)(tcell41290* c);
static N_INLINE(void, rtladdzct_46202)(tcell41290* c);
N_NOINLINE(void, addzct_44618)(tcellseq41306* s, tcell41290* c);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, canbecycleroot_44662)(tcell41290* c);
static N_INLINE(void, rtladdcycleroot_45435)(tcell41290* c);
N_NOINLINE(void, incl_42055)(tcellset41302* s, tcell41290* cell);
static N_INLINE(tcell41290*, usrtocell_44643)(void* usr);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_NIMCALL(void, TMP707)(void* p, NI op);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
TY790033* cattygameobjects_790054;
extern TNimType NTI2409; /* TObject */
TNimType NTI790027; /* TCattyGameObject:ObjectType */
TNimType NTI790011; /* TCattyGameObjectType */
extern TNimType NTI790029; /* ptr TObject */
TNimType NTI790017; /* TCattyGameObject */
TNimType NTI790033; /* seq[TCattyGameObject] */
extern tgcheap43216 gch_43244;
extern TFrame* frameptr_13038;
TY790055* cattykeyisdown_790076;
TNimType NTI790013; /* TCattyKeyType */
TNimType NTI790055; /* seq[TCattyKeyType] */
N_NIMCALL(void, TMP702)(void* p, NI op) {
	tcattygameobjectHEX3Aobjecttype790027* a;
	a = (tcattygameobjectHEX3Aobjecttype790027*)p;
}
N_NIMCALL(void, TMP703)(void* p, NI op) {
	TY790033* a;
	NI LOC1;
	a = (TY790033*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1], op);
	}
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_13038;
	frameptr_13038 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_13038 = (*frameptr_13038).prev;
}

static N_INLINE(void, rtladdzct_46202)(tcell41290* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_44618(&gch_43244.Zct, c);
	popFrame();
}

static N_INLINE(NIM_BOOL, canbecycleroot_44662)(tcell41290* c) {
	NIM_BOOL result;
	nimfr("canbeCycleRoot", "gc.nim")
	result = 0;
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	result = !((((*(*c).Typ).flags &(1<<((((NU8) 1))&7)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_45435)(tcell41290* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(189, "gc.nim");
	{
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		if (!!((((NI) ((NI)((*c).Refcount & 3))) == 3))) goto LA3;
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		(*c).Refcount = (NI)((NI)((*c).Refcount & -4) | 3);
		nimln(191, "gc.nim");
		incl_42055(&gch_43244.Cycleroots, c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, decref_46602)(tcell41290* c) {
	nimfr("decRef", "gc.nim")
	nimln(206, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		nimln(207, "gc.nim");
		rtladdzct_46202(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(208, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_44662(c);
		if (!LOC6) goto LA7;
		nimln(211, "gc.nim");
		rtladdcycleroot_45435(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(tcell41290*, usrtocell_44643)(void* usr) {
	tcell41290* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell41290*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell41290))))));
	popFrame();
	return result;
}

static N_INLINE(void, nimGCunref)(void* p) {
	tcell41290* LOC1;
	nimfr("nimGCunref", "gc.nim")
	nimln(223, "gc.nim");
	nimln(223, "gc.nim");
	LOC1 = 0;
	LOC1 = usrtocell_44643(p);
	decref_46602(LOC1);
	popFrame();
}
N_NIMCALL(void, TMP707)(void* p, NI op) {
	TY790055* a;
	NI LOC1;
	a = (TY790055*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	}
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell41290* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_44643(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_46202(c);
	}
	LA3: ;
	popFrame();
}
N_NOINLINE(void, MGlobalInit)(void) {
	nimfr("MGlobal", "MGlobal.nim")
	nimln(22, "MGlobal.nim");
	if (cattygameobjects_790054) nimGCunref(cattygameobjects_790054);
	cattygameobjects_790054 = (TY790033*) newSeqRC1((&NTI790033), 0);
	nimln(23, "MGlobal.nim");
	if (cattykeyisdown_790076) nimGCunrefNoCycle(cattykeyisdown_790076);
	cattykeyisdown_790076 = (TY790055*) newSeqRC1((&NTI790055), 0);
	popFrame();
}

N_NOINLINE(void, MGlobalDatInit)(void) {
static TNimNode* TMP698[2];
static TNimNode* TMP699[3];
NI TMP701;
static char* NIM_CONST TMP700[3] = {
"gtNil", 
"gtGameField", 
"gtProtagonist"};
static TNimNode* TMP704[4];
NI TMP706;
static char* NIM_CONST TMP705[4] = {
"kdRControl", 
"kdLControl", 
"kdRAlt", 
"kdLAlt"};
static TNimNode TMP694[12];
NTI790027.size = sizeof(tcattygameobjectHEX3Aobjecttype790027);
NTI790027.kind = 17;
NTI790027.base = (&NTI2409);
NTI790027.flags = 1;
TMP698[0] = &TMP694[1];
NTI790011.size = sizeof(NU8);
NTI790011.kind = 14;
NTI790011.base = 0;
NTI790011.flags = 3;
for (TMP701 = 0; TMP701 < 3; TMP701++) {
TMP694[TMP701+2].kind = 1;
TMP694[TMP701+2].offset = TMP701;
TMP694[TMP701+2].name = TMP700[TMP701];
TMP699[TMP701] = &TMP694[TMP701+2];
}
TMP694[5].len = 3; TMP694[5].kind = 2; TMP694[5].sons = &TMP699[0];
NTI790011.node = &TMP694[5];
TMP694[1].kind = 1;
TMP694[1].offset = offsetof(tcattygameobjectHEX3Aobjecttype790027, Kind);
TMP694[1].typ = (&NTI790011);
TMP694[1].name = "kind";
TMP698[1] = &TMP694[6];
TMP694[6].kind = 1;
TMP694[6].offset = offsetof(tcattygameobjectHEX3Aobjecttype790027, Node);
TMP694[6].typ = (&NTI790029);
TMP694[6].name = "node";
TMP694[0].len = 2; TMP694[0].kind = 2; TMP694[0].sons = &TMP698[0];
NTI790027.node = &TMP694[0];
NTI790017.size = sizeof(tcattygameobjectHEX3Aobjecttype790027*);
NTI790017.kind = 22;
NTI790017.base = (&NTI790027);
NTI790017.marker = TMP702;
NTI790033.size = sizeof(TY790033*);
NTI790033.kind = 24;
NTI790033.base = (&NTI790017);
NTI790033.marker = TMP703;
NTI790013.size = sizeof(NU8);
NTI790013.kind = 14;
NTI790013.base = 0;
NTI790013.flags = 3;
for (TMP706 = 0; TMP706 < 4; TMP706++) {
TMP694[TMP706+7].kind = 1;
TMP694[TMP706+7].offset = TMP706;
TMP694[TMP706+7].name = TMP705[TMP706];
TMP704[TMP706] = &TMP694[TMP706+7];
}
TMP694[11].len = 4; TMP694[11].kind = 2; TMP694[11].sons = &TMP704[0];
NTI790013.node = &TMP694[11];
NTI790055.size = sizeof(TY790055*);
NTI790055.kind = 24;
NTI790055.base = (&NTI790013);
NTI790055.flags = 2;
NTI790055.marker = TMP707;
}

