/* Generated by Nimrod Compiler v0.9.5 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nimrod -o /home/andreysh/Projects/nimrod/stone_head/nimcache/MMaps.o /home/andreysh/Projects/nimrod/stone_head/nimcache/MMaps.c */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct TY791217 TY791217;
typedef struct TY10665 TY10665;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct TY10665 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct TY791217 {
  TGenericSeq Sup;
  TY10665* data[SEQ_DECL_SIZE];
};
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
STRING_LITERAL(TMP710, " ", 1);
STRING_LITERAL(TMP711, "w", 1);
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[20];
} CNSTSEQ713 = {{20, 20}, {((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710)}};
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[20];
} CNSTSEQ714 = {{20, 20}, {((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710)}};
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[20];
} CNSTSEQ715 = {{20, 20}, {((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710)}};
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[20];
} CNSTSEQ716 = {{20, 20}, {((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710)}};
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[20];
} CNSTSEQ717 = {{20, 20}, {((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710)}};
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[20];
} CNSTSEQ718 = {{20, 20}, {((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710)}};
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[20];
} CNSTSEQ719 = {{20, 20}, {((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710)}};
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[20];
} CNSTSEQ720 = {{20, 20}, {((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710)}};
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[20];
} CNSTSEQ721 = {{20, 20}, {((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710)}};
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[20];
} CNSTSEQ722 = {{20, 20}, {((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710)}};
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[20];
} CNSTSEQ723 = {{20, 20}, {((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710)}};
NIM_CONST struct {
  TGenericSeq Sup;
  TY10665* data[11];
} CNSTSEQ724 = {{11, 11}, {((TY10665*)&CNSTSEQ713),
((TY10665*)&CNSTSEQ714),
((TY10665*)&CNSTSEQ715),
((TY10665*)&CNSTSEQ716),
((TY10665*)&CNSTSEQ717),
((TY10665*)&CNSTSEQ718),
((TY10665*)&CNSTSEQ719),
((TY10665*)&CNSTSEQ720),
((TY10665*)&CNSTSEQ721),
((TY10665*)&CNSTSEQ722),
((TY10665*)&CNSTSEQ723)}};
NIM_CONST TY791217* level1_791004 = ((TY791217*)&CNSTSEQ724);
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[20];
} CNSTSEQ725 = {{20, 20}, {((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710)}};
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[20];
} CNSTSEQ726 = {{20, 20}, {((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710)}};
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[20];
} CNSTSEQ727 = {{20, 20}, {((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710)}};
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[20];
} CNSTSEQ728 = {{20, 20}, {((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710)}};
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[20];
} CNSTSEQ729 = {{20, 20}, {((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710)}};
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[20];
} CNSTSEQ730 = {{20, 20}, {((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710)}};
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[20];
} CNSTSEQ731 = {{20, 20}, {((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710)}};
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[20];
} CNSTSEQ732 = {{20, 20}, {((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710)}};
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[20];
} CNSTSEQ733 = {{20, 20}, {((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710)}};
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[20];
} CNSTSEQ734 = {{20, 20}, {((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP711),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710)}};
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[20];
} CNSTSEQ735 = {{20, 20}, {((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710),
((NimStringDesc*) &TMP710)}};
NIM_CONST struct {
  TGenericSeq Sup;
  TY10665* data[11];
} CNSTSEQ736 = {{11, 11}, {((TY10665*)&CNSTSEQ725),
((TY10665*)&CNSTSEQ726),
((TY10665*)&CNSTSEQ727),
((TY10665*)&CNSTSEQ728),
((TY10665*)&CNSTSEQ729),
((TY10665*)&CNSTSEQ730),
((TY10665*)&CNSTSEQ731),
((TY10665*)&CNSTSEQ732),
((TY10665*)&CNSTSEQ733),
((TY10665*)&CNSTSEQ734),
((TY10665*)&CNSTSEQ735)}};
NIM_CONST TY791217* level2_791243 = ((TY791217*)&CNSTSEQ736);
extern TFrame* frameptr_13038;

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_13038;
	frameptr_13038 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_13038 = (*frameptr_13038).prev;
}
N_NOINLINE(void, MMapsInit)(void) {
	nimfr("MMaps", "MMaps.nim")
	popFrame();
}

N_NOINLINE(void, MMapsDatInit)(void) {
}

