/* Generated by Nimrod Compiler v0.9.5 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nimrod -o /home/andreysh/Projects/nimrod/stone_head/nimcache/MProtagonistBody.o /home/andreysh/Projects/nimrod/stone_head/nimcache/MProtagonistBody.c */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct tprotagonistHEX3Aobjecttype789013 tprotagonistHEX3Aobjecttype789013;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY2289) (void* p, NI op);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY2289 marker;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  tprotagonistHEX3Aobjecttype789013  {
  TNimObject Sup;
NI X;
NI Y;
NimStringDesc* Fillcolor;
NIM_BOOL Iscollision;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
N_NIMCALL(void, draw_793006)(tprotagonistHEX3Aobjecttype789013* this_793008);
N_NIMCALL(void, glcolor_786005)(NimStringDesc* str);
N_NIMCALL(void, glrect_792048)(NI x1_792052, NI y1_792054, NI x2_792056, NI y2_792058);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, onkeydown_793023)(tprotagonistHEX3Aobjecttype789013* this_793025, NI keycode);
extern TFrame* frameptr_13038;

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_13038;
	frameptr_13038 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_13038 = (*frameptr_13038).prev;
}

N_NIMCALL(void, draw_793006)(tprotagonistHEX3Aobjecttype789013* this_793008) {
	NI TMP748;
	NI TMP749;
	NI TMP750;
	NI TMP751;
	NI TMP752;
	NI TMP753;
	NI TMP754;
	NI TMP755;
	nimfr("draw", "MProtagonistBody.nim")
	nimln(12, "MProtagonistBody.nim");
	glcolor_786005((*this_793008).Fillcolor);
	nimln(13, "MProtagonistBody.nim");
	nimln(13, "MProtagonistBody.nim");
	TMP748 = mulInt((*this_793008).X, 25);
	nimln(13, "MProtagonistBody.nim");
	nimln(13, "MProtagonistBody.nim");
	TMP749 = mulInt((*this_793008).Y, 25);
	TMP750 = addInt((NI64)(TMP749), 1);
	nimln(13, "MProtagonistBody.nim");
	nimln(13, "MProtagonistBody.nim");
	nimln(13, "MProtagonistBody.nim");
	TMP751 = addInt((*this_793008).X, 1);
	TMP752 = mulInt((NI64)(TMP751), 25);
	TMP753 = subInt((NI64)(TMP752), 1);
	nimln(13, "MProtagonistBody.nim");
	nimln(13, "MProtagonistBody.nim");
	TMP754 = addInt((*this_793008).Y, 1);
	TMP755 = mulInt((NI64)(TMP754), 25);
	glrect_792048((NI64)(TMP748), (NI64)(TMP750), (NI64)(TMP753), (NI64)(TMP755));
	popFrame();
}

N_NIMCALL(void, onkeydown_793023)(tprotagonistHEX3Aobjecttype789013* this_793025, NI keycode) {
	nimfr("onKeyDown", "MProtagonistBody.nim")
	nimln(17, "MProtagonistBody.nim");
	switch (keycode) {
	case 273:
	case 119:
	{
		nimln(19, "MProtagonistBody.nim");
		{
			nimln(19, "MProtagonistBody.nim");
			if (!(0 < (*this_793025).Y)) goto LA4;
			nimln(19, "MProtagonistBody.nim");
			(*this_793025).Y = subInt((*this_793025).Y, 1);
		}
		LA4: ;
	}
	break;
	case 274:
	case 115:
	{
		nimln(21, "MProtagonistBody.nim");
		{
			nimln(21, "MProtagonistBody.nim");
			if (!((*this_793025).Y < 10)) goto LA9;
			nimln(21, "MProtagonistBody.nim");
			(*this_793025).Y = addInt((*this_793025).Y, 1);
		}
		LA9: ;
	}
	break;
	case 276:
	case 97:
	{
		nimln(23, "MProtagonistBody.nim");
		{
			nimln(23, "MProtagonistBody.nim");
			if (!((*this_793025).Y < 10)) goto LA14;
			nimln(23, "MProtagonistBody.nim");
			(*this_793025).Y = addInt((*this_793025).Y, 1);
		}
		LA14: ;
	}
	break;
	case 275:
	case 100:
	{
		nimln(25, "MProtagonistBody.nim");
		{
			nimln(25, "MProtagonistBody.nim");
			if (!((*this_793025).Y < 10)) goto LA19;
			nimln(25, "MProtagonistBody.nim");
			(*this_793025).Y = addInt((*this_793025).Y, 1);
		}
		LA19: ;
	}
	break;
	default:
	{
	}
	break;
	}
	popFrame();
}
N_NOINLINE(void, MProtagonistBodyInit)(void) {
	nimfr("MProtagonistBody", "MProtagonistBody.nim")
	popFrame();
}

N_NOINLINE(void, MProtagonistBodyDatInit)(void) {
}

