/* Generated by Nimrod Compiler v0.9.5 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nimrod -o /home/andreysh/Projects/nimrod/stone_head/nimcache/opengl_opengl.o /home/andreysh/Projects/nimrod/stone_head/nimcache/opengl_opengl.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <GL/glew.h>

#include <string.h>
typedef struct egl121042 egl121042;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct E_Base E_Base;
typedef struct TNimObject TNimObject;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tcell41290 tcell41290;
typedef struct tcellseq41306 tcellseq41306;
typedef struct tgcheap43216 tgcheap43216;
typedef struct tcellset41302 tcellset41302;
typedef struct tpagedesc41298 tpagedesc41298;
typedef struct tmemregion23610 tmemregion23610;
typedef struct tsmallchunk22838 tsmallchunk22838;
typedef struct tllchunk23604 tllchunk23604;
typedef struct tbigchunk22840 tbigchunk22840;
typedef struct tintset22815 tintset22815;
typedef struct ttrunk22811 ttrunk22811;
typedef struct tavlnode23608 tavlnode23608;
typedef struct tgcstat43214 tgcstat43214;
typedef struct TY121287 TY121287;
typedef struct tnimrodnode80606 tnimrodnode80606;
typedef struct tslice79092 tslice79092;
typedef struct tbasechunk22836 tbasechunk22836;
typedef struct tfreecell22828 tfreecell22828;
typedef N_NIMCALL_PTR(void, TY2289) (void* p, NI op);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY2289 marker;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  E_Base  {
  TNimObject Sup;
E_Base* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  egl121042  {
  E_Base Sup;
NI32 Code;
};
struct  tcell41290  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq41306  {
NI Len;
NI Cap;
tcell41290** D;
};
struct  tcellset41302  {
NI Counter;
NI Max;
tpagedesc41298* Head;
tpagedesc41298** Data;
};
typedef tsmallchunk22838* TY23622[512];
typedef ttrunk22811* ttrunkbuckets22813[256];
struct  tintset22815  {
ttrunkbuckets22813 Data;
};
struct  tmemregion23610  {
NI Minlargeobj;
NI Maxlargeobj;
TY23622 Freesmallchunks;
tllchunk23604* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk22840* Freechunkslist;
tintset22815 Chunkstarts;
tavlnode23608* Root;
tavlnode23608* Deleted;
tavlnode23608* Last;
tavlnode23608* Freeavlnodes;
};
struct  tgcstat43214  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap43216  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq41306 Zct;
tcellseq41306 Decstack;
tcellset41302 Cycleroots;
tcellseq41306 Tempstack;
NI Recgclock;
tmemregion23610 Region;
tgcstat43214 Stat;
};
struct  tslice79092  {
NI A;
NI B;
};
typedef NI TY22818[8];
struct  tpagedesc41298  {
tpagedesc41298* Next;
NI Key;
TY22818 Bits;
};
struct  tbasechunk22836  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk22838  {
  tbasechunk22836 Sup;
tsmallchunk22838* Next;
tsmallchunk22838* Prev;
tfreecell22828* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk23604  {
NI Size;
NI Acc;
tllchunk23604* Next;
};
struct  tbigchunk22840  {
  tbasechunk22836 Sup;
tbigchunk22840* Next;
tbigchunk22840* Prev;
NI Align;
NF Data;
};
struct  ttrunk22811  {
ttrunk22811* Next;
NI Key;
TY22818 Bits;
};
typedef tavlnode23608* TY23614[2];
struct  tavlnode23608  {
TY23614 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tnimrodnode80606  {
char dummy;
};
struct  tfreecell22828  {
tfreecell22828* Next;
NI Zerofield;
};
struct TY121287 {
  TGenericSeq Sup;
  tnimrodnode80606* data[SEQ_DECL_SIZE];
};
N_NIMCALL(NI32, getglerror_121036)(void);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(egl121042*, new_121059)(void);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP161)(void* p, NI op);
N_NIMCALL(void, checkglerror_121045)(void);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, reprEnum)(NI e_76080, TNimType* typ);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell41290*, usrtocell_44643)(void* usr);
static N_INLINE(void, rtladdzct_46202)(tcell41290* c);
N_NOINLINE(void, addzct_44618)(tcellseq41306* s, tcell41290* c);
N_NIMCALL(void, raiseException)(E_Base* e, NCSTRING ename);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void, enableautoglerrorcheck_121176)(NIM_BOOL yes);
N_NIMCALL(TY121287*, newseq_121282)(NI len_121286);
N_NIMCALL(TY121287*, HEX5BHEX5D_121350)(TY121287* s_121356, tslice79092 x_121361);
STRING_LITERAL(TMP162, "OpenGL error: ", 14);
STRING_LITERAL(TMP163, "OpenGL error: unknown (", 23);
STRING_LITERAL(TMP164, ")", 1);
extern TFrame* frameptr_13038;
extern TNimType NTI2425; /* E_Base */
TNimType NTI121042; /* E_GL */
TNimType NTI121003; /* TGlError */
TNimType NTI121064; /* ref E_GL */
extern tgcheap43216 gch_43244;
NIM_BOOL gautoglerrorcheck_121173;
NIM_BOOL ginsidebeginend_121174;

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_13038;
	frameptr_13038 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_13038 = (*frameptr_13038).prev;
}

N_NIMCALL(NI32, getglerror_121036)(void) {
	NI32 result;
	NU32 LOC1;
	nimfr("getGlError", "opengl.nim")
	result = 0;
	nimln(274, "opengl.nim");
	nimln(274, "opengl.nim");
	LOC1 = 0;
	LOC1 = glGetError();
	result = ((NI32)chckRange(LOC1, ((NI32) 0), ((NI32) 32817)));
	popFrame();
	return result;
}
N_NIMCALL(void, TMP161)(void* p, NI op) {
	egl121042* a;
	a = (egl121042*)p;
	nimGCvisit((void*)(*a).Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.message, op);
	nimGCvisit((void*)(*a).Sup.trace, op);
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) (&(*dest).data[((*dest).Sup.len)- 0])), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(tcell41290*, usrtocell_44643)(void* usr) {
	tcell41290* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell41290*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell41290))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_46202)(tcell41290* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_44618(&gch_43244.Zct, c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell41290* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_44643(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell41290* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_44643((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_46202(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, checkglerror_121045)(void) {
	NI32 error;
	egl121042* exc;
	NI32 e_121138;
	NI32 v_121165;
	NI32 res_121167;
	NimStringDesc* LOC11;
	nimfr("checkGlError", "opengl.nim")
	nimln(287, "opengl.nim");
	error = getglerror_121036();
	nimln(288, "opengl.nim");
	{
		nimln(288, "opengl.nim");
		if (!(error == ((NI32) 0))) goto LA3;
		nimln(289, "opengl.nim");
		goto BeforeRet;
	}
	LA3: ;
	nimln(292, "opengl.nim");
	exc = new_121059();
	e_121138 = 0;
	v_121165 = 0;
	nimln(1458, "system.nim");
	res_121167 = ((NI32) 0);
	nimln(1459, "system.nim");
	while (1) {
		nimln(1459, "system.nim");
		if (!(res_121167 <= ((NI32) 32817))) goto LA5;
		nimln(1458, "system.nim");
		v_121165 = res_121167;
		nimln(1565, "system.nim");
		e_121138 = v_121165;
		nimln(294, "opengl.nim");
		{
			NimStringDesc* LOC10;
			nimln(294, "opengl.nim");
			if (!(e_121138 == error)) goto LA8;
			nimln(295, "opengl.nim");
			nimln(295, "opengl.nim");
			LOC10 = 0;
			nimln(295, "opengl.nim");
			LOC10 = rawNewString(reprEnum(e_121138, (&NTI121003))->Sup.len + 14);
appendString(LOC10, ((NimStringDesc*) &TMP162));
appendString(LOC10, reprEnum(e_121138, (&NTI121003)));
			asgnRefNoCycle((void**) &(*exc).Sup.message, LOC10);
			nimln(296, "opengl.nim");
			raiseException((E_Base*)exc, "E_GL");
		}
		LA8: ;
		nimln(1461, "system.nim");
		res_121167 = addInt(res_121167, 1);
	} LA5: ;
	nimln(298, "opengl.nim");
	(*exc).Code = error;
	nimln(299, "opengl.nim");
	nimln(299, "opengl.nim");
	LOC11 = 0;
	nimln(299, "opengl.nim");
	LOC11 = rawNewString(reprEnum(error, (&NTI121003))->Sup.len + 24);
appendString(LOC11, ((NimStringDesc*) &TMP163));
appendString(LOC11, reprEnum(error, (&NTI121003)));
appendString(LOC11, ((NimStringDesc*) &TMP164));
	asgnRefNoCycle((void**) &(*exc).Sup.message, LOC11);
	nimln(300, "opengl.nim");
	raiseException((E_Base*)exc, "E_GL");
	BeforeRet: ;
	popFrame();
}

N_NIMCALL(void, enableautoglerrorcheck_121176)(NIM_BOOL yes) {
	nimfr("enableAutoGlErrorCheck", "opengl.nim")
	nimln(317, "opengl.nim");
	gautoglerrorcheck_121173 = yes;
	popFrame();
}

N_STDCALL(void, glclearcolor_308202)(NF32 red, NF32 green, NF32 blue, NF32 alpha) {
	nimfr("glClearColor", "opengl.nim")
	nimln(322, "macros.nim");
	glClearColor(red, green, blue, alpha);
	nimln(354, "opengl.nim");
	{
		NIM_BOOL LOC3;
		nimln(354, "opengl.nim");
		LOC3 = 0;
		LOC3 = gautoglerrorcheck_121173;
		if (!(LOC3)) goto LA4;
		nimln(354, "opengl.nim");
		LOC3 = !(ginsidebeginend_121174);
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(355, "opengl.nim");
		checkglerror_121045();
	}
	LA5: ;
	popFrame();
}

N_STDCALL(void, glcolor4f_307802)(NF32 red, NF32 green, NF32 blue, NF32 alpha) {
	nimfr("glColor4f", "opengl.nim")
	nimln(322, "macros.nim");
	glColor4f(red, green, blue, alpha);
	nimln(354, "opengl.nim");
	{
		NIM_BOOL LOC3;
		nimln(354, "opengl.nim");
		LOC3 = 0;
		LOC3 = gautoglerrorcheck_121173;
		if (!(LOC3)) goto LA4;
		nimln(354, "opengl.nim");
		LOC3 = !(ginsidebeginend_121174);
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(355, "opengl.nim");
		checkglerror_121045();
	}
	LA5: ;
	popFrame();
}

N_STDCALL(void, glcleardepth_310802)(NF depth) {
	nimfr("glClearDepth", "opengl.nim")
	nimln(322, "macros.nim");
	glClearDepth(depth);
	nimln(354, "opengl.nim");
	{
		NIM_BOOL LOC3;
		nimln(354, "opengl.nim");
		LOC3 = 0;
		LOC3 = gautoglerrorcheck_121173;
		if (!(LOC3)) goto LA4;
		nimln(354, "opengl.nim");
		LOC3 = !(ginsidebeginend_121174);
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(355, "opengl.nim");
		checkglerror_121045();
	}
	LA5: ;
	popFrame();
}

N_STDCALL(void, glviewport_645202)(NI32 x, NI32 y, NI32 width, NI32 height) {
	nimfr("glViewport", "opengl.nim")
	nimln(322, "macros.nim");
	glViewport(x, y, width, height);
	nimln(354, "opengl.nim");
	{
		NIM_BOOL LOC3;
		nimln(354, "opengl.nim");
		LOC3 = 0;
		LOC3 = gautoglerrorcheck_121173;
		if (!(LOC3)) goto LA4;
		nimln(354, "opengl.nim");
		LOC3 = !(ginsidebeginend_121174);
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(355, "opengl.nim");
		checkglerror_121045();
	}
	LA5: ;
	popFrame();
}

N_STDCALL(void, glmatrixmode_229002)(NU32 mode) {
	nimfr("glMatrixMode", "opengl.nim")
	nimln(322, "macros.nim");
	glMatrixMode(mode);
	nimln(354, "opengl.nim");
	{
		NIM_BOOL LOC3;
		nimln(354, "opengl.nim");
		LOC3 = 0;
		LOC3 = gautoglerrorcheck_121173;
		if (!(LOC3)) goto LA4;
		nimln(354, "opengl.nim");
		LOC3 = !(ginsidebeginend_121174);
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(355, "opengl.nim");
		checkglerror_121045();
	}
	LA5: ;
	popFrame();
}

N_STDCALL(void, glloadidentity_516802)(void) {
	nimfr("glLoadIdentity", "opengl.nim")
	nimln(322, "macros.nim");
	glLoadIdentity();
	nimln(354, "opengl.nim");
	{
		NIM_BOOL LOC3;
		nimln(354, "opengl.nim");
		LOC3 = 0;
		LOC3 = gautoglerrorcheck_121173;
		if (!(LOC3)) goto LA4;
		nimln(354, "opengl.nim");
		LOC3 = !(ginsidebeginend_121174);
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(355, "opengl.nim");
		checkglerror_121045();
	}
	LA5: ;
	popFrame();
}

N_STDCALL(void, glortho_433002)(NF left, NF right, NF bottom, NF top, NF znear, NF zfar) {
	nimfr("glOrtho", "opengl.nim")
	nimln(322, "macros.nim");
	glOrtho(left, right, bottom, top, znear, zfar);
	nimln(354, "opengl.nim");
	{
		NIM_BOOL LOC3;
		nimln(354, "opengl.nim");
		LOC3 = 0;
		LOC3 = gautoglerrorcheck_121173;
		if (!(LOC3)) goto LA4;
		nimln(354, "opengl.nim");
		LOC3 = !(ginsidebeginend_121174);
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(355, "opengl.nim");
		checkglerror_121045();
	}
	LA5: ;
	popFrame();
}

N_STDCALL(void, glenable_527802)(NU32 cap) {
	nimfr("glEnable", "opengl.nim")
	nimln(322, "macros.nim");
	glEnable(cap);
	nimln(354, "opengl.nim");
	{
		NIM_BOOL LOC3;
		nimln(354, "opengl.nim");
		LOC3 = 0;
		LOC3 = gautoglerrorcheck_121173;
		if (!(LOC3)) goto LA4;
		nimln(354, "opengl.nim");
		LOC3 = !(ginsidebeginend_121174);
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(355, "opengl.nim");
		checkglerror_121045();
	}
	LA5: ;
	popFrame();
}

N_STDCALL(void, glbegin_494602)(NU32 mode) {
	nimfr("glBegin", "opengl.nim")
	nimln(322, "macros.nim");
	glBegin(mode);
	nimln(472, "macros.nim");
	ginsidebeginend_121174 = NIM_TRUE;
	nimln(354, "opengl.nim");
	{
		NIM_BOOL LOC3;
		nimln(354, "opengl.nim");
		LOC3 = 0;
		LOC3 = gautoglerrorcheck_121173;
		if (!(LOC3)) goto LA4;
		nimln(354, "opengl.nim");
		LOC3 = !(ginsidebeginend_121174);
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(355, "opengl.nim");
		checkglerror_121045();
	}
	LA5: ;
	popFrame();
}

N_STDCALL(void, glvertex4i_613802)(NI32 x, NI32 y, NI32 z, NI32 w) {
	nimfr("glVertex4i", "opengl.nim")
	nimln(322, "macros.nim");
	glVertex4i(x, y, z, w);
	nimln(354, "opengl.nim");
	{
		NIM_BOOL LOC3;
		nimln(354, "opengl.nim");
		LOC3 = 0;
		LOC3 = gautoglerrorcheck_121173;
		if (!(LOC3)) goto LA4;
		nimln(354, "opengl.nim");
		LOC3 = !(ginsidebeginend_121174);
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(355, "opengl.nim");
		checkglerror_121045();
	}
	LA5: ;
	popFrame();
}

N_STDCALL(void, glvertex4f_168402)(NF32 x, NF32 y, NF32 z, NF32 w) {
	nimfr("glVertex4f", "opengl.nim")
	nimln(322, "macros.nim");
	glVertex4f(x, y, z, w);
	nimln(354, "opengl.nim");
	{
		NIM_BOOL LOC3;
		nimln(354, "opengl.nim");
		LOC3 = 0;
		LOC3 = gautoglerrorcheck_121173;
		if (!(LOC3)) goto LA4;
		nimln(354, "opengl.nim");
		LOC3 = !(ginsidebeginend_121174);
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(355, "opengl.nim");
		checkglerror_121045();
	}
	LA5: ;
	popFrame();
}

N_STDCALL(void, glend_187002)(void) {
	nimfr("glEnd", "opengl.nim")
	nimln(322, "macros.nim");
	glEnd();
	nimln(472, "macros.nim");
	ginsidebeginend_121174 = NIM_FALSE;
	nimln(354, "opengl.nim");
	{
		NIM_BOOL LOC3;
		nimln(354, "opengl.nim");
		LOC3 = 0;
		LOC3 = gautoglerrorcheck_121173;
		if (!(LOC3)) goto LA4;
		nimln(354, "opengl.nim");
		LOC3 = !(ginsidebeginend_121174);
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(355, "opengl.nim");
		checkglerror_121045();
	}
	LA5: ;
	popFrame();
}
N_NOINLINE(void, openglopenglInit)(void) {
	nimfr("opengl", "opengl.nim")
	nimln(310, "opengl.nim");
	gautoglerrorcheck_121173 = NIM_TRUE;
	nimln(311, "opengl.nim");
	ginsidebeginend_121174 = NIM_FALSE;
	popFrame();
}

N_NOINLINE(void, openglopenglDatInit)(void) {
static TNimNode* TMP158[9];
NI TMP160;
static char* NIM_CONST TMP159[9] = {
"no error", 
"invalid enum", 
"invalid value", 
"invalid operation", 
"stack overflow", 
"stack underflow", 
"out of memory", 
"invalid framebuffer operation", 
"table too large"};
static TNimNode TMP128[11];
NTI121042.size = sizeof(egl121042);
NTI121042.kind = 17;
NTI121042.base = (&NTI2425);
NTI121003.size = sizeof(NI32);
NTI121003.kind = 14;
NTI121003.base = 0;
NTI121003.flags = 3;
for (TMP160 = 0; TMP160 < 9; TMP160++) {
TMP128[TMP160+1].kind = 1;
TMP128[TMP160+1].offset = TMP160;
TMP128[TMP160+1].name = TMP159[TMP160];
TMP158[TMP160] = &TMP128[TMP160+1];
}
TMP128[1].offset = 0;
TMP128[2].offset = 1280;
TMP128[3].offset = 1281;
TMP128[4].offset = 1282;
TMP128[5].offset = 1283;
TMP128[6].offset = 1284;
TMP128[7].offset = 1285;
TMP128[8].offset = 1286;
TMP128[9].offset = 32817;
TMP128[10].len = 9; TMP128[10].kind = 2; TMP128[10].sons = &TMP158[0];
NTI121003.node = &TMP128[10];
NTI121003.flags = 1<<2;
TMP128[0].kind = 1;
TMP128[0].offset = offsetof(egl121042, Code);
TMP128[0].typ = (&NTI121003);
TMP128[0].name = "code";
NTI121042.node = &TMP128[0];
NTI121064.size = sizeof(egl121042*);
NTI121064.kind = 22;
NTI121064.base = (&NTI121042);
NTI121064.marker = TMP161;
}

