/* Generated by Nimrod Compiler v0.9.5 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nimrod -o /home/andreysh/Projects/nimrod/stone_head/nimcache/os.o /home/andreysh/Projects/nimrod/stone_head/nimcache/os.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <stdlib.h>

#include <string.h>

#include <unistd.h>

#include <sys/stat.h>

#include <sys/types.h>

#include <sys/time.h>
typedef struct TY10665 TY10665;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY772700 TY772700;
typedef struct einvalidindex2459 einvalidindex2459;
typedef struct esynch2429 esynch2429;
typedef struct E_Base E_Base;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tcell41290 tcell41290;
typedef struct tcellseq41306 tcellseq41306;
typedef struct tgcheap43216 tgcheap43216;
typedef struct tcellset41302 tcellset41302;
typedef struct tpagedesc41298 tpagedesc41298;
typedef struct tmemregion23610 tmemregion23610;
typedef struct tsmallchunk22838 tsmallchunk22838;
typedef struct tllchunk23604 tllchunk23604;
typedef struct tbigchunk22840 tbigchunk22840;
typedef struct tintset22815 tintset22815;
typedef struct ttrunk22811 ttrunk22811;
typedef struct tavlnode23608 tavlnode23608;
typedef struct tgcstat43214 tgcstat43214;
typedef struct tbasechunk22836 tbasechunk22836;
typedef struct tfreecell22828 tfreecell22828;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct TY772700 {
NimStringDesc* Field0;
NimStringDesc* Field1;
NimStringDesc* Field2;
};
typedef N_NIMCALL_PTR(void, TY2289) (void* p, NI op);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY2289 marker;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  E_Base  {
  TNimObject Sup;
E_Base* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  esynch2429  {
  E_Base Sup;
};
struct  einvalidindex2459  {
  esynch2429 Sup;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  tcell41290  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq41306  {
NI Len;
NI Cap;
tcell41290** D;
};
struct  tcellset41302  {
NI Counter;
NI Max;
tpagedesc41298* Head;
tpagedesc41298** Data;
};
typedef tsmallchunk22838* TY23622[512];
typedef ttrunk22811* ttrunkbuckets22813[256];
struct  tintset22815  {
ttrunkbuckets22813 Data;
};
struct  tmemregion23610  {
NI Minlargeobj;
NI Maxlargeobj;
TY23622 Freesmallchunks;
tllchunk23604* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk22840* Freechunkslist;
tintset22815 Chunkstarts;
tavlnode23608* Root;
tavlnode23608* Deleted;
tavlnode23608* Last;
tavlnode23608* Freeavlnodes;
};
struct  tgcstat43214  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap43216  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq41306 Zct;
tcellseq41306 Decstack;
tcellset41302 Cycleroots;
tcellseq41306 Tempstack;
NI Recgclock;
tmemregion23610 Region;
tgcstat43214 Stat;
};
typedef NI TY22818[8];
struct  tpagedesc41298  {
tpagedesc41298* Next;
NI Key;
TY22818 Bits;
};
struct  tbasechunk22836  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk22838  {
  tbasechunk22836 Sup;
tsmallchunk22838* Next;
tsmallchunk22838* Prev;
tfreecell22828* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk23604  {
NI Size;
NI Acc;
tllchunk23604* Next;
};
struct  tbigchunk22840  {
  tbasechunk22836 Sup;
tbigchunk22840* Next;
tbigchunk22840* Prev;
NI Align;
NF Data;
};
struct  ttrunk22811  {
ttrunk22811* Next;
NI Key;
TY22818 Bits;
};
typedef tavlnode23608* TY23614[2];
struct  tavlnode23608  {
TY23614 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell22828  {
tfreecell22828* Next;
NI Zerofield;
};
struct TY10665 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
static N_INLINE(NimStringDesc*, pop_776300)(TY10665** s_776308);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemsize, NI newlen);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NimStringDesc*, nosjoinPath)(NimStringDesc* head, NimStringDesc* tail);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI start);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI first);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(void, nossplitFile)(NimStringDesc* path, TY772700* Result);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_70824, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(NimStringDesc*, nosgetAppFilename)(void);
N_NIMCALL(NimStringDesc*, getapplaux_778602)(NimStringDesc* procpath);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newlen);
N_NIMCALL(NimStringDesc*, getapplheuristic_778802)(void);
N_NIMCALL(NimStringDesc*, paramstr_778205)(NI i);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tcell41290*, usrtocell_44643)(void* usr);
static N_INLINE(void, rtladdzct_46202)(tcell41290* c);
N_NOINLINE(void, addzct_44618)(tcellseq41306* s, tcell41290* c);
N_NIMCALL(void, raiseException)(E_Base* e, NCSTRING ename);
N_NIMCALL(NimStringDesc*, getenv_775426)(NimStringDesc* key);
N_NIMCALL(NI, findenvvar_775403)(NimStringDesc* key);
N_NIMCALL(void, getenvvarsc_775002)(void);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_NIMCALL(TGenericSeq*, incrSeq)(TGenericSeq* seq, NI elemsize);
N_NIMCALL(NIM_BOOL, nsuStartsWith)(NimStringDesc* s, NimStringDesc* prefix);
N_NIMCALL(NI, nsuFindChar)(NimStringDesc* s, NIM_CHAR sub, NI start);
N_NIMCALL(void, failedassertimpl_79821)(NimStringDesc* msg);
N_NIMCALL(NIM_BOOL, nosexistsFile)(NimStringDesc* filename);
STRING_LITERAL(TMP658, "", 0);
STRING_LITERAL(TMP665, "/proc/self/exe", 14);
STRING_LITERAL(TMP666, "invalid index", 13);
STRING_LITERAL(TMP669, "PATH", 4);
STRING_LITERAL(TMP670, "not (\'\\0\' in seps) ", 19);
NIM_BOOL envcomputed_774804;
TY10665* environment_774806;
extern NCSTRING* environ;
extern TFrame* frameptr_13038;
extern int cmdCount;
extern NCSTRING* cmdLine;
extern TNimType NTI17201; /* ref EInvalidIndex */
extern TNimType NTI2459; /* EInvalidIndex */
extern tgcheap43216 gch_43244;
extern TNimType NTI10665; /* seq[string] */

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_13038;
	frameptr_13038 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_13038 = (*frameptr_13038).prev;
}

static N_INLINE(NimStringDesc*, pop_776300)(TY10665** s_776308) {
	NimStringDesc* result;
	NI l;
	NI TMP647;
	nimfr("pop", "system.nim")
	result = 0;
	nimln(1692, "system.nim");
	nimln(1692, "system.nim");
	nimln(1692, "system.nim");
	TMP647 = subInt((*s_776308)->Sup.len, 1);
	l = (NI64)(TMP647);
	nimln(1693, "system.nim");
	if ((NU)(l) >= (NU)((*s_776308)->Sup.len)) raiseIndexError();
	result = copyString((*s_776308)->data[l]);
	nimln(1694, "system.nim");
	(*s_776308) = (TY10665*) setLengthSeq(&((*s_776308))->Sup, sizeof(NimStringDesc*), l);
	popFrame();
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) (&(*dest).data[((*dest).Sup.len)- 0])), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI64)((*dest).Sup.len + 1))- 0] = 0;
	(*dest).Sup.len += 1;
}

N_NIMCALL(NimStringDesc*, nosjoinPath)(NimStringDesc* head, NimStringDesc* tail) {
	NimStringDesc* result;
	nimfr("joinPath", "os.nim")
	result = 0;
	nimln(527, "os.nim");
	{
		nimln(527, "os.nim");
		nimln(527, "os.nim");
		if (!(head->Sup.len == 0)) goto LA3;
		nimln(528, "os.nim");
		result = copyString(tail);
	}
	goto LA1;
	LA3: ;
	{
		NI TMP656;
		nimln(529, "os.nim");
		nimln(529, "os.nim");
		nimln(529, "os.nim");
		TMP656 = subInt(head->Sup.len, 1);
		if ((NU)((NI64)(TMP656)) > (NU)(head->Sup.len)) raiseIndexError();
		if (!(((NU8)(head->data[(NI64)(TMP656)])) == ((NU8)(47)) || ((NU8)(head->data[(NI64)(TMP656)])) == ((NU8)(47)))) goto LA6;
		nimln(530, "os.nim");
		{
			NimStringDesc* LOC12;
			NimStringDesc* LOC13;
			nimln(530, "os.nim");
			if ((NU)(0) > (NU)(tail->Sup.len)) raiseIndexError();
			if (!(((NU8)(tail->data[0])) == ((NU8)(47)) || ((NU8)(tail->data[0])) == ((NU8)(47)))) goto LA10;
			nimln(531, "os.nim");
			nimln(531, "os.nim");
			LOC12 = 0;
			nimln(531, "os.nim");
			LOC13 = 0;
			LOC13 = copyStr(tail, 1);
			LOC12 = rawNewString(head->Sup.len + LOC13->Sup.len + 0);
appendString(LOC12, head);
appendString(LOC12, LOC13);
			result = LOC12;
		}
		goto LA8;
		LA10: ;
		{
			NimStringDesc* LOC15;
			nimln(533, "os.nim");
			nimln(533, "os.nim");
			LOC15 = 0;
			LOC15 = rawNewString(head->Sup.len + tail->Sup.len + 0);
appendString(LOC15, head);
appendString(LOC15, tail);
			result = LOC15;
		}
		LA8: ;
	}
	goto LA1;
	LA6: ;
	{
		nimln(535, "os.nim");
		{
			NimStringDesc* LOC21;
			nimln(535, "os.nim");
			if ((NU)(0) > (NU)(tail->Sup.len)) raiseIndexError();
			if (!(((NU8)(tail->data[0])) == ((NU8)(47)) || ((NU8)(tail->data[0])) == ((NU8)(47)))) goto LA19;
			nimln(536, "os.nim");
			nimln(536, "os.nim");
			LOC21 = 0;
			LOC21 = rawNewString(head->Sup.len + tail->Sup.len + 0);
appendString(LOC21, head);
appendString(LOC21, tail);
			result = LOC21;
		}
		goto LA17;
		LA19: ;
		{
			NimStringDesc* LOC23;
			nimln(538, "os.nim");
			nimln(538, "os.nim");
			LOC23 = 0;
			LOC23 = rawNewString(head->Sup.len + tail->Sup.len + 1);
appendString(LOC23, head);
appendChar(LOC23, 47);
appendString(LOC23, tail);
			result = LOC23;
		}
		LA17: ;
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, HEX2F_772477)(NimStringDesc* head, NimStringDesc* tail) {
	NimStringDesc* result;
	nimfr("/", "os.nim")
	result = 0;
	nimln(559, "os.nim");
	nimln(559, "os.nim");
	result = nosjoinPath(head, tail);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, nossplitFile)(NimStringDesc* path, TY772700* Result) {
	nimfr("splitFile", "os.nim")
	nimln(677, "os.nim");
	{
		NIM_BOOL LOC3;
		NI TMP657;
		nimln(677, "os.nim");
		LOC3 = 0;
		nimln(677, "os.nim");
		nimln(677, "os.nim");
		LOC3 = (path->Sup.len == 0);
		if (LOC3) goto LA4;
		nimln(677, "os.nim");
		nimln(677, "os.nim");
		nimln(677, "os.nim");
		TMP657 = subInt(path->Sup.len, 1);
		if ((NU)((NI64)(TMP657)) > (NU)(path->Sup.len)) raiseIndexError();
		LOC3 = (((NU8)(path->data[(NI64)(TMP657)])) == ((NU8)(47)) || ((NU8)(path->data[(NI64)(TMP657)])) == ((NU8)(47)));
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(678, "os.nim");
		unsureAsgnRef((void**) &(*Result).Field0, copyString(path));
		unsureAsgnRef((void**) &(*Result).Field1, copyString(((NimStringDesc*) &TMP658)));
		unsureAsgnRef((void**) &(*Result).Field2, copyString(((NimStringDesc*) &TMP658)));
	}
	goto LA1;
	LA5: ;
	{
		NI seppos;
		NI dotpos;
		NI i_772733;
		NI HEX3Atmp_772763;
		NI TMP659;
		NI res_772765;
		NI TMP661;
		NI TMP662;
		NI TMP663;
		nimln(680, "os.nim");
		seppos = -1;
		nimln(681, "os.nim");
		nimln(681, "os.nim");
		dotpos = path->Sup.len;
		i_772733 = 0;
		HEX3Atmp_772763 = 0;
		nimln(682, "os.nim");
		nimln(682, "os.nim");
		nimln(682, "os.nim");
		TMP659 = subInt(path->Sup.len, 1);
		HEX3Atmp_772763 = (NI64)(TMP659);
		nimln(1442, "system.nim");
		res_772765 = HEX3Atmp_772763;
		nimln(1443, "system.nim");
		while (1) {
			nimln(1443, "system.nim");
			if (!(0 <= res_772765)) goto LA8;
			nimln(1442, "system.nim");
			i_772733 = res_772765;
			nimln(683, "os.nim");
			{
				nimln(683, "os.nim");
				if ((NU)(i_772733) > (NU)(path->Sup.len)) raiseIndexError();
				if (!((NU8)(path->data[i_772733]) == (NU8)(46))) goto LA11;
				nimln(684, "os.nim");
				{
					NIM_BOOL LOC15;
					NIM_BOOL LOC16;
					NI TMP660;
					nimln(684, "os.nim");
					LOC15 = 0;
					nimln(684, "os.nim");
					LOC16 = 0;
					nimln(684, "os.nim");
					nimln(684, "os.nim");
					LOC16 = (dotpos == path->Sup.len);
					if (!(LOC16)) goto LA17;
					nimln(684, "os.nim");
					LOC16 = (0 < i_772733);
					LA17: ;
					LOC15 = LOC16;
					if (!(LOC15)) goto LA18;
					nimln(685, "os.nim");
					nimln(685, "os.nim");
					nimln(685, "os.nim");
					TMP660 = subInt(i_772733, 1);
					if ((NU)((NI64)(TMP660)) > (NU)(path->Sup.len)) raiseIndexError();
					LOC15 = !((((NU8)(path->data[(NI64)(TMP660)])) == ((NU8)(47)) || ((NU8)(path->data[(NI64)(TMP660)])) == ((NU8)(47))));
					LA18: ;
					if (!LOC15) goto LA19;
					nimln(685, "os.nim");
					dotpos = i_772733;
				}
				LA19: ;
			}
			goto LA9;
			LA11: ;
			{
				nimln(686, "os.nim");
				if ((NU)(i_772733) > (NU)(path->Sup.len)) raiseIndexError();
				if (!(((NU8)(path->data[i_772733])) == ((NU8)(47)) || ((NU8)(path->data[i_772733])) == ((NU8)(47)))) goto LA22;
				nimln(687, "os.nim");
				seppos = i_772733;
				nimln(688, "os.nim");
				goto LA8;
			}
			goto LA9;
			LA22: ;
			LA9: ;
			nimln(1445, "system.nim");
			res_772765 = subInt(res_772765, 1);
		} LA8: ;
		nimln(689, "os.nim");
		nimln(689, "os.nim");
		nimln(689, "os.nim");
		TMP661 = subInt(seppos, 1);
		unsureAsgnRef((void**) &(*Result).Field0, copyStrLast(path, 0, (NI64)(TMP661)));
		nimln(690, "os.nim");
		nimln(690, "os.nim");
		nimln(690, "os.nim");
		TMP662 = addInt(seppos, 1);
		nimln(690, "os.nim");
		TMP663 = subInt(dotpos, 1);
		unsureAsgnRef((void**) &(*Result).Field1, copyStrLast(path, (NI64)(TMP662), (NI64)(TMP663)));
		nimln(691, "os.nim");
		nimln(691, "os.nim");
		unsureAsgnRef((void**) &(*Result).Field2, copyStr(path, dotpos));
	}
	LA1: ;
	popFrame();
}

N_NIMCALL(NimStringDesc*, getapplaux_778602)(NimStringDesc* procpath) {
	NimStringDesc* result;
	NI len;
	nimfr("getApplAux", "os.nim")
	result = 0;
	nimln(1608, "os.nim");
	nimln(1608, "os.nim");
	result = mnewString(256);
	nimln(1609, "os.nim");
	len = readlink(procpath->data, result->data, 256);
	nimln(1610, "os.nim");
	{
		NI TMP664;
		nimln(1610, "os.nim");
		if (!(256 < len)) goto LA3;
		nimln(1611, "os.nim");
		nimln(1611, "os.nim");
		nimln(1611, "os.nim");
		TMP664 = addInt(len, 1);
		result = mnewString((NI64)(TMP664));
		nimln(1612, "os.nim");
		len = readlink(procpath->data, result->data, len);
	}
	LA3: ;
	nimln(1613, "os.nim");
	result = setLengthStr(result, len);
	popFrame();
	return result;
}

static N_INLINE(tcell41290*, usrtocell_44643)(void* usr) {
	tcell41290* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell41290*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell41290))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_46202)(tcell41290* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_44618(&gch_43244.Zct, c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell41290* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_44643(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_46202(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(NimStringDesc*, paramstr_778205)(NI i) {
	NimStringDesc* result;
	einvalidindex2459* e_778212;
	NimStringDesc* LOC7;
	nimfr("paramStr", "os.nim")
	result = 0;
	nimln(1595, "os.nim");
	{
		NIM_BOOL LOC3;
		nimln(1595, "os.nim");
		LOC3 = 0;
		nimln(1595, "os.nim");
		LOC3 = (i < ((NI) (cmdCount)));
		if (!(LOC3)) goto LA4;
		nimln(1595, "os.nim");
		LOC3 = (0 <= i);
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(1595, "os.nim");
		nimln(1595, "os.nim");
		nimln(1595, "os.nim");
		if ((NU)(i) > (NU)(50000)) raiseIndexError();
		result = cstrToNimstr(cmdLine[(i)- 0]);
		goto BeforeRet;
	}
	LA5: ;
	e_778212 = 0;
	nimln(1992, "system.nim");
	e_778212 = (einvalidindex2459*) newObj((&NTI17201), sizeof(einvalidindex2459));
	(*e_778212).Sup.Sup.Sup.m_type = (&NTI2459);
	nimln(1993, "system.nim");
	LOC7 = 0;
	LOC7 = (*e_778212).Sup.Sup.message; (*e_778212).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP666));
	if (LOC7) nimGCunrefNoCycle(LOC7);
	nimln(1596, "os.nim");
	raiseException((E_Base*)e_778212, "EInvalidIndex");
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, getenvvarsc_775002)(void) {
	nimfr("getEnvVarsC", "os.nim")
	nimln(1113, "os.nim");
	{
		NI i;
		nimln(1113, "os.nim");
		if (!!(envcomputed_774804)) goto LA3;
		nimln(1114, "os.nim");
		if (environment_774806) nimGCunrefNoCycle(environment_774806);
		environment_774806 = (TY10665*) newSeqRC1((&NTI10665), 0);
		nimln(1117, "os.nim");
		i = 0;
		nimln(1118, "os.nim");
		while (1) {
			NimStringDesc* LOC10;
			NimStringDesc* LOC11;
			nimln(1119, "os.nim");
			{
				nimln(1119, "os.nim");
				if ((NU)(i) > (NU)(50000)) raiseIndexError();
				if (!(environ[(i)- 0] == NIM_NIL)) goto LA8;
				nimln(1119, "os.nim");
				goto LA5;
			}
			LA8: ;
			nimln(1120, "os.nim");
			nimln(1120, "os.nim");
			if ((NU)(i) > (NU)(50000)) raiseIndexError();
			LOC10 = 0;
			LOC10 = cstrToNimstr(environ[(i)- 0]);
			environment_774806 = (TY10665*) incrSeq(&(environment_774806)->Sup, sizeof(NimStringDesc*));
			LOC11 = 0;
			LOC11 = environment_774806->data[environment_774806->Sup.len-1]; environment_774806->data[environment_774806->Sup.len-1] = copyStringRC1(LOC10);
			if (LOC11) nimGCunrefNoCycle(LOC11);
			nimln(1121, "os.nim");
			i = addInt(i, 1);
		} LA5: ;
		nimln(1122, "os.nim");
		envcomputed_774804 = NIM_TRUE;
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(NI, findenvvar_775403)(NimStringDesc* key) {
	NI result;
	NimStringDesc* temp;
	NimStringDesc* LOC1;
	NI i_775418;
	NI HEX3Atmp_775419;
	NI res_775421;
	nimfr("findEnvVar", "os.nim")
	result = 0;
	nimln(1125, "os.nim");
	getenvvarsc_775002();
	nimln(1126, "os.nim");
	nimln(1126, "os.nim");
	LOC1 = 0;
	LOC1 = rawNewString(key->Sup.len + 1);
appendString(LOC1, key);
appendChar(LOC1, 61);
	temp = LOC1;
	i_775418 = 0;
	HEX3Atmp_775419 = 0;
	nimln(1127, "os.nim");
	nimln(1127, "os.nim");
	HEX3Atmp_775419 = (environment_774806->Sup.len-1);
	nimln(1458, "system.nim");
	res_775421 = 0;
	nimln(1459, "system.nim");
	while (1) {
		nimln(1459, "system.nim");
		if (!(res_775421 <= HEX3Atmp_775419)) goto LA2;
		nimln(1458, "system.nim");
		i_775418 = res_775421;
		nimln(1128, "os.nim");
		{
			NIM_BOOL LOC5;
			nimln(1128, "os.nim");
			if ((NU)(i_775418) >= (NU)(environment_774806->Sup.len)) raiseIndexError();
			LOC5 = 0;
			LOC5 = nsuStartsWith(environment_774806->data[i_775418], temp);
			if (!LOC5) goto LA6;
			nimln(1128, "os.nim");
			nimln(1128, "os.nim");
			result = i_775418;
			goto BeforeRet;
		}
		LA6: ;
		nimln(1461, "system.nim");
		res_775421 = addInt(res_775421, 1);
	} LA2: ;
	nimln(1129, "os.nim");
	nimln(1129, "os.nim");
	result = -1;
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, getenv_775426)(NimStringDesc* key) {
	NimStringDesc* result;
	NI i;
	nimfr("getEnv", "os.nim")
	result = 0;
	nimln(1137, "os.nim");
	i = findenvvar_775403(key);
	nimln(1138, "os.nim");
	{
		NI LOC5;
		NI TMP668;
		nimln(1138, "os.nim");
		if (!(0 <= i)) goto LA3;
		nimln(1139, "os.nim");
		nimln(1139, "os.nim");
		nimln(1139, "os.nim");
		if ((NU)(i) >= (NU)(environment_774806->Sup.len)) raiseIndexError();
		nimln(1139, "os.nim");
		nimln(1139, "os.nim");
		if ((NU)(i) >= (NU)(environment_774806->Sup.len)) raiseIndexError();
		LOC5 = 0;
		LOC5 = nsuFindChar(environment_774806->data[i], 61, 0);
		TMP668 = addInt(LOC5, 1);
		result = copyStr(environment_774806->data[i], (NI64)(TMP668));
		goto BeforeRet;
	}
	goto LA1;
	LA3: ;
	{
		NCSTRING env;
		nimln(1141, "os.nim");
		env = getenv(key->data);
		nimln(1142, "os.nim");
		{
			nimln(1142, "os.nim");
			if (!(env == NIM_NIL)) goto LA9;
			nimln(1142, "os.nim");
			nimln(1142, "os.nim");
			result = copyString(((NimStringDesc*) &TMP658));
			goto BeforeRet;
		}
		LA9: ;
		nimln(1143, "os.nim");
		nimln(1143, "os.nim");
		result = cstrToNimstr(env);
	}
	LA1: ;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, nosexistsFile)(NimStringDesc* filename) {
	NIM_BOOL result;
	struct stat res;
	NIM_BOOL LOC1;
	int LOC2;
	nimfr("existsFile", "os.nim")
	result = 0;
	memset((void*)&res, 0, sizeof(res));
	nimln(384, "os.nim");
	nimln(384, "os.nim");
	nimln(384, "os.nim");
	LOC1 = 0;
	nimln(384, "os.nim");
	nimln(384, "os.nim");
	LOC2 = 0;
	LOC2 = stat(filename->data, &res);
	LOC1 = (((NI32) 0) <= LOC2);
	if (!(LOC1)) goto LA3;
	nimln(384, "os.nim");
	LOC1 = S_ISREG(res.st_mode);
	LA3: ;
	result = LOC1;
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, getapplheuristic_778802)(void) {
	NimStringDesc* result;
	nimfr("getApplHeuristic", "os.nim")
	result = 0;
	nimln(1618, "os.nim");
	nimln(1618, "os.nim");
	result = paramstr_778205(0);
	nimln(1621, "os.nim");
	{
		NIM_BOOL LOC3;
		NimStringDesc* p_779003;
		NimStringDesc* HEX3Atmp_779009;
		NI last_779011;
		nimln(1621, "os.nim");
		LOC3 = 0;
		nimln(1621, "os.nim");
		nimln(1621, "os.nim");
		LOC3 = (0 < result->Sup.len);
		if (!(LOC3)) goto LA4;
		nimln(1621, "os.nim");
		nimln(1621, "os.nim");
		if ((NU)(0) > (NU)(result->Sup.len)) raiseIndexError();
		LOC3 = !(((NU8)(result->data[0]) == (NU8)(47)));
		LA4: ;
		if (!LOC3) goto LA5;
		p_779003 = 0;
		HEX3Atmp_779009 = 0;
		nimln(1623, "os.nim");
		nimln(1623, "os.nim");
		HEX3Atmp_779009 = getenv_775426(((NimStringDesc*) &TMP669));
		nimln(222, "strutils.nim");
		last_779011 = 0;
		nimln(223, "strutils.nim");
		{
			if (!NIM_FALSE) goto LA9;
			nimln(223, "strutils.nim");
			failedassertimpl_79821(((NimStringDesc*) &TMP670));
		}
		LA9: ;
		nimln(224, "strutils.nim");
		while (1) {
			NI first_779013;
			nimln(224, "strutils.nim");
			nimln(224, "strutils.nim");
			if (!(last_779011 < HEX3Atmp_779009->Sup.len)) goto LA11;
			nimln(225, "strutils.nim");
			while (1) {
				nimln(225, "strutils.nim");
				if ((NU)(last_779011) > (NU)(HEX3Atmp_779009->Sup.len)) raiseIndexError();
				if (!(((NU8)(HEX3Atmp_779009->data[last_779011])) == ((NU8)(58)))) goto LA12;
				nimln(225, "strutils.nim");
				last_779011 = addInt(last_779011, 1);
			} LA12: ;
			nimln(226, "strutils.nim");
			first_779013 = last_779011;
			nimln(227, "strutils.nim");
			while (1) {
				NIM_BOOL LOC14;
				nimln(227, "strutils.nim");
				LOC14 = 0;
				nimln(227, "strutils.nim");
				nimln(227, "strutils.nim");
				LOC14 = (last_779011 < HEX3Atmp_779009->Sup.len);
				if (!(LOC14)) goto LA15;
				nimln(227, "strutils.nim");
				nimln(227, "strutils.nim");
				if ((NU)(last_779011) > (NU)(HEX3Atmp_779009->Sup.len)) raiseIndexError();
				LOC14 = !((((NU8)(HEX3Atmp_779009->data[last_779011])) == ((NU8)(58))));
				LA15: ;
				if (!LOC14) goto LA13;
				nimln(227, "strutils.nim");
				last_779011 = addInt(last_779011, 1);
			} LA13: ;
			nimln(228, "strutils.nim");
			{
				NI TMP671;
				NI TMP672;
				NimStringDesc* x;
				nimln(228, "strutils.nim");
				nimln(228, "strutils.nim");
				TMP671 = subInt(last_779011, 1);
				if (!(first_779013 <= (NI64)(TMP671))) goto LA18;
				nimln(229, "strutils.nim");
				nimln(229, "strutils.nim");
				nimln(229, "strutils.nim");
				TMP672 = subInt(last_779011, 1);
				p_779003 = copyStrLast(HEX3Atmp_779009, first_779013, (NI64)(TMP672));
				nimln(1624, "os.nim");
				x = nosjoinPath(p_779003, result);
				nimln(1625, "os.nim");
				{
					NIM_BOOL LOC22;
					nimln(1625, "os.nim");
					LOC22 = 0;
					LOC22 = nosexistsFile(x);
					if (!LOC22) goto LA23;
					nimln(1625, "os.nim");
					nimln(1625, "os.nim");
					result = copyString(x);
					goto BeforeRet;
				}
				LA23: ;
			}
			LA18: ;
		} LA11: ;
	}
	LA5: ;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nosgetAppFilename)(void) {
	NimStringDesc* result;
	nimfr("getAppFilename", "os.nim")
	result = 0;
	nimln(1664, "os.nim");
	result = getapplaux_778602(((NimStringDesc*) &TMP665));
	nimln(1665, "os.nim");
	{
		nimln(1665, "os.nim");
		nimln(1665, "os.nim");
		if (!(result->Sup.len == 0)) goto LA3;
		nimln(1665, "os.nim");
		result = getapplheuristic_778802();
	}
	LA3: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nosgetApplicationDir)(void) {
	NimStringDesc* result;
	NimStringDesc* LOC1;
	TY772700 LOC2;
	nimfr("getApplicationDir", "os.nim")
	result = 0;
	nimln(1695, "os.nim");
	nimln(1695, "os.nim");
	nimln(1695, "os.nim");
	LOC1 = 0;
	LOC1 = nosgetAppFilename();
	memset((void*)&LOC2, 0, sizeof(LOC2));
	nossplitFile(LOC1, &LOC2);
	result = copyString(LOC2.Field0);
	popFrame();
	return result;
}
N_NOINLINE(void, osInit)(void) {
	nimfr("os", "os.nim")
	popFrame();
}

N_NOINLINE(void, osDatInit)(void) {
}

