/* Generated by Nimrod Compiler v0.9.5 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nimrod -o /home/andreysh/Projects/nimrod/stone_head/nimcache/sdl.o /home/andreysh/Projects/nimrod/stone_head/nimcache/sdl.c */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct tsurface85253 tsurface85253;
typedef struct tpixelformat85243 tpixelformat85243;
typedef struct trect85225 trect85225;
typedef struct tpalette85239 tpalette85239;
typedef struct tcolor85231 tcolor85231;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(NI, TY88420) (NI32 flags);
typedef N_CDECL_PTR(tsurface85253*, TY89187) (NI width, NI height, NI bpp, NU32 flags);
typedef N_CDECL_PTR(void, TY89318) (tsurface85253* surface);
typedef N_CDECL_PTR(void, TY88436) (void);
typedef N_CDECL_PTR(void, TY89481) (NCSTRING title, NCSTRING icon);
struct  trect85225  {
NI16 X;
NI16 Y;
NU16 W;
NU16 H;
};
struct  tsurface85253  {
NI32 Flags;
tpixelformat85243* Format;
int W;
int H;
NU16 Pitch;
void* Pixels;
int Offset;
void* Hwdata;
trect85225 Cliprect;
NI32 Unused1;
NI32 Locked;
void* Blitmap;
int Formatversion;
int Refcount;
};
struct  tpixelformat85243  {
tpalette85239* Palette;
NU8 Bitsperpixel;
NU8 Bytesperpixel;
NU8 Rloss;
NU8 Gloss;
NU8 Bloss;
NU8 Aloss;
NU8 Rshift;
NU8 Gshift;
NU8 Bshift;
NU8 Ashift;
NI32 Rmask;
NI32 Gmask;
NI32 Bmask;
NI32 Amask;
NI32 Colorkey;
NU8 Alpha;
};
struct  tpalette85239  {
NI Ncolors;
tcolor85231* Colors;
};
struct  tcolor85231  {
NU8 R;
NU8 G;
NU8 B;
NU8 Unused;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
STRING_LITERAL(TMP675, "libSDL.so", 9);
STRING_LITERAL(TMP676, "libSDL.so.1", 11);
STRING_LITERAL(TMP677, "libSDL.so.0", 11);
STRING_LITERAL(TMP678, "libSDL.so(|.1|.0)", 17);
static void* TMP674;
TY88420 Dl_88419;
TY89187 Dl_89186;
TY89318 Dl_89317;
TY88436 Dl_88435;
TY89481 Dl_89480;
extern TFrame* frameptr_13038;

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_13038;
	frameptr_13038 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_13038 = (*frameptr_13038).prev;
}
N_NOINLINE(void, sdlInit)(void) {
	nimfr("sdl", "sdl.nim")
	popFrame();
}

N_NOINLINE(void, sdlDatInit)(void) {
if (!((TMP674 = nimLoadLibrary((NimStringDesc*) &TMP675))
||(TMP674 = nimLoadLibrary((NimStringDesc*) &TMP676))
||(TMP674 = nimLoadLibrary((NimStringDesc*) &TMP677))
)) nimLoadLibraryError((NimStringDesc*) &TMP678);
	Dl_88419 = (TY88420) nimGetProcAddr(TMP674, "SDL_Init");
	Dl_89186 = (TY89187) nimGetProcAddr(TMP674, "SDL_SetVideoMode");
	Dl_89317 = (TY89318) nimGetProcAddr(TMP674, "SDL_FreeSurface");
	Dl_88435 = (TY88436) nimGetProcAddr(TMP674, "SDL_Quit");
	Dl_89480 = (TY89481) nimGetProcAddr(TMP674, "SDL_WM_SetCaption");
}

