/* Generated by Nimrod Compiler v0.9.5 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nimrod -o /home/andreysh/Projects/nimrod/stone_head/nimcache/streams.o /home/andreysh/Projects/nimrod/stone_head/nimcache/streams.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>

#include <stdio.h>
typedef struct eio2433 eio2433;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct esystem2431 esystem2431;
typedef struct esynch2429 esynch2429;
typedef struct E_Base E_Base;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tcell41290 tcell41290;
typedef struct tcellseq41306 tcellseq41306;
typedef struct tgcheap43216 tgcheap43216;
typedef struct tcellset41302 tcellset41302;
typedef struct tpagedesc41298 tpagedesc41298;
typedef struct tmemregion23610 tmemregion23610;
typedef struct tsmallchunk22838 tsmallchunk22838;
typedef struct tllchunk23604 tllchunk23604;
typedef struct tbigchunk22840 tbigchunk22840;
typedef struct tintset22815 tintset22815;
typedef struct ttrunk22811 ttrunk22811;
typedef struct tavlnode23608 tavlnode23608;
typedef struct tgcstat43214 tgcstat43214;
typedef struct tstream739829 tstream739829;
typedef struct tstringstream740230 tstringstream740230;
typedef struct tfilestream740356 tfilestream740356;
typedef struct tbasechunk22836 tbasechunk22836;
typedef struct tfreecell22828 tfreecell22828;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY2289) (void* p, NI op);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY2289 marker;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  E_Base  {
  TNimObject Sup;
E_Base* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  esynch2429  {
  E_Base Sup;
};
struct  esystem2431  {
  esynch2429 Sup;
};
struct  eio2433  {
  esystem2431 Sup;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  tcell41290  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq41306  {
NI Len;
NI Cap;
tcell41290** D;
};
struct  tcellset41302  {
NI Counter;
NI Max;
tpagedesc41298* Head;
tpagedesc41298** Data;
};
typedef tsmallchunk22838* TY23622[512];
typedef ttrunk22811* ttrunkbuckets22813[256];
struct  tintset22815  {
ttrunkbuckets22813 Data;
};
struct  tmemregion23610  {
NI Minlargeobj;
NI Maxlargeobj;
TY23622 Freesmallchunks;
tllchunk23604* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk22840* Freechunkslist;
tintset22815 Chunkstarts;
tavlnode23608* Root;
tavlnode23608* Deleted;
tavlnode23608* Last;
tavlnode23608* Freeavlnodes;
};
struct  tgcstat43214  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap43216  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq41306 Zct;
tcellseq41306 Decstack;
tcellset41302 Cycleroots;
tcellseq41306 Tempstack;
NI Recgclock;
tmemregion23610 Region;
tgcstat43214 Stat;
};
typedef N_NIMCALL_PTR(void, TY739830) (tstream739829* s);
typedef N_NIMCALL_PTR(NIM_BOOL, TY739834) (tstream739829* s);
typedef N_NIMCALL_PTR(void, TY739838) (tstream739829* s, NI pos);
typedef N_NIMCALL_PTR(NI, TY739843) (tstream739829* s);
typedef N_NIMCALL_PTR(NI, TY739847) (tstream739829* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY739853) (tstream739829* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY739859) (tstream739829* s);
struct  tstream739829  {
  TNimObject Sup;
TY739830 Closeimpl;
TY739834 Atendimpl;
TY739838 Setpositionimpl;
TY739843 Getpositionimpl;
TY739847 Readdataimpl;
TY739853 Writedataimpl;
TY739859 Flushimpl;
};
struct  tstringstream740230  {
  tstream739829 Sup;
NimStringDesc* Data;
NI Pos;
};
struct  tfilestream740356  {
  tstream739829 Sup;
FILE* F;
};
typedef NI TY22818[8];
struct  tpagedesc41298  {
tpagedesc41298* Next;
NI Key;
TY22818 Bits;
};
struct  tbasechunk22836  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk22838  {
  tbasechunk22836 Sup;
tsmallchunk22838* Next;
tsmallchunk22838* Prev;
tfreecell22828* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk23604  {
NI Size;
NI Acc;
tllchunk23604* Next;
};
struct  tbigchunk22840  {
  tbasechunk22836 Sup;
tbigchunk22840* Next;
tbigchunk22840* Prev;
NI Align;
NF Data;
};
struct  ttrunk22811  {
ttrunk22811* Next;
NI Key;
TY22818 Bits;
};
typedef tavlnode23608* TY23614[2];
struct  tavlnode23608  {
TY23614 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell22828  {
tfreecell22828* Next;
NI Zerofield;
};
N_NIMCALL(eio2433*, neweio_739803)(NimStringDesc* msg);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tcell41290*, usrtocell_44643)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_46202)(tcell41290* c);
N_NOINLINE(void, addzct_44618)(tcellseq41306* s, tcell41290* c);
N_NIMCALL(void, flush_739864)(tstream739829* s);
N_NIMCALL(void, close_739876)(tstream739829* s);
N_NIMCALL(void, close_739888)(tstream739829* s, tstream739829* unused);
N_NIMCALL(NIM_BOOL, atend_739894)(tstream739829* s);
N_NIMCALL(NIM_BOOL, atend_739900)(tstream739829* s, tstream739829* unused);
N_NIMCALL(void, setposition_739907)(tstream739829* s, NI pos);
N_NIMCALL(void, setposition_739913)(tstream739829* s, tstream739829* unused, NI pos);
N_NIMCALL(NI, getposition_739920)(tstream739829* s);
N_NIMCALL(NI, getposition_739926)(tstream739829* s, tstream739829* unused);
N_NIMCALL(NI, readdata_739933)(tstream739829* s, void* buffer, NI buflen);
N_NIMCALL(NI, readdata_739941)(tstream739829* s, tstream739829* unused, void* buffer, NI buflen);
N_NIMCALL(void, writedata_739950)(tstream739829* s, void* buffer, NI buflen);
N_NIMCALL(void, writedata_739957)(tstream739829* s, tstream739829* unused, void* buffer, NI buflen);
N_NIMCALL(void, write_739974)(tstream739829* s, NimStringDesc* x);
N_NIMCALL(void, writeln_739980)(tstream739829* s, NimStringDesc** args, NI argsLen0);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NIM_CHAR, readchar_740011)(tstream739829* s);
N_NIMCALL(void, read_740024)(tstream739829* s_740028, NIM_BOOL* result_740032);
N_NIMCALL(void, raiseException)(E_Base* e, NCSTRING ename);
N_NIMCALL(NIM_BOOL, readbool_740018)(tstream739829* s);
N_NIMCALL(void, read_740049)(tstream739829* s_740053, NI8* result_740057);
N_NIMCALL(NI8, readint8_740043)(tstream739829* s);
N_NIMCALL(void, read_740074)(tstream739829* s_740078, NI16* result_740082);
N_NIMCALL(NI16, readint16_740068)(tstream739829* s);
N_NIMCALL(void, read_740099)(tstream739829* s_740103, NI32* result_740107);
N_NIMCALL(NI32, readint32_740093)(tstream739829* s);
N_NIMCALL(void, read_740124)(tstream739829* s_740128, NI64* result_740132);
N_NIMCALL(NI64, readint64_740118)(tstream739829* s);
N_NIMCALL(void, read_740149)(tstream739829* s_740153, NF32* result_740157);
N_NIMCALL(NF32, readfloat32_740143)(tstream739829* s);
N_NIMCALL(void, read_740174)(tstream739829* s_740178, NF* result_740182);
N_NIMCALL(NF, readfloat64_740168)(tstream739829* s);
N_NIMCALL(NimStringDesc*, readstr_740193)(tstream739829* s, NI length);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newlen);
N_NIMCALL(NIM_BOOL, readline_740204)(tstream739829* s, NimStringDesc** line);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, readline_740217)(tstream739829* s);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NIM_BOOL, ssatend_740234)(tstream739829* s_740236);
N_NIMCALL(void, chckObj)(TNimType* obj, TNimType* subclass);
N_NIMCALL(NI, clamp_740247)(NI x_740251, NI a_740253, NI b_740255);
N_NIMCALL(void, sssetposition_740241)(tstream739829* s_740243, NI pos);
N_NIMCALL(NI, ssgetposition_740262)(tstream739829* s_740264);
N_NIMCALL(NI, ssreaddata_740269)(tstream739829* s_740271, void* buffer, NI buflen);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(void, sswritedata_740299)(tstream739829* s_740301, void* buffer, NI buflen);
N_NIMCALL(void, ssclose_740325)(tstream739829* s_740327);
N_NIMCALL(tstringstream740230*, newstringstream_740331)(NimStringDesc* s);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP468)(void* p, NI op);
N_NIMCALL(void, fsclose_740358)(tstream739829* s);
N_NIMCALL(void, fsflush_740379)(tstream739829* s);
N_NIMCALL(NIM_BOOL, fsatend_740383)(tstream739829* s);
N_NIMCALL(NIM_BOOL, endoffile_10428)(FILE* f);
N_NIMCALL(void, fssetposition_740388)(tstream739829* s, NI pos);
N_NIMCALL(void, setfilepos_10651)(FILE* f, NI64 pos);
N_NIMCALL(NI, fsgetposition_740393)(tstream739829* s);
N_NIMCALL(NI64, getfilepos_10655)(FILE* f);
N_NIMCALL(NI, fsreaddata_740399)(tstream739829* s, void* buffer, NI buflen);
N_NIMCALL(NI, readbuffer_10627)(FILE* f, void* buffer, NI len);
N_NIMCALL(void, fswritedata_740406)(tstream739829* s, void* buffer, NI buflen);
N_NIMCALL(NI, writebuffer_10646)(FILE* f, void* buffer, NI len);
N_NIMCALL(tfilestream740356*, newfilestream_740412)(FILE* f);
N_NIMCALL(void, TMP470)(void* p, NI op);
N_NIMCALL(tfilestream740356*, newfilestream_740433)(NimStringDesc* filename, NU8 mode);
N_NIMCALL(NIM_BOOL, open_10203)(FILE** f, NimStringDesc* filename, NU8 mode, NI bufsize);
N_NIMCALL(void, TMP630)(void* p, NI op);
STRING_LITERAL(TMP461, "\012", 1);
STRING_LITERAL(TMP462, "cannot read from stream", 23);
STRING_LITERAL(TMP463, "", 0);
STRING_LITERAL(TMP469, "cannot write to stream", 22);
extern TNimType NTI10401; /* ref EIO */
extern TNimType NTI2433; /* EIO */
extern TFrame* frameptr_13038;
extern tgcheap43216 gch_43244;
extern TNimType NTI2409; /* TObject */
TNimType NTI739829; /* TStream */
TNimType NTI739830; /* proc (PStream) */
TNimType NTI739834; /* proc (PStream): bool */
TNimType NTI739838; /* proc (PStream, int) */
TNimType NTI739843; /* proc (PStream): int */
TNimType NTI739847; /* proc (PStream, pointer, int): int */
TNimType NTI739853; /* proc (PStream, pointer, int) */
TNimType NTI739859; /* proc (PStream) */
TNimType NTI740230; /* TStringStream */
extern TNimType NTI143; /* string */
extern TNimType NTI106; /* int */
TNimType NTI740228; /* PStringStream */
TNimType NTI740356; /* TFileStream */
extern TNimType NTI10004; /* TFile */
TNimType NTI740354; /* PFileStream */
TNimType NTI739827; /* PStream */

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_13038;
	frameptr_13038 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_13038 = (*frameptr_13038).prev;
}

static N_INLINE(tcell41290*, usrtocell_44643)(void* usr) {
	tcell41290* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell41290*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell41290))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_46202)(tcell41290* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_44618(&gch_43244.Zct, c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell41290* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_44643(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_46202(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(eio2433*, neweio_739803)(NimStringDesc* msg) {
	eio2433* result;
	NimStringDesc* LOC1;
	nimfr("newEIO", "streams.nim")
	result = 0;
	nimln(18, "streams.nim");
	result = (eio2433*) newObj((&NTI10401), sizeof(eio2433));
	(*result).Sup.Sup.Sup.Sup.m_type = (&NTI2433);
	nimln(19, "streams.nim");
	LOC1 = 0;
	LOC1 = (*result).Sup.Sup.Sup.message; (*result).Sup.Sup.Sup.message = copyStringRC1(msg);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	popFrame();
	return result;
}

N_NIMCALL(void, flush_739864)(tstream739829* s) {
	nimfr("flush", "streams.nim")
	nimln(40, "streams.nim");
	{
		nimln(40, "streams.nim");
		nimln(40, "streams.nim");
		if (!!((*s).Flushimpl == 0)) goto LA3;
		nimln(40, "streams.nim");
		(*s).Flushimpl(s);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, close_739876)(tstream739829* s) {
	nimfr("close", "streams.nim")
	nimln(44, "streams.nim");
	{
		nimln(44, "streams.nim");
		nimln(44, "streams.nim");
		if (!!((*s).Closeimpl == 0)) goto LA3;
		nimln(44, "streams.nim");
		(*s).Closeimpl(s);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, close_739888)(tstream739829* s, tstream739829* unused) {
	nimfr("close", "streams.nim")
	nimln(48, "streams.nim");
	(*s).Closeimpl(s);
	popFrame();
}

N_NIMCALL(NIM_BOOL, atend_739894)(tstream739829* s) {
	NIM_BOOL result;
	nimfr("atEnd", "streams.nim")
	result = 0;
	nimln(53, "streams.nim");
	result = (*s).Atendimpl(s);
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, atend_739900)(tstream739829* s, tstream739829* unused) {
	NIM_BOOL result;
	nimfr("atEnd", "streams.nim")
	result = 0;
	nimln(58, "streams.nim");
	result = (*s).Atendimpl(s);
	popFrame();
	return result;
}

N_NIMCALL(void, setposition_739907)(tstream739829* s, NI pos) {
	nimfr("setPosition", "streams.nim")
	nimln(62, "streams.nim");
	(*s).Setpositionimpl(s, pos);
	popFrame();
}

N_NIMCALL(void, setposition_739913)(tstream739829* s, tstream739829* unused, NI pos) {
	nimfr("setPosition", "streams.nim")
	nimln(66, "streams.nim");
	(*s).Setpositionimpl(s, pos);
	popFrame();
}

N_NIMCALL(NI, getposition_739920)(tstream739829* s) {
	NI result;
	nimfr("getPosition", "streams.nim")
	result = 0;
	nimln(70, "streams.nim");
	result = (*s).Getpositionimpl(s);
	popFrame();
	return result;
}

N_NIMCALL(NI, getposition_739926)(tstream739829* s, tstream739829* unused) {
	NI result;
	nimfr("getPosition", "streams.nim")
	result = 0;
	nimln(74, "streams.nim");
	result = (*s).Getpositionimpl(s);
	popFrame();
	return result;
}

N_NIMCALL(NI, readdata_739933)(tstream739829* s, void* buffer, NI buflen) {
	NI result;
	nimfr("readData", "streams.nim")
	result = 0;
	nimln(78, "streams.nim");
	result = (*s).Readdataimpl(s, buffer, buflen);
	popFrame();
	return result;
}

N_NIMCALL(NI, readdata_739941)(tstream739829* s, tstream739829* unused, void* buffer, NI buflen) {
	NI result;
	nimfr("readData", "streams.nim")
	result = 0;
	nimln(83, "streams.nim");
	result = (*s).Readdataimpl(s, buffer, buflen);
	popFrame();
	return result;
}

N_NIMCALL(void, writedata_739950)(tstream739829* s, void* buffer, NI buflen) {
	nimfr("writeData", "streams.nim")
	nimln(88, "streams.nim");
	(*s).Writedataimpl(s, buffer, buflen);
	popFrame();
}

N_NIMCALL(void, writedata_739957)(tstream739829* s, tstream739829* unused, void* buffer, NI buflen) {
	nimfr("writeData", "streams.nim")
	nimln(94, "streams.nim");
	(*s).Writedataimpl(s, buffer, buflen);
	popFrame();
}

N_NIMCALL(void, write_739974)(tstream739829* s, NimStringDesc* x) {
	nimfr("write", "streams.nim")
	nimln(109, "streams.nim");
	nimln(109, "streams.nim");
	writedata_739950(s, ((void*) (x->data)), x->Sup.len);
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, writeln_739980)(tstream739829* s, NimStringDesc** args, NI argsLen0) {
	NimStringDesc* str_739996;
	NI i_739998;
	nimfr("writeln", "streams.nim")
	str_739996 = 0;
	nimln(1531, "system.nim");
	i_739998 = 0;
	nimln(1532, "system.nim");
	while (1) {
		nimln(1532, "system.nim");
		nimln(1532, "system.nim");
		if (!(i_739998 < argsLen0)) goto LA1;
		nimln(1533, "system.nim");
		if ((NU)(i_739998) >= (NU)(argsLen0)) raiseIndexError();
		str_739996 = args[i_739998];
		nimln(114, "streams.nim");
		write_739974(s, str_739996);
		nimln(1534, "system.nim");
		i_739998 = addInt(i_739998, 1);
	} LA1: ;
	nimln(115, "streams.nim");
	write_739974(s, ((NimStringDesc*) &TMP461));
	popFrame();
}

N_NIMCALL(NIM_CHAR, readchar_740011)(tstream739829* s) {
	NIM_CHAR result;
	nimfr("readChar", "streams.nim")
	result = 0;
	nimln(125, "streams.nim");
	{
		NI LOC3;
		nimln(125, "streams.nim");
		nimln(125, "streams.nim");
		nimln(125, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_739933(s, ((void*) (&result)), 1);
		if (!!((LOC3 == 1))) goto LA4;
		nimln(125, "streams.nim");
		result = 0;
	}
	LA4: ;
	popFrame();
	return result;
}

N_NIMCALL(void, read_740024)(tstream739829* s_740028, NIM_BOOL* result_740032) {
	nimfr("read", "streams.nim")
	nimln(119, "streams.nim");
	{
		NI LOC3;
		eio2433* LOC6;
		nimln(119, "streams.nim");
		nimln(119, "streams.nim");
		nimln(119, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_739933(s_740028, ((void*) (result_740032)), 1);
		if (!!((LOC3 == 1))) goto LA4;
		nimln(120, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_739803(((NimStringDesc*) &TMP462));
		nimln(120, "streams.nim");
		raiseException((E_Base*)LOC6, "EIO");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NIM_BOOL, readbool_740018)(tstream739829* s) {
	NIM_BOOL result;
	nimfr("readBool", "streams.nim")
	result = 0;
	nimln(129, "streams.nim");
	read_740024(s, &result);
	popFrame();
	return result;
}

N_NIMCALL(void, read_740049)(tstream739829* s_740053, NI8* result_740057) {
	nimfr("read", "streams.nim")
	nimln(119, "streams.nim");
	{
		NI LOC3;
		eio2433* LOC6;
		nimln(119, "streams.nim");
		nimln(119, "streams.nim");
		nimln(119, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_739933(s_740053, ((void*) (result_740057)), 1);
		if (!!((LOC3 == 1))) goto LA4;
		nimln(120, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_739803(((NimStringDesc*) &TMP462));
		nimln(120, "streams.nim");
		raiseException((E_Base*)LOC6, "EIO");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI8, readint8_740043)(tstream739829* s) {
	NI8 result;
	nimfr("readInt8", "streams.nim")
	result = 0;
	nimln(133, "streams.nim");
	read_740049(s, &result);
	popFrame();
	return result;
}

N_NIMCALL(void, read_740074)(tstream739829* s_740078, NI16* result_740082) {
	nimfr("read", "streams.nim")
	nimln(119, "streams.nim");
	{
		NI LOC3;
		eio2433* LOC6;
		nimln(119, "streams.nim");
		nimln(119, "streams.nim");
		nimln(119, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_739933(s_740078, ((void*) (result_740082)), 2);
		if (!!((LOC3 == 2))) goto LA4;
		nimln(120, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_739803(((NimStringDesc*) &TMP462));
		nimln(120, "streams.nim");
		raiseException((E_Base*)LOC6, "EIO");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI16, readint16_740068)(tstream739829* s) {
	NI16 result;
	nimfr("readInt16", "streams.nim")
	result = 0;
	nimln(137, "streams.nim");
	read_740074(s, &result);
	popFrame();
	return result;
}

N_NIMCALL(void, read_740099)(tstream739829* s_740103, NI32* result_740107) {
	nimfr("read", "streams.nim")
	nimln(119, "streams.nim");
	{
		NI LOC3;
		eio2433* LOC6;
		nimln(119, "streams.nim");
		nimln(119, "streams.nim");
		nimln(119, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_739933(s_740103, ((void*) (result_740107)), 4);
		if (!!((LOC3 == 4))) goto LA4;
		nimln(120, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_739803(((NimStringDesc*) &TMP462));
		nimln(120, "streams.nim");
		raiseException((E_Base*)LOC6, "EIO");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI32, readint32_740093)(tstream739829* s) {
	NI32 result;
	nimfr("readInt32", "streams.nim")
	result = 0;
	nimln(141, "streams.nim");
	read_740099(s, &result);
	popFrame();
	return result;
}

N_NIMCALL(void, read_740124)(tstream739829* s_740128, NI64* result_740132) {
	nimfr("read", "streams.nim")
	nimln(119, "streams.nim");
	{
		NI LOC3;
		eio2433* LOC6;
		nimln(119, "streams.nim");
		nimln(119, "streams.nim");
		nimln(119, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_739933(s_740128, ((void*) (result_740132)), 8);
		if (!!((LOC3 == 8))) goto LA4;
		nimln(120, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_739803(((NimStringDesc*) &TMP462));
		nimln(120, "streams.nim");
		raiseException((E_Base*)LOC6, "EIO");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI64, readint64_740118)(tstream739829* s) {
	NI64 result;
	nimfr("readInt64", "streams.nim")
	result = 0;
	nimln(145, "streams.nim");
	read_740124(s, &result);
	popFrame();
	return result;
}

N_NIMCALL(void, read_740149)(tstream739829* s_740153, NF32* result_740157) {
	nimfr("read", "streams.nim")
	nimln(119, "streams.nim");
	{
		NI LOC3;
		eio2433* LOC6;
		nimln(119, "streams.nim");
		nimln(119, "streams.nim");
		nimln(119, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_739933(s_740153, ((void*) (result_740157)), 4);
		if (!!((LOC3 == 4))) goto LA4;
		nimln(120, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_739803(((NimStringDesc*) &TMP462));
		nimln(120, "streams.nim");
		raiseException((E_Base*)LOC6, "EIO");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NF32, readfloat32_740143)(tstream739829* s) {
	NF32 result;
	nimfr("readFloat32", "streams.nim")
	result = 0;
	nimln(149, "streams.nim");
	read_740149(s, &result);
	popFrame();
	return result;
}

N_NIMCALL(void, read_740174)(tstream739829* s_740178, NF* result_740182) {
	nimfr("read", "streams.nim")
	nimln(119, "streams.nim");
	{
		NI LOC3;
		eio2433* LOC6;
		nimln(119, "streams.nim");
		nimln(119, "streams.nim");
		nimln(119, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_739933(s_740178, ((void*) (result_740182)), 8);
		if (!!((LOC3 == 8))) goto LA4;
		nimln(120, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_739803(((NimStringDesc*) &TMP462));
		nimln(120, "streams.nim");
		raiseException((E_Base*)LOC6, "EIO");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NF, readfloat64_740168)(tstream739829* s) {
	NF result;
	nimfr("readFloat64", "streams.nim")
	result = 0;
	nimln(153, "streams.nim");
	read_740174(s, &result);
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, readstr_740193)(tstream739829* s, NI length) {
	NimStringDesc* result;
	NI l;
	nimfr("readStr", "streams.nim")
	result = 0;
	nimln(158, "streams.nim");
	nimln(158, "streams.nim");
	result = mnewString(length);
	nimln(159, "streams.nim");
	if ((NU)(0) > (NU)(result->Sup.len)) raiseIndexError();
	l = readdata_739933(s, ((void*) (&result->data[0])), length);
	nimln(160, "streams.nim");
	{
		nimln(160, "streams.nim");
		nimln(160, "streams.nim");
		if (!!((l == length))) goto LA3;
		nimln(160, "streams.nim");
		result = setLengthStr(result, l);
	}
	LA3: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, readline_740204)(tstream739829* s, NimStringDesc** line) {
	NIM_BOOL result;
	nimfr("readLine", "streams.nim")
	result = 0;
	nimln(169, "streams.nim");
	(*line) = setLengthStr((*line), 0);
	nimln(170, "streams.nim");
	while (1) {
		NIM_CHAR c;
		nimln(171, "streams.nim");
		c = readchar_740011(s);
		nimln(172, "streams.nim");
		{
			nimln(172, "streams.nim");
			if (!((NU8)(c) == (NU8)(13))) goto LA4;
			nimln(173, "streams.nim");
			c = readchar_740011(s);
			nimln(174, "streams.nim");
			goto LA1;
		}
		goto LA2;
		LA4: ;
		{
			nimln(175, "streams.nim");
			if (!((NU8)(c) == (NU8)(10))) goto LA7;
			nimln(175, "streams.nim");
			goto LA1;
		}
		goto LA2;
		LA7: ;
		{
			nimln(176, "streams.nim");
			if (!((NU8)(c) == (NU8)(0))) goto LA10;
			nimln(177, "streams.nim");
			{
				nimln(177, "streams.nim");
				nimln(177, "streams.nim");
				if (!(0 < (*line)->Sup.len)) goto LA14;
				nimln(177, "streams.nim");
				goto LA1;
			}
			goto LA12;
			LA14: ;
			{
				nimln(178, "streams.nim");
				nimln(178, "streams.nim");
				result = NIM_FALSE;
				goto BeforeRet;
			}
			LA12: ;
		}
		goto LA2;
		LA10: ;
		LA2: ;
		nimln(179, "streams.nim");
		(*line) = addChar((*line), c);
	} LA1: ;
	nimln(180, "streams.nim");
	result = NIM_TRUE;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, readline_740217)(tstream739829* s) {
	NimStringDesc* result;
	nimfr("readLine", "streams.nim")
	result = 0;
	nimln(185, "streams.nim");
	result = copyString(((NimStringDesc*) &TMP463));
	nimln(186, "streams.nim");
	while (1) {
		NIM_CHAR c;
		nimln(187, "streams.nim");
		c = readchar_740011(s);
		nimln(188, "streams.nim");
		{
			nimln(188, "streams.nim");
			if (!((NU8)(c) == (NU8)(13))) goto LA4;
			nimln(189, "streams.nim");
			c = readchar_740011(s);
			nimln(190, "streams.nim");
			goto LA1;
		}
		LA4: ;
		nimln(191, "streams.nim");
		{
			NIM_BOOL LOC8;
			nimln(191, "streams.nim");
			LOC8 = 0;
			nimln(191, "streams.nim");
			LOC8 = ((NU8)(c) == (NU8)(10));
			if (LOC8) goto LA9;
			nimln(191, "streams.nim");
			LOC8 = ((NU8)(c) == (NU8)(0));
			LA9: ;
			if (!LOC8) goto LA10;
			nimln(192, "streams.nim");
			goto LA1;
		}
		goto LA6;
		LA10: ;
		{
			nimln(194, "streams.nim");
			result = addChar(result, c);
		}
		LA6: ;
	} LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, ssatend_740234)(tstream739829* s_740236) {
	NIM_BOOL result;
	tstringstream740230* s;
	nimfr("ssAtEnd", "streams.nim")
	result = 0;
	nimln(203, "streams.nim");
	if (s_740236) chckObj((*s_740236).Sup.m_type, (&NTI740230));
	s = ((tstringstream740230*) (s_740236));
	nimln(204, "streams.nim");
	nimln(204, "streams.nim");
	nimln(204, "streams.nim");
	nimln(204, "streams.nim");
	result = ((*s).Data->Sup.len <= (*s).Pos);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, sssetposition_740241)(tstream739829* s_740243, NI pos) {
	tstringstream740230* s;
	nimfr("ssSetPosition", "streams.nim")
	nimln(207, "streams.nim");
	if (s_740243) chckObj((*s_740243).Sup.m_type, (&NTI740230));
	s = ((tstringstream740230*) (s_740243));
	nimln(208, "streams.nim");
	nimln(208, "streams.nim");
	(*s).Pos = clamp_740247(pos, 0, ((*s).Data->Sup.len-1));
	popFrame();
}

N_NIMCALL(NI, ssgetposition_740262)(tstream739829* s_740264) {
	NI result;
	tstringstream740230* s;
	nimfr("ssGetPosition", "streams.nim")
	result = 0;
	nimln(211, "streams.nim");
	if (s_740264) chckObj((*s_740264).Sup.m_type, (&NTI740230));
	s = ((tstringstream740230*) (s_740264));
	nimln(212, "streams.nim");
	nimln(212, "streams.nim");
	result = (*s).Pos;
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, ssreaddata_740269)(tstream739829* s_740271, void* buffer, NI buflen) {
	NI result;
	tstringstream740230* s;
	NI TMP466;
	nimfr("ssReadData", "streams.nim")
	result = 0;
	nimln(215, "streams.nim");
	if (s_740271) chckObj((*s_740271).Sup.m_type, (&NTI740230));
	s = ((tstringstream740230*) (s_740271));
	nimln(216, "streams.nim");
	nimln(216, "streams.nim");
	nimln(216, "streams.nim");
	nimln(216, "streams.nim");
	TMP466 = subInt((*s).Data->Sup.len, (*s).Pos);
	result = ((buflen <= (NI64)(TMP466)) ? buflen : (NI64)(TMP466));
	nimln(217, "streams.nim");
	{
		nimln(217, "streams.nim");
		if (!(0 < result)) goto LA3;
		nimln(218, "streams.nim");
		if ((NU)((*s).Pos) > (NU)((*s).Data->Sup.len)) raiseIndexError();
		memcpy(buffer, ((void*) (&(*s).Data->data[(*s).Pos])), result);
		nimln(219, "streams.nim");
		(*s).Pos = addInt((*s).Pos, result);
	}
	LA3: ;
	popFrame();
	return result;
}

N_NIMCALL(void, sswritedata_740299)(tstream739829* s_740301, void* buffer, NI buflen) {
	tstringstream740230* s;
	nimfr("ssWriteData", "streams.nim")
	nimln(222, "streams.nim");
	if (s_740301) chckObj((*s_740301).Sup.m_type, (&NTI740230));
	s = ((tstringstream740230*) (s_740301));
	nimln(223, "streams.nim");
	{
		NI TMP467;
		nimln(223, "streams.nim");
		if (!(0 < buflen)) goto LA3;
		nimln(224, "streams.nim");
		nimln(224, "streams.nim");
		nimln(224, "streams.nim");
		TMP467 = addInt((*s).Data->Sup.len, buflen);
		(*s).Data = setLengthStr((*s).Data, (NI64)(TMP467));
		nimln(225, "streams.nim");
		if ((NU)((*s).Pos) > (NU)((*s).Data->Sup.len)) raiseIndexError();
		memcpy(((void*) (&(*s).Data->data[(*s).Pos])), buffer, buflen);
		nimln(226, "streams.nim");
		(*s).Pos = addInt((*s).Pos, buflen);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, ssclose_740325)(tstream739829* s_740327) {
	tstringstream740230* s;
	NimStringDesc* LOC1;
	nimfr("ssClose", "streams.nim")
	nimln(229, "streams.nim");
	if (s_740327) chckObj((*s_740327).Sup.m_type, (&NTI740230));
	s = ((tstringstream740230*) (s_740327));
	nimln(230, "streams.nim");
	LOC1 = 0;
	LOC1 = (*s).Data; (*s).Data = copyStringRC1(NIM_NIL);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	popFrame();
}
N_NIMCALL(void, TMP468)(void* p, NI op) {
	tstringstream740230* a;
	a = (tstringstream740230*)p;
	nimGCvisit((void*)(*a).Data, op);
}

N_NIMCALL(tstringstream740230*, newstringstream_740331)(NimStringDesc* s) {
	tstringstream740230* result;
	NimStringDesc* LOC1;
	nimfr("newStringStream", "streams.nim")
	result = 0;
	nimln(234, "streams.nim");
	result = (tstringstream740230*) newObj((&NTI740228), sizeof(tstringstream740230));
	(*result).Sup.Sup.m_type = (&NTI740230);
	nimln(235, "streams.nim");
	LOC1 = 0;
	LOC1 = (*result).Data; (*result).Data = copyStringRC1(s);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	nimln(236, "streams.nim");
	(*result).Pos = 0;
	nimln(237, "streams.nim");
	(*result).Sup.Closeimpl = ssclose_740325;
	nimln(238, "streams.nim");
	(*result).Sup.Atendimpl = ssatend_740234;
	nimln(239, "streams.nim");
	(*result).Sup.Setpositionimpl = sssetposition_740241;
	nimln(240, "streams.nim");
	(*result).Sup.Getpositionimpl = ssgetposition_740262;
	nimln(241, "streams.nim");
	(*result).Sup.Readdataimpl = ssreaddata_740269;
	nimln(242, "streams.nim");
	(*result).Sup.Writedataimpl = sswritedata_740299;
	popFrame();
	return result;
}

N_NIMCALL(void, fsclose_740358)(tstream739829* s) {
	nimfr("fsClose", "streams.nim")
	nimln(252, "streams.nim");
	{
		nimln(252, "streams.nim");
		nimln(252, "streams.nim");
		if (s) chckObj((*s).Sup.m_type, (&NTI740356));
		if (!!(((*((tfilestream740356*) (s))).F == NIM_NIL))) goto LA3;
		nimln(253, "streams.nim");
		if (s) chckObj((*s).Sup.m_type, (&NTI740356));
		fclose((*((tfilestream740356*) (s))).F);
		nimln(254, "streams.nim");
		if (s) chckObj((*s).Sup.m_type, (&NTI740356));
		(*((tfilestream740356*) (s))).F = NIM_NIL;
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, fsflush_740379)(tstream739829* s) {
	nimfr("fsFlush", "streams.nim")
	nimln(255, "streams.nim");
	if (s) chckObj((*s).Sup.m_type, (&NTI740356));
	fflush((*((tfilestream740356*) (s))).F);
	popFrame();
}

N_NIMCALL(NIM_BOOL, fsatend_740383)(tstream739829* s) {
	NIM_BOOL result;
	nimfr("fsAtEnd", "streams.nim")
	result = 0;
	nimln(256, "streams.nim");
	nimln(256, "streams.nim");
	if (s) chckObj((*s).Sup.m_type, (&NTI740356));
	result = endoffile_10428((*((tfilestream740356*) (s))).F);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, fssetposition_740388)(tstream739829* s, NI pos) {
	nimfr("fsSetPosition", "streams.nim")
	nimln(257, "streams.nim");
	if (s) chckObj((*s).Sup.m_type, (&NTI740356));
	setfilepos_10651((*((tfilestream740356*) (s))).F, ((NI64) (pos)));
	popFrame();
}

N_NIMCALL(NI, fsgetposition_740393)(tstream739829* s) {
	NI result;
	NI64 LOC1;
	nimfr("fsGetPosition", "streams.nim")
	result = 0;
	nimln(258, "streams.nim");
	nimln(258, "streams.nim");
	nimln(258, "streams.nim");
	if (s) chckObj((*s).Sup.m_type, (&NTI740356));
	LOC1 = 0;
	LOC1 = getfilepos_10655((*((tfilestream740356*) (s))).F);
	result = ((NI) (LOC1));
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, fsreaddata_740399)(tstream739829* s, void* buffer, NI buflen) {
	NI result;
	nimfr("fsReadData", "streams.nim")
	result = 0;
	nimln(261, "streams.nim");
	if (s) chckObj((*s).Sup.m_type, (&NTI740356));
	result = readbuffer_10627((*((tfilestream740356*) (s))).F, buffer, buflen);
	popFrame();
	return result;
}

N_NIMCALL(void, fswritedata_740406)(tstream739829* s, void* buffer, NI buflen) {
	nimfr("fsWriteData", "streams.nim")
	nimln(264, "streams.nim");
	{
		NI LOC3;
		eio2433* LOC6;
		nimln(264, "streams.nim");
		nimln(264, "streams.nim");
		nimln(264, "streams.nim");
		if (s) chckObj((*s).Sup.m_type, (&NTI740356));
		LOC3 = 0;
		LOC3 = writebuffer_10646((*((tfilestream740356*) (s))).F, buffer, buflen);
		if (!!((LOC3 == buflen))) goto LA4;
		nimln(265, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_739803(((NimStringDesc*) &TMP469));
		nimln(265, "streams.nim");
		raiseException((E_Base*)LOC6, "EIO");
	}
	LA4: ;
	popFrame();
}
N_NIMCALL(void, TMP470)(void* p, NI op) {
	tfilestream740356* a;
	a = (tfilestream740356*)p;
}

N_NIMCALL(tfilestream740356*, newfilestream_740412)(FILE* f) {
	tfilestream740356* result;
	nimfr("newFileStream", "streams.nim")
	result = 0;
	nimln(269, "streams.nim");
	result = (tfilestream740356*) newObj((&NTI740354), sizeof(tfilestream740356));
	(*result).Sup.Sup.m_type = (&NTI740356);
	nimln(270, "streams.nim");
	(*result).F = f;
	nimln(271, "streams.nim");
	(*result).Sup.Closeimpl = fsclose_740358;
	nimln(272, "streams.nim");
	(*result).Sup.Atendimpl = fsatend_740383;
	nimln(273, "streams.nim");
	(*result).Sup.Setpositionimpl = fssetposition_740388;
	nimln(274, "streams.nim");
	(*result).Sup.Getpositionimpl = fsgetposition_740393;
	nimln(275, "streams.nim");
	(*result).Sup.Readdataimpl = fsreaddata_740399;
	nimln(276, "streams.nim");
	(*result).Sup.Writedataimpl = fswritedata_740406;
	nimln(277, "streams.nim");
	(*result).Sup.Flushimpl = fsflush_740379;
	popFrame();
	return result;
}

N_NIMCALL(tfilestream740356*, newfilestream_740433)(NimStringDesc* filename, NU8 mode) {
	tfilestream740356* result;
	FILE* f;
	nimfr("newFileStream", "streams.nim")
	result = 0;
	f = 0;
	nimln(284, "streams.nim");
	{
		NIM_BOOL LOC3;
		nimln(284, "streams.nim");
		LOC3 = 0;
		LOC3 = open_10203(&f, filename, mode, -1);
		if (!LOC3) goto LA4;
		nimln(284, "streams.nim");
		result = newfilestream_740412(f);
	}
	LA4: ;
	popFrame();
	return result;
}
N_NIMCALL(void, TMP630)(void* p, NI op) {
	tstream739829* a;
	a = (tstream739829*)p;
}
N_NOINLINE(void, streamsInit)(void) {
	nimfr("streams", "streams.nim")
	popFrame();
}

N_NOINLINE(void, streamsDatInit)(void) {
static TNimNode* TMP464[7];
static TNimNode* TMP465[2];
static TNimNode TMP459[12];
NTI739829.size = sizeof(tstream739829);
NTI739829.kind = 17;
NTI739829.base = (&NTI2409);
NTI739829.flags = 1;
TMP464[0] = &TMP459[1];
NTI739830.size = sizeof(TY739830);
NTI739830.kind = 25;
NTI739830.base = 0;
NTI739830.flags = 3;
TMP459[1].kind = 1;
TMP459[1].offset = offsetof(tstream739829, Closeimpl);
TMP459[1].typ = (&NTI739830);
TMP459[1].name = "closeImpl";
TMP464[1] = &TMP459[2];
NTI739834.size = sizeof(TY739834);
NTI739834.kind = 25;
NTI739834.base = 0;
NTI739834.flags = 3;
TMP459[2].kind = 1;
TMP459[2].offset = offsetof(tstream739829, Atendimpl);
TMP459[2].typ = (&NTI739834);
TMP459[2].name = "atEndImpl";
TMP464[2] = &TMP459[3];
NTI739838.size = sizeof(TY739838);
NTI739838.kind = 25;
NTI739838.base = 0;
NTI739838.flags = 3;
TMP459[3].kind = 1;
TMP459[3].offset = offsetof(tstream739829, Setpositionimpl);
TMP459[3].typ = (&NTI739838);
TMP459[3].name = "setPositionImpl";
TMP464[3] = &TMP459[4];
NTI739843.size = sizeof(TY739843);
NTI739843.kind = 25;
NTI739843.base = 0;
NTI739843.flags = 3;
TMP459[4].kind = 1;
TMP459[4].offset = offsetof(tstream739829, Getpositionimpl);
TMP459[4].typ = (&NTI739843);
TMP459[4].name = "getPositionImpl";
TMP464[4] = &TMP459[5];
NTI739847.size = sizeof(TY739847);
NTI739847.kind = 25;
NTI739847.base = 0;
NTI739847.flags = 3;
TMP459[5].kind = 1;
TMP459[5].offset = offsetof(tstream739829, Readdataimpl);
TMP459[5].typ = (&NTI739847);
TMP459[5].name = "readDataImpl";
TMP464[5] = &TMP459[6];
NTI739853.size = sizeof(TY739853);
NTI739853.kind = 25;
NTI739853.base = 0;
NTI739853.flags = 3;
TMP459[6].kind = 1;
TMP459[6].offset = offsetof(tstream739829, Writedataimpl);
TMP459[6].typ = (&NTI739853);
TMP459[6].name = "writeDataImpl";
TMP464[6] = &TMP459[7];
NTI739859.size = sizeof(TY739859);
NTI739859.kind = 25;
NTI739859.base = 0;
NTI739859.flags = 3;
TMP459[7].kind = 1;
TMP459[7].offset = offsetof(tstream739829, Flushimpl);
TMP459[7].typ = (&NTI739859);
TMP459[7].name = "flushImpl";
TMP459[0].len = 7; TMP459[0].kind = 2; TMP459[0].sons = &TMP464[0];
NTI739829.node = &TMP459[0];
NTI740230.size = sizeof(tstringstream740230);
NTI740230.kind = 17;
NTI740230.base = (&NTI739829);
TMP465[0] = &TMP459[9];
TMP459[9].kind = 1;
TMP459[9].offset = offsetof(tstringstream740230, Data);
TMP459[9].typ = (&NTI143);
TMP459[9].name = "data";
TMP465[1] = &TMP459[10];
TMP459[10].kind = 1;
TMP459[10].offset = offsetof(tstringstream740230, Pos);
TMP459[10].typ = (&NTI106);
TMP459[10].name = "pos";
TMP459[8].len = 2; TMP459[8].kind = 2; TMP459[8].sons = &TMP465[0];
NTI740230.node = &TMP459[8];
NTI740228.size = sizeof(tstringstream740230*);
NTI740228.kind = 22;
NTI740228.base = (&NTI740230);
NTI740228.marker = TMP468;
NTI740356.size = sizeof(tfilestream740356);
NTI740356.kind = 17;
NTI740356.base = (&NTI739829);
NTI740356.flags = 1;
TMP459[11].kind = 1;
TMP459[11].offset = offsetof(tfilestream740356, F);
TMP459[11].typ = (&NTI10004);
TMP459[11].name = "f";
NTI740356.node = &TMP459[11];
NTI740354.size = sizeof(tfilestream740356*);
NTI740354.kind = 22;
NTI740354.base = (&NTI740356);
NTI740354.marker = TMP470;
NTI739827.size = sizeof(tstream739829*);
NTI739827.kind = 22;
NTI739827.base = (&NTI739829);
NTI739827.marker = TMP630;
}

