/* Generated by Nimrod Compiler v0.9.5 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nimrod -o /home/andreysh/Projects/nimrod/stone_head/nimcache/strutils.o /home/andreysh/Projects/nimrod/stone_head/nimcache/strutils.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct einvalidvalue2453 einvalidvalue2453;
typedef struct esynch2429 esynch2429;
typedef struct E_Base E_Base;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tcell41290 tcell41290;
typedef struct tcellseq41306 tcellseq41306;
typedef struct tgcheap43216 tgcheap43216;
typedef struct tcellset41302 tcellset41302;
typedef struct tpagedesc41298 tpagedesc41298;
typedef struct tmemregion23610 tmemregion23610;
typedef struct tsmallchunk22838 tsmallchunk22838;
typedef struct tllchunk23604 tllchunk23604;
typedef struct tbigchunk22840 tbigchunk22840;
typedef struct tintset22815 tintset22815;
typedef struct ttrunk22811 ttrunk22811;
typedef struct tavlnode23608 tavlnode23608;
typedef struct tgcstat43214 tgcstat43214;
typedef struct tbasechunk22836 tbasechunk22836;
typedef struct tfreecell22828 tfreecell22828;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY2289) (void* p, NI op);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY2289 marker;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  E_Base  {
  TNimObject Sup;
E_Base* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  esynch2429  {
  E_Base Sup;
};
struct  einvalidvalue2453  {
  esynch2429 Sup;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  tcell41290  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq41306  {
NI Len;
NI Cap;
tcell41290** D;
};
struct  tcellset41302  {
NI Counter;
NI Max;
tpagedesc41298* Head;
tpagedesc41298** Data;
};
typedef tsmallchunk22838* TY23622[512];
typedef ttrunk22811* ttrunkbuckets22813[256];
struct  tintset22815  {
ttrunkbuckets22813 Data;
};
struct  tmemregion23610  {
NI Minlargeobj;
NI Maxlargeobj;
TY23622 Freesmallchunks;
tllchunk23604* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk22840* Freechunkslist;
tintset22815 Chunkstarts;
tavlnode23608* Root;
tavlnode23608* Deleted;
tavlnode23608* Last;
tavlnode23608* Freeavlnodes;
};
struct  tgcstat43214  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap43216  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq41306 Zct;
tcellseq41306 Decstack;
tcellset41302 Cycleroots;
tcellseq41306 Tempstack;
NI Recgclock;
tmemregion23610 Region;
tgcstat43214 Stat;
};
typedef NU8 TY741004[32];
typedef NI TY22818[8];
struct  tpagedesc41298  {
tpagedesc41298* Next;
NI Key;
TY22818 Bits;
};
struct  tbasechunk22836  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk22838  {
  tbasechunk22836 Sup;
tsmallchunk22838* Next;
tsmallchunk22838* Prev;
tfreecell22828* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk23604  {
NI Size;
NI Acc;
tllchunk23604* Next;
};
struct  tbigchunk22840  {
  tbasechunk22836 Sup;
tbigchunk22840* Next;
tbigchunk22840* Prev;
NI Align;
NF Data;
};
struct  ttrunk22811  {
ttrunk22811* Next;
NI Key;
TY22818 Bits;
};
typedef tavlnode23608* TY23614[2];
struct  tavlnode23608  {
TY23614 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell22828  {
tfreecell22828* Next;
NI Zerofield;
};
N_NIMCALL(NIM_CHAR, nsuToLowerChar)(NIM_CHAR c);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(NI, subInt)(NI a, NI b);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NI, npuParseInt)(NimStringDesc* s, NI* number, NI start);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell41290*, usrtocell_44643)(void* usr);
static N_INLINE(void, rtladdzct_46202)(tcell41290* c);
N_NOINLINE(void, addzct_44618)(tcellseq41306* s, tcell41290* c);
N_NIMCALL(void, raiseException)(E_Base* e, NCSTRING ename);
N_NIMCALL(NI, npuParseFloat)(NimStringDesc* s, NF* number, NI start);
static N_INLINE(NI64, addInt64)(NI64 a, NI64 b);
N_NIMCALL(NI, npuParseBiggestInt)(NimStringDesc* s, NI64* number, NI start);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
N_NIMCALL(void, nsuAddf)(NimStringDesc** s, NimStringDesc* formatstr, NimStringDesc** a, NI aLen0);
N_NOINLINE(void, invalidformatstring_100624)(void);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NI, mulInt)(NI a, NI b);
N_NIMCALL(NI, findnormalized_100597)(NimStringDesc* x, NimStringDesc** inarray, NI inarrayLen0);
N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_70824, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_NIMCALL(NI, nsuFindCharSet)(NimStringDesc* s, TY741004 chars, NI start);
STRING_LITERAL(TMP326, "invalid integer: ", 17);
STRING_LITERAL(TMP347, "invalid float: ", 15);
STRING_LITERAL(TMP351, "0123456789ABCDEF", 16);
STRING_LITERAL(TMP543, "invalid format string", 21);
extern TFrame* frameptr_13038;
extern TNimType NTI18001; /* ref EInvalidValue */
extern TNimType NTI2453; /* EInvalidValue */
extern tgcheap43216 gch_43244;

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_13038;
	frameptr_13038 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_13038 = (*frameptr_13038).prev;
}

N_NIMCALL(NIM_CHAR, nsuToLowerChar)(NIM_CHAR c) {
	NIM_CHAR result;
	nimfr("toLower", "strutils.nim")
	result = 0;
	nimln(62, "strutils.nim");
	{
		NI TMP139;
		nimln(62, "strutils.nim");
		if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA3;
		nimln(63, "strutils.nim");
		nimln(63, "strutils.nim");
		nimln(63, "strutils.nim");
		nimln(63, "strutils.nim");
		TMP139 = addInt(((NI) (((NU8)(c)))), 32);
		result = ((NIM_CHAR) (((NI)chckRange((NI64)(TMP139), 0, 255))));
	}
	goto LA1;
	LA3: ;
	{
		nimln(65, "strutils.nim");
		result = c;
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringDesc* a, NimStringDesc* b) {
	NI result;
	NI i;
	NI j;
	nimfr("cmpIgnoreStyle", "strutils.nim")
	result = 0;
	i = 0;
	j = 0;
	while (1) {
		NIM_CHAR aa;
		NIM_CHAR bb;
		while (1) {
			if (!((NU8)(a->data[i]) == (NU8)(95))) goto LA2;
			i += 1;
		} LA2: ;
		while (1) {
			if (!((NU8)(b->data[j]) == (NU8)(95))) goto LA3;
			j += 1;
		} LA3: ;
		aa = nsuToLowerChar(a->data[i]);
		bb = nsuToLowerChar(b->data[j]);
		result = (NI64)(((NI) (((NU8)(aa)))) - ((NI) (((NU8)(bb)))));
		{
			NIM_BOOL LOC6;
			LOC6 = 0;
			LOC6 = !((result == 0));
			if (LOC6) goto LA7;
			LOC6 = ((NU8)(aa) == (NU8)(0));
			LA7: ;
			if (!LOC6) goto LA8;
			goto LA1;
		}
		LA8: ;
		i += 1;
		j += 1;
	} LA1: ;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI64)((*dest).Sup.len + 1))- 0] = 0;
	(*dest).Sup.len += 1;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) (&(*dest).data[((*dest).Sup.len)- 0])), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(NimStringDesc*, nsuIntToStr)(NI x, NI minchars) {
	NimStringDesc* result;
	NI i_98116;
	NI HEX3Atmp_98118;
	NI TMP187;
	NI res_98120;
	nimfr("intToStr", "strutils.nim")
	result = 0;
	nimln(371, "strutils.nim");
	nimln(371, "strutils.nim");
	nimln(371, "strutils.nim");
	if (x == (IL64(-9223372036854775807) - IL64(1))) raiseOverflow();
	result = nimIntToStr((NI64)abs(x));
	i_98116 = 0;
	HEX3Atmp_98118 = 0;
	nimln(372, "strutils.nim");
	nimln(372, "strutils.nim");
	nimln(372, "strutils.nim");
	TMP187 = subInt(minchars, result->Sup.len);
	HEX3Atmp_98118 = (NI64)(TMP187);
	nimln(1458, "system.nim");
	res_98120 = 1;
	nimln(1459, "system.nim");
	while (1) {
		NimStringDesc* LOC2;
		nimln(1459, "system.nim");
		if (!(res_98120 <= HEX3Atmp_98118)) goto LA1;
		nimln(1458, "system.nim");
		i_98116 = res_98120;
		nimln(373, "strutils.nim");
		nimln(373, "strutils.nim");
		LOC2 = 0;
		LOC2 = rawNewString(result->Sup.len + 1);
appendChar(LOC2, 48);
appendString(LOC2, result);
		result = LOC2;
		nimln(1461, "system.nim");
		res_98120 = addInt(res_98120, 1);
	} LA1: ;
	nimln(374, "strutils.nim");
	{
		NimStringDesc* LOC7;
		nimln(374, "strutils.nim");
		if (!(x < 0)) goto LA5;
		nimln(375, "strutils.nim");
		nimln(375, "strutils.nim");
		LOC7 = 0;
		LOC7 = rawNewString(result->Sup.len + 1);
appendChar(LOC7, 45);
appendString(LOC7, result);
		result = LOC7;
	}
	LA5: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nsuRepeatChar)(NI count, NIM_CHAR c) {
	NimStringDesc* result;
	NI i_98463;
	NI HEX3Atmp_98464;
	NI TMP239;
	NI res_98466;
	nimfr("repeatChar", "strutils.nim")
	result = 0;
	nimln(464, "strutils.nim");
	nimln(464, "strutils.nim");
	result = mnewString(count);
	i_98463 = 0;
	HEX3Atmp_98464 = 0;
	nimln(465, "strutils.nim");
	nimln(465, "strutils.nim");
	TMP239 = subInt(count, 1);
	HEX3Atmp_98464 = (NI64)(TMP239);
	nimln(1458, "system.nim");
	res_98466 = 0;
	nimln(1459, "system.nim");
	while (1) {
		nimln(1459, "system.nim");
		if (!(res_98466 <= HEX3Atmp_98464)) goto LA1;
		nimln(1458, "system.nim");
		i_98463 = res_98466;
		nimln(465, "strutils.nim");
		if ((NU)(i_98463) > (NU)(result->Sup.len)) raiseIndexError();
		result->data[i_98463] = c;
		nimln(1461, "system.nim");
		res_98466 = addInt(res_98466, 1);
	} LA1: ;
	popFrame();
	return result;
}

static N_INLINE(tcell41290*, usrtocell_44643)(void* usr) {
	tcell41290* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell41290*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell41290))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_46202)(tcell41290* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_44618(&gch_43244.Zct, c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell41290* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_44643(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell41290* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_44643((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_46202(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s) {
	NI result;
	NI l;
	nimfr("parseInt", "strutils.nim")
	result = 0;
	nimln(381, "strutils.nim");
	l = npuParseInt(s, &result, 0);
	nimln(382, "strutils.nim");
	{
		NIM_BOOL LOC3;
		einvalidvalue2453* e_98133;
		NimStringDesc* LOC7;
		nimln(382, "strutils.nim");
		LOC3 = 0;
		nimln(382, "strutils.nim");
		nimln(382, "strutils.nim");
		nimln(382, "strutils.nim");
		LOC3 = !((l == s->Sup.len));
		if (LOC3) goto LA4;
		nimln(382, "strutils.nim");
		LOC3 = (l == 0);
		LA4: ;
		if (!LOC3) goto LA5;
		e_98133 = 0;
		nimln(1992, "system.nim");
		e_98133 = (einvalidvalue2453*) newObj((&NTI18001), sizeof(einvalidvalue2453));
		(*e_98133).Sup.Sup.Sup.m_type = (&NTI2453);
		nimln(1993, "system.nim");
		nimln(383, "strutils.nim");
		LOC7 = 0;
		LOC7 = rawNewString(s->Sup.len + 17);
appendString(LOC7, ((NimStringDesc*) &TMP326));
appendString(LOC7, s);
		asgnRefNoCycle((void**) &(*e_98133).Sup.Sup.message, LOC7);
		nimln(383, "strutils.nim");
		raiseException((E_Base*)e_98133, "EInvalidValue");
	}
	LA5: ;
	popFrame();
	return result;
}

N_NIMCALL(NF, nsuParseFloat)(NimStringDesc* s) {
	NF result;
	NI l;
	nimfr("parseFloat", "strutils.nim")
	result = 0;
	nimln(398, "strutils.nim");
	l = npuParseFloat(s, &result, 0);
	nimln(399, "strutils.nim");
	{
		NIM_BOOL LOC3;
		einvalidvalue2453* e_98191;
		NimStringDesc* LOC7;
		nimln(399, "strutils.nim");
		LOC3 = 0;
		nimln(399, "strutils.nim");
		nimln(399, "strutils.nim");
		nimln(399, "strutils.nim");
		LOC3 = !((l == s->Sup.len));
		if (LOC3) goto LA4;
		nimln(399, "strutils.nim");
		LOC3 = (l == 0);
		LA4: ;
		if (!LOC3) goto LA5;
		e_98191 = 0;
		nimln(1992, "system.nim");
		e_98191 = (einvalidvalue2453*) newObj((&NTI18001), sizeof(einvalidvalue2453));
		(*e_98191).Sup.Sup.Sup.m_type = (&NTI2453);
		nimln(1993, "system.nim");
		nimln(400, "strutils.nim");
		LOC7 = 0;
		LOC7 = rawNewString(s->Sup.len + 15);
appendString(LOC7, ((NimStringDesc*) &TMP347));
appendString(LOC7, s);
		asgnRefNoCycle((void**) &(*e_98191).Sup.Sup.message, LOC7);
		nimln(400, "strutils.nim");
		raiseException((E_Base*)e_98191, "EInvalidValue");
	}
	LA5: ;
	popFrame();
	return result;
}

static N_INLINE(NI64, addInt64)(NI64 a, NI64 b) {
	NI64 result;
	result = 0;
	result = (NI64)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI64)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI64)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(NimStringDesc*, nsuToHex)(NI64 x, NI len) {
	NimStringDesc* result;
	NI64 shift;
	NI j_98092;
	NI HEX3Atmp_98095;
	NI TMP350;
	NI res_98097;
	nimfr("toHex", "strutils.nim")
	result = 0;
	shift = 0;
	nimln(361, "strutils.nim");
	nimln(361, "strutils.nim");
	result = mnewString(len);
	j_98092 = 0;
	HEX3Atmp_98095 = 0;
	nimln(362, "strutils.nim");
	nimln(362, "strutils.nim");
	TMP350 = subInt(len, 1);
	HEX3Atmp_98095 = (NI64)(TMP350);
	nimln(1442, "system.nim");
	res_98097 = HEX3Atmp_98095;
	nimln(1443, "system.nim");
	while (1) {
		NI64 TMP352;
		nimln(1443, "system.nim");
		if (!(0 <= res_98097)) goto LA1;
		nimln(1442, "system.nim");
		j_98092 = res_98097;
		nimln(363, "strutils.nim");
		if ((NU)(j_98092) > (NU)(result->Sup.len)) raiseIndexError();
		nimln(363, "strutils.nim");
		nimln(363, "strutils.nim");
		nimln(363, "strutils.nim");
		if ((NU)((NI32)(((NI32)(NU32)(NU64)((NI64)((NU64)(x) >> (NU64)(shift)))) & ((NI32) 15))) > (NU)(((NimStringDesc*) &TMP351)->Sup.len)) raiseIndexError();
		result->data[j_98092] = ((NimStringDesc*) &TMP351)->data[(NI32)(((NI32)(NU32)(NU64)((NI64)((NU64)(x) >> (NU64)(shift)))) & ((NI32) 15))];
		nimln(364, "strutils.nim");
		nimln(364, "strutils.nim");
		TMP352 = addInt64(shift, 4);
		shift = (NI64)(TMP352);
		nimln(1445, "system.nim");
		res_98097 = subInt(res_98097, 1);
	} LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nsuToLowerStr)(NimStringDesc* s) {
	NimStringDesc* result;
	NI i_96884;
	NI HEX3Atmp_96885;
	NI TMP408;
	NI res_96887;
	nimfr("toLower", "strutils.nim")
	result = 0;
	nimln(71, "strutils.nim");
	nimln(71, "strutils.nim");
	nimln(71, "strutils.nim");
	result = mnewString(s->Sup.len);
	i_96884 = 0;
	HEX3Atmp_96885 = 0;
	nimln(72, "strutils.nim");
	nimln(72, "strutils.nim");
	nimln(72, "strutils.nim");
	TMP408 = subInt(s->Sup.len, 1);
	HEX3Atmp_96885 = (NI64)(TMP408);
	nimln(1458, "system.nim");
	res_96887 = 0;
	nimln(1459, "system.nim");
	while (1) {
		nimln(1459, "system.nim");
		if (!(res_96887 <= HEX3Atmp_96885)) goto LA1;
		nimln(1458, "system.nim");
		i_96884 = res_96887;
		nimln(73, "strutils.nim");
		if ((NU)(i_96884) > (NU)(result->Sup.len)) raiseIndexError();
		if ((NU)(i_96884) > (NU)(s->Sup.len)) raiseIndexError();
		result->data[i_96884] = nsuToLowerChar(s->data[i_96884]);
		nimln(1461, "system.nim");
		res_96887 = addInt(res_96887, 1);
	} LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, nsuParseHexInt)(NimStringDesc* s) {
	NI result;
	NI i;
	nimfr("parseHexInt", "strutils.nim")
	result = 0;
	nimln(408, "strutils.nim");
	i = 0;
	nimln(409, "strutils.nim");
	{
		NIM_BOOL LOC3;
		NIM_BOOL LOC5;
		NI TMP439;
		NI TMP440;
		nimln(409, "strutils.nim");
		LOC3 = 0;
		nimln(409, "strutils.nim");
		if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
		LOC3 = ((NU8)(s->data[i]) == (NU8)(48));
		if (!(LOC3)) goto LA4;
		nimln(409, "strutils.nim");
		LOC5 = 0;
		nimln(409, "strutils.nim");
		nimln(409, "strutils.nim");
		TMP439 = addInt(i, 1);
		if ((NU)((NI64)(TMP439)) > (NU)(s->Sup.len)) raiseIndexError();
		LOC5 = ((NU8)(s->data[(NI64)(TMP439)]) == (NU8)(120));
		if (LOC5) goto LA6;
		nimln(409, "strutils.nim");
		nimln(409, "strutils.nim");
		TMP440 = addInt(i, 1);
		if ((NU)((NI64)(TMP440)) > (NU)(s->Sup.len)) raiseIndexError();
		LOC5 = ((NU8)(s->data[(NI64)(TMP440)]) == (NU8)(88));
		LA6: ;
		LOC3 = LOC5;
		LA4: ;
		if (!LOC3) goto LA7;
		nimln(409, "strutils.nim");
		i = addInt(i, 2);
	}
	goto LA1;
	LA7: ;
	{
		nimln(410, "strutils.nim");
		if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
		if (!((NU8)(s->data[i]) == (NU8)(35))) goto LA10;
		nimln(410, "strutils.nim");
		i = addInt(i, 1);
	}
	goto LA1;
	LA10: ;
	LA1: ;
	nimln(411, "strutils.nim");
	while (1) {
		nimln(412, "strutils.nim");
		if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
		switch (((NU8)(s->data[i]))) {
		case 95:
		{
			nimln(413, "strutils.nim");
			i = addInt(i, 1);
		}
		break;
		case 48 ... 57:
		{
			NI TMP441;
			nimln(415, "strutils.nim");
			nimln(415, "strutils.nim");
			nimln(415, "strutils.nim");
			nimln(415, "strutils.nim");
			nimln(415, "strutils.nim");
			if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
			TMP441 = subInt(((NI) (((NU8)(s->data[i])))), 48);
			result = (NI)((NI)((NU64)(result) << (NU64)(4)) | ((NI) ((NI64)(TMP441))));
			nimln(416, "strutils.nim");
			i = addInt(i, 1);
		}
		break;
		case 97 ... 102:
		{
			NI TMP442;
			NI TMP443;
			nimln(418, "strutils.nim");
			nimln(418, "strutils.nim");
			nimln(418, "strutils.nim");
			nimln(418, "strutils.nim");
			nimln(418, "strutils.nim");
			nimln(418, "strutils.nim");
			if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
			TMP442 = subInt(((NI) (((NU8)(s->data[i])))), 97);
			TMP443 = addInt(((NI) ((NI64)(TMP442))), 10);
			result = (NI)((NI)((NU64)(result) << (NU64)(4)) | ((NI) ((NI64)(TMP443))));
			nimln(419, "strutils.nim");
			i = addInt(i, 1);
		}
		break;
		case 65 ... 70:
		{
			NI TMP444;
			NI TMP445;
			nimln(421, "strutils.nim");
			nimln(421, "strutils.nim");
			nimln(421, "strutils.nim");
			nimln(421, "strutils.nim");
			nimln(421, "strutils.nim");
			nimln(421, "strutils.nim");
			if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
			TMP444 = subInt(((NI) (((NU8)(s->data[i])))), 65);
			TMP445 = addInt(((NI) ((NI64)(TMP444))), 10);
			result = (NI)((NI)((NU64)(result) << (NU64)(4)) | ((NI) ((NI64)(TMP445))));
			nimln(422, "strutils.nim");
			i = addInt(i, 1);
		}
		break;
		case 0:
		{
			nimln(423, "strutils.nim");
			goto LA12;
		}
		break;
		default:
		{
			einvalidvalue2453* e_98370;
			NimStringDesc* LOC19;
			e_98370 = 0;
			nimln(1992, "system.nim");
			e_98370 = (einvalidvalue2453*) newObj((&NTI18001), sizeof(einvalidvalue2453));
			(*e_98370).Sup.Sup.Sup.m_type = (&NTI2453);
			nimln(1993, "system.nim");
			nimln(424, "strutils.nim");
			LOC19 = 0;
			LOC19 = rawNewString(s->Sup.len + 17);
appendString(LOC19, ((NimStringDesc*) &TMP326));
appendString(LOC19, s);
			asgnRefNoCycle((void**) &(*e_98370).Sup.Sup.message, LOC19);
			nimln(424, "strutils.nim");
			raiseException((E_Base*)e_98370, "EInvalidValue");
		}
		break;
		}
	} LA12: ;
	popFrame();
	return result;
}

N_NIMCALL(NI64, nsuParseBiggestInt)(NimStringDesc* s) {
	NI64 result;
	NI l;
	nimfr("parseBiggestInt", "strutils.nim")
	result = 0;
	nimln(389, "strutils.nim");
	l = npuParseBiggestInt(s, &result, 0);
	nimln(390, "strutils.nim");
	{
		NIM_BOOL LOC3;
		einvalidvalue2453* e_98162;
		NimStringDesc* LOC7;
		nimln(390, "strutils.nim");
		LOC3 = 0;
		nimln(390, "strutils.nim");
		nimln(390, "strutils.nim");
		nimln(390, "strutils.nim");
		LOC3 = !((l == s->Sup.len));
		if (LOC3) goto LA4;
		nimln(390, "strutils.nim");
		LOC3 = (l == 0);
		LA4: ;
		if (!LOC3) goto LA5;
		e_98162 = 0;
		nimln(1992, "system.nim");
		e_98162 = (einvalidvalue2453*) newObj((&NTI18001), sizeof(einvalidvalue2453));
		(*e_98162).Sup.Sup.Sup.m_type = (&NTI2453);
		nimln(1993, "system.nim");
		nimln(391, "strutils.nim");
		LOC7 = 0;
		LOC7 = rawNewString(s->Sup.len + 17);
appendString(LOC7, ((NimStringDesc*) &TMP326));
appendString(LOC7, s);
		asgnRefNoCycle((void**) &(*e_98162).Sup.Sup.message, LOC7);
		nimln(391, "strutils.nim");
		raiseException((E_Base*)e_98162, "EInvalidValue");
	}
	LA5: ;
	popFrame();
	return result;
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell41290* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_44643(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_46202(c);
	}
	LA3: ;
	popFrame();
}

N_NOINLINE(void, invalidformatstring_100624)(void) {
	einvalidvalue2453* e_100628;
	NimStringDesc* LOC1;
	nimfr("invalidFormatString", "strutils.nim")
	e_100628 = 0;
	nimln(1992, "system.nim");
	e_100628 = (einvalidvalue2453*) newObj((&NTI18001), sizeof(einvalidvalue2453));
	(*e_100628).Sup.Sup.Sup.m_type = (&NTI2453);
	nimln(1993, "system.nim");
	LOC1 = 0;
	LOC1 = (*e_100628).Sup.Sup.message; (*e_100628).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP543));
	if (LOC1) nimGCunrefNoCycle(LOC1);
	nimln(1140, "strutils.nim");
	raiseException((E_Base*)e_100628, "EInvalidValue");
	popFrame();
}

N_NIMCALL(NI, findnormalized_100597)(NimStringDesc* x, NimStringDesc** inarray, NI inarrayLen0) {
	NI result;
	NI i;
	nimfr("findNormalized", "strutils.nim")
	result = 0;
	nimln(1132, "strutils.nim");
	i = 0;
	nimln(1133, "strutils.nim");
	while (1) {
		nimln(1133, "strutils.nim");
		nimln(1133, "strutils.nim");
		if (!(i < (inarrayLen0-1))) goto LA1;
		nimln(1134, "strutils.nim");
		{
			NI LOC4;
			nimln(1134, "strutils.nim");
			nimln(1134, "strutils.nim");
			if ((NU)(i) >= (NU)(inarrayLen0)) raiseIndexError();
			LOC4 = 0;
			LOC4 = nsuCmpIgnoreStyle(x, inarray[i]);
			if (!(LOC4 == 0)) goto LA5;
			nimln(1134, "strutils.nim");
			nimln(1134, "strutils.nim");
			result = i;
			goto BeforeRet;
		}
		LA5: ;
		nimln(1135, "strutils.nim");
		i = addInt(i, 2);
	} LA1: ;
	nimln(1137, "strutils.nim");
	nimln(1137, "strutils.nim");
	result = -1;
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, nsuAddf)(NimStringDesc** s, NimStringDesc* formatstr, NimStringDesc** a, NI aLen0) {
	NI i;
	NI num;
	nimfr("addf", "strutils.nim")
	nimln(1146, "strutils.nim");
	i = 0;
	nimln(1147, "strutils.nim");
	num = 0;
	nimln(1148, "strutils.nim");
	while (1) {
		nimln(1148, "strutils.nim");
		nimln(1148, "strutils.nim");
		if (!(i < formatstr->Sup.len)) goto LA1;
		nimln(1149, "strutils.nim");
		{
			NI TMP542;
			nimln(1149, "strutils.nim");
			if ((NU)(i) > (NU)(formatstr->Sup.len)) raiseIndexError();
			if (!((NU8)(formatstr->data[i]) == (NU8)(36))) goto LA4;
			nimln(1150, "strutils.nim");
			nimln(1150, "strutils.nim");
			TMP542 = addInt(i, 1);
			if ((NU)((NI64)(TMP542)) > (NU)(formatstr->Sup.len)) raiseIndexError();
			switch (((NU8)(formatstr->data[(NI64)(TMP542)]))) {
			case 35:
			{
				nimln(1153, "strutils.nim");
				{
					nimln(1153, "strutils.nim");
					nimln(1153, "strutils.nim");
					if (!((NU64)((aLen0-1)) < (NU64)(num))) goto LA9;
					nimln(1153, "strutils.nim");
					invalidformatstring_100624();
				}
				LA9: ;
				nimln(1154, "strutils.nim");
				if ((NU)(num) >= (NU)(aLen0)) raiseIndexError();
				(*s) = resizeString((*s), a[num]->Sup.len + 0);
appendString((*s), a[num]);
				nimln(1155, "strutils.nim");
				i = addInt(i, 2);
				nimln(1156, "strutils.nim");
				num = addInt(num, 1);
			}
			break;
			case 36:
			{
				nimln(1158, "strutils.nim");
				(*s) = addChar((*s), 36);
				nimln(1159, "strutils.nim");
				i = addInt(i, 2);
			}
			break;
			case 49 ... 57:
			case 45:
			{
				NI j;
				NIM_BOOL negative;
				NI idx;
				nimln(1161, "strutils.nim");
				j = 0;
				nimln(1162, "strutils.nim");
				i = addInt(i, 1);
				nimln(1163, "strutils.nim");
				nimln(1163, "strutils.nim");
				if ((NU)(i) > (NU)(formatstr->Sup.len)) raiseIndexError();
				negative = ((NU8)(formatstr->data[i]) == (NU8)(45));
				nimln(1164, "strutils.nim");
				{
					if (!negative) goto LA15;
					nimln(1164, "strutils.nim");
					i = addInt(i, 1);
				}
				LA15: ;
				nimln(1165, "strutils.nim");
				while (1) {
					NI TMP544;
					NI TMP545;
					NI TMP546;
					nimln(1165, "strutils.nim");
					if ((NU)(i) > (NU)(formatstr->Sup.len)) raiseIndexError();
					if (!(((NU8)(formatstr->data[i])) >= ((NU8)(48)) && ((NU8)(formatstr->data[i])) <= ((NU8)(57)))) goto LA17;
					nimln(1166, "strutils.nim");
					nimln(1166, "strutils.nim");
					nimln(1166, "strutils.nim");
					nimln(1166, "strutils.nim");
					TMP544 = mulInt(j, 10);
					nimln(1166, "strutils.nim");
					if ((NU)(i) > (NU)(formatstr->Sup.len)) raiseIndexError();
					TMP545 = addInt((NI64)(TMP544), ((NI) (((NU8)(formatstr->data[i])))));
					TMP546 = subInt((NI64)(TMP545), 48);
					j = (NI64)(TMP546);
					nimln(1167, "strutils.nim");
					i = addInt(i, 1);
				} LA17: ;
				nimln(1168, "strutils.nim");
				nimln(1168, "strutils.nim");
				{
					NI TMP547;
					nimln(1168, "strutils.nim");
					if (!!(negative)) goto LA20;
					nimln(1168, "strutils.nim");
					TMP547 = subInt(j, 1);
					idx = (NI64)(TMP547);
				}
				goto LA18;
				LA20: ;
				{
					NI TMP548;
					nimln(1168, "strutils.nim");
					nimln(1168, "strutils.nim");
					TMP548 = subInt(aLen0, j);
					idx = (NI64)(TMP548);
				}
				LA18: ;
				nimln(1169, "strutils.nim");
				{
					nimln(1169, "strutils.nim");
					nimln(1169, "strutils.nim");
					if (!((NU64)((aLen0-1)) < (NU64)(idx))) goto LA25;
					nimln(1169, "strutils.nim");
					invalidformatstring_100624();
				}
				LA25: ;
				nimln(1170, "strutils.nim");
				if ((NU)(idx) >= (NU)(aLen0)) raiseIndexError();
				(*s) = resizeString((*s), a[idx]->Sup.len + 0);
appendString((*s), a[idx]);
			}
			break;
			case 123:
			{
				NI j;
				NI TMP549;
				NI x;
				NI TMP550;
				NI TMP551;
				NimStringDesc* LOC29;
				NI TMP553;
				nimln(1172, "strutils.nim");
				nimln(1172, "strutils.nim");
				TMP549 = addInt(i, 1);
				j = (NI64)(TMP549);
				nimln(1173, "strutils.nim");
				while (1) {
					nimln(1173, "strutils.nim");
					nimln(1173, "strutils.nim");
					if ((NU)(j) > (NU)(formatstr->Sup.len)) raiseIndexError();
					if (!!((((NU8)(formatstr->data[j])) == ((NU8)(0)) || ((NU8)(formatstr->data[j])) == ((NU8)(125))))) goto LA28;
					nimln(1173, "strutils.nim");
					j = addInt(j, 1);
				} LA28: ;
				nimln(1174, "strutils.nim");
				nimln(1174, "strutils.nim");
				nimln(1174, "strutils.nim");
				TMP550 = addInt(i, 2);
				nimln(1174, "strutils.nim");
				TMP551 = subInt(j, 1);
				LOC29 = 0;
				LOC29 = copyStrLast(formatstr, (NI64)(TMP550), (NI64)(TMP551));
				x = findnormalized_100597(LOC29, a, aLen0);
				nimln(1175, "strutils.nim");
				{
					NIM_BOOL LOC32;
					NI TMP552;
					nimln(1175, "strutils.nim");
					LOC32 = 0;
					nimln(1175, "strutils.nim");
					LOC32 = (0 <= x);
					if (!(LOC32)) goto LA33;
					nimln(1175, "strutils.nim");
					nimln(1175, "strutils.nim");
					LOC32 = (x < (aLen0-1));
					LA33: ;
					if (!LOC32) goto LA34;
					nimln(1175, "strutils.nim");
					nimln(1175, "strutils.nim");
					TMP552 = addInt(x, 1);
					if ((NU)((NI64)(TMP552)) >= (NU)(aLen0)) raiseIndexError();
					(*s) = resizeString((*s), a[(NI64)(TMP552)]->Sup.len + 0);
appendString((*s), a[(NI64)(TMP552)]);
				}
				goto LA30;
				LA34: ;
				{
					nimln(1176, "strutils.nim");
					invalidformatstring_100624();
				}
				LA30: ;
				nimln(1177, "strutils.nim");
				nimln(1177, "strutils.nim");
				TMP553 = addInt(j, 1);
				i = (NI64)(TMP553);
			}
			break;
			case 97 ... 122:
			case 65 ... 90:
			case 128 ... 255:
			case 95:
			{
				NI j;
				NI TMP554;
				NI x;
				NI TMP555;
				NI TMP556;
				NimStringDesc* LOC39;
				nimln(1179, "strutils.nim");
				nimln(1179, "strutils.nim");
				TMP554 = addInt(i, 1);
				j = (NI64)(TMP554);
				nimln(1180, "strutils.nim");
				while (1) {
					nimln(1180, "strutils.nim");
					if ((NU)(j) > (NU)(formatstr->Sup.len)) raiseIndexError();
					if (!(((NU8)(formatstr->data[j])) >= ((NU8)(97)) && ((NU8)(formatstr->data[j])) <= ((NU8)(122)) || ((NU8)(formatstr->data[j])) >= ((NU8)(65)) && ((NU8)(formatstr->data[j])) <= ((NU8)(90)) || ((NU8)(formatstr->data[j])) >= ((NU8)(48)) && ((NU8)(formatstr->data[j])) <= ((NU8)(57)) || ((NU8)(formatstr->data[j])) >= ((NU8)(128)) && ((NU8)(formatstr->data[j])) <= ((NU8)(255)) || ((NU8)(formatstr->data[j])) == ((NU8)(95)))) goto LA38;
					nimln(1180, "strutils.nim");
					j = addInt(j, 1);
				} LA38: ;
				nimln(1181, "strutils.nim");
				nimln(1181, "strutils.nim");
				nimln(1181, "strutils.nim");
				TMP555 = addInt(i, 1);
				nimln(1181, "strutils.nim");
				TMP556 = subInt(j, 1);
				LOC39 = 0;
				LOC39 = copyStrLast(formatstr, (NI64)(TMP555), (NI64)(TMP556));
				x = findnormalized_100597(LOC39, a, aLen0);
				nimln(1182, "strutils.nim");
				{
					NIM_BOOL LOC42;
					NI TMP557;
					nimln(1182, "strutils.nim");
					LOC42 = 0;
					nimln(1182, "strutils.nim");
					LOC42 = (0 <= x);
					if (!(LOC42)) goto LA43;
					nimln(1182, "strutils.nim");
					nimln(1182, "strutils.nim");
					LOC42 = (x < (aLen0-1));
					LA43: ;
					if (!LOC42) goto LA44;
					nimln(1182, "strutils.nim");
					nimln(1182, "strutils.nim");
					TMP557 = addInt(x, 1);
					if ((NU)((NI64)(TMP557)) >= (NU)(aLen0)) raiseIndexError();
					(*s) = resizeString((*s), a[(NI64)(TMP557)]->Sup.len + 0);
appendString((*s), a[(NI64)(TMP557)]);
				}
				goto LA40;
				LA44: ;
				{
					nimln(1183, "strutils.nim");
					invalidformatstring_100624();
				}
				LA40: ;
				nimln(1184, "strutils.nim");
				i = j;
			}
			break;
			default:
			{
				nimln(1186, "strutils.nim");
				invalidformatstring_100624();
			}
			break;
			}
		}
		goto LA2;
		LA4: ;
		{
			nimln(1188, "strutils.nim");
			if ((NU)(i) > (NU)(formatstr->Sup.len)) raiseIndexError();
			(*s) = addChar((*s), formatstr->data[i]);
			nimln(1189, "strutils.nim");
			i = addInt(i, 1);
		}
		LA2: ;
	} LA1: ;
	popFrame();
}

N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr, NimStringDesc** a, NI aLen0) {
	NimStringDesc* result;
	NI TMP541;
	nimfr("%", "strutils.nim")
	result = 0;
	nimln(1231, "strutils.nim");
	nimln(1231, "strutils.nim");
	nimln(1231, "strutils.nim");
	nimln(1231, "strutils.nim");
	nimln(1231, "strutils.nim");
	nimln(1231, "strutils.nim");
	TMP541 = addInt(formatstr->Sup.len, (NI)((NU64)(aLen0) << (NU64)(4)));
	result = rawNewString((NI64)(TMP541));
	nimln(1232, "strutils.nim");
	nsuAddf(&result, formatstr, a, aLen0);
	popFrame();
	return result;
}

N_NIMCALL(NI, nsuFindCharSet)(NimStringDesc* s, TY741004 chars, NI start) {
	NI result;
	NI i_99175;
	NI HEX3Atmp_99189;
	NI TMP571;
	NI res_99191;
	nimfr("find", "strutils.nim")
	result = 0;
	i_99175 = 0;
	HEX3Atmp_99189 = 0;
	nimln(724, "strutils.nim");
	nimln(724, "strutils.nim");
	nimln(724, "strutils.nim");
	TMP571 = subInt(s->Sup.len, 1);
	HEX3Atmp_99189 = (NI64)(TMP571);
	nimln(1458, "system.nim");
	res_99191 = start;
	nimln(1459, "system.nim");
	while (1) {
		nimln(1459, "system.nim");
		if (!(res_99191 <= HEX3Atmp_99189)) goto LA1;
		nimln(1458, "system.nim");
		i_99175 = res_99191;
		nimln(725, "strutils.nim");
		{
			nimln(725, "strutils.nim");
			if ((NU)(i_99175) > (NU)(s->Sup.len)) raiseIndexError();
			if (!((chars[((NU8)(s->data[i_99175]))/8] &(1<<(((NU8)(s->data[i_99175]))%8)))!=0)) goto LA4;
			nimln(725, "strutils.nim");
			nimln(725, "strutils.nim");
			result = i_99175;
			goto BeforeRet;
		}
		LA4: ;
		nimln(1461, "system.nim");
		res_99191 = addInt(res_99191, 1);
	} LA1: ;
	nimln(726, "strutils.nim");
	nimln(726, "strutils.nim");
	result = -1;
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, contains_99258)(NimStringDesc* s, TY741004 chars) {
	NIM_BOOL result;
	NI LOC1;
	nimfr("contains", "strutils.nim")
	result = 0;
	nimln(762, "strutils.nim");
	nimln(762, "strutils.nim");
	nimln(762, "strutils.nim");
	nimln(762, "strutils.nim");
	LOC1 = 0;
	LOC1 = nsuFindCharSet(s, chars, 0);
	result = (0 <= LOC1);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, nsuStartsWith)(NimStringDesc* s, NimStringDesc* prefix) {
	NIM_BOOL result;
	NI i;
	nimfr("startsWith", "strutils.nim")
	result = 0;
	nimln(588, "strutils.nim");
	i = 0;
	nimln(589, "strutils.nim");
	while (1) {
		nimln(590, "strutils.nim");
		{
			nimln(590, "strutils.nim");
			if ((NU)(i) > (NU)(prefix->Sup.len)) raiseIndexError();
			if (!((NU8)(prefix->data[i]) == (NU8)(0))) goto LA4;
			nimln(590, "strutils.nim");
			nimln(590, "strutils.nim");
			result = NIM_TRUE;
			goto BeforeRet;
		}
		LA4: ;
		nimln(591, "strutils.nim");
		{
			nimln(591, "strutils.nim");
			nimln(591, "strutils.nim");
			if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
			if ((NU)(i) > (NU)(prefix->Sup.len)) raiseIndexError();
			if (!!(((NU8)(s->data[i]) == (NU8)(prefix->data[i])))) goto LA8;
			nimln(591, "strutils.nim");
			nimln(591, "strutils.nim");
			result = NIM_FALSE;
			goto BeforeRet;
		}
		LA8: ;
		nimln(592, "strutils.nim");
		i = addInt(i, 1);
	}
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, nsuFindChar)(NimStringDesc* s, NIM_CHAR sub, NI start) {
	NI result;
	NI i_99150;
	NI HEX3Atmp_99151;
	NI TMP667;
	NI res_99153;
	nimfr("find", "strutils.nim")
	result = 0;
	i_99150 = 0;
	HEX3Atmp_99151 = 0;
	nimln(716, "strutils.nim");
	nimln(716, "strutils.nim");
	nimln(716, "strutils.nim");
	TMP667 = subInt(s->Sup.len, 1);
	HEX3Atmp_99151 = (NI64)(TMP667);
	nimln(1458, "system.nim");
	res_99153 = start;
	nimln(1459, "system.nim");
	while (1) {
		nimln(1459, "system.nim");
		if (!(res_99153 <= HEX3Atmp_99151)) goto LA1;
		nimln(1458, "system.nim");
		i_99150 = res_99153;
		nimln(717, "strutils.nim");
		{
			nimln(717, "strutils.nim");
			if ((NU)(i_99150) > (NU)(s->Sup.len)) raiseIndexError();
			if (!((NU8)(sub) == (NU8)(s->data[i_99150]))) goto LA4;
			nimln(717, "strutils.nim");
			nimln(717, "strutils.nim");
			result = i_99150;
			goto BeforeRet;
		}
		LA4: ;
		nimln(1461, "system.nim");
		res_99153 = addInt(res_99153, 1);
	} LA1: ;
	nimln(718, "strutils.nim");
	nimln(718, "strutils.nim");
	result = -1;
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}
N_NOINLINE(void, strutilsInit)(void) {
	nimfr("strutils", "strutils.nim")
	popFrame();
}

N_NOINLINE(void, strutilsDatInit)(void) {
}

