/* Generated by Nimrod Compiler v0.9.5 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nimrod -o /home/andreysh/Projects/nimrod/stone_head/nimcache/tables.o /home/andreysh/Projects/nimrod/stone_head/nimcache/tables.c */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
static N_INLINE(NIM_BOOL, mustrehash_782414)(NI length, NI counter);
N_NIMCALL(void, failedassertimpl_79821)(NimStringDesc* msg);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, nexttry_782606)(NI h, NI maxhash);
static N_INLINE(NI, addInt)(NI a, NI b);
STRING_LITERAL(TMP650, "length > counter ", 17);
extern TFrame* frameptr_13038;

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_13038;
	frameptr_13038 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_13038 = (*frameptr_13038).prev;
}

static N_INLINE(NIM_BOOL, mustrehash_782414)(NI length, NI counter) {
	NIM_BOOL result;
	NIM_BOOL LOC5;
	NI TMP651;
	NI TMP652;
	NI TMP653;
	nimfr("mustRehash", "tables.nim")
	result = 0;
	nimln(107, "tables.nim");
	{
		nimln(107, "tables.nim");
		nimln(107, "tables.nim");
		if (!!((counter < length))) goto LA3;
		nimln(107, "tables.nim");
		failedassertimpl_79821(((NimStringDesc*) &TMP650));
	}
	LA3: ;
	nimln(108, "tables.nim");
	nimln(108, "tables.nim");
	LOC5 = 0;
	nimln(108, "tables.nim");
	nimln(108, "tables.nim");
	TMP651 = mulInt(length, 2);
	nimln(108, "tables.nim");
	TMP652 = mulInt(counter, 3);
	LOC5 = ((NI64)(TMP651) < (NI64)(TMP652));
	if (LOC5) goto LA6;
	nimln(108, "tables.nim");
	nimln(108, "tables.nim");
	TMP653 = subInt(length, counter);
	LOC5 = ((NI64)(TMP653) < 4);
	LA6: ;
	result = LOC5;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, nexttry_782606)(NI h, NI maxhash) {
	NI result;
	NI TMP654;
	NI TMP655;
	nimfr("nextTry", "tables.nim")
	result = 0;
	nimln(111, "tables.nim");
	nimln(111, "tables.nim");
	nimln(111, "tables.nim");
	nimln(111, "tables.nim");
	TMP654 = mulInt(5, h);
	TMP655 = addInt((NI64)(TMP654), 1);
	result = (NI)((NI64)(TMP655) & maxhash);
	popFrame();
	return result;
}
N_NOINLINE(void, tablesInit)(void) {
	nimfr("tables", "tables.nim")
	popFrame();
}

N_NOINLINE(void, tablesDatInit)(void) {
}

