/* Generated by Nimrod Compiler v0.9.5 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nimrod -o /home/andreysh/Projects/nimrod/stone_head/nimcache/times.o /home/andreysh/Projects/nimrod/stone_head/nimcache/times.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <time.h>

#include <sys/time.h>

#include <string.h>

#include <sys/select.h>
typedef struct ttimeinterval714005 ttimeinterval714005;
typedef struct ttimeinfo714003 ttimeinfo714003;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY714103 TY714103;
typedef struct tslice79092 tslice79092;
typedef struct einvalidvalue2453 einvalidvalue2453;
typedef struct esynch2429 esynch2429;
typedef struct E_Base E_Base;
typedef struct tcell41290 tcell41290;
typedef struct tcellseq41306 tcellseq41306;
typedef struct tgcheap43216 tgcheap43216;
typedef struct tcellset41302 tcellset41302;
typedef struct tpagedesc41298 tpagedesc41298;
typedef struct tmemregion23610 tmemregion23610;
typedef struct tsmallchunk22838 tsmallchunk22838;
typedef struct tllchunk23604 tllchunk23604;
typedef struct tbigchunk22840 tbigchunk22840;
typedef struct tintset22815 tintset22815;
typedef struct ttrunk22811 ttrunk22811;
typedef struct tavlnode23608 tavlnode23608;
typedef struct tgcstat43214 tgcstat43214;
typedef struct tbasechunk22836 tbasechunk22836;
typedef struct tfreecell22828 tfreecell22828;
struct  ttimeinterval714005  {
NI Miliseconds;
NI Seconds;
NI Minutes;
NI Hours;
NI Days;
NI Months;
NI Years;
};
typedef N_NIMCALL_PTR(void, TY2289) (void* p, NI op);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY2289 marker;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  ttimeinfo714003  {
  TNimObject Sup;
NI Second;
NI Minute;
NI Hour;
NI Monthday;
NU8 Month;
NI Year;
NU8 Weekday;
NI Yearday;
NIM_BOOL Isdst;
NimStringDesc* Tzname;
NI Timezone;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NU8 TY714650[7];
struct TY714103 {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
typedef NI8 TY714669[7];
typedef NimStringDesc* TY715829[7];
typedef NimStringDesc* TY715841[12];
struct  tslice79092  {
NI A;
NI B;
};
struct  E_Base  {
  TNimObject Sup;
E_Base* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  esynch2429  {
  E_Base Sup;
};
struct  einvalidvalue2453  {
  esynch2429 Sup;
};
struct  tcell41290  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq41306  {
NI Len;
NI Cap;
tcell41290** D;
};
struct  tcellset41302  {
NI Counter;
NI Max;
tpagedesc41298* Head;
tpagedesc41298** Data;
};
typedef tsmallchunk22838* TY23622[512];
typedef ttrunk22811* ttrunkbuckets22813[256];
struct  tintset22815  {
ttrunkbuckets22813 Data;
};
struct  tmemregion23610  {
NI Minlargeobj;
NI Maxlargeobj;
TY23622 Freesmallchunks;
tllchunk23604* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk22840* Freechunkslist;
tintset22815 Chunkstarts;
tavlnode23608* Root;
tavlnode23608* Deleted;
tavlnode23608* Last;
tavlnode23608* Freeavlnodes;
};
struct  tgcstat43214  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap43216  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq41306 Zct;
tcellseq41306 Decstack;
tcellset41302 Cycleroots;
tcellseq41306 Tempstack;
NI Recgclock;
tmemregion23610 Region;
tgcstat43214 Stat;
};
typedef NI TY22818[8];
struct  tpagedesc41298  {
tpagedesc41298* Next;
NI Key;
TY22818 Bits;
};
struct  tbasechunk22836  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk22838  {
  tbasechunk22836 Sup;
tsmallchunk22838* Next;
tsmallchunk22838* Prev;
tfreecell22828* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk23604  {
NI Size;
NI Acc;
tllchunk23604* Next;
};
struct  tbigchunk22840  {
  tbasechunk22836 Sup;
tbigchunk22840* Next;
tbigchunk22840* Prev;
NI Align;
NF Data;
};
struct  ttrunk22811  {
ttrunk22811* Next;
NI Key;
TY22818 Bits;
};
typedef tavlnode23608* TY23614[2];
struct  tavlnode23608  {
TY23614 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell22828  {
tfreecell22828* Next;
NI Zerofield;
};
N_NIMCALL(time_t, fromseconds_714054)(NI64 since1970);
N_NIMCALL(NIM_BOOL, ntLtTime)(time_t a, time_t b);
N_NIMCALL(NIM_BOOL, ntLeTime)(time_t a, time_t b);
N_NIMCALL(NIM_BOOL, ntEqTime)(time_t a, time_t b);
N_NIMCALL(ttimeinterval714005, initinterval_714208)(NI miliseconds, NI seconds, NI minutes, NI hours, NI days, NI months, NI years);
N_NIMCALL(NIM_BOOL, isleapyear_714220)(NI year);
N_NIMCALL(NI, getdaysinmonth_714231)(NU8 month, NI year);
static N_INLINE(void, HEX2BHEX3D_714271)(NF* x_714277, NF y_714280);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NF, toseconds_714238)(ttimeinfo714003* a, ttimeinterval714005* interval);
N_NIMCALL(void, genericAssign)(void* dest, void* src, TNimType* mt);
static N_INLINE(NF, HEX2F_79038)(NI x, NI y);
N_NIMCALL(void, HEX2B_714403)(ttimeinfo714003* a, ttimeinterval714005* interval, ttimeinfo714003* Result);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, HEX2D_714412)(ttimeinfo714003* a, ttimeinterval714005* interval, ttimeinfo714003* Result);
N_NIMCALL(void, tmtotimeinfo_714644)(struct tm* tm, NIM_BOOL local, ttimeinfo714003* Result);
N_NIMCALL(void, gettzname_714101)(TY714103* Result);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NI, gettimezone_714202)(void);
N_NIMCALL(void, genericShallowAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(struct tm, timeinfototm_714664)(ttimeinfo714003* t);
N_NIMCALL(NI64, ntDiffTime)(time_t a, time_t b);
N_NIMCALL(NI, getstartmilsecs_714205)(void);
N_NIMCALL(time_t, gettime_714035)(void);
N_NIMCALL(void, getlocaltime_714038)(time_t t, ttimeinfo714003* Result);
N_NIMCALL(void, getgmtime_714042)(time_t t, ttimeinfo714003* Result);
N_NIMCALL(time_t, timeinfototime_714046)(ttimeinfo714003* timeinfo);
N_NIMCALL(NimStringDesc*, tostringtillnl_715227)(NCSTRING p);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, HEX24_714065)(ttimeinfo714003* timeinfo);
N_NIMCALL(NimStringDesc*, HEX24_714069)(time_t time);
N_NIMCALL(NI64, unixtimetowintime_715265)(time_t t);
N_NIMCALL(time_t, wintimetounixtime_715271)(NI64 t);
N_NIMCALL(time_t, fromseconds_714050)(NF since1970);
N_NIMCALL(NF, toseconds_714061)(time_t time);
N_NIMCALL(NF, ntepochTime)(void);
N_NIMCALL(NF, ntcpuTime)(void);
N_NIMCALL(NimStringDesc*, ntgetDateStr)(void);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, nsuIntToStr)(NI x, NI minchars);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, ntgetClockStr)(void);
N_NIMCALL(NimStringDesc*, HEX24_715824)(NU8 day);
N_NIMCALL(NimStringDesc*, HEX24_715836)(NU8 m);
N_NIMCALL(void, formattoken_715848)(ttimeinfo714003* info, NimStringDesc* token, NimStringDesc** buf);
N_NIMCALL(NI, hashString)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
static N_INLINE(NimStringDesc*, HEX5BHEX5D_79085)(NimStringDesc* s, tslice79092 x);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_70824, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(tslice79092, HEX2EHEX2E_95022)(NI a_95026, NI b_95028);
N_NIMCALL(NimStringDesc*, nsuRepeatChar)(NI count, NIM_CHAR c);
N_NIMCALL(void, insert_80801)(NimStringDesc** x, NimStringDesc* item, NI i);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell41290*, usrtocell_44643)(void* usr);
static N_INLINE(void, rtladdzct_46202)(tcell41290* c);
N_NOINLINE(void, addzct_44618)(tcellseq41306* s, tcell41290* c);
N_NIMCALL(void, raiseException)(E_Base* e, NCSTRING ename);
N_NIMCALL(NimStringDesc*, format_715999)(ttimeinfo714003* info, NimStringDesc* f);
STRING_LITERAL(TMP185, "UTC", 3);
NIM_CONST TY714650 weekdays_714649 = {((NU8) 6),
((NU8) 0),
((NU8) 1),
((NU8) 2),
((NU8) 3),
((NU8) 4),
((NU8) 5)}
;
NIM_CONST TY714669 weekdays_714668 = {((NI8) 1),
((NI8) 2),
((NI8) 3),
((NI8) 4),
((NI8) 5),
((NI8) 6),
((NI8) 0)}
;
STRING_LITERAL(TMP186, "", 0);
STRING_LITERAL(TMP188, "Monday", 6);
STRING_LITERAL(TMP189, "Tuesday", 7);
STRING_LITERAL(TMP190, "Wednesday", 9);
STRING_LITERAL(TMP191, "Thursday", 8);
STRING_LITERAL(TMP192, "Friday", 6);
STRING_LITERAL(TMP193, "Saturday", 8);
STRING_LITERAL(TMP194, "Sunday", 6);
NIM_CONST TY715829 lookup_715828 = {((NimStringDesc*) &TMP188),
((NimStringDesc*) &TMP189),
((NimStringDesc*) &TMP190),
((NimStringDesc*) &TMP191),
((NimStringDesc*) &TMP192),
((NimStringDesc*) &TMP193),
((NimStringDesc*) &TMP194)}
;
STRING_LITERAL(TMP195, "January", 7);
STRING_LITERAL(TMP196, "February", 8);
STRING_LITERAL(TMP197, "March", 5);
STRING_LITERAL(TMP198, "April", 5);
STRING_LITERAL(TMP199, "May", 3);
STRING_LITERAL(TMP200, "June", 4);
STRING_LITERAL(TMP201, "July", 4);
STRING_LITERAL(TMP202, "August", 6);
STRING_LITERAL(TMP203, "September", 9);
STRING_LITERAL(TMP204, "October", 7);
STRING_LITERAL(TMP205, "November", 8);
STRING_LITERAL(TMP206, "December", 8);
NIM_CONST TY715841 lookup_715840 = {((NimStringDesc*) &TMP195),
((NimStringDesc*) &TMP196),
((NimStringDesc*) &TMP197),
((NimStringDesc*) &TMP198),
((NimStringDesc*) &TMP199),
((NimStringDesc*) &TMP200),
((NimStringDesc*) &TMP201),
((NimStringDesc*) &TMP202),
((NimStringDesc*) &TMP203),
((NimStringDesc*) &TMP204),
((NimStringDesc*) &TMP205),
((NimStringDesc*) &TMP206)}
;
STRING_LITERAL(TMP207, "d", 1);
STRING_LITERAL(TMP208, "dd", 2);
STRING_LITERAL(TMP209, "ddd", 3);
STRING_LITERAL(TMP210, "dddd", 4);
STRING_LITERAL(TMP211, "h", 1);
STRING_LITERAL(TMP212, "hh", 2);
STRING_LITERAL(TMP213, "H", 1);
STRING_LITERAL(TMP214, "HH", 2);
STRING_LITERAL(TMP215, "m", 1);
STRING_LITERAL(TMP216, "mm", 2);
STRING_LITERAL(TMP217, "M", 1);
STRING_LITERAL(TMP218, "MM", 2);
STRING_LITERAL(TMP219, "MMM", 3);
STRING_LITERAL(TMP220, "MMMM", 4);
STRING_LITERAL(TMP221, "s", 1);
STRING_LITERAL(TMP222, "ss", 2);
STRING_LITERAL(TMP223, "t", 1);
STRING_LITERAL(TMP224, "tt", 2);
STRING_LITERAL(TMP225, "y", 1);
STRING_LITERAL(TMP226, "yy", 2);
STRING_LITERAL(TMP227, "yyy", 3);
STRING_LITERAL(TMP228, "yyyy", 4);
STRING_LITERAL(TMP229, "yyyyy", 5);
STRING_LITERAL(TMP230, "z", 1);
STRING_LITERAL(TMP231, "zz", 2);
STRING_LITERAL(TMP232, "zzz", 3);
STRING_LITERAL(TMP233, "ZZZ", 3);
STRING_LITERAL(TMP234, "0", 1);
STRING_LITERAL(TMP237, "PM", 2);
STRING_LITERAL(TMP238, "AM", 2);
STRING_LITERAL(TMP240, ":00", 3);
STRING_LITERAL(TMP241, "Invalid format string: ", 23);
extern TFrame* frameptr_13038;
extern TNimType NTI2409; /* TObject */
TNimType NTI714003; /* TTimeInfo */
extern TNimType NTI106; /* int */
TNimType NTI714006; /* range 0..61(int) */
TNimType NTI714008; /* range 0..59(int) */
TNimType NTI714010; /* range 0..23(int) */
TNimType NTI714012; /* range 1..31(int) */
TNimType NTI713804; /* TMonth */
TNimType NTI714015; /* range -10000..10000(int) */
TNimType NTI713806; /* TWeekDay */
TNimType NTI714021; /* range 0..365(int) */
extern TNimType NTI134; /* bool */
extern TNimType NTI143; /* string */
extern TNimType NTI18001; /* ref EInvalidValue */
extern TNimType NTI2453; /* EInvalidValue */
extern tgcheap43216 gch_43244;

N_NIMCALL(time_t, fromseconds_714054)(NI64 since1970) {
	time_t result;
	result = 0;
	result = fromseconds_714050(((NF) (since1970)));
	return result;
}

N_NIMCALL(NIM_BOOL, ntLtTime)(time_t a, time_t b) {
	NIM_BOOL result;
	NI64 LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = ntDiffTime(a, b);
	result = (LOC1 < 0);
	return result;
}

N_NIMCALL(NIM_BOOL, ntLeTime)(time_t a, time_t b) {
	NIM_BOOL result;
	NI64 LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = ntDiffTime(a, b);
	result = (LOC1 <= 0);
	return result;
}

N_NIMCALL(NIM_BOOL, ntEqTime)(time_t a, time_t b) {
	NIM_BOOL result;
	NI64 LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = ntDiffTime(a, b);
	result = (LOC1 == 0);
	return result;
}

N_NIMCALL(ttimeinterval714005, initinterval_714208)(NI miliseconds, NI seconds, NI minutes, NI hours, NI days, NI months, NI years) {
	ttimeinterval714005 result;
	memset((void*)&result, 0, sizeof(result));
	result.Miliseconds = miliseconds;
	result.Seconds = seconds;
	result.Minutes = minutes;
	result.Hours = hours;
	result.Days = days;
	result.Months = months;
	result.Years = years;
	return result;
}

N_NIMCALL(NIM_BOOL, isleapyear_714220)(NI year) {
	NIM_BOOL result;
	result = 0;
	{
		if (!(((NI) ((NI64)(year % 400))) == 0)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	goto LA1;
	LA3: ;
	{
		if (!(((NI) ((NI64)(year % 100))) == 0)) goto LA6;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	goto LA1;
	LA6: ;
	{
		if (!(((NI) ((NI64)(year % 4))) == 0)) goto LA9;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	goto LA1;
	LA9: ;
	{
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA1: ;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, getdaysinmonth_714231)(NU8 month, NI year) {
	NI result;
	result = 0;
	switch (month) {
	case ((NU8) 1):
	{
		{
			NIM_BOOL LOC4;
			LOC4 = 0;
			LOC4 = isleapyear_714220(year);
			if (!LOC4) goto LA5;
			result = 29;
		}
		goto LA2;
		LA5: ;
		{
			result = 28;
		}
		LA2: ;
	}
	break;
	case ((NU8) 3):
	case ((NU8) 5):
	case ((NU8) 8):
	case ((NU8) 10):
	{
		result = 30;
	}
	break;
	default:
	{
		result = 31;
	}
	break;
	}
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_13038;
	frameptr_13038 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_13038 = (*frameptr_13038).prev;
}

static N_INLINE(void, HEX2BHEX3D_714271)(NF* x_714277, NF y_714280) {
	nimfr("+=", "system.nim")
	nimln(2706, "system.nim");
	nimln(2706, "system.nim");
	(*x_714277) = ((NF)((*x_714277)) + (NF)(y_714280));
	popFrame();
}

static N_INLINE(NF, HEX2F_79038)(NI x, NI y) {
	NF result;
	nimfr("/", "system.nim")
	result = 0;
	nimln(2567, "system.nim");
	nimln(2567, "system.nim");
	nimln(2567, "system.nim");
	nimln(2567, "system.nim");
	result = ((NF)(((double) (x))) / (NF)(((double) (y))));
	popFrame();
	return result;
}

N_NIMCALL(NF, toseconds_714238)(ttimeinfo714003* a, ttimeinterval714005* interval) {
	NF result;
	ttimeinfo714003 anew;
	ttimeinterval714005 newinterv;
	NU8 curmonth;
	NI mth_714268;
	NI HEX3Atmp_714392;
	NI res_714394;
	NF LOC8;
	result = 0;
	genericAssign((void*)&anew, (void*)a, (&NTI714003));
	newinterv = (*interval);
	result = 0.0;
	newinterv.Months += (NI64)((*interval).Years * 12);
	curmonth = anew.Month;
	mth_714268 = 0;
	HEX3Atmp_714392 = 0;
	HEX3Atmp_714392 = newinterv.Months;
	res_714394 = 1;
	while (1) {
		NI LOC2;
		if (!(res_714394 <= HEX3Atmp_714392)) goto LA1;
		mth_714268 = res_714394;
		LOC2 = 0;
		LOC2 = getdaysinmonth_714231(curmonth, ((NI) (anew.Year)));
		HEX2BHEX3D_714271(&result, ((NF) ((NI64)((NI64)((NI64)(LOC2 * 24) * 60) * 60))));
		{
			if (!(curmonth == ((NU8) 11))) goto LA5;
			curmonth = ((NU8) 0);
			anew.Year += 1;
		}
		goto LA3;
		LA5: ;
		{
			curmonth += 1;
		}
		LA3: ;
		res_714394 += 1;
	} LA1: ;
	HEX2BHEX3D_714271(&result, ((NF) ((NI64)((NI64)((NI64)(newinterv.Days * 24) * 60) * 60))));
	HEX2BHEX3D_714271(&result, ((NF) ((NI64)((NI64)(newinterv.Hours * 60) * 60))));
	HEX2BHEX3D_714271(&result, ((NF) ((NI64)(newinterv.Minutes * 60))));
	HEX2BHEX3D_714271(&result, ((NF) (newinterv.Seconds)));
	LOC8 = 0;
	LOC8 = HEX2F_79038(newinterv.Miliseconds, 1000);
	HEX2BHEX3D_714271(&result, LOC8);
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (NI64)((*a).Sup.len * 1));
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, HEX2B_714403)(ttimeinfo714003* a, ttimeinterval714005* interval, ttimeinfo714003* Result) {
	NF t;
	time_t LOC1;
	NF secs;
	LOC1 = 0;
	LOC1 = timeinfototime_714046(a);
	t = toseconds_714061(LOC1);
	secs = toseconds_714238(a, interval);
	{
		time_t LOC6;
		if (!eqStrings((*a).Tzname, ((NimStringDesc*) &TMP185))) goto LA4;
		LOC6 = 0;
		LOC6 = fromseconds_714050(((NF)(t) + (NF)(secs)));
		genericReset((void*)Result, (&NTI714003));
		(*Result).Sup.m_type = (&NTI714003);
		getgmtime_714042(LOC6, Result);
	}
	goto LA2;
	LA4: ;
	{
		time_t LOC8;
		LOC8 = 0;
		LOC8 = fromseconds_714050(((NF)(t) + (NF)(secs)));
		genericReset((void*)Result, (&NTI714003));
		(*Result).Sup.m_type = (&NTI714003);
		getlocaltime_714038(LOC8, Result);
	}
	LA2: ;
}

N_NIMCALL(void, HEX2D_714412)(ttimeinfo714003* a, ttimeinterval714005* interval, ttimeinfo714003* Result) {
	NF t;
	time_t LOC1;
	NF secs;
	LOC1 = 0;
	LOC1 = timeinfototime_714046(a);
	t = toseconds_714061(LOC1);
	secs = toseconds_714238(a, interval);
	{
		time_t LOC6;
		if (!eqStrings((*a).Tzname, ((NimStringDesc*) &TMP185))) goto LA4;
		LOC6 = 0;
		LOC6 = fromseconds_714050(((NF)(t) - (NF)(secs)));
		genericReset((void*)Result, (&NTI714003));
		(*Result).Sup.m_type = (&NTI714003);
		getgmtime_714042(LOC6, Result);
	}
	goto LA2;
	LA4: ;
	{
		time_t LOC8;
		LOC8 = 0;
		LOC8 = fromseconds_714050(((NF)(t) - (NF)(secs)));
		genericReset((void*)Result, (&NTI714003));
		(*Result).Sup.m_type = (&NTI714003);
		getlocaltime_714038(LOC8, Result);
	}
	LA2: ;
}

N_NIMCALL(void, gettzname_714101)(TY714103* Result) {
	unsureAsgnRef((void**) &(*Result).Field0, cstrToNimstr(tzname[(0)- 0]));
	unsureAsgnRef((void**) &(*Result).Field1, cstrToNimstr(tzname[(1)- 0]));
	goto BeforeRet;
	BeforeRet: ;
}

N_NIMCALL(NI, gettimezone_714202)(void) {
	NI result;
	result = 0;
	result = timezone;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, tmtotimeinfo_714644)(struct tm* tm, NIM_BOOL local, ttimeinfo714003* Result) {
	ttimeinfo714003 LOC1;
	memset((void*)&LOC1, 0, sizeof(LOC1));
	LOC1.Sup.m_type = (&NTI714003);
	memset((void*)&LOC1, 0, sizeof(LOC1));
	LOC1.Sup.m_type = (&NTI714003);
	LOC1.Second = ((NI) (((NI) ((*tm).tm_sec))));
	LOC1.Minute = ((NI) (((NI) ((*tm).tm_min))));
	LOC1.Hour = ((NI) (((NI) ((*tm).tm_hour))));
	LOC1.Monthday = ((NI) (((NI) ((*tm).tm_mday))));
	LOC1.Month = ((NU8) ((*tm).tm_mon));
	LOC1.Year = ((NI) ((NI32)((*tm).tm_year + ((NI32) 1900))));
	LOC1.Weekday = weekdays_714649[(((NI) ((*tm).tm_wday)))- 0];
	LOC1.Yearday = ((NI) (((NI) ((*tm).tm_yday))));
	LOC1.Isdst = (((NI32) 0) < (*tm).tm_isdst);
	{
		if (!local) goto LA4;
		{
			TY714103 LOC10;
			if (!(((NI32) 0) < (*tm).tm_isdst)) goto LA8;
			memset((void*)&LOC10, 0, sizeof(LOC10));
			gettzname_714101(&LOC10);
			LOC1.Tzname = copyString(LOC10.Field1);
		}
		goto LA6;
		LA8: ;
		{
			TY714103 LOC12;
			memset((void*)&LOC12, 0, sizeof(LOC12));
			gettzname_714101(&LOC12);
			LOC1.Tzname = copyString(LOC12.Field0);
		}
		LA6: ;
	}
	goto LA2;
	LA4: ;
	{
		LOC1.Tzname = copyString(((NimStringDesc*) &TMP185));
	}
	LA2: ;
	{
		if (!local) goto LA16;
		LOC1.Timezone = gettimezone_714202();
	}
	goto LA14;
	LA16: ;
	{
		LOC1.Timezone = 0;
	}
	LA14: ;
	genericShallowAssign((void*)Result, (void*)&LOC1, (&NTI714003));
}

N_NIMCALL(struct tm, timeinfototm_714664)(ttimeinfo714003* t) {
	struct tm result;
	NI LOC1;
	memset((void*)&result, 0, sizeof(result));
	result.tm_sec = ((int) ((*t).Second));
	result.tm_min = ((int) ((*t).Minute));
	result.tm_hour = ((int) ((*t).Hour));
	result.tm_mday = ((int) ((*t).Monthday));
	result.tm_mon = ((int) ((*t).Month));
	result.tm_year = ((int) ((NI64)(((NI) ((*t).Year)) - 1900)));
	result.tm_wday = ((int) (weekdays_714668[((*t).Weekday)- 0]));
	result.tm_yday = ((int) ((*t).Yearday));
	LOC1 = 0;
	{
		if (!(*t).Isdst) goto LA4;
		LOC1 = 1;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = 0;
	}
	LA2: ;
	result.tm_isdst = ((int) (LOC1));
	return result;
}

N_NIMCALL(NI64, ntDiffTime)(time_t a, time_t b) {
	NI64 result;
	NF LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = difftime(a, b);
	result = float64ToInt64(LOC1);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, getstartmilsecs_714205)(void) {
	NI result;
	NI LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = clock();
	result = (NI64)(LOC1 / (NI64)(CLOCKS_PER_SEC / 1000));
	return result;
}

N_NIMCALL(time_t, gettime_714035)(void) {
	time_t result;
	result = 0;
	result = time(NIM_NIL);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, getlocaltime_714038)(time_t t, ttimeinfo714003* Result) {
	time_t a;
	struct tm* LOC1;
	a = t;
	LOC1 = 0;
	LOC1 = localtime(&a);
	genericReset((void*)Result, (&NTI714003));
	(*Result).Sup.m_type = (&NTI714003);
	tmtotimeinfo_714644(&(*LOC1), NIM_TRUE, Result);
}

N_NIMCALL(void, getgmtime_714042)(time_t t, ttimeinfo714003* Result) {
	time_t a;
	struct tm* LOC1;
	a = t;
	LOC1 = 0;
	LOC1 = gmtime(&a);
	genericReset((void*)Result, (&NTI714003));
	(*Result).Sup.m_type = (&NTI714003);
	tmtotimeinfo_714644(&(*LOC1), NIM_FALSE, Result);
}

N_NIMCALL(time_t, timeinfototime_714046)(ttimeinfo714003* timeinfo) {
	time_t result;
	ttimeinfo714003 ctimeinfo;
	struct tm LOC1;
	result = 0;
	genericAssign((void*)&ctimeinfo, (void*)timeinfo, (&NTI714003));
	LOC1 = timeinfototm_714664(&ctimeinfo);
	result = mktime(&LOC1);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NimStringDesc*, tostringtillnl_715227)(NCSTRING p) {
	NimStringDesc* result;
	NI i;
	result = 0;
	result = copyString(((NimStringDesc*) &TMP186));
	i = 0;
	while (1) {
		NIM_BOOL LOC2;
		NIM_BOOL LOC3;
		LOC2 = 0;
		LOC3 = 0;
		LOC3 = !(((NU8)(p[i]) == (NU8)(0)));
		if (!(LOC3)) goto LA4;
		LOC3 = !(((NU8)(p[i]) == (NU8)(10)));
		LA4: ;
		LOC2 = LOC3;
		if (!(LOC2)) goto LA5;
		LOC2 = !(((NU8)(p[i]) == (NU8)(13)));
		LA5: ;
		if (!LOC2) goto LA1;
		result = addChar(result, p[i]);
		i += 1;
	} LA1: ;
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_714065)(ttimeinfo714003* timeinfo) {
	NimStringDesc* result;
	NCSTRING p;
	struct tm LOC1;
	result = 0;
	LOC1 = timeinfototm_714664(timeinfo);
	p = asctime(&LOC1);
	result = tostringtillnl_715227(p);
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_714069)(time_t time) {
	NimStringDesc* result;
	time_t a;
	NCSTRING LOC1;
	result = 0;
	a = time;
	LOC1 = 0;
	LOC1 = ctime(&a);
	result = tostringtillnl_715227(LOC1);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI64, unixtimetowintime_715265)(time_t t) {
	NI64 result;
	result = 0;
	result = (NI64)((NI64)(((NI64) (t)) * 10000000) + IL64(116444736000000000));
	return result;
}

N_NIMCALL(time_t, wintimetounixtime_715271)(NI64 t) {
	time_t result;
	result = 0;
	result = ((time_t) ((NI64)((NI64)(t - IL64(116444736000000000)) / 10000000)));
	return result;
}

N_NIMCALL(time_t, fromseconds_714050)(NF since1970) {
	time_t result;
	result = 0;
	result = ((time_t) (since1970));
	return result;
}

N_NIMCALL(NF, toseconds_714061)(time_t time) {
	NF result;
	result = 0;
	result = ((NF) (time));
	return result;
}

N_NIMCALL(NF, ntepochTime)(void) {
	NF result;
	struct timeval a;
	result = 0;
	memset((void*)&a, 0, sizeof(a));
	gettimeofday(&a, NIM_NIL);
	result = ((NF)(((double) (a.tv_sec))) + (NF)(((NF)(((double) (a.tv_usec))) * (NF)(9.9999999999999995e-07))));
	return result;
}

N_NIMCALL(NF, ntcpuTime)(void) {
	NF result;
	NI LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = clock();
	result = ((NF)(((double) (LOC1))) / (NF)(((double) (CLOCKS_PER_SEC))));
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) (&(*dest).data[((*dest).Sup.len)- 0])), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI64)((*dest).Sup.len + 1))- 0] = 0;
	(*dest).Sup.len += 1;
}

N_NIMCALL(NimStringDesc*, ntgetDateStr)(void) {
	NimStringDesc* result;
	ttimeinfo714003 ti;
	time_t LOC1;
	NimStringDesc* LOC2;
	NimStringDesc* LOC3;
	NimStringDesc* LOC4;
	NimStringDesc* LOC5;
	result = 0;
	LOC1 = 0;
	LOC1 = gettime_714035();
	memset((void*)&ti, 0, sizeof(ti));
	ti.Sup.m_type = (&NTI714003);
	getlocaltime_714038(LOC1, &ti);
	LOC2 = 0;
	LOC3 = 0;
	LOC3 = nimIntToStr(((NI) (ti.Year)));
	LOC4 = 0;
	LOC4 = nsuIntToStr(((NI) ((NI64)(((NI) (ti.Month)) + 1))), 2);
	LOC5 = 0;
	LOC5 = nsuIntToStr(((NI) (ti.Monthday)), 2);
	LOC2 = rawNewString(LOC3->Sup.len + LOC4->Sup.len + LOC5->Sup.len + 2);
appendString(LOC2, LOC3);
appendChar(LOC2, 45);
appendString(LOC2, LOC4);
appendChar(LOC2, 45);
appendString(LOC2, LOC5);
	result = LOC2;
	return result;
}

N_NIMCALL(NimStringDesc*, ntgetClockStr)(void) {
	NimStringDesc* result;
	ttimeinfo714003 ti;
	time_t LOC1;
	NimStringDesc* LOC2;
	NimStringDesc* LOC3;
	NimStringDesc* LOC4;
	NimStringDesc* LOC5;
	result = 0;
	LOC1 = 0;
	LOC1 = gettime_714035();
	memset((void*)&ti, 0, sizeof(ti));
	ti.Sup.m_type = (&NTI714003);
	getlocaltime_714038(LOC1, &ti);
	LOC2 = 0;
	LOC3 = 0;
	LOC3 = nsuIntToStr(((NI) (ti.Hour)), 2);
	LOC4 = 0;
	LOC4 = nsuIntToStr(((NI) (ti.Minute)), 2);
	LOC5 = 0;
	LOC5 = nsuIntToStr(((NI) (ti.Second)), 2);
	LOC2 = rawNewString(LOC3->Sup.len + LOC4->Sup.len + LOC5->Sup.len + 2);
appendString(LOC2, LOC3);
appendChar(LOC2, 58);
appendString(LOC2, LOC4);
appendChar(LOC2, 58);
appendString(LOC2, LOC5);
	result = LOC2;
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_715824)(NU8 day) {
	NimStringDesc* result;
	result = 0;
	result = copyString(lookup_715828[(day)- 0]);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_715836)(NU8 m) {
	NimStringDesc* result;
	result = 0;
	result = copyString(lookup_715840[(m)- 0]);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NimStringDesc*, HEX5BHEX5D_79085)(NimStringDesc* s, tslice79092 x) {
	NimStringDesc* result;
	NI LOC1;
	NI LOC7;
	nimfr("[]", "system.nim")
	result = 0;
	nimln(2591, "system.nim");
	nimln(2591, "system.nim");
	LOC1 = 0;
	nimln(2570, "system.nim");
	{
		nimln(2570, "system.nim");
		if (!(0 <= x.A)) goto LA4;
		LOC1 = x.A;
	}
	goto LA2;
	LA4: ;
	{
		NI TMP235;
		nimln(2570, "system.nim");
		nimln(2570, "system.nim");
		TMP235 = addInt(s->Sup.len, x.A);
		LOC1 = (NI64)(TMP235);
	}
	LA2: ;
	LOC7 = 0;
	nimln(2570, "system.nim");
	{
		nimln(2570, "system.nim");
		if (!(0 <= x.B)) goto LA10;
		LOC7 = x.B;
	}
	goto LA8;
	LA10: ;
	{
		NI TMP236;
		nimln(2570, "system.nim");
		nimln(2570, "system.nim");
		TMP236 = addInt(s->Sup.len, x.B);
		LOC7 = (NI64)(TMP236);
	}
	LA8: ;
	result = copyStrLast(s, LOC1, LOC7);
	popFrame();
	return result;
}

static N_INLINE(tslice79092, HEX2EHEX2E_95022)(NI a_95026, NI b_95028) {
	tslice79092 result;
	nimfr("..", "system.nim")
	memset((void*)&result, 0, sizeof(result));
	nimln(179, "system.nim");
	result.A = a_95026;
	nimln(180, "system.nim");
	result.B = b_95028;
	popFrame();
	return result;
}

static N_INLINE(tcell41290*, usrtocell_44643)(void* usr) {
	tcell41290* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell41290*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell41290))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_46202)(tcell41290* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_44618(&gch_43244.Zct, c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell41290* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_44643(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell41290* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_44643((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_46202(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(void, formattoken_715848)(ttimeinfo714003* info, NimStringDesc* token, NimStringDesc** buf) {
	switch (hashString(token) & 31) {
	case 0: 
if (eqStrings(token, ((NimStringDesc*) &TMP186))) goto LA28;
break;
	case 1: 
if (eqStrings(token, ((NimStringDesc*) &TMP216))) goto LA10;
break;
	case 5: 
if (eqStrings(token, ((NimStringDesc*) &TMP207))) goto LA1;
break;
	case 6: 
if (eqStrings(token, ((NimStringDesc*) &TMP224))) goto LA18;
break;
	case 7: 
if (eqStrings(token, ((NimStringDesc*) &TMP233))) goto LA27;
break;
	case 8: 
if (eqStrings(token, ((NimStringDesc*) &TMP225))) goto LA19;
break;
	case 10: 
if (eqStrings(token, ((NimStringDesc*) &TMP211))) goto LA5;
if (eqStrings(token, ((NimStringDesc*) &TMP217))) goto LA11;
if (eqStrings(token, ((NimStringDesc*) &TMP218))) goto LA12;
if (eqStrings(token, ((NimStringDesc*) &TMP222))) goto LA16;
if (eqStrings(token, ((NimStringDesc*) &TMP226))) goto LA20;
break;
	case 12: 
if (eqStrings(token, ((NimStringDesc*) &TMP219))) goto LA13;
break;
	case 14: 
if (eqStrings(token, ((NimStringDesc*) &TMP232))) goto LA26;
break;
	case 15: 
if (eqStrings(token, ((NimStringDesc*) &TMP210))) goto LA4;
if (eqStrings(token, ((NimStringDesc*) &TMP223))) goto LA17;
break;
	case 20: 
if (eqStrings(token, ((NimStringDesc*) &TMP229))) goto LA23;
break;
	case 21: 
if (eqStrings(token, ((NimStringDesc*) &TMP208))) goto LA2;
if (eqStrings(token, ((NimStringDesc*) &TMP215))) goto LA9;
break;
	case 22: 
if (eqStrings(token, ((NimStringDesc*) &TMP221))) goto LA15;
if (eqStrings(token, ((NimStringDesc*) &TMP231))) goto LA25;
break;
	case 24: 
if (eqStrings(token, ((NimStringDesc*) &TMP213))) goto LA7;
break;
	case 25: 
if (eqStrings(token, ((NimStringDesc*) &TMP214))) goto LA8;
break;
	case 28: 
if (eqStrings(token, ((NimStringDesc*) &TMP220))) goto LA14;
break;
	case 29: 
if (eqStrings(token, ((NimStringDesc*) &TMP227))) goto LA21;
break;
	case 30: 
if (eqStrings(token, ((NimStringDesc*) &TMP230))) goto LA24;
break;
	case 31: 
if (eqStrings(token, ((NimStringDesc*) &TMP209))) goto LA3;
if (eqStrings(token, ((NimStringDesc*) &TMP212))) goto LA6;
if (eqStrings(token, ((NimStringDesc*) &TMP228))) goto LA22;
break;
	}
	goto LA29;
	LA1: ;
	{
		NimStringDesc* LOC32;
		LOC32 = 0;
		LOC32 = nimIntToStr(((NI) ((*info).Monthday)));
		(*buf) = resizeString((*buf), LOC32->Sup.len + 0);
appendString((*buf), LOC32);
	}
	goto LA30;
	LA2: ;
	{
		NimStringDesc* LOC38;
		{
			if (!(((NI) ((*info).Monthday)) < 10)) goto LA36;
			(*buf) = resizeString((*buf), 1);
appendString((*buf), ((NimStringDesc*) &TMP234));
		}
		LA36: ;
		LOC38 = 0;
		LOC38 = nimIntToStr(((NI) ((*info).Monthday)));
		(*buf) = resizeString((*buf), LOC38->Sup.len + 0);
appendString((*buf), LOC38);
	}
	goto LA30;
	LA3: ;
	{
		NimStringDesc* LOC40;
		tslice79092 LOC41;
		NimStringDesc* LOC42;
		LOC40 = 0;
		LOC40 = HEX24_715824((*info).Weekday);
		LOC41 = HEX2EHEX2E_95022(0, 2);
		LOC42 = 0;
		LOC42 = HEX5BHEX5D_79085(LOC40, LOC41);
		(*buf) = resizeString((*buf), LOC42->Sup.len + 0);
appendString((*buf), LOC42);
	}
	goto LA30;
	LA4: ;
	{
		NimStringDesc* LOC44;
		LOC44 = 0;
		LOC44 = HEX24_715824((*info).Weekday);
		(*buf) = resizeString((*buf), LOC44->Sup.len + 0);
appendString((*buf), LOC44);
	}
	goto LA30;
	LA5: ;
	{
		NI LOC46;
		NimStringDesc* LOC52;
		LOC46 = 0;
		{
			if (!(12 < ((NI) ((*info).Hour)))) goto LA49;
			LOC46 = ((NI) ((NI64)(((NI) ((*info).Hour)) - 12)));
		}
		goto LA47;
		LA49: ;
		{
			LOC46 = ((NI) ((*info).Hour));
		}
		LA47: ;
		LOC52 = 0;
		LOC52 = nimIntToStr(LOC46);
		(*buf) = resizeString((*buf), LOC52->Sup.len + 0);
appendString((*buf), LOC52);
	}
	goto LA30;
	LA6: ;
	{
		NI amerhour;
		NimStringDesc* LOC63;
		{
			if (!(12 < ((NI) ((*info).Hour)))) goto LA56;
			amerhour = ((NI) ((NI64)(((NI) ((*info).Hour)) - 12)));
		}
		goto LA54;
		LA56: ;
		{
			amerhour = ((NI) ((*info).Hour));
		}
		LA54: ;
		{
			if (!(amerhour < 10)) goto LA61;
			(*buf) = addChar((*buf), 48);
		}
		LA61: ;
		LOC63 = 0;
		LOC63 = nimIntToStr(amerhour);
		(*buf) = resizeString((*buf), LOC63->Sup.len + 0);
appendString((*buf), LOC63);
	}
	goto LA30;
	LA7: ;
	{
		NimStringDesc* LOC65;
		LOC65 = 0;
		LOC65 = nimIntToStr(((NI) ((*info).Hour)));
		(*buf) = resizeString((*buf), LOC65->Sup.len + 0);
appendString((*buf), LOC65);
	}
	goto LA30;
	LA8: ;
	{
		NimStringDesc* LOC71;
		{
			if (!(((NI) ((*info).Hour)) < 10)) goto LA69;
			(*buf) = addChar((*buf), 48);
		}
		LA69: ;
		LOC71 = 0;
		LOC71 = nimIntToStr(((NI) ((*info).Hour)));
		(*buf) = resizeString((*buf), LOC71->Sup.len + 0);
appendString((*buf), LOC71);
	}
	goto LA30;
	LA9: ;
	{
		NimStringDesc* LOC73;
		LOC73 = 0;
		LOC73 = nimIntToStr(((NI) ((*info).Minute)));
		(*buf) = resizeString((*buf), LOC73->Sup.len + 0);
appendString((*buf), LOC73);
	}
	goto LA30;
	LA10: ;
	{
		NimStringDesc* LOC79;
		{
			if (!(((NI) ((*info).Minute)) < 10)) goto LA77;
			(*buf) = addChar((*buf), 48);
		}
		LA77: ;
		LOC79 = 0;
		LOC79 = nimIntToStr(((NI) ((*info).Minute)));
		(*buf) = resizeString((*buf), LOC79->Sup.len + 0);
appendString((*buf), LOC79);
	}
	goto LA30;
	LA11: ;
	{
		NimStringDesc* LOC81;
		LOC81 = 0;
		LOC81 = nimIntToStr((NI64)(((NI) ((*info).Month)) + 1));
		(*buf) = resizeString((*buf), LOC81->Sup.len + 0);
appendString((*buf), LOC81);
	}
	goto LA30;
	LA12: ;
	{
		NimStringDesc* LOC87;
		{
			if (!((*info).Month < ((NU8) 9))) goto LA85;
			(*buf) = addChar((*buf), 48);
		}
		LA85: ;
		LOC87 = 0;
		LOC87 = nimIntToStr((NI64)(((NI) ((*info).Month)) + 1));
		(*buf) = resizeString((*buf), LOC87->Sup.len + 0);
appendString((*buf), LOC87);
	}
	goto LA30;
	LA13: ;
	{
		NimStringDesc* LOC89;
		tslice79092 LOC90;
		NimStringDesc* LOC91;
		LOC89 = 0;
		LOC89 = HEX24_715836((*info).Month);
		LOC90 = HEX2EHEX2E_95022(0, 2);
		LOC91 = 0;
		LOC91 = HEX5BHEX5D_79085(LOC89, LOC90);
		(*buf) = resizeString((*buf), LOC91->Sup.len + 0);
appendString((*buf), LOC91);
	}
	goto LA30;
	LA14: ;
	{
		NimStringDesc* LOC93;
		LOC93 = 0;
		LOC93 = HEX24_715836((*info).Month);
		(*buf) = resizeString((*buf), LOC93->Sup.len + 0);
appendString((*buf), LOC93);
	}
	goto LA30;
	LA15: ;
	{
		NimStringDesc* LOC95;
		LOC95 = 0;
		LOC95 = nimIntToStr(((NI) ((*info).Second)));
		(*buf) = resizeString((*buf), LOC95->Sup.len + 0);
appendString((*buf), LOC95);
	}
	goto LA30;
	LA16: ;
	{
		NimStringDesc* LOC101;
		{
			if (!(((NI) ((*info).Second)) < 10)) goto LA99;
			(*buf) = addChar((*buf), 48);
		}
		LA99: ;
		LOC101 = 0;
		LOC101 = nimIntToStr(((NI) ((*info).Second)));
		(*buf) = resizeString((*buf), LOC101->Sup.len + 0);
appendString((*buf), LOC101);
	}
	goto LA30;
	LA17: ;
	{
		{
			if (!(12 <= ((NI) ((*info).Hour)))) goto LA105;
			(*buf) = addChar((*buf), 80);
		}
		goto LA103;
		LA105: ;
		{
			(*buf) = addChar((*buf), 65);
		}
		LA103: ;
	}
	goto LA30;
	LA18: ;
	{
		{
			if (!(12 <= ((NI) ((*info).Hour)))) goto LA111;
			(*buf) = resizeString((*buf), 2);
appendString((*buf), ((NimStringDesc*) &TMP237));
		}
		goto LA109;
		LA111: ;
		{
			(*buf) = resizeString((*buf), 2);
appendString((*buf), ((NimStringDesc*) &TMP238));
		}
		LA109: ;
	}
	goto LA30;
	LA19: ;
	{
		NI fr;
		NimStringDesc* LOC115;
		NimStringDesc* LOC120;
		NimStringDesc* LOC121;
		tslice79092 LOC122;
		NimStringDesc* LOC123;
		LOC115 = 0;
		LOC115 = nimIntToStr(((NI) ((*info).Year)));
		fr = (NI64)(LOC115->Sup.len - 1);
		{
			if (!(fr < 0)) goto LA118;
			fr = 0;
		}
		LA118: ;
		LOC120 = 0;
		LOC120 = nimIntToStr(((NI) ((*info).Year)));
		LOC121 = 0;
		LOC121 = nimIntToStr(((NI) ((*info).Year)));
		LOC122 = HEX2EHEX2E_95022(fr, (NI64)(LOC121->Sup.len - 1));
		LOC123 = 0;
		LOC123 = HEX5BHEX5D_79085(LOC120, LOC122);
		(*buf) = resizeString((*buf), LOC123->Sup.len + 0);
appendString((*buf), LOC123);
	}
	goto LA30;
	LA20: ;
	{
		NI fr;
		NimStringDesc* LOC125;
		NimStringDesc* fyear;
		NimStringDesc* LOC130;
		NimStringDesc* LOC131;
		tslice79092 LOC132;
		LOC125 = 0;
		LOC125 = nimIntToStr(((NI) ((*info).Year)));
		fr = (NI64)(LOC125->Sup.len - 2);
		{
			if (!(fr < 0)) goto LA128;
			fr = 0;
		}
		LA128: ;
		LOC130 = 0;
		LOC130 = nimIntToStr(((NI) ((*info).Year)));
		LOC131 = 0;
		LOC131 = nimIntToStr(((NI) ((*info).Year)));
		LOC132 = HEX2EHEX2E_95022(fr, (NI64)(LOC131->Sup.len - 1));
		fyear = HEX5BHEX5D_79085(LOC130, LOC132);
		{
			NimStringDesc* LOC137;
			NimStringDesc* LOC138;
			if (!!((fyear->Sup.len == 2))) goto LA135;
			LOC137 = 0;
			LOC138 = 0;
			LOC138 = nsuRepeatChar((NI64)(2 - fyear->Sup.len), 48);
			LOC137 = rawNewString(LOC138->Sup.len + fyear->Sup.len + 0);
appendString(LOC137, LOC138);
appendString(LOC137, fyear);
			fyear = LOC137;
		}
		LA135: ;
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA21: ;
	{
		NI fr;
		NimStringDesc* LOC140;
		NimStringDesc* fyear;
		NimStringDesc* LOC145;
		NimStringDesc* LOC146;
		tslice79092 LOC147;
		LOC140 = 0;
		LOC140 = nimIntToStr(((NI) ((*info).Year)));
		fr = (NI64)(LOC140->Sup.len - 3);
		{
			if (!(fr < 0)) goto LA143;
			fr = 0;
		}
		LA143: ;
		LOC145 = 0;
		LOC145 = nimIntToStr(((NI) ((*info).Year)));
		LOC146 = 0;
		LOC146 = nimIntToStr(((NI) ((*info).Year)));
		LOC147 = HEX2EHEX2E_95022(fr, (NI64)(LOC146->Sup.len - 1));
		fyear = HEX5BHEX5D_79085(LOC145, LOC147);
		{
			NimStringDesc* LOC152;
			NimStringDesc* LOC153;
			if (!!((fyear->Sup.len == 3))) goto LA150;
			LOC152 = 0;
			LOC153 = 0;
			LOC153 = nsuRepeatChar((NI64)(3 - fyear->Sup.len), 48);
			LOC152 = rawNewString(LOC153->Sup.len + fyear->Sup.len + 0);
appendString(LOC152, LOC153);
appendString(LOC152, fyear);
			fyear = LOC152;
		}
		LA150: ;
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA22: ;
	{
		NI fr;
		NimStringDesc* LOC155;
		NimStringDesc* fyear;
		NimStringDesc* LOC160;
		NimStringDesc* LOC161;
		tslice79092 LOC162;
		LOC155 = 0;
		LOC155 = nimIntToStr(((NI) ((*info).Year)));
		fr = (NI64)(LOC155->Sup.len - 4);
		{
			if (!(fr < 0)) goto LA158;
			fr = 0;
		}
		LA158: ;
		LOC160 = 0;
		LOC160 = nimIntToStr(((NI) ((*info).Year)));
		LOC161 = 0;
		LOC161 = nimIntToStr(((NI) ((*info).Year)));
		LOC162 = HEX2EHEX2E_95022(fr, (NI64)(LOC161->Sup.len - 1));
		fyear = HEX5BHEX5D_79085(LOC160, LOC162);
		{
			NimStringDesc* LOC167;
			NimStringDesc* LOC168;
			if (!!((fyear->Sup.len == 4))) goto LA165;
			LOC167 = 0;
			LOC168 = 0;
			LOC168 = nsuRepeatChar((NI64)(4 - fyear->Sup.len), 48);
			LOC167 = rawNewString(LOC168->Sup.len + fyear->Sup.len + 0);
appendString(LOC167, LOC168);
appendString(LOC167, fyear);
			fyear = LOC167;
		}
		LA165: ;
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA23: ;
	{
		NI fr;
		NimStringDesc* LOC170;
		NimStringDesc* fyear;
		NimStringDesc* LOC175;
		NimStringDesc* LOC176;
		tslice79092 LOC177;
		LOC170 = 0;
		LOC170 = nimIntToStr(((NI) ((*info).Year)));
		fr = (NI64)(LOC170->Sup.len - 5);
		{
			if (!(fr < 0)) goto LA173;
			fr = 0;
		}
		LA173: ;
		LOC175 = 0;
		LOC175 = nimIntToStr(((NI) ((*info).Year)));
		LOC176 = 0;
		LOC176 = nimIntToStr(((NI) ((*info).Year)));
		LOC177 = HEX2EHEX2E_95022(fr, (NI64)(LOC176->Sup.len - 1));
		fyear = HEX5BHEX5D_79085(LOC175, LOC177);
		{
			NimStringDesc* LOC182;
			NimStringDesc* LOC183;
			if (!!((fyear->Sup.len == 5))) goto LA180;
			LOC182 = 0;
			LOC183 = 0;
			LOC183 = nsuRepeatChar((NI64)(5 - fyear->Sup.len), 48);
			LOC182 = rawNewString(LOC183->Sup.len + fyear->Sup.len + 0);
appendString(LOC182, LOC183);
appendString(LOC182, fyear);
			fyear = LOC182;
		}
		LA180: ;
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA24: ;
	{
		NI hrs;
		NimStringDesc* LOC185;
		hrs = (NI64)((NI64)((*info).Timezone / 60) / 60);
		LOC185 = 0;
		LOC185 = nimIntToStr(hrs);
		(*buf) = resizeString((*buf), LOC185->Sup.len + 0);
appendString((*buf), LOC185);
	}
	goto LA30;
	LA25: ;
	{
		NI hrs;
		NimStringDesc* LOC187;
		hrs = (NI64)((NI64)((*info).Timezone / 60) / 60);
		LOC187 = 0;
		LOC187 = nimIntToStr(hrs);
		(*buf) = resizeString((*buf), LOC187->Sup.len + 0);
appendString((*buf), LOC187);
		{
			NI atindex;
			NimStringDesc* LOC192;
			NI LOC193;
			if (!((NI64)abs(hrs) < 10)) goto LA190;
			LOC192 = 0;
			LOC192 = nimIntToStr(hrs);
			LOC193 = 0;
			{
				if (!(hrs < 0)) goto LA196;
				LOC193 = 1;
			}
			goto LA194;
			LA196: ;
			{
				LOC193 = 0;
			}
			LA194: ;
			atindex = (NI64)((*buf)->Sup.len - (NI64)(LOC192->Sup.len - LOC193));
			insert_80801(buf, ((NimStringDesc*) &TMP234), atindex);
		}
		LA190: ;
	}
	goto LA30;
	LA26: ;
	{
		NI hrs;
		NimStringDesc* LOC200;
		NimStringDesc* LOC201;
		hrs = (NI64)((NI64)((*info).Timezone / 60) / 60);
		LOC200 = 0;
		LOC201 = 0;
		LOC201 = nimIntToStr(hrs);
		LOC200 = rawNewString(LOC201->Sup.len + 3);
appendString(LOC200, LOC201);
appendString(LOC200, ((NimStringDesc*) &TMP240));
		(*buf) = resizeString((*buf), LOC200->Sup.len + 0);
appendString((*buf), LOC200);
		{
			NI atindex;
			NimStringDesc* LOC206;
			NimStringDesc* LOC207;
			NI LOC208;
			if (!((NI64)abs(hrs) < 10)) goto LA204;
			LOC206 = 0;
			LOC207 = 0;
			LOC207 = nimIntToStr(hrs);
			LOC206 = rawNewString(LOC207->Sup.len + 3);
appendString(LOC206, LOC207);
appendString(LOC206, ((NimStringDesc*) &TMP240));
			LOC208 = 0;
			{
				if (!(hrs < 0)) goto LA211;
				LOC208 = 1;
			}
			goto LA209;
			LA211: ;
			{
				LOC208 = 0;
			}
			LA209: ;
			atindex = (NI64)((*buf)->Sup.len - (NI64)(LOC206->Sup.len - LOC208));
			insert_80801(buf, ((NimStringDesc*) &TMP234), atindex);
		}
		LA204: ;
	}
	goto LA30;
	LA27: ;
	{
		(*buf) = resizeString((*buf), (*info).Tzname->Sup.len + 0);
appendString((*buf), (*info).Tzname);
	}
	goto LA30;
	LA28: ;
	{
	}
	goto LA30;
	LA29: ;
	{
		einvalidvalue2453* e_715976;
		NimStringDesc* LOC217;
		e_715976 = 0;
		e_715976 = (einvalidvalue2453*) newObj((&NTI18001), sizeof(einvalidvalue2453));
		(*e_715976).Sup.Sup.Sup.m_type = (&NTI2453);
		LOC217 = 0;
		LOC217 = rawNewString(token->Sup.len + 23);
appendString(LOC217, ((NimStringDesc*) &TMP241));
appendString(LOC217, token);
		asgnRefNoCycle((void**) &(*e_715976).Sup.Sup.message, LOC217);
		raiseException((E_Base*)e_715976, "EInvalidValue");
	}
	LA30: ;
}

N_NIMCALL(NimStringDesc*, format_715999)(ttimeinfo714003* info, NimStringDesc* f) {
	NimStringDesc* result;
	NI i;
	NimStringDesc* currentf;
	result = 0;
	result = copyString(((NimStringDesc*) &TMP186));
	i = 0;
	currentf = copyString(((NimStringDesc*) &TMP186));
	while (1) {
		switch (((NU8)(f->data[i]))) {
		case 32:
		case 45:
		case 47:
		case 58:
		case 39:
		case 0:
		case 40:
		case 41:
		case 91:
		case 93:
		case 44:
		{
			formattoken_715848(info, currentf, &result);
			currentf = copyString(((NimStringDesc*) &TMP186));
			{
				if (!((NU8)(f->data[i]) == (NU8)(0))) goto LA5;
				goto LA1;
			}
			LA5: ;
			{
				if (!((NU8)(f->data[i]) == (NU8)(39))) goto LA9;
				i += 1;
				while (1) {
					NIM_BOOL LOC12;
					LOC12 = 0;
					LOC12 = !(((NU8)(f->data[i]) == (NU8)(39)));
					if (!(LOC12)) goto LA13;
					LOC12 = (i < (NI64)(f->Sup.len - 1));
					LA13: ;
					if (!LOC12) goto LA11;
					result = addChar(result, f->data[i]);
					i += 1;
				} LA11: ;
			}
			goto LA7;
			LA9: ;
			{
				result = addChar(result, f->data[i]);
			}
			LA7: ;
		}
		break;
		default:
		{
			{
				NIM_BOOL LOC18;
				LOC18 = 0;
				LOC18 = (currentf->Sup.len < 1);
				if (LOC18) goto LA19;
				LOC18 = ((NU8)(currentf->data[(currentf->Sup.len-1)]) == (NU8)(f->data[i]));
				LA19: ;
				if (!LOC18) goto LA20;
				currentf = addChar(currentf, f->data[i]);
			}
			goto LA16;
			LA20: ;
			{
				formattoken_715848(info, currentf, &result);
				i -= 1;
				currentf = copyString(((NimStringDesc*) &TMP186));
			}
			LA16: ;
		}
		break;
		}
		i += 1;
	} LA1: ;
	return result;
}
N_NOINLINE(void, timesInit)(void) {
}

N_NOINLINE(void, timesDatInit)(void) {
static TNimNode* TMP178[11];
static TNimNode* TMP179[12];
NI TMP181;
static char* NIM_CONST TMP180[12] = {
"mJan", 
"mFeb", 
"mMar", 
"mApr", 
"mMay", 
"mJun", 
"mJul", 
"mAug", 
"mSep", 
"mOct", 
"mNov", 
"mDec"};
static TNimNode* TMP182[7];
NI TMP184;
static char* NIM_CONST TMP183[7] = {
"dMon", 
"dTue", 
"dWed", 
"dThu", 
"dFri", 
"dSat", 
"dSun"};
static TNimNode TMP176[33];
NTI714003.size = sizeof(ttimeinfo714003);
NTI714003.kind = 17;
NTI714003.base = (&NTI2409);
TMP178[0] = &TMP176[1];
NTI714006.size = sizeof(NI);
NTI714006.kind = 20;
NTI714006.base = (&NTI106);
NTI714006.flags = 3;
TMP176[1].kind = 1;
TMP176[1].offset = offsetof(ttimeinfo714003, Second);
TMP176[1].typ = (&NTI714006);
TMP176[1].name = "second";
TMP178[1] = &TMP176[2];
NTI714008.size = sizeof(NI);
NTI714008.kind = 20;
NTI714008.base = (&NTI106);
NTI714008.flags = 3;
TMP176[2].kind = 1;
TMP176[2].offset = offsetof(ttimeinfo714003, Minute);
TMP176[2].typ = (&NTI714008);
TMP176[2].name = "minute";
TMP178[2] = &TMP176[3];
NTI714010.size = sizeof(NI);
NTI714010.kind = 20;
NTI714010.base = (&NTI106);
NTI714010.flags = 3;
TMP176[3].kind = 1;
TMP176[3].offset = offsetof(ttimeinfo714003, Hour);
TMP176[3].typ = (&NTI714010);
TMP176[3].name = "hour";
TMP178[3] = &TMP176[4];
NTI714012.size = sizeof(NI);
NTI714012.kind = 20;
NTI714012.base = (&NTI106);
NTI714012.flags = 3;
TMP176[4].kind = 1;
TMP176[4].offset = offsetof(ttimeinfo714003, Monthday);
TMP176[4].typ = (&NTI714012);
TMP176[4].name = "monthday";
TMP178[4] = &TMP176[5];
NTI713804.size = sizeof(NU8);
NTI713804.kind = 14;
NTI713804.base = 0;
NTI713804.flags = 3;
for (TMP181 = 0; TMP181 < 12; TMP181++) {
TMP176[TMP181+6].kind = 1;
TMP176[TMP181+6].offset = TMP181;
TMP176[TMP181+6].name = TMP180[TMP181];
TMP179[TMP181] = &TMP176[TMP181+6];
}
TMP176[18].len = 12; TMP176[18].kind = 2; TMP176[18].sons = &TMP179[0];
NTI713804.node = &TMP176[18];
TMP176[5].kind = 1;
TMP176[5].offset = offsetof(ttimeinfo714003, Month);
TMP176[5].typ = (&NTI713804);
TMP176[5].name = "month";
TMP178[5] = &TMP176[19];
NTI714015.size = sizeof(NI);
NTI714015.kind = 20;
NTI714015.base = (&NTI106);
NTI714015.flags = 3;
TMP176[19].kind = 1;
TMP176[19].offset = offsetof(ttimeinfo714003, Year);
TMP176[19].typ = (&NTI714015);
TMP176[19].name = "year";
TMP178[6] = &TMP176[20];
NTI713806.size = sizeof(NU8);
NTI713806.kind = 14;
NTI713806.base = 0;
NTI713806.flags = 3;
for (TMP184 = 0; TMP184 < 7; TMP184++) {
TMP176[TMP184+21].kind = 1;
TMP176[TMP184+21].offset = TMP184;
TMP176[TMP184+21].name = TMP183[TMP184];
TMP182[TMP184] = &TMP176[TMP184+21];
}
TMP176[28].len = 7; TMP176[28].kind = 2; TMP176[28].sons = &TMP182[0];
NTI713806.node = &TMP176[28];
TMP176[20].kind = 1;
TMP176[20].offset = offsetof(ttimeinfo714003, Weekday);
TMP176[20].typ = (&NTI713806);
TMP176[20].name = "weekday";
TMP178[7] = &TMP176[29];
NTI714021.size = sizeof(NI);
NTI714021.kind = 20;
NTI714021.base = (&NTI106);
NTI714021.flags = 3;
TMP176[29].kind = 1;
TMP176[29].offset = offsetof(ttimeinfo714003, Yearday);
TMP176[29].typ = (&NTI714021);
TMP176[29].name = "yearday";
TMP178[8] = &TMP176[30];
TMP176[30].kind = 1;
TMP176[30].offset = offsetof(ttimeinfo714003, Isdst);
TMP176[30].typ = (&NTI134);
TMP176[30].name = "isDST";
TMP178[9] = &TMP176[31];
TMP176[31].kind = 1;
TMP176[31].offset = offsetof(ttimeinfo714003, Tzname);
TMP176[31].typ = (&NTI143);
TMP176[31].name = "tzname";
TMP178[10] = &TMP176[32];
TMP176[32].kind = 1;
TMP176[32].offset = offsetof(ttimeinfo714003, Timezone);
TMP176[32].typ = (&NTI106);
TMP176[32].name = "timezone";
TMP176[0].len = 11; TMP176[0].kind = 2; TMP176[0].sons = &TMP178[0];
NTI714003.node = &TMP176[0];
}

