/* Generated by Nimrod Compiler v0.9.5 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nimrod -o /home/andreysh/Projects/nimrod/stone_head/nimcache/utils.o /home/andreysh/Projects/nimrod/stone_head/nimcache/utils.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
N_NIMCALL(NimStringDesc*, HEX2A_787048)(NimStringDesc* a, NI b);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NimStringDesc*, HEX2B_787280)(NimStringDesc* a_787284, NimStringDesc* b_787286);
STRING_LITERAL(TMP689, "", 0);
extern TFrame* frameptr_13038;

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) (&(*dest).data[((*dest).Sup.len)- 0])), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_13038;
	frameptr_13038 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_13038 = (*frameptr_13038).prev;
}

N_NIMCALL(NimStringDesc*, HEX2A_787048)(NimStringDesc* a, NI b) {
	NimStringDesc* result;
	NimStringDesc* s;
	NI i_787084;
	NI res_787087;
	nimfr("*", "utils.nim")
	result = 0;
	nimln(25, "utils.nim");
	s = copyString(((NimStringDesc*) &TMP689));
	i_787084 = 0;
	nimln(11, "utils.nim");
	res_787087 = 0;
	nimln(13, "utils.nim");
	while (1) {
		NimStringDesc* LOC2;
		nimln(13, "utils.nim");
		if (!(res_787087 <= b)) goto LA1;
		nimln(11, "utils.nim");
		i_787084 = res_787087;
		nimln(26, "utils.nim");
		nimln(26, "utils.nim");
		LOC2 = 0;
		LOC2 = rawNewString(s->Sup.len + a->Sup.len + 0);
appendString(LOC2, s);
appendString(LOC2, a);
		s = LOC2;
		nimln(15, "utils.nim");
		res_787087 = addInt(res_787087, 1);
	} LA1: ;
	nimln(27, "utils.nim");
	nimln(27, "utils.nim");
	result = copyString(s);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, HEX2B_787280)(NimStringDesc* a_787284, NimStringDesc* b_787286) {
	NimStringDesc* result;
	NimStringDesc* LOC1;
	nimfr("+", "utils.nim")
	result = 0;
	nimln(17, "utils.nim");
	nimln(17, "utils.nim");
	LOC1 = 0;
	nimln(17, "utils.nim");
	LOC1 = rawNewString(a_787284->Sup.len + b_787286->Sup.len + 0);
appendString(LOC1, a_787284);
appendString(LOC1, b_787286);
	result = LOC1;
	popFrame();
	return result;
}
N_NOINLINE(void, utilsInit)(void) {
	nimfr("utils", "utils.nim")
	popFrame();
}

N_NOINLINE(void, utilsDatInit)(void) {
}

