/* Generated by Nimrod Compiler v0.9.5 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nimrod -o /home/andreysh/Projects/nimrod/stone_head/nimcache/x11_xutil.o /home/andreysh/Projects/nimrod/stone_head/nimcache/x11_xutil.c */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct txclasshint119114 txclasshint119114;
typedef struct txiconsize119110 txiconsize119110;
typedef struct txsizehints119018 txsizehints119018;
typedef struct txstandardcolormap119184 txstandardcolormap119184;
typedef struct txwmhints119058 txwmhints119058;
typedef struct txregion119139 txregion119139;
typedef struct txrectangle107537 txrectangle107537;
typedef struct tdisplay107487 tdisplay107487;
typedef struct txtextproperty119090 txtextproperty119090;
typedef struct txvisualinfo119152 txvisualinfo119152;
typedef struct txkeyevent107577 txkeyevent107577;
typedef struct txcomposestatus119132 txcomposestatus119132;
typedef struct txpoint107533 txpoint107533;
typedef struct txgc107471 txgc107471;
typedef struct tximage107517 tximage107517;
typedef struct tf107515 tf107515;
typedef struct tvisual107479 tvisual107479;
typedef struct tcpoint119014 tcpoint119014;
typedef struct txextdata107455 txextdata107455;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(txclasshint119114*, TY119211) (void);
typedef N_CDECL_PTR(txiconsize119110*, TY119214) (void);
typedef N_CDECL_PTR(txsizehints119018*, TY119217) (void);
typedef N_CDECL_PTR(txstandardcolormap119184*, TY119220) (void);
typedef N_CDECL_PTR(txwmhints119058*, TY119223) (void);
typedef N_CDECL_PTR(int, TY119226) (txregion119139* para1, txrectangle107537* para2);
typedef N_CDECL_PTR(txregion119139*, TY119231) (void);
typedef N_CDECL_PTR(NCSTRING, TY119234) (void);
typedef N_CDECL_PTR(int, TY119237) (tdisplay107487* para1, unsigned long para2, int para3);
typedef N_CDECL_PTR(int, TY119243) (txregion119139* para1);
typedef N_CDECL_PTR(int, TY119247) (txregion119139* para1);
typedef N_CDECL_PTR(int, TY119251) (txregion119139* para1, txregion119139* para2);
typedef N_CDECL_PTR(int, TY119256) (tdisplay107487* para1, unsigned long para2, int para3, NIM_CHAR** para4);
typedef N_CDECL_PTR(int, TY119263) (tdisplay107487* para1, unsigned long para2, txclasshint119114* para3);
typedef N_CDECL_PTR(int, TY119269) (tdisplay107487* para1, unsigned long para2, txiconsize119110** para3, NI32* para4);
typedef N_CDECL_PTR(int, TY119276) (tdisplay107487* para1, unsigned long para2, txsizehints119018* para3);
typedef N_CDECL_PTR(int, TY119282) (tdisplay107487* para1, unsigned long para2, txstandardcolormap119184** para3, NI32* para4, unsigned long para5);
typedef N_CDECL_PTR(int, TY119290) (tdisplay107487* para1, unsigned long para2, txsizehints119018* para3, unsigned long para4);
typedef N_CDECL_PTR(int, TY119297) (tdisplay107487* para1, unsigned long para2, txstandardcolormap119184* para3, unsigned long para4);
typedef N_CDECL_PTR(int, TY119304) (tdisplay107487* para1, unsigned long para2, txtextproperty119090* para3, unsigned long para4);
typedef N_CDECL_PTR(txvisualinfo119152*, TY119311) (tdisplay107487* para1, long para2, txvisualinfo119152* para3, NI32* para4);
typedef N_CDECL_PTR(int, TY119318) (tdisplay107487* para1, unsigned long para2, txtextproperty119090* para3);
typedef N_CDECL_PTR(txwmhints119058*, TY119324) (tdisplay107487* para1, unsigned long para2);
typedef N_CDECL_PTR(int, TY119329) (tdisplay107487* para1, unsigned long para2, txtextproperty119090* para3);
typedef N_CDECL_PTR(int, TY119335) (tdisplay107487* para1, unsigned long para2, txtextproperty119090* para3);
typedef N_CDECL_PTR(int, TY119341) (tdisplay107487* para1, unsigned long para2, txsizehints119018* para3, NI* para4);
typedef N_CDECL_PTR(int, TY119349) (tdisplay107487* para1, unsigned long para2, txsizehints119018* para3, NI* para4, unsigned long para5);
typedef N_CDECL_PTR(int, TY119358) (tdisplay107487* para1, unsigned long para2, txsizehints119018* para3);
typedef N_CDECL_PTR(int, TY119364) (txregion119139* para1, txregion119139* para2, txregion119139* para3);
typedef N_CDECL_PTR(void, TY119370) (unsigned long para1, unsigned long* para2, unsigned long* para3);
typedef N_CDECL_PTR(int, TY119376) (txkeyevent107577* para1, NCSTRING para2, int para3, unsigned long* para4, txcomposestatus119132* para5);
typedef N_CDECL_PTR(int, TY119384) (tdisplay107487* para1, int para2, int para3, int para4, txvisualinfo119152* para5);
typedef N_CDECL_PTR(int, TY119392) (txregion119139* para1, int para2, int para3);
typedef N_CDECL_PTR(NI, TY119398) (txregion119139* para1, int para2, int para3);
typedef N_CDECL_PTR(txregion119139*, TY119404) (txpoint107533* para1, int para2, int para3);
typedef N_CDECL_PTR(int, TY119410) (txregion119139* para1, int para2, int para3, int para4, int para5);
typedef N_CDECL_PTR(int, TY119418) (tdisplay107487* para1, unsigned long para2, int para3, NCSTRING para4);
typedef N_CDECL_PTR(int, TY119425) (tdisplay107487* para1, unsigned long para2, txclasshint119114* para3);
typedef N_CDECL_PTR(int, TY119431) (tdisplay107487* para1, unsigned long para2, txiconsize119110* para3, int para4);
typedef N_CDECL_PTR(int, TY119438) (tdisplay107487* para1, unsigned long para2, txsizehints119018* para3);
typedef N_CDECL_PTR(void, TY119444) (tdisplay107487* para1, unsigned long para2, txstandardcolormap119184* para3, int para4, unsigned long para5);
typedef N_CDECL_PTR(int, TY119452) (tdisplay107487* para1, unsigned long para2, txsizehints119018* para3, unsigned long para4);
typedef N_CDECL_PTR(int, TY119459) (tdisplay107487* para1, unsigned long para2, NCSTRING para3, NCSTRING para4, unsigned long para5, NCSTRING* para6, int para7, txsizehints119018* para8);
typedef N_CDECL_PTR(void, TY119470) (tdisplay107487* para1, unsigned long para2, txtextproperty119090* para3, unsigned long para4);
typedef N_CDECL_PTR(void, TY119477) (tdisplay107487* para1, unsigned long para2, txtextproperty119090* para3);
typedef N_CDECL_PTR(int, TY119483) (tdisplay107487* para1, unsigned long para2, txwmhints119058* para3);
typedef N_CDECL_PTR(void, TY119489) (tdisplay107487* para1, unsigned long para2, txtextproperty119090* para3);
typedef N_CDECL_PTR(void, TY119495) (tdisplay107487* para1, unsigned long para2, txtextproperty119090* para3);
typedef N_CDECL_PTR(void, TY119501) (tdisplay107487* para1, unsigned long para2, txsizehints119018* para3);
typedef N_CDECL_PTR(void, TY119507) (tdisplay107487* para1, unsigned long para2, txtextproperty119090* para3, txtextproperty119090* para4, NCSTRING* para5, int para6, txsizehints119018* para7, txwmhints119058* para8, txclasshint119114* para9);
typedef N_CDECL_PTR(void, TY119519) (tdisplay107487* para1, unsigned long para2, NCSTRING para3, NCSTRING para4, NCSTRING* para5, int para6, txsizehints119018* para7, txwmhints119058* para8, txclasshint119114* para9);
typedef N_CDECL_PTR(void, TY119531) (tdisplay107487* para1, unsigned long para2, NCSTRING para3, NCSTRING para4, NCSTRING* para5, int para6, txsizehints119018* para7, txwmhints119058* para8, txclasshint119114* para9);
typedef N_CDECL_PTR(void, TY119543) (tdisplay107487* para1, unsigned long para2, txsizehints119018* para3, unsigned long para4);
typedef N_CDECL_PTR(int, TY119550) (tdisplay107487* para1, txgc107471* para2, txregion119139* para3);
typedef N_CDECL_PTR(void, TY119556) (tdisplay107487* para1, unsigned long para2, txstandardcolormap119184* para3, unsigned long para4);
typedef N_CDECL_PTR(int, TY119563) (tdisplay107487* para1, unsigned long para2, txsizehints119018* para3);
typedef N_CDECL_PTR(int, TY119569) (txregion119139* para1, int para2, int para3);
typedef N_CDECL_PTR(int, TY119575) (NCSTRING* para1, int para2, txtextproperty119090* para3);
typedef N_CDECL_PTR(int, TY119581) (txregion119139* para1, txregion119139* para2, txregion119139* para3);
typedef N_CDECL_PTR(int, TY119587) (tdisplay107487* para1, NCSTRING* para2, int para3, NU8 para4, txtextproperty119090* para5);
typedef N_CDECL_PTR(int, TY119595) (tdisplay107487* para1, NI16** para2, int para3, NU8 para4, txtextproperty119090* para5);
typedef N_CDECL_PTR(int, TY119605) (tdisplay107487* para1, NCSTRING* para2, int para3, NU8 para4, txtextproperty119090* para5);
typedef N_CDECL_PTR(void, TY119613) (NI16** para1);
typedef N_CDECL_PTR(int, TY119619) (txtextproperty119090* para1, NCSTRING** para2, NI32* para3);
typedef N_CDECL_PTR(int, TY119625) (tdisplay107487* para1, txtextproperty119090* para2, NCSTRING** para3, NI32* para4);
typedef N_CDECL_PTR(int, TY119632) (tdisplay107487* para1, txtextproperty119090* para2, NI16*** para3, NI32* para4);
typedef N_CDECL_PTR(int, TY119642) (tdisplay107487* para1, txtextproperty119090* para2, NCSTRING** para3, NI32* para4);
typedef N_CDECL_PTR(int, TY119649) (txrectangle107537* para1, txregion119139* para2, txregion119139* para3);
typedef N_CDECL_PTR(int, TY119655) (txregion119139* para1, txregion119139* para2, txregion119139* para3);
typedef N_CDECL_PTR(int, TY119661) (tdisplay107487* para1, int para2, NCSTRING para3, NCSTRING para4, int para5, txsizehints119018* para6, NI32* para7, NI32* para8, NI32* para9, NI32* para10, NI32* para11);
typedef N_CDECL_PTR(int, TY119675) (txregion119139* para1, txregion119139* para2, txregion119139* para3);
typedef N_CDECL_PTR(tximage107517*, TY107855) (tdisplay107487* para1, tvisual107479* para2, int para3, int para4, int para5, NCSTRING para6, int para7, int para8, int para9, int para10);
typedef N_CDECL_PTR(int, TY107868) (tximage107517* para1);
typedef N_CDECL_PTR(unsigned long, TY107872) (tximage107517* para1, int para2, int para3);
typedef N_CDECL_PTR(int, TY107878) (tximage107517* para1, int para2, int para3, unsigned long para4);
typedef N_CDECL_PTR(tximage107517*, TY107885) (tximage107517* para1, int para2, int para3, int para4, int para5);
typedef N_CDECL_PTR(int, TY107893) (tximage107517* para1, long para2);
struct  tf107515  {
TY107855 Createimage;
TY107868 Destroyimage;
TY107872 Getpixel;
TY107878 Putpixel;
TY107885 Subimage;
TY107893 Addpixel;
};
struct  tximage107517  {
int Width;
int Height;
int Xoffset;
int Format;
NCSTRING Data;
int Byteorder;
int Bitmapunit;
int Bitmapbitorder;
int Bitmappad;
int Depth;
int Bytesperline;
int Bitsperpixel;
unsigned long Redmask;
unsigned long Greenmask;
unsigned long Bluemask;
NIM_CHAR* Obdata;
tf107515 F;
};
struct  txclasshint119114  {
NCSTRING Resname;
NCSTRING Resclass;
};
struct  txiconsize119110  {
int Minwidth;
int Minheight;
int Maxwidth;
int Maxheight;
int Widthinc;
int Heightinc;
};
struct  tcpoint119014  {
int X;
int Y;
};
struct  txsizehints119018  {
long Flags;
int X;
int Y;
int Width;
int Height;
int Minwidth;
int Minheight;
int Maxwidth;
int Maxheight;
int Widthinc;
int Heightinc;
tcpoint119014 Minaspect;
tcpoint119014 Maxaspect;
int Basewidth;
int Baseheight;
int Wingravity;
};
struct  txstandardcolormap119184  {
unsigned long Colormap;
unsigned long Redmax;
unsigned long Redmult;
unsigned long Greenmax;
unsigned long Greenmult;
unsigned long Bluemax;
unsigned long Bluemult;
unsigned long Basepixel;
unsigned long Visualid;
unsigned long Killid;
};
struct  txwmhints119058  {
long Flags;
NI Input;
int Initialstate;
unsigned long Iconpixmap;
unsigned long Iconwindow;
int Iconx;
int Icony;
unsigned long Iconmask;
unsigned long Windowgroup;
};
struct  txregion119139  {
char dummy;
};
struct  txrectangle107537  {
short X;
short Y;
unsigned short Width;
unsigned short Height;
};
struct  tdisplay107487  {
char dummy;
};
struct  txtextproperty119090  {
NCSTRING Value;
unsigned long Encoding;
int Format;
unsigned long Nitems;
};
struct  txvisualinfo119152  {
tvisual107479* Visual;
unsigned long Visualid;
int Screen;
int Depth;
int Class;
unsigned long Redmask;
unsigned long Greenmask;
unsigned long Bluemask;
int Colormapsize;
int Bitsperrgb;
};
struct  txkeyevent107577  {
int Thetype;
unsigned long Serial;
NI Sendevent;
tdisplay107487* Display;
unsigned long Window;
unsigned long Root;
unsigned long Subwindow;
unsigned long Time;
int X;
int Y;
int Xroot;
int Yroot;
int State;
int Keycode;
NI Samescreen;
};
struct  txcomposestatus119132  {
NIM_CHAR* Composeptr;
int Charsmatched;
};
struct  txpoint107533  {
short X;
short Y;
};
struct  txgc107471  {
char dummy;
};
struct  tvisual107479  {
txextdata107455* Extdata;
unsigned long Visualid;
int Cclass;
unsigned long Redmask;
unsigned long Greenmask;
unsigned long Bluemask;
int Bitsperrgb;
int Mapentries;
};
typedef N_CDECL_PTR(int, TY107740) (txextdata107455* extension);
struct  txextdata107455  {
int Number;
txextdata107455* Next;
TY107740 Freeprivate;
NIM_CHAR* Privatedata;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
N_NIMCALL(int, xdestroyimage_119681)(tximage107517* ximage);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(unsigned long, xgetpixel_119685)(tximage107517* ximage, int x, int y);
N_NIMCALL(int, xputpixel_119691)(tximage107517* ximage, int x, int y, unsigned long pixel);
N_NIMCALL(tximage107517*, xsubimage_119698)(tximage107517* ximage, int x, int y, int width, int height);
N_NIMCALL(int, xaddpixel_119706)(tximage107517* ximage, long value);
N_NIMCALL(NIM_BOOL, iskeypadkey_119711)(unsigned long keysym);
N_NIMCALL(NIM_BOOL, isprivatekeypadkey_119715)(unsigned long keysym);
N_NIMCALL(NIM_BOOL, iscursorkey_119719)(unsigned long keysym);
N_NIMCALL(NIM_BOOL, ispfkey_119723)(unsigned long keysym);
N_NIMCALL(NIM_BOOL, isfunctionkey_119727)(unsigned long keysym);
N_NIMCALL(NIM_BOOL, ismiscfunctionkey_119731)(unsigned long keysym);
N_NIMCALL(NIM_BOOL, ismodifierkey_119735)(unsigned long keysym);
N_NIMCALL(NIM_BOOL, HEX3DHEX3D_106070)(unsigned long a, unsigned long b);
STRING_LITERAL(TMP156, "libX11.so", 9);
STRING_LITERAL(TMP157, "libX11.so", 9);
static void* TMP155;
TY119211 Dl_119210;
TY119214 Dl_119213;
TY119217 Dl_119216;
TY119220 Dl_119219;
TY119223 Dl_119222;
TY119226 Dl_119225;
TY119231 Dl_119230;
TY119234 Dl_119233;
TY119237 Dl_119236;
TY119243 Dl_119242;
TY119247 Dl_119246;
TY119251 Dl_119250;
TY119256 Dl_119255;
TY119263 Dl_119262;
TY119269 Dl_119268;
TY119276 Dl_119275;
TY119282 Dl_119281;
TY119290 Dl_119289;
TY119297 Dl_119296;
TY119304 Dl_119303;
TY119311 Dl_119310;
TY119318 Dl_119317;
TY119324 Dl_119323;
TY119329 Dl_119328;
TY119335 Dl_119334;
TY119341 Dl_119340;
TY119349 Dl_119348;
TY119358 Dl_119357;
TY119364 Dl_119363;
TY119370 Dl_119369;
TY119376 Dl_119375;
TY119384 Dl_119383;
TY119392 Dl_119391;
TY119398 Dl_119397;
TY119404 Dl_119403;
TY119410 Dl_119409;
TY119418 Dl_119417;
TY119425 Dl_119424;
TY119431 Dl_119430;
TY119438 Dl_119437;
TY119444 Dl_119443;
TY119452 Dl_119451;
TY119459 Dl_119458;
TY119470 Dl_119469;
TY119477 Dl_119476;
TY119483 Dl_119482;
TY119489 Dl_119488;
TY119495 Dl_119494;
TY119501 Dl_119500;
TY119507 Dl_119506;
TY119519 Dl_119518;
TY119531 Dl_119530;
TY119543 Dl_119542;
TY119550 Dl_119549;
TY119556 Dl_119555;
TY119563 Dl_119562;
TY119569 Dl_119568;
TY119575 Dl_119574;
TY119581 Dl_119580;
TY119587 Dl_119586;
TY119595 Dl_119594;
TY119605 Dl_119604;
TY119613 Dl_119612;
TY119619 Dl_119618;
TY119625 Dl_119624;
TY119632 Dl_119631;
TY119642 Dl_119641;
TY119649 Dl_119648;
TY119655 Dl_119654;
TY119661 Dl_119660;
TY119675 Dl_119674;
extern TFrame* frameptr_13038;

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_13038;
	frameptr_13038 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_13038 = (*frameptr_13038).prev;
}

N_NIMCALL(int, xdestroyimage_119681)(tximage107517* ximage) {
	int result;
	nimfr("XDestroyImage", "xutil.nim")
	result = 0;
	nimln(378, "xutil.nim");
	result = (*ximage).F.Destroyimage(ximage);
	popFrame();
	return result;
}

N_NIMCALL(unsigned long, xgetpixel_119685)(tximage107517* ximage, int x, int y) {
	unsigned long result;
	nimfr("XGetPixel", "xutil.nim")
	result = 0;
	nimln(381, "xutil.nim");
	result = (*ximage).F.Getpixel(ximage, x, y);
	popFrame();
	return result;
}

N_NIMCALL(int, xputpixel_119691)(tximage107517* ximage, int x, int y, unsigned long pixel) {
	int result;
	nimfr("XPutPixel", "xutil.nim")
	result = 0;
	nimln(384, "xutil.nim");
	result = (*ximage).F.Putpixel(ximage, x, y, pixel);
	popFrame();
	return result;
}

N_NIMCALL(tximage107517*, xsubimage_119698)(tximage107517* ximage, int x, int y, int width, int height) {
	tximage107517* result;
	nimfr("XSubImage", "xutil.nim")
	result = 0;
	nimln(387, "xutil.nim");
	result = (*ximage).F.Subimage(ximage, x, y, width, height);
	popFrame();
	return result;
}

N_NIMCALL(int, xaddpixel_119706)(tximage107517* ximage, long value) {
	int result;
	nimfr("XAddPixel", "xutil.nim")
	result = 0;
	nimln(390, "xutil.nim");
	result = (*ximage).F.Addpixel(ximage, value);
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, iskeypadkey_119711)(unsigned long keysym) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	nimfr("IsKeypadKey", "xutil.nim")
	result = 0;
	nimln(393, "xutil.nim");
	nimln(393, "xutil.nim");
	LOC1 = 0;
	nimln(393, "xutil.nim");
	LOC1 = ((NU64)(((unsigned long) 65408)) <= (NU64)(keysym));
	if (!(LOC1)) goto LA2;
	nimln(393, "xutil.nim");
	LOC1 = ((NU64)(keysym) <= (NU64)(((unsigned long) 65469)));
	LA2: ;
	result = LOC1;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, isprivatekeypadkey_119715)(unsigned long keysym) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	nimfr("IsPrivateKeypadKey", "xutil.nim")
	result = 0;
	nimln(396, "xutil.nim");
	nimln(396, "xutil.nim");
	LOC1 = 0;
	nimln(396, "xutil.nim");
	LOC1 = ((NU64)(((unsigned long) 285212672)) <= (NU64)(keysym));
	if (!(LOC1)) goto LA2;
	nimln(396, "xutil.nim");
	LOC1 = ((NU64)(keysym) <= (NU64)(((unsigned long) 285278207)));
	LA2: ;
	result = LOC1;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, iscursorkey_119719)(unsigned long keysym) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	nimfr("IsCursorKey", "xutil.nim")
	result = 0;
	nimln(399, "xutil.nim");
	nimln(399, "xutil.nim");
	LOC1 = 0;
	nimln(399, "xutil.nim");
	LOC1 = ((NU64)(((unsigned long) 65360)) <= (NU64)(keysym));
	if (!(LOC1)) goto LA2;
	nimln(399, "xutil.nim");
	LOC1 = ((NU64)(keysym) < (NU64)(((unsigned long) 65376)));
	LA2: ;
	result = LOC1;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, ispfkey_119723)(unsigned long keysym) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	nimfr("IsPFKey", "xutil.nim")
	result = 0;
	nimln(402, "xutil.nim");
	nimln(402, "xutil.nim");
	LOC1 = 0;
	nimln(402, "xutil.nim");
	LOC1 = ((NU64)(((unsigned long) 65425)) <= (NU64)(keysym));
	if (!(LOC1)) goto LA2;
	nimln(402, "xutil.nim");
	LOC1 = ((NU64)(keysym) <= (NU64)(((unsigned long) 65428)));
	LA2: ;
	result = LOC1;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, isfunctionkey_119727)(unsigned long keysym) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	nimfr("IsFunctionKey", "xutil.nim")
	result = 0;
	nimln(405, "xutil.nim");
	nimln(405, "xutil.nim");
	LOC1 = 0;
	nimln(405, "xutil.nim");
	LOC1 = ((NU64)(((unsigned long) 65470)) <= (NU64)(keysym));
	if (!(LOC1)) goto LA2;
	nimln(405, "xutil.nim");
	LOC1 = ((NU64)(keysym) <= (NU64)(((unsigned long) 65504)));
	LA2: ;
	result = LOC1;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, ismiscfunctionkey_119731)(unsigned long keysym) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	nimfr("IsMiscFunctionKey", "xutil.nim")
	result = 0;
	nimln(408, "xutil.nim");
	nimln(408, "xutil.nim");
	LOC1 = 0;
	nimln(408, "xutil.nim");
	LOC1 = ((NU64)(((unsigned long) 65376)) <= (NU64)(keysym));
	if (!(LOC1)) goto LA2;
	nimln(408, "xutil.nim");
	LOC1 = ((NU64)(keysym) <= (NU64)(((unsigned long) 65387)));
	LA2: ;
	result = LOC1;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, ismodifierkey_119735)(unsigned long keysym) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	NIM_BOOL LOC2;
	NIM_BOOL LOC3;
	nimfr("IsModifierKey", "xutil.nim")
	result = 0;
	nimln(411, "xutil.nim");
	nimln(412, "xutil.nim");
	LOC1 = 0;
	nimln(411, "xutil.nim");
	LOC2 = 0;
	nimln(411, "xutil.nim");
	LOC3 = 0;
	nimln(411, "xutil.nim");
	LOC3 = ((NU64)(((unsigned long) 65505)) <= (NU64)(keysym));
	if (!(LOC3)) goto LA4;
	nimln(411, "xutil.nim");
	LOC3 = ((NU64)(keysym) <= (NU64)(((unsigned long) 65518)));
	LA4: ;
	LOC2 = LOC3;
	if (LOC2) goto LA5;
	nimln(412, "xutil.nim");
	LOC2 = HEX3DHEX3D_106070(keysym, ((unsigned long) 65406));
	LA5: ;
	LOC1 = LOC2;
	if (LOC1) goto LA6;
	nimln(412, "xutil.nim");
	LOC1 = HEX3DHEX3D_106070(keysym, ((unsigned long) 65407));
	LA6: ;
	result = LOC1;
	popFrame();
	return result;
}
N_NOINLINE(void, x11xutilInit)(void) {
	nimfr("xutil", "xutil.nim")
	popFrame();
}

N_NOINLINE(void, x11xutilDatInit)(void) {
if (!((TMP155 = nimLoadLibrary((NimStringDesc*) &TMP156))
)) nimLoadLibraryError((NimStringDesc*) &TMP157);
	Dl_119210 = (TY119211) nimGetProcAddr(TMP155, "XAllocClassHint");
	Dl_119213 = (TY119214) nimGetProcAddr(TMP155, "XAllocIconSize");
	Dl_119216 = (TY119217) nimGetProcAddr(TMP155, "XAllocSizeHints");
	Dl_119219 = (TY119220) nimGetProcAddr(TMP155, "XAllocStandardColormap");
	Dl_119222 = (TY119223) nimGetProcAddr(TMP155, "XAllocWMHints");
	Dl_119225 = (TY119226) nimGetProcAddr(TMP155, "XClipBox");
	Dl_119230 = (TY119231) nimGetProcAddr(TMP155, "XCreateRegion");
	Dl_119233 = (TY119234) nimGetProcAddr(TMP155, "XDefaultString");
	Dl_119236 = (TY119237) nimGetProcAddr(TMP155, "XDeleteContext");
	Dl_119242 = (TY119243) nimGetProcAddr(TMP155, "XDestroyRegion");
	Dl_119246 = (TY119247) nimGetProcAddr(TMP155, "XEmptyRegion");
	Dl_119250 = (TY119251) nimGetProcAddr(TMP155, "XEqualRegion");
	Dl_119255 = (TY119256) nimGetProcAddr(TMP155, "XFindContext");
	Dl_119262 = (TY119263) nimGetProcAddr(TMP155, "XGetClassHint");
	Dl_119268 = (TY119269) nimGetProcAddr(TMP155, "XGetIconSizes");
	Dl_119275 = (TY119276) nimGetProcAddr(TMP155, "XGetNormalHints");
	Dl_119281 = (TY119282) nimGetProcAddr(TMP155, "XGetRGBColormaps");
	Dl_119289 = (TY119290) nimGetProcAddr(TMP155, "XGetSizeHints");
	Dl_119296 = (TY119297) nimGetProcAddr(TMP155, "XGetStandardColormap");
	Dl_119303 = (TY119304) nimGetProcAddr(TMP155, "XGetTextProperty");
	Dl_119310 = (TY119311) nimGetProcAddr(TMP155, "XGetVisualInfo");
	Dl_119317 = (TY119318) nimGetProcAddr(TMP155, "XGetWMClientMachine");
	Dl_119323 = (TY119324) nimGetProcAddr(TMP155, "XGetWMHints");
	Dl_119328 = (TY119329) nimGetProcAddr(TMP155, "XGetWMIconName");
	Dl_119334 = (TY119335) nimGetProcAddr(TMP155, "XGetWMName");
	Dl_119340 = (TY119341) nimGetProcAddr(TMP155, "XGetWMNormalHints");
	Dl_119348 = (TY119349) nimGetProcAddr(TMP155, "XGetWMSizeHints");
	Dl_119357 = (TY119358) nimGetProcAddr(TMP155, "XGetZoomHints");
	Dl_119363 = (TY119364) nimGetProcAddr(TMP155, "XIntersectRegion");
	Dl_119369 = (TY119370) nimGetProcAddr(TMP155, "XConvertCase");
	Dl_119375 = (TY119376) nimGetProcAddr(TMP155, "XLookupString");
	Dl_119383 = (TY119384) nimGetProcAddr(TMP155, "XMatchVisualInfo");
	Dl_119391 = (TY119392) nimGetProcAddr(TMP155, "XOffsetRegion");
	Dl_119397 = (TY119398) nimGetProcAddr(TMP155, "XPointInRegion");
	Dl_119403 = (TY119404) nimGetProcAddr(TMP155, "XPolygonRegion");
	Dl_119409 = (TY119410) nimGetProcAddr(TMP155, "XRectInRegion");
	Dl_119417 = (TY119418) nimGetProcAddr(TMP155, "XSaveContext");
	Dl_119424 = (TY119425) nimGetProcAddr(TMP155, "XSetClassHint");
	Dl_119430 = (TY119431) nimGetProcAddr(TMP155, "XSetIconSizes");
	Dl_119437 = (TY119438) nimGetProcAddr(TMP155, "XSetNormalHints");
	Dl_119443 = (TY119444) nimGetProcAddr(TMP155, "XSetRGBColormaps");
	Dl_119451 = (TY119452) nimGetProcAddr(TMP155, "XSetSizeHints");
	Dl_119458 = (TY119459) nimGetProcAddr(TMP155, "XSetStandardProperties");
	Dl_119469 = (TY119470) nimGetProcAddr(TMP155, "XSetTextProperty");
	Dl_119476 = (TY119477) nimGetProcAddr(TMP155, "XSetWMClientMachine");
	Dl_119482 = (TY119483) nimGetProcAddr(TMP155, "XSetWMHints");
	Dl_119488 = (TY119489) nimGetProcAddr(TMP155, "XSetWMIconName");
	Dl_119494 = (TY119495) nimGetProcAddr(TMP155, "XSetWMName");
	Dl_119500 = (TY119501) nimGetProcAddr(TMP155, "XSetWMNormalHints");
	Dl_119506 = (TY119507) nimGetProcAddr(TMP155, "XSetWMProperties");
	Dl_119518 = (TY119519) nimGetProcAddr(TMP155, "XmbSetWMProperties");
	Dl_119530 = (TY119531) nimGetProcAddr(TMP155, "Xutf8SetWMProperties");
	Dl_119542 = (TY119543) nimGetProcAddr(TMP155, "XSetWMSizeHints");
	Dl_119549 = (TY119550) nimGetProcAddr(TMP155, "XSetRegion");
	Dl_119555 = (TY119556) nimGetProcAddr(TMP155, "XSetStandardColormap");
	Dl_119562 = (TY119563) nimGetProcAddr(TMP155, "XSetZoomHints");
	Dl_119568 = (TY119569) nimGetProcAddr(TMP155, "XShrinkRegion");
	Dl_119574 = (TY119575) nimGetProcAddr(TMP155, "XStringListToTextProperty");
	Dl_119580 = (TY119581) nimGetProcAddr(TMP155, "XSubtractRegion");
	Dl_119586 = (TY119587) nimGetProcAddr(TMP155, "XmbTextListToTextProperty");
	Dl_119594 = (TY119595) nimGetProcAddr(TMP155, "XwcTextListToTextProperty");
	Dl_119604 = (TY119605) nimGetProcAddr(TMP155, "Xutf8TextListToTextProperty");
	Dl_119612 = (TY119613) nimGetProcAddr(TMP155, "XwcFreeStringList");
	Dl_119618 = (TY119619) nimGetProcAddr(TMP155, "XTextPropertyToStringList");
	Dl_119624 = (TY119625) nimGetProcAddr(TMP155, "XmbTextPropertyToTextList");
	Dl_119631 = (TY119632) nimGetProcAddr(TMP155, "XwcTextPropertyToTextList");
	Dl_119641 = (TY119642) nimGetProcAddr(TMP155, "Xutf8TextPropertyToTextList");
	Dl_119648 = (TY119649) nimGetProcAddr(TMP155, "XUnionRectWithRegion");
	Dl_119654 = (TY119655) nimGetProcAddr(TMP155, "XUnionRegion");
	Dl_119660 = (TY119661) nimGetProcAddr(TMP155, "XWMGeometry");
	Dl_119674 = (TY119675) nimGetProcAddr(TMP155, "XXorRegion");
}

