/* Generated by Nimrod Compiler v0.9.5 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nimrod -o /home/andreysh/Projects/nimrod/stone_head/nimcache/x11_x.o /home/andreysh/Projects/nimrod/stone_head/nimcache/x11_x.c */
#define NIM_INTBITS 64
#include "nimbase.h"
N_NIMCALL(NIM_BOOL, HEX3DHEX3D_106070)(unsigned long a, unsigned long b);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
extern TFrame* frameptr_13038;

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_13038;
	frameptr_13038 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_13038 = (*frameptr_13038).prev;
}

N_NIMCALL(NIM_BOOL, HEX3DHEX3D_106070)(unsigned long a, unsigned long b) {
	NIM_BOOL result;
	nimfr("==", "x.nim")
	result = 0;
	nimln(52, "x.nim");
	nimln(52, "x.nim");
	nimln(52, "x.nim");
	result = (a == b);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}
N_NOINLINE(void, x11xInit)(void) {
	nimfr("x", "x.nim")
	popFrame();
}

N_NOINLINE(void, x11xDatInit)(void) {
}

